### ISSUE TITLE
Reports>Record Creation : additional filters

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#146]
Partly in lieu of some of the functions that would have gone into the summary tab, it would be very useful to add three additional filters to this report tab. 

@rcking would appreciate your advice on the amount of additional work involved with these.

(i) Filter by NPLD Criteria Met
[ie drop-down with each criterion: UK TLD, UK Hosting, UK Reg  etc., including 'No LD Criteria Met' and *also*  None.
We need to be able to see both when the curator has recorded positively that no criteria have been met, and also that no such determination has been made.

(ii) similarly, but quite distinct:  Filter by UK TLD   
- this is a simple Yes/No choice.

(iii) Filter by Crawl Frequency
- ie a dropdown with all the values: Monthly, Weekly  etc.
BUT where the schedule is still active - that is, where the schedule end date is either not set, or is in the future.

**Comment by PsypherPunk** [comment]
Just looking at this in reference to #264—we shouldn't need to look at _every_ Target record, just those where the WHOIS might make a difference (i.e. those where the has-a-UK-address is the _only_ rule keeping it in scope and those with no LD criteria met).

That might keep the number relatively low.

**Comment by anjackson** [comment]
Closing this and moving details over to #264.
