### ISSUE TITLE
Superfluous links to licence in Crawl Permissions queue

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#160]
Archivist Tasks > Crawl Permissions

When viewing the queue with statuses Queued, Pending, Email Rejected, Refused, the link to the Licence is superfluous (as there is no completed licence to match the crawl permission. )

Could this be either hidden or greyed out under these conditions.

**Comment by peterwebster** [comment]
This needs redoing.

**Comment by peterwebster** [comment]
This needs re-doing, but I haven't added it to either milestone, as an indication of priority.

**Comment by ldbiz** [comment]
Clarified with @nicolabingham : just show the View option for Granted. Suppress for all other status.

**Comment by GilHoggarth** [comment]
Seen to work on /actstage.

**Comment by GilHoggarth** [comment]
Seen on live, closing.
