### ISSUE TITLE
QA workflow enhancement: Reports to QA dashboard link

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#167]
An enhancement requested by Nicola: to allow Archivist users to get from the Reports > QA area to the QA Dashboard for a particular target. At the minute this view gives a number of instances, but no way through to the list.
http://www.webarchive.org.uk/actdev/reportsqa/targets/?s=title&status=awaitingQa&query_start_date=29-07-2014 

A _minimal_ solution would be to link from the number '1' for 'Anarchist Federation' to the QA dashboard  for that target:  http://www.webarchive.org.uk/actdev/qa/list?s=title&f=afed.org.uk

**Comment by nicolabingham** [comment]
Closing this ticket, this is no longer a requirement
