### ISSUE TITLE
QA Status filter in Archivist Tasks > QA Dashboard

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#169]
The filter in the QA Dashboard is not being applied correctly - the example target below should only appear when QA Status = "Passed_publish..." but it also appears incorrectly when other values are selected.

http://www.webarchive.org.uk/actdev/qa/list?s=title&f=afed.org.uk&query_collection=act-&query_qa_status=act-164

Also, in Chrome, the collections tree view is not loading.

**Comment by kinmanli** [comment]
This seems to be working okay. But the QA Status column is showing the "Most Recent" Instance's QA Status, or is it meant to be the same as the selected filter "By QA Status"  @peterwebster @nicolabingham?

http://www.webarchive.org.uk/actdev/qa/list?f=afed.org.uk&qaIssueId=191

**Comment by nicolabingham** [comment]
@kinmanli @peterwebster the QA status column is supposed to be the same as the 'By QA Status' filter that has been applied, sorted by the most recent instances at the top of the list.

**Comment by ldbiz** [comment]
The issue as described is not clear; I've discussed it with @nicolabingham and looked at the current behaviour and data, and this is my analysis:

There are two main issues.

**1. Filter**: When a QA Status is selected, it is not being correctly applied as a filter at Target level.

**2. Results**: The QA Status column, is 
   a) redundant, given there is always only one QA Status being filtered for ("None" = "Unassigned", not "No Filter").
   b) incorrect, as it is not showing the status which has been selected anyway.

Therefore, the fixes should be:

**1. **Apply the QA Status filter at Target Level.
**2. **Either 
    a) drop the column 
       or 
    b) Allow an "All QA Status" filter option and display each Target's QA Status in the result set.

**Comment by ldbiz** [comment]
I've fixed the issues as described. I've also made a couple of display changes to clarify the QA Status information is now at Target, not Instance level. QA Status column moved over to the Target section of the results list; "Instance" added to the last column header.
