### ISSUE TITLE
Migration of instance level QA data from Andy's ACT

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#171]
Currently no instance level QA status seems to be migrated: e.g. 

http://www.webarchive.org.uk/act/node/12873

has an instance level QA status value,  but the corresponding W3ACT instance has none

 http://www.webarchive.org.uk/actdev/instanceedit/act-12873#qa 

This may be a mapping issue, in that W3ACT has more potential values for this field than Andy's ACT:

Andy’s ACT has two:  No QA issues found (OK to publish)   and QA issues found      

W3ACT has five:  Passed, Publish, No Action Required / Issue Noted / Failed, Do Not Publish  / Failed, Pass to Engineer / Recrawl Requested

On import, we suggest that the mapping is as follows:

No QA Issues   - >  Passed, Publish, No Action required
QA Issues Found - > Issue Noted

Cd @anjackson review, and assign ?

**Comment by nicolabingham** [comment]
This is no longer a requirement
