### ISSUE TITLE
Retention of crawl permissions that are superseded

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#173]
Our tester created two crawl permissions for a target, both of which were then granted by the website owner. The second one shows as Granted at:
http://www.webarchive.org.uk/actdev/crawlpermissions/list?status=GRANTED  (14-18NOW)
(This is the permission itself: http://www.webarchive.org.uk/actdev/crawlpermissions/act-3756677908307687915 )

However, the first one does not show up in the Superseded view. Any crawl permission for a target for which there is a later crawl permission with status = Granted should show up as superseded.

**Comment by peterwebster** [comment]
Hi @nicolabingham  : another very marginal use case that Rav found some time ago. I now think that the validation at the target record doesn't allow two crawl permissions to be active simultaneously - you can't send out a second email while the first is Pending or Queued or Granted.

So, feel free to close this one if you're happy.

**Comment by nicolabingham** [comment]
@peterwebster Happy to close this
