### ISSUE TITLE
Reports>Record Creation: filter not working

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#179]
Transplanted from #146 for clarity : here is an issue with this requirement (copied down from the top of the ticket)

"(i) Filter by NPLD Criteria Met
 [ie drop-down with each criterion: UK TLD, UK Hosting, UK Reg etc., including 'No LD Criteria Met' and also None.
 We need to be able to see both when the curator has recorded positively that no criteria have been met, and also that no such determination has been made."

A filter on None needs to show records where none of the criteria have been met AND where the curator has *not* selected 'No LD Criteria Met' - that is, records which need attention from a curator to make a determination one way or the other. 
Right now, it just returns all records in ACT.

**Comment by niladreeb** [comment]
Now selecting 'None' in filter by NPLD shows only those targets for whom no determination have been made.

**Comment by niladreeb** [comment]
Tested in actstage and its working properly.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Nils, reading through this ticket I don't understand what's been asked for and what's been done. Can you test on /actstage please, and update this ticket as appropriate.

**Comment by niladreeb** [comment]
In this ticket Reports>Target creation>Filter by NPLD was not filtering properly. Now it is giving proper result in actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Think this is working but @niladreeb can you test and label as appropriate please.

**Comment by niladreeb** [comment]
Sure @GilHoggarth. The NPLD filter is working properly in actstage.

**Comment by niladreeb** [comment]
Done on live.
