### ISSUE TITLE
Transition to production

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#182]
Steps required:

(i) full production deployment of latest code, tagged

(ii) full re-import of data from Andy's ACT

(iii) @PsypherPunk and @GilHoggarth to test integrity of data import

Then:

(iv) change Roles of all non-WAT-team users of Andy's ACT to read-only
- PW to inform users of this

(vi) Nicola, PW and Jason to input identical data to Andy's ACT and W3ACT 

(viii) GH/RC/AJ to check that the tables in both are matching

**Comment by anjackson** [comment]
Just prior to release, please tag the codebase in git as 'w3act-1.0.0'

**Comment by peterwebster** [comment]
After discussion with @anjackson let's plan to have a clean deployment of W3ACT this Friday @GilHoggarth 

I'll arrange that active users of Andy's ACT get to know that it will be closed to new data from first thing Monday. Not sure who is able to set them all to read only @anjackson ?

Some combination of Nicola, Jason and I will do some double-entry data entry, next Monday to Wednesday.

The key ticket to resolve before then @kinmanli is #241 

After that it will be over to @PsypherPunk for testing of the new data by comparison between the tables in the two services.

**Comment by peterwebster** [comment]
OK @PsypherPunk @anjackson @GilHoggarth : Nicola and I have this morning created eight new target records in both Andy's ACT and W3ACT at /act . Could you compare and contrast the data in the tables ?

**Comment by GilHoggarth** [comment]
I didn't think we could compare the databases of Andy's ACT and W3act as their structures have changed significantly.

Could you provide some sort of target ID, perhaps just the URL, so we can check the different tables that the data goes into?

**Comment by anjackson** [comment]
Perhaps it's possible to compare the crawl feeds from both? Or also note that Targets have JSON representations in each case and that may be handy to compare contents:

* http://www.webarchive.org.uk/act/node/1.json
* https://www.webarchive.org.uk/act/api/targets/1

**Comment by GilHoggarth** [comment]
As an ignorant question, is it important that the target numbers, 1 in both examples above, resolve to the same target? I changed these URLs to 16000 and they give different records.
http://www.webarchive.org.uk/act/node/16000.json - belfasttelegraph.co.uk
https://www.webarchive.org.uk/act/api/targets/16000 - fishmapmon.naturalresourceswales.gov.uk

**Comment by anjackson** [comment]
The numbers will start off the same because the import is in order. I don't think we enforce the ID's to be the same, and I imagine Drupal has some gaps in the sequence. I don't think this indicates anything has gone wrong, but perhaps @kinmanli can comment.

**Comment by peterwebster** [comment]
These are the seeds: does that help ? @GilHoggarth 

All created with today's date.

http://www.bbc.co.uk/news/uk-england-31242433
http://www.bl.uk/magna-carta/
http://www.theguardian.com/books/2015/feb/02/british-library-magna-carta-copies-...
http://www.theguardian.com/culture/2015/feb/08/10m-magna-carta-found-in-council-...
http://www.legislation.gov.uk/aep/Edw1cc1929/25/9/contents
http://websterresearchconsulting.com
http://evangelicalnetworks.wordpress.com
http://twitter.com/pj_webster

**Comment by GilHoggarth** [comment]
Kinman's showed me that the two webarchive.org.uk URLs above won't be enforce to be the same, but it's possible to work out the comparision - https://www.webarchive.org.uk/act/targets/act/act-16000, in the new w3act service, shows the same data as the Andy's ACT 16000.json URL.

**Comment by anjackson** [comment]
Note also you can search for Targets via e.g. https://www.webarchive.org.uk/act/targets/filterbyjson/bbc.co.uk

**Comment by GilHoggarth** [comment]
Checking http://www.webarchive.org.uk/act/node/21891 against https://www.webarchive.org.uk/act/targets/16930:
- Several fields unset in Andy's ACT but set to 'no' in w3act. Guessing this is the default value if data not entered but wonder if 'not entered' should equal no. Fields include "Ignore Robot.txt", "UK Postal Address", "Via Correspondence", "Professional Judgement", "No LD Criteria Met". 

This last value makes me wonder - does the system check that this can only be 'yes' if all other LD criteria fields are no?

**Comment by GilHoggarth** [comment]
Have looked into the Andy's ACT and w3act databases, and struggled to find the corresponding data - just because Andy's ACT uses a database table structure automatically generated by Drupal and many tables and fields are internal code names and values - difficult to traverse a target for example to find all the actual ACT data (as opposed to internal Drupal fields and values). 

Consequently, I'll look through the URLs via their respective UIs and visually compare.

**Comment by GilHoggarth** [comment]
Comparing http://www.webarchive.org.uk/act/node/21887 and https://www.webarchive.org.uk/act/targets/16927 (former = latter):
- Crawl End Date: 20 Dec 2015, 11pm   =   20-12-2015 00:00
- Crawled URL: http://crawler03.bl.uk:8080/wayback/*/http://www.bl.uk/magna-carta/  =  http://opera.bl.uk:8080/wayback/*/http://www.bl.uk/magna-carta/
Neither find crawled content but presumably due to wayback index not updated yet.

**Comment by PsypherPunk** [comment]
The start date's in the future: `Start date 20-02-2015 06:00`

**Comment by GilHoggarth** [comment]
Surprised that I'm not finding a sort by date option in Targets list, or actually a date recorded (displayed) for when the record data was input.

**Comment by GilHoggarth** [comment]
It occurs to me that I'm testing the dual input of data more than I am testing the import of data from Andy's ACT, so thought I'd check a few previously entered sites.

http://acommonreader.org/ (first in the alphabetical order ;) shows in Andy's ACT 5,017 URLs crawled (http://www.webarchive.org.uk/act/node/5987) and links to wayback versions at http://crawler03.bl.uk:8080/wayback/*/http://acommonreader.org/*; the equivalent in w3act (https://www.webarchive.org.uk/act/targets/2672) doesn't show such information, and gets "Resource Not In Archive" from http://opera.bl.uk:8080/wayback/*/http://acommonreader.org/

@peterwebster @anjackson I'd have thought this and the differences above are significant?

**Comment by PsypherPunk** [comment]
Although the `prod.conf` file has:

    application.wayback.url="http://crawler03.bl.uk:8080/wayback/xmlquery.jsp?url="

...the `In QA Wayback` links still reference `opera.bl.uk` (which is now out of date).

**Comment by kinmanli** [comment]
@PsypherPunk fixed and ticket https://github.com/ukwa/w3act/issues/267

**Comment by peterwebster** [comment]
@GilHoggarth wrote: 

"Several fields unset in Andy's ACT but set to 'no' in w3act. Guessing this is the default value if data not entered but wonder if 'not entered' should equal no. Fields include "Ignore Robot.txt", "UK Postal Address", "Via Correspondence", "Professional Judgement", "No LD Criteria Met"."

@anjackson should these all in fact default to Null ?

**Comment by peterwebster** [comment]
@GilHoggarth also wrote in relation to the No LD Criteria Met field:

"does the system check that this can only be 'yes' if all other LD criteria fields are no?"

The answer is: Not Yet, but it is captured at #240

**Comment by peterwebster** [comment]
A comparison of the crawl feeds for both applications would be the easiest means of comparing @GilHoggarth (bearing in mind one issue with the timestamps)

**Comment by anjackson** [comment]
@GilHoggarth They should be 'no', because 'Null' means 'unknown' or 'unset'.

**Comment by GilHoggarth** [comment]
Note to self: w3act crawl feed example: https://www.webarchive.org.uk/act/targets/export/ld/daily

**Comment by anjackson** [comment]
@PsypherPunk looked at the feeds and found some minor differences:

```
a script for comparing the daily feeds: /home/rcoram/Tasks/20140430-act-export-verification/compare_jobs.py
Had to fiddle with it a bit as it looks like field_crawl_start_date and field_crawl_end_date are now blank but there are new fields, crawlStartDateText and crawlEndDateText. However, these last two aren't in ISO date format so they might throw the date parser.
It looks like the feeds aren't quite the same; here's the output from the script:
[New; daily-0100]
set(['http://www.express.co.uk/scotland'])
[Old; daily-0000]
set(['http://smashfestuk.com/', 
'http://www.cityam.com/'])
[New; daily-0900]
set(['https://twitter.com/TelePolitics/lists/members-of-parliament'])
[Old; daily-0600]
set(['https://twitter.com/TelePolitics/lists/members-of-parliament', 
'http://www.twitter.com/pj_webster/', 
'http://www.electionwatch.co.uk/', 
'http://www.thebigproject.co.uk/'])
It looks like the "...members-of-parliament" URL has switched from 0600 to 0900 between ACT and w3act. Most of the rest, I think are down to the date parsing (it's confusing a start date of 03-02-2015 as 2nd March 2015, i.e. a future date).
```

**Comment by anjackson** [comment]
Nicola is going through the discrepancies at the moment. We should be able to push on tomorrow.

**Comment by anjackson** [comment]
@GilHoggarth note that /opt/w3act/waybackinstance_import.sh should be added to cron when we go to production (#231).

**Comment by nicolabingham** [comment]
I have resolved the list of discrepancies and am happy that there are no issues here.

**Comment by PsypherPunk** [comment]
Re. the above, can we get the date formats in the feeds changed (not sure if there's a ticket open for this)?

They're currently of the form: `"06-04-2013 13:00"`

However, could they be changed to ISO 8601 format and clearly UTC? i.e. `2013-04-06T13:00:00Z`?

**Comment by anjackson** [comment]
I have asked @PsypherPunk to switch over to W3ACT to drive the crawls. I believe we should get data though sometime after 13:00.

@GilHoggarth can the 'import instances' script be run hourly? Then the Instances should show up automatically later today.

**Comment by anjackson** [comment]
Note that I have re-tagged the initial W3ACT release that started this process as w3act-1.0.0-beta. When we have transitioned to production, I will tag the w3act-1.0.0 release.

**Comment by GilHoggarth** [comment]
In talking with Andy about this, it's a good idea for 'play dist' zip to be added to github as part of the official w3act-1.0.0 release. Consequently we'll have a definitive record of the first release.

**Comment by GilHoggarth** [comment]
We’re down to the last issue on W3ACT milestone 1.0.0 development – and it’s been decided that that last issue will be shifted to milestone 1.0.1! So, we’re about to launch!!

Plan of action:
- Gil to block all Andy’s ACT update actions (so old /act doesn’t accept any new data) - DONE
- Gil to redirect http /act to https /act
- Andy to move last issue to milestone 1.0.1
- Kinman to move the ‘schemafactor’ branch into the master github branch, and tag this code as ‘w3act-1.0.0’

When done:
- Gil to build w3act-1.0.0 master, check built zip (dist version) into github as release w3act-1.0.0

Nicola to use https://www.webarchive.org.uk/act as the official production ACT service.

**Comment by GilHoggarth** [comment]
http > https /act DONE

**Comment by GilHoggarth** [comment]
Last issue to milestone 1.0.1 DONE

**Comment by kinmanli** [comment]
@GilHoggarth merged into master and up-to-date https://github.com/ukwa/w3act/commits/master

**Comment by GilHoggarth** [comment]
w3act-1.0.0 master built and now in service; play dist .zip added to github as release w3act-1.0.0
W3ACT now in production!
