### ISSUE TITLE
Review field labels

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#187]
Hi @rcking , hope you're keeping well. After discussion with @anjackson , here are some revisions to the labelling in the W3ACT UI in the target record. We thought it best if this was folded in with the work AIT are doing on the UI.

As and when I have other such suggestions from elsewhere in the UI, I'll raise new tickets.

**Comment by peterwebster** [comment]
Suggest more natural language at http://www.webarchive.org.uk/actdev/targets/lookup  :  Annual, Domain Crawl, etc

**Comment by peterwebster** [comment]
To revise in Target Record: overview

Seed URLs:  'One or more URLs, separated by commas, including the http:// '

For UK Hosting / UK TLD / UK registration: in each label, add in brackets (automated check)

'Keywords' : label to read 'Free text keywords, private to you'

'Tag(s):  label to read 'keywords common to all users, controlled centrally and visible to other users'

Synonyms: 'If this content is also hosted at another URL, record it here.  For example, if www.company.co.uk is the same as www.company.com'

**Comment by peterwebster** [comment]
To revise in Target Record, metadata tab:

Subject:   delete the whole section in brackets.

Nominating Organisation:  delete everything from 'Used to track down..' to the end.

Selector:  delete everything from 'A record can be.. ' to the end.

**Comment by peterwebster** [comment]
To review in Target Record, crawl policy tab

Scope: to read 'Determines the scope of the crawl around this URL. To capture a whole site, specify the homepage and select 'All URLs that start like this'. To include all subdomains (e.g. example.co.uk but also anything like www.example.co.uk, images.example.co.uk, etc.) then select the 'any subdomains' option).

Depth:  'Determines the depth of the crawl

**Comment by peterwebster** [comment]
To change in Target Record, NPLD tab:

UK Hosting / UK TLD / UK Registration: add in brackets in each case (automated check)

UK Postal Address: should read (Does the 'about us' or other contact page contain a UK address for a significant part of the organisation (ie. is not just a PO box)?)

Postal Address URL: should read:   (The URL on the site that contains the postal address)

Via Correspondence: should read (Has previous correspondence with the web site owner by a Curator contained evidence of a UK address?)

Professional Judgement:   missing question mark after 'Legislation'

Professional Judgement Explanation:  rationale, not rational.

**Comment by nicolabingham** [comment]
This has been done.
