### ISSUE TITLE
Upward "cascade" of subject terms (child to parent)

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#191]
When a user assigns a Subject value to a target, they have the choice of parent terms and child terms.

I think users will expect that, when they select a child terms (Art and Design), the target will as a matter of course be assigned to the parent (in this case, Arts and Humanities). I don't think this is the case now.

eg. this target
http://www.webarchive.org.uk/actdev/targets/view?target=act-1556765206208428430 

appears under Art and Design (the child):
http://www.webarchive.org.uk/actdev/targets/subjecttargets/?s=title&subject_url=act-155367630121551131

but not under Arts and Humanities (the parent)
http://www.webarchive.org.uk/actdev/targets/subjecttargets/?s=title&subject_url=act-10 

This can be dealt with by training users to check both parent boxes in the target record, but it isn't intuitive.

Checking with Nicola before going any further.

**Comment by kinmanli** [comment]
check tree option to select parent when choosing child

**Comment by kinmanli** [comment]
@peterwebster Is this option only on the creation and editing of targets?

I know that the editing of subjects and collections don't need it as they are choosing a parent.

**Comment by peterwebster** [comment]
@kinmanli to check whether this has been committed

**Comment by kinmanli** [comment]
automatically selects parent, but is not saved.

**Comment by kinmanli** [comment]
@peterwebster fixed

Target editing now show's Subject and Collection Parent's being selected in the UI.

![screen shot 2015-02-21 at 01 19 00](https://cloud.githubusercontent.com/assets/1652105/6312180/996b2c94-b968-11e4-968f-fc7c95cce338.png)

Tables show that the parent's are being persisted.

Subjects
![screen shot 2015-02-21 at 01 25 26](https://cloud.githubusercontent.com/assets/1652105/6312210/66177b76-b969-11e4-906b-0f76abab5a2a.png)

Collections
![screen shot 2015-02-21 at 01 25 36](https://cloud.githubusercontent.com/assets/1652105/6312209/66104c84-b969-11e4-8d48-6b1d9addda85.png)

**Comment by peterwebster** [comment]
Hi @kinmanli the *upward* cascade looks good - I've selected a child value in both subject and collection which correctly selects the parent too.

However, it also cascades down - ie. selecting a parent automatically selects all the children. I don't think this is the right behaviour, but need to check. Could you confirm whether the two behaviours come as a package - ie. the same code that enables the upward flow also requires the downward, and the two can't be separated ?

**Comment by kinmanli** [comment]
@peterwebster in a tree UI that seems be normal behaviour, and the code does both things.

**Comment by peterwebster** [comment]
So, if it is both or neither (we can't have down without up) I need to check with Nicola as to whether we need to revert, and have neither. Assigning this to me while I do that.  
cc @anjackson FYI

**Comment by peterwebster** [comment]
@kinmanli is it possible/straightforward to *require* the user to select a child (if there are any) when selecting a parent? This would mean that it would not be possible for a user to select only a parent and thus have all the children selected by default.
This is just a question right now; talking to Nicola about the best option.

**Comment by peterwebster** [comment]
@anjackson I think we need to move this one to the most immediate milestone, alas. At the minute, if a user selects a parent subject term, W3ACT defaults to checking *all* the children. (See the thread in the last 2-3 days.) This is the quid pro quo of the fix we asked for, so we might need to ask Kinman to undo that.
The requirement is then that we train users to individually select parents and children, for both subjects and collections. The UI should not automatically select anything that the user has not, for either subjects or collections.

On a later milestone, Nicola suggests some validation that enforces that the user select a sub-collection if there are any for a parent collection - but the same doesn't apply to subjects.

Would you agree ? If so, could you change the milestone ?

**Comment by anjackson** [comment]
Here's the plan for @kinmanli :

* Revert the change, so that users need to manually add the parent to the selection.
* Add server-side validation that automatically checks if the parent terms are selected and selects them if not before saving the target.

**Comment by kinmanli** [comment]
@GilHoggarth 

fixed: view doesn't auto select parent but server side code does and saves

**Comment by nicolabingham** [comment]
Selecting child subject term only automatically adds parent term on saving target record. Tested on target http://www.webarchive.org.uk/actdev/targets/16928

**Comment by GilHoggarth** [comment]
Reopening so the same test is performed on w3act.

**Comment by peterwebster** [comment]
This looks fine to me. Was there a particular reason why this should be any different when the code is deployed to the production version @GilHoggarth ? If not, this can be closed.

**Comment by GilHoggarth** [comment]
@nicolabingham Can you test this again please on w3act.

**Comment by nicolabingham** [comment]
Tested on W3ACT. Selecting child term automatically adds parent term on saving record. Tested on Target http://www.webarchive.org.uk/actdev/targets/16928
