### ISSUE TITLE
Duplicate results in Reports view

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#194]
Just spotted the appearance of duplicate entries in this view (first two - testdotcomtarget1 )

http://www.webarchive.org.uk/actdev/reportscreation/targets/?s=created&o=desc&query_start_date=31-10-2014&npld=none&tld=either

We've had this before, and it was to do with seeing multiple revisions of the same target.

**Comment by kinmanli** [comment]
@peterwebster these is "pre-refactor". Is it working now?

**Comment by nicolabingham** [comment]
@peterwebster @kinmanli I can't see the duplicates in the reports view

**Comment by kinmanli** [comment]
@GilHoggarth seems to be fixed now

**Comment by GilHoggarth** [comment]
Difficult to see any duplicates in URL example as there's 5000+ targets to consider. But couldn't see any in the first 100. 
@nicolabingham Is there an easier way to clarify this as working (or not)?

**Comment by nicolabingham** [comment]
@GilHoggarth what filters did you use to build this report?

**Comment by nicolabingham** [comment]
@GilHoggarth, no sorry, I can't think of an easier way to test this, but I can't see any duplicates either.

**Comment by GilHoggarth** [comment]
Ah, basically none. Used the /act version of Kinman's example (i.e., https://www.webarchive.org.uk/act/reportscreation/targets/?s=createdAt&o=desc&startDate=31-10-2014&tld=either) and just clicked Apply.

**Comment by GilHoggarth** [comment]
Fine, think this passes the issue Peter raised.
