### ISSUE TITLE
Refactor Schema/Model

### ISSUE THREAD

**Issue by kinmanli** [ukwa/w3act#195]
Updating the Model and Schema

**Comment by kinmanli** [comment]
@peterwebster @anjackson 

How do you reference a Target when adding a new Instance?

http://www.webarchive.org.uk/actdev/instances/search#overview

Update: 

I have added this pattern accessible from targets/:id and was thinking of adding an instance this way? What do you think?

http://localhost:9000/actdev/targets/4116/instances/1
http://localhost:9000/actdev/targets/4116/instances/new

![2015-01-05 09-40-21_w3act](https://cloud.githubusercontent.com/assets/1652105/5611531/a670b184-94bf-11e4-8747-2af103b8c039.png)

**Comment by peterwebster** [comment]
Hi @kinmanli :  I'm ready to start testing the whole application, starting tomorrow. Is there anything that will still break, that I should leave until later ? @anjackson

**Comment by kinmanli** [comment]
@peterwebster the majority of it should be there. I'm just testing it at the moment and fixing minor issues when I find them.

**Comment by peterwebster** [comment]
OK: I'm planning to spend more or less all of tomorrow on it.

On Mon, Jan 5, 2015 at 4:23 PM, kinmanli <notifications@github.com> wrote:

> @peterwebster <https://github.com/peterwebster> the majority of it should
> be there. I'm just testing it at the moment and fixing minor issues when I
> find them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/w3act/issues/195#issuecomment-68732026>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by kinmanli** [comment]
@peterwebster @anjackson will you need @GilHoggarth to do a deployment as a new instance? He's off today with flu.

**Comment by anjackson** [comment]
I think we can call this done. We can open new tickets for any future changes. (Obviously feel free to re-open if I've missed something).
