### ISSUE TITLE
UKWA license permission emails sent without templates

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#198]
At the minute it is *possible* to send out an Open UKWA license email without any text, by going to the queue at:
http://www.webarchive.org.uk/actdev/crawlpermissions/list

and under 'Template' selecting None.

It's a fairly marginal use case, but the 'Template' currently defaults to General [which is right], so we should just remove None  as an option, thus solving the problem.

This doesn't need to hold us up from going into production.

cc @anjackson

**Comment by kinmanli** [comment]
"None" template removed in next release

![2015-03-10 10-28-02_w3act](https://cloud.githubusercontent.com/assets/1652105/6573160/2911d0f0-c710-11e4-99e0-6ad11c83e569.png)

**Comment by anjackson** [comment]
@niladreeb could you check this is resolved, please?

**Comment by niladreeb** [comment]
Working as expected.

**Comment by niladreeb** [comment]
Tested in actstage and its working fine.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
The bug is resolved and it is working fine.
