### ISSUE TITLE
Sending out Open UKWA permissions where permission previously refused

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#201]
If the Archivist sends a permission email, the form that the site owner must fill in does not allow them to refuse (they have just to ignore it.)
On rare occasions, a site owner gets in touch to say they are refusing. This needs to be recorded manually, by the Archivist setting the Open UWWA Licence Status field to 'Refused'.

Even more rarely, that site owner may change their mind. At this point, Archivist sets the status back to None, and begins the licence process once again.

If one does this, the site owner receives two emails - I suspect that ACT picks up the old crawl permission email and sends it out along with the new one. 

The old crawl permission probably needs marking as defunct, and the site owner should only receive the "new" email.

See http://www.webarchive.org.uk/actdev/ukwa/licenceform/act-7363216948176598198  and also 
http://www.webarchive.org.uk/actdev/ukwa/licenceform/act-3006512507649372826 

Assiging @anjackson for now. This is a very marginal use case, and not probably a priority.

**Comment by peterwebster** [comment]
So, as things have developed, I think this is now no longer a real use case. 

If a licence request is refused, Archivist marks the crawl permission as refused. Should the site owner now change their mind, the Archivist no longer needs to do anything to the target record. They simply begin the process again, creating a new crawl permission, leaving the old one set to refused. So, the sequence of actions described above no longer occurs.

Does @nicolabingham want to test this sequence of events out? Or, we can close the ticket, and re-open it if this unlikely case ever occurs and there is an issue.

**Comment by nicolabingham** [comment]
@peterwebster Agree that the archivist will send out a new crawl permission negating the sequence above. Closing this ticket.
