### ISSUE TITLE
Incorrect mail templates available in crawl permissions queue

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#202]
In the crawl permissions queue, in the list of available templates includes Acknowledgement, which should not be listed. (This is the thankyou email that goes to the owner once they've given their permission.)

If you try to select it, it produces Execution exception[[ArrayIndexOutOfBoundsException: 1]] and the email is not sent; but it should come out of the list.

There is also a Test Template which should be removed if it isn't being used for testing anymore.

**Comment by kinmanli** [comment]
fixed

**Comment by peterwebster** [comment]
Indeed it is @kinmanli : closing ticket now. Related issue still open but on hold at #198
