### ISSUE TITLE
Targets and Watched Targets

### ISSUE THREAD

**Issue by rcking** [ukwa/w3act#207]
A few issues:
1. The diplays between View and Edit are not consistent. Under Edit, the sub-tab is called "Documents", under View, it is called "Journal Titles". In both cases it should be called "Watched Target"
2. Furthermore, these two states (Edit versus View) do not present the same information, and they should. That is, in both cases, one should see: is it a watch target, what is the Document Url Scheme, and what are the associated Journal Titles. Add Journal title should appear under the Edit (NOT the View) sub-tab.
3. It should be "Document URL Scheme" (not "Document Url Scheme")
4. When modifiying a previously saved Target to become a Watched Target, the Watched Target state and the Document URL Scheme do not persist.

**Comment by niladreeb** [comment]
All issues resolved.
1. Displays between View and Edit are consistent now.
2. Edit and View layout properly organised and are now in sync."New Journal Title" and "Add Login Credentials" buttons functionality are modified. Both of them now works similar to the "Open License Request" button under UKWA Licensing tab.  Alert-info added.
3. Label fixed.
4. Data persists now.

**Comment by niladreeb** [comment]
@anjackson Kindly have a look at the present workflow.
