### ISSUE TITLE
My Watched Targets Modifications

### ISSUE THREAD

**Issue by rcking** [ukwa/w3act#210]
The following things should be modified on this page:

(1) There should be a third column in the table that says "Documents" and links to the Documents list page (http://localhost:9000/w3act-ddhapt-dev/watchedtargets/[#])

(2) The Title link should link to the Target record of the associated Watched Target (http://localhost:9000/w3act-ddhapt-dev/targets/view?target=[ID])

(3) The column header "Url" should be "URL"

(4) The URL link should open in a pop-up window and not re-direct the user away from the application

**Comment by niladreeb** [comment]
All these issues are resolved.
