### ISSUE TITLE
UI reporting of bad URL input to new target record

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#212]
As I understand it from @kinmanli , when a user creates a new target record with a malformed URL, the application writes an error to the log, but does not alert the UI user or force them to try again.

If user attempts to save a new target record with an invalid URL, they should get an error message: 'The URL entered is not valid. Please check and correct it, and click Save again.'

cc @anjackson

**Comment by kinmanli** [comment]
![2015-01-27 13-40-50_w3act](https://cloud.githubusercontent.com/assets/1652105/5919429/81c92a14-a62b-11e4-9e6b-fee4a869a03d.png)

**Comment by peterwebster** [comment]
@kinmanli I managed to save this target twice with bad URLS: once as .cot, and then again without any TLD.  http://www.webarchive.org.uk/actdev/targets/16201

**Comment by peterwebster** [comment]
And then again with  http://.com

**Comment by kinmanli** [comment]
We are currently using Java's uri = new URI(url.trim()).normalize().toURL();

Will investigate further.

**Comment by kinmanli** [comment]
Now using UrlValidator to check url format

Tested with http://.com

![2015-02-04 16-36-40_w3act](https://cloud.githubusercontent.com/assets/1652105/6044580/1e363912-ac8c-11e4-9315-53f6bc690c3b.png)

**Comment by peterwebster** [comment]
Thanks @kinmanli , looking good. Closing ticket now

**Comment by kinmanli** [comment]
@peterwebster URLValidator may not handle .london, .scot etc

**Comment by peterwebster** [comment]
@anjackson I'm happy that the issue in this ticket is solved, but not sure what the significance is of @kinmanli 's last comment. This was about malformed URLs. What was the problem @kinmanli ?

**Comment by kinmanli** [comment]
@peterwebster @GilHoggarth there was another ticket that was similar to this where I changed it to use regex. Going to test it a bit more

**Comment by kinmanli** [comment]
@GilHoggarth should be fixed now.

**Comment by GilHoggarth** [comment]
@nicolabingham Please test, including a newer domain suffix, on /actdev.

**Comment by nicolabingham** [comment]
@GilHoggarth I was able to save websites with .scot, .london and .cymru suffixes. They were all saved and passed the UK top level domain test. 
I entered a malformed URL (htt://www.nicolaagain.co.uk) into the lookup URL bar. There is no error message at this stage. Could we have one at this point informing the user that the URL is malformed? When I select Add to create a target with this malformed URL it is put into the title field as W3ACT does not recognise it as a URL. It would be better to inform the user that the URL is malformed rather than just adding it to the title field. This could confuse users.

**Comment by nicolabingham** [comment]
@GilHoggarth I was able to add this URL, without any TLD: http://www.nicelife  
I think that is a malformed URL and should not have been accepted?

**Comment by GilHoggarth** [comment]
@kinmanli Can you inviestigate these issues please.

**Comment by kinmanli** [comment]
@GilHoggarth 

At the moment this reg ex states:

```
https?:\/\/[\w-]+[\w\d.-]+\.[\w]{2,}
```

this is valid url http://nicelife
but this is invalid http://www.nicelife

Need to look at the reg ex

```
  Scenario Outline: Checking if it's there my URL is malformed
    Given I have a malformed URL of "<input>"
  	When I check to see if it is malformed
  	Then I should see a result of "<output>"
    Examples:
      | input 							| output  	| 
      | http://nicelife.co.uk   		| yes		| 
      | https://www.nicelife.wales   	| yes		| 
      | htt://www.nicelife   			| no		| 
      | nicelife   						| no		| 
      | http://nicelife					| no		|
      | http://www.nicelife   			| no		| 
```

**Comment by kinmanli** [comment]
@nicolabingham you now cannot save 'http://www.nicelife' as a Target.

> I entered a malformed URL (htt://www.nicolaagain.co.uk) into the lookup URL bar. There is no error > message at this stage. Could we have one at this point informing the user that the URL is > malformed? 

If you now enter that url and click 'search' or 'add' it will show an error message.

![2015-03-25 13-27-19_w3act](https://cloud.githubusercontent.com/assets/1652105/6825458/adf42e42-d2f2-11e4-9bb7-033c8aa3ed3a.png)

> When I select Add to create a target with this malformed URL it is put into the title field as W3ACT > does not recognise it as a URL. It would be better to inform the user that the URL is malformed > rather than just adding it to the title field. This could confuse users.

**Comment by GilHoggarth** [comment]
Gone through examples above (listed as BDD tests) and all found to work as expected.

**Comment by GilHoggarth** [comment]
Still not working - allows http://www.duffurl.coaaa to be save.

**Comment by GilHoggarth** [comment]
Ah, Roger raises that with the new, lax domain names, this could be a valid URL. Leaving this ticket as open so it gets considered, but potentially this ticket is thus closed.

**Comment by PsypherPunk** [comment]
Looks like IANA do actually [publish](https://github.com/ukwa/w3act/issues/212#issuecomment-90591488) a list of registered TLDs. Potentially this could be integrated.

**Comment by anjackson** [comment]
Moved sanity-checking to a new issue: #336
