### ISSUE TITLE
Correcting malformed URLs from Andy's ACT

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#213]
Andy's-ACT evidently contains some malformed URLs associated with target records.

We need a CSV report of them all, including URL, Target Title, and target record ID, so they can be corrected by hand in Andy's ACT, ahead of being reimported to W3ACT.

cc @anjackson

**Comment by kinmanli** [comment]
Currently using Apache Common's UrlValidator and testing

**Comment by kinmanli** [comment]
Regex test for valid urls.

@peterwebster @GilHoggarth new file exportBadUrls.sh (same pattern as previous), which generates a CSV file in w3act-1.0

**Comment by peterwebster** [comment]
@anjackson I think that these malformed URLs need fixed directly in the production version of W3ACT. I suppose @GilHoggarth might need to extract this CSV file and pass to @nicolabingham to begin weeding ?

**Comment by peterwebster** [comment]
Assigning to @anjackson for addition to a milestone - I imagine 1.1.0 ?

**Comment by PsypherPunk** [comment]
Apologies, I sent @nicolabingham a list of Targets (13521, 16046, 16164, 16754) with malformed URLs earlier (didn't realise there was a ticket).

Acquired using the `/all` export and `django.core.validators.URLValidator`.

**Comment by nicolabingham** [comment]
The targets listed have all been edited so that the URLs are correct.

**Comment by peterwebster** [comment]
So, I guess this can be closed :-)
