### ISSUE TITLE
Incorrect display of number of targets

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#215]
The following filtered query for targets should almost certainly produce zero results (which is what happens in the list), but it still shows "Displaying 31 of 30"

http://www.webarchive.org.uk/actdev/targets/list?p=3&s=title&curatorId=37&organisationId=6&collections=2&licenseId=-1&flagId=293

**Comment by kinmanli** [comment]
latest commit shouldn't show pagination if no results. Should also apply this across the board to other 'list' pages with pagination

**Comment by peterwebster** [comment]
This looks good at the place reported.

The issue still occurs at:
http://www.webarchive.org.uk/actdev/crawlpermissions/list 
http://www.webarchive.org.uk/actdev/nominations/list
http://www.webarchive.org.uk/actdev/targets/collectiontargets?s=title&collectionId=2

Will add any more as I find them; but it's not a high priority.

**Comment by peterwebster** [comment]
Cheers @kinmanli : closing ticket now, but will reopen if I find any more of these
