### ISSUE TITLE
Filters not being applied in targets

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#216]
The license field doesn't seem to be being applied at all. This search should produce at least some results

http://www.webarchive.org.uk/actdev/targets/list?p=1&s=title&curatorId=-1&organisationId=-1&licenseId=271&flagId=-1

**Comment by kinmanli** [comment]
I think it might not be saving the target's license. Did look at it yesterday, will look again

**Comment by kinmanli** [comment]
filter licenses should work with new commit above

**Comment by peterwebster** [comment]
OK, the filter looks good now: closing ticket @kinmanli
