### ISSUE TITLE
Broken links in target lookup view

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#218]
We've already corrected these elsewhere, but I think that the 'archival' and 'mid-crawl' links at

http://www.webarchive.org.uk/actdev/targets/lookup

are not being generated properly.

**Comment by peterwebster** [comment]
See #64 and #170

**Comment by kinmanli** [comment]
Originally /actdev/targets/lookup never had archival and midcrawl in the results. It only had "mementos". Do you want them adding this?

https://github.com/ukwa/w3act/blob/master/app/views/targets/list.scala.html#L150
or

https://github.com/ukwa/w3act/blob/master/app/views/targets/targets.scala.html#L348-L352

**Comment by peterwebster** [comment]
Those are the ones @kinmanli . Would @anjackson favour removing them ?

**Comment by peterwebster** [comment]
@kinmanli I think we should agree to comment this column out, as they are superfluous at this point in the workflow

**Comment by peterwebster** [comment]
Thanks @kinmanli - closing this ticket now
