### ISSUE TITLE
CSV download from reports pages not working

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#222]
Hi @kinmanli :  an attempt to download CSV from this just hangs up the browser:

http://www.webarchive.org.uk/actdev/reportscreation/targets/?s=createdAt&o=desc&crawlFrequency=DAILY&tld=either

**Comment by peterwebster** [comment]
I'm using Chrome, and there's no visual indication that anything has happened, and I'm not finding the files anywhere in the Chrome Program Files, or in the WIndows download folder (which is where it would go by default). Same for /actbeta

**Comment by kinmanli** [comment]
I guess it never worked.

**Comment by peterwebster** [comment]
I'm not sure it even got tested here; never a priority.

While we're on the subject, could we make the output comma separated (looks like semi-colons in your screenshot.) ? [matches the filename and the user expectation]

**Comment by kinmanli** [comment]
@peterwebster might have to change the way it's done so the browser gets a "save as" popup

**Comment by kinmanli** [comment]
@peterwebster reports creation page now redirects to browser and shows a save as popup. Also, changed to colon

**Comment by peterwebster** [comment]
Looking good now; thanks @kinmanli . Closing ticket
