### ISSUE TITLE
Archivist unable to change role for user

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#225]
Hi @kinmanli :  when logged in as an archivist, I can make changes to all the fields in the record for a user, except one: the role.

I can remove a role, but not change it.  eg. I changed Ian Walker's record to remove him as an expert user, but can't add him as any other role.

http://www.webarchive.org.uk/actdev/curators/2

**Comment by kinmanli** [comment]
Fixed in next deploy

![screen shot 2015-01-07 at 15 53 04](https://cloud.githubusercontent.com/assets/1652105/5648318/7db73ffc-9685-11e4-9123-21e7886e4d85.png)

**Comment by peterwebster** [comment]
Hi @kinmanli that's great, thanks.

Two quite minor points that I now spot:

(i) a user shouldn't be able to have more than one role. As all the permissions are stacked such that an Expert User can do everything that a User can, plus extras, (and an Archivist all that an Expert can etc), there should be no reason for a user to need to toggle between two roles (and the UI doesn't support it in any case.)  Could @anjackson confirm ?  There are already generic archivist@bl.uk, expert etc users set up, should anything need testing.

(ii) an Archivist shouldn't be able to make any user a system admin - that should be reserved to users who are already sysadmin.

However, these are very low risk at this point, so making them low priority.

**Comment by kinmanli** [comment]
Sys Admin role option only available if logged in with a user with Sys admin role.

**Comment by anjackson** [comment]
I agree with you @peterwebster there should be no need to switch roles. Right now we have no need to allow users to hold multiple roles, but this may need a rethink later.

**Comment by peterwebster** [comment]
@kinmanli :  Archivist not able to make another user a SysAdm - great, thanks.

It looks as though an Archivist can give a user two roles:  should only be one, but this is not a blocker to going into production, so putting ticket on hold.
eg. http://www.webarchive.org.uk/actdev/curators/2

**Comment by peterwebster** [comment]
As the remaining point on this ticket is now covered at #274 , closing this ticket.
