### ISSUE TITLE
Archivist unable to add new curator record

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#226]
Trying this produces a 'This action is not allowed'

http://www.webarchive.org.uk/actdev/curators/search?p=0&s=name&o=asc&name=Test+Curator&action=addentry

Related to #223 ?

**Comment by peterwebster** [comment]
I managed to get past the previous issue and get to the screen to create a new curator, at:

http://www.webarchive.org.uk/actdev/curators/new?name=Test+Curator

However, it auto-populated the email field with my email (archivist@bl.uk) which is clearly an impossible use case.

I changed the email address to test.curator@bl.uk and got:

Execution exception[[PersistenceException: ERROR executing DML bindLog[] error[ERROR: duplicate key value violates unique constraint "uq_creator_url"\n Detail: Key (url)=(act-61) already exists.]]]

**Comment by kinmanli** [comment]
@peterwebster this is because after each deploy we need to run the script "./resetSequence.sh'. @GilHoggarth This is to reset the sequence keys after each import from 'ACT'

**Comment by peterwebster** [comment]
Hi @kinmanli : I didn't get the exception this time, for which thanks.

The view is still auto-populating with the logged-in user's email and (I think) password. Both should default to being empty

![image](https://cloud.githubusercontent.com/assets/5520710/5875260/25a96224-a303-11e4-9c27-58f1589811b2.png)

**Comment by kinmanli** [comment]
I can't seem to recreate this. I think it is to do with your browser saving (login fields) 'email' and 'password' fields and will auto-populate it.

![2015-01-23 14-25-44_w3act](https://cloud.githubusercontent.com/assets/1652105/5876045/b18bf204-a30b-11e4-9fac-45c0e73cf2cf.png)

**Comment by peterwebster** [comment]
Hi @kinmanli :  yes, the auto-populating thing is to do with Chrome storing details.

The duplicate email issue is dealt with at #243 so closing this ticket now.
