### ISSUE TITLE
Creation of new target populates Title field with URL

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#227]
When I search here for a URL of a new target

http://www.webarchive.org.uk/actdev/targets/lookup?f=TestTarget3.co.uk

and then hit Add Target. the new target record view open, but placing the URL in the title field. It should really be added to the URL field.  As it is,, users will only cut and paste it from one field to the other.

**Comment by kinmanli** [comment]
if it is an absolute URL (http://www.google.co.uk) then put it the url field else put it in the title field. It will not work with part URL's such as google.com

**Comment by peterwebster** [comment]
Thanks @kinmanli this is great. Closing ticket
