### ISSUE TITLE
Incorrect default values in fields in new targets

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#228]
I just created and saved http://www.webarchive.org.uk/actdev/targets/15742#overview and many fields have incorrect default values. 

(a) I populated the subject field with one parent value, and it has saved several child values, and not the parent (I think - don't remember which one I selected)

I selected no other values, and so all the following are wrong:

(b) Nominating Organisation should be populated automatically

(c) 'Selector' should auto-populate with the logged in user.

(d) Language should default to Null.

(e) Selection Type should default to Selection.  Nomination is the value for those that have come in through the nomination page - the workflow for that hasn't yet been built (for turning a nomination to a target record)

(f) in the Crawl Policy, all fields should default to null, except Crawl Frequency which correctly default to "Domain Crawl Only"

(g) in the LD scope tab, everything should default to null except the ones that are being checked dynamically.

(h) UKWA Licensing tab: the Licence field should default to null.

**Comment by kinmanli** [comment]
a, b, c, d, e (except nomination) fixed

**Comment by kinmanli** [comment]
@peterwebster what needs change on the NPLD tab?

![screen shot 2015-01-11 at 17 44 54](https://cloud.githubusercontent.com/assets/1652105/5696115/a20622c4-99b9-11e4-9bc9-33047df8ca68.png)

**Comment by peterwebster** [comment]
At the moment, I'm getting an error when I try to save a new record:  Execution exception[[NumberFormatException: For input string: ""]]

I think I got all the required fields.

In answer to your question above, that looks right in the NPLD tab. IS there something @kinmanli that you're not sure about ?

 - UK Hosting should be happening dynamically 
- UK TLD is a validation on the URL itself.  [NB I don't think this is happening]
- UK Reg - I think this is also dynamic ?
- No values for any of the remaining.

**Comment by kinmanli** [comment]
@peterwebster (@anjackson) these 3 values 'ukhosting', 'topleveldomain' and 'isukregistration' are dynamically looked up all the time on every page view, edit. There are also these 3 fields stored the database (from previous code).

Do you want it to stay dynamic so everytime we search based on these values/filters we do a 'dynamic' check (will be slower), or do you want them persisted and saved so the search is quicker? Maybe do the dynamic check and save when persisting the 'Target'?

**Comment by anjackson** [comment]
I think rechecking should be occasional, e.g. when the Target is saved etc. Not every single time it's used at all.

**Comment by kinmanli** [comment]
Rechecking is done on 'ukhosting', 'topleveldomain' and 'isukregistration' on a Target save and update.

**Comment by peterwebster** [comment]
@anjackson I don't have an easy way of testing this from the UI alone; can it be done via checking the trace in the logs ?

**Comment by kinmanli** [comment]
![2015-01-23 14-38-30_w3act](https://cloud.githubusercontent.com/assets/1652105/5876268/d68e2ade-a30d-11e4-878b-bf1481c7fa62.png)

![2015-01-23 14-42-38_w3act](https://cloud.githubusercontent.com/assets/1652105/5876301/0f95a9e2-a30e-11e4-82a7-a2c038b61770.png)

![2015-01-23 14-43-04_w3act](https://cloud.githubusercontent.com/assets/1652105/5876303/12b8bf38-a30e-11e4-8293-beebd0e0eed6.png)

**Comment by peterwebster** [comment]
I just created this new target, which doesn't exist: but the UI suggests that it is hosted and registered in the UK.  It is correct when in Edit mode, but the View mode is wrong.

http://www.webarchive.org.uk/actdev/targets/16182#crawlpermission

It also set the Professional Judgement field to Yes, when it should default to null.  @kinmanli

**Comment by peterwebster** [comment]
Question for @anjackson :  in the crawl policy tab, I'm having second thoughts about what the default values should be. At the minute, if a new target record is created and saved without populating the fields, both Scope and Depth default to null, and Frequency to Domain Crawl Only. What will Heritrix do with that target ? Presumably it won't know what to do.

I don't think that all users who can create a target record have the right to edit these fields so they can't be made required fields - so do we need some positive default values ?

**Comment by kinmanli** [comment]
Fixed the professional judgement issue.

@peterwebster can you tell me the url you used so I can recreate it?

Cheers

**Comment by anjackson** [comment]
For parity with Andy's ACT:
* Default scope should be 'All URLs that start like this.'
* Default depth should be 'Capped'.
* And, if a crawl frequency other than 'Domain Crawl Only' is set, the start date should default to the 09:00am on the current date.

**Comment by peterwebster** [comment]
Relates to #242

**Comment by peterwebster** [comment]
Professional Judgement issue sorted. Just the default values in Crawl Policy tab remaining to do.

**Comment by kinmanli** [comment]
@anjackson I've got it defaulting to 09:00 for non "Domain Crawl Only".

Are curators able to set a time?

**Comment by peterwebster** [comment]
@kinmanli only archivists, I think  @anjackson ?

**Comment by anjackson** [comment]
Let's say yes, for now anyway.

**Comment by kinmanli** [comment]
fixed added timepicker

**Comment by peterwebster** [comment]
I think that the remaining elements in this ticket are open elsewhere, so closing this one now.
