### ISSUE TITLE
Execution exception when beginning a new licence request

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#229]
If I try to start a new Open UKWA licence process using the green button at:

http://www.webarchive.org.uk/actdev/targets/10/edit#licensing

I get

Execution exception[[MatchError: null]]

If you could prioritise this one @kinmanli , I'd be obliged, as without it I can't test the rest of the process.

**Comment by kinmanli** [comment]
@peterwebster fixed in next deploy

**Comment by peterwebster** [comment]
Thanks @kinmanli . Closing ticket now.
