### ISSUE TITLE
Unable to save instance record

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#230]
http://www.webarchive.org.uk/actdev/instances/13/edit

I'm unable to save any changes to a instance record.

"Bad Gateway:  The proxy server received an invalid response from an upstream server.

Could you prioritise this one @kinmanli ? Cheers

**Comment by kinmanli** [comment]
Seems like is Instance record 13

This one seems to work:

http://www.webarchive.org.uk/actdev/instances/2/edit

![2015-01-09 15-10-59_w3act](https://cloud.githubusercontent.com/assets/1652105/5681582/aa99cf16-9811-11e4-9400-ad1dbfdf6a6b.png)

**Comment by peterwebster** [comment]
@anjackson any ideas on this Andy ? Is it just the length of the contents ?

**Comment by peterwebster** [comment]
@anjackson  : @kinmanli thinks that this related to maximum allowable field lengths. How typical is this amount of data, do you think ? 60,000 characters seems to work, and I would have thought that this was long enough ?

**Comment by peterwebster** [comment]
@kinmanli let's set the limit at 60,000 characters (or whatever the easiest number was) - if users need more, we can revisit this some other time.

**Comment by kinmanli** [comment]
@peterwebster what about existing "Instances" etc that require editing and saving? Do we truncate certain fields on import?

**Comment by peterwebster** [comment]
Good question @kinmanli : what does @anjackson think ?

Are there many in Andy's ACT that are very long ? Can we easily find out ?

**Comment by peterwebster** [comment]
@kinmanli @anjackson Kinman and I discussed this today. Very long fields import OK, but will present a problem next time they;re saved in W3ACT.

**Comment by peterwebster** [comment]
So @anjackson if there is only an issue with this single record, it may be that we can leave it. It will import correctly. Users are unlikely to reinspect this instance and want to update the record.

**Comment by anjackson** [comment]
Hm, not liking this. Seems maybe the framework is getting in the way? http://stackoverflow.com/questions/18085291/play-framework-not-receiving-big-post-data

Can we fix this as outlined here: https://www.playframework.com/documentation/2.2.x/JavaBodyParsers#Max-content-length

**Comment by kinmanli** [comment]
@peterwebster fixed in next deploy

**Comment by peterwebster** [comment]
OK, this looks good now. Closing ticket, thanks @kinmanli
