### ISSUE TITLE
Auto-populate Instances for a given Target based on what's in Wayback

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#231]
The original intention was that W3ACT would take the 'lead' URL for a site and auto-populate the instances based on what's in Wayback. e.g.

http://www.webarchive.org.uk/wayback/archive/xmlquery.jsp?url=http://www.bl.uk/bibliographic/ukmarc.html

Similarly, our internal Wayback instance has an XML query endpoint that allows you to look up the dates we have instances for.

The idea would be to automatically scan for new instances when a Target is visited, but to also have a special URL we can call every night that checks for new instances of all Targets.

**Comment by anjackson** [comment]
How's that, Peter?

**Comment by peterwebster** [comment]
@anjackson wondering whether to dynamically check for each target record when opened by user might not slow things down. Perhaps just on creation of a *new* record ? So:

(i) User creates new target record -> ACT checks for instances of that target in Wayback > creates new instance record for each

AND

(ii) nightly, ACT checks the Wayback XML endpoint for instances of any targets for which there are not existing instance records (ie checking instances with timestamps since the last check) > creates new instance records for each.

@kinmanli how much work do you think this might be ?

**Comment by kinmanli** [comment]
@anjackson if i was to deal with a Target with a url "https://www.gov.uk/government/publications". Is the url to wayback

"http://www.webarchive.org.uk/wayback/archive/xmlquery.jsp?url=https://www.gov.uk/government/publications" ????

As it gives me "Resource Not In Archive"

or is it the domain? 

"http://www.webarchive.org.uk/wayback/archive/xmlquery.jsp?url=https://www.gov.uk/" 

Cheers

**Comment by anjackson** [comment]
Hello, yes, that was the right URL for the public instance, which you can use for testing. Unfortunately, there was a problem with it, but it's fixed now.

However, note that in production, this should be pointing to our internal QA Wayback (which gets to see much more content much earlier than the public Wayback) so the location of this endpoint should be configurable.

**Comment by peterwebster** [comment]
@kinmanli I created a new target, saved the record; and then hit Get New Instances.

I know this site, and doubt it is in the public Wayback - so this may have returned no new instances - is that why I get?

Execution exception[[RuntimeException: uk.bl.exception.ActException: javax.xml.bind.UnmarshalException - with linked exception: [java.io.FileNotFoundException: http://www.webarchive.org.uk/wayback/archive/xmlquery.jsp?url=http://www.fishbournepreschool.org.uk/]]]

There should be a better messaging if the check returns no instances.

**Comment by peterwebster** [comment]
@anjackson @kinmanli just to confirm that it would be good if this endpoint was the QA Wayback soonish, so I can test the workflows

**Comment by peterwebster** [comment]
@anjackson @kinmanli is it going to be possible to see the daily check in action before we go into production ? I imagine it might not be straightforward, but I don't think it is running so far - I would expect lots of instances to show up at http://www.webarchive.org.uk/actdev/qa/list?f=bbc.co.uk if it was

**Comment by kinmanli** [comment]
QA - http://crawler03.bl.uk:8080/wayback/xmlquery.jsp?url=http://www.bbc.co.uk/

**Comment by kinmanli** [comment]
Friendlier message when there are no new instances or bad url. Also, set to QA wayback url

**Comment by anjackson** [comment]
@kinmanli to answer @peterwebster's question, is there a hook URL that will look for new instances for all targets?

**Comment by kinmanli** [comment]
@anjackson @peterwebster I've created a script to do it (was thinking CRON). Can easily attach it to a URL?

**Comment by anjackson** [comment]
Oh, that's fine then. I was suggesting a web hook because I thought that might be easier, but you've already written a script so that's simpler to cron. Let's ask @GilHoggarth if he'll add an act-dev hook that will run your script nightly...

**Comment by GilHoggarth** [comment]
So, I should configure this 'waybackinstance_import.sh' script to run nightly. @kinmanli Given /actdev redeploys/restarts daily at 17, when should i schedule this script to run?

**Comment by kinmanli** [comment]
@GilHoggarth depends when @peterwebster will want to start testing this functionality?

**Comment by peterwebster** [comment]
@GilHoggarth @kinmanli well, I guess that out of normal hours is the best time, so this evening, after the service has redeployed ? No preference as to exact time

**Comment by GilHoggarth** [comment]
@kinmanli Looking at the actual 'waybackinstance_import.sh' script, I'm afraid that that won't work. The PLAY_HOME envar won't resolve as this script lives as /opt/w3act/ - so3 levels up is actually to /, and I don't have a /tools/ directory for play 2.2.1 (even though, to clarify, we are using v2.2.1). I'm assuming therefore that your dev environment is different from the server environment.

**Comment by kinmanli** [comment]
@GilHoggarth Yes just remove the "tools" directory and it will tell you to enter your play home directory.

**Comment by GilHoggarth** [comment]
@kinmanli But this should be done in the repo not on the server to be included in future deployments. I'd suggest  this should be set as
`PLAY_HOME=/opt/play`
But I don't know if that's what you want it to be. Please test and deploy as appropriate.

**Comment by kinmanli** [comment]
@GilHoggarth I've tested it and works locally. Never tested it on your servers.

But will set to /opt/play

**Comment by peterwebster** [comment]
This also needs documenting in the system installation documentation @kinmanli (if it isn't already)

**Comment by GilHoggarth** [comment]
Sorry, ticket lost in the mud. Can I test this script now? (Or wait until after the current conference call?)

**Comment by peterwebster** [comment]
Go ahead @GilHoggarth

**Comment by kinmanli** [comment]
@GilHoggarth this line should pick up the class "./target/scala-2.10/classes"

```
CLASSPATH=${CLASSPATH}:./target/scala-2.10/classes:./conf:./target/scala-2.10/classes_managed:./target/scala-2.10/src_managed:.
```

**Comment by GilHoggarth** [comment]
The file exists:
```
[root@actdev01 ~]# find /opt/w3act/ -name "WaybackExport.*" -ls
  3788   28 -rw-r--r--   1 root     root        27690 Feb  3 17:03 /opt/w3act/target/scala-2.10/api/uk/bl/export/WaybackExport.html
  2375    8 -rw-r--r--   1 root     root         5862 Feb  3 17:02 /opt/w3act/target/scala-2.10/classes/uk/bl/export/WaybackExport.class
  3867   28 -rw-r--r--   1 root     root        27690 Feb  3 17:03 /opt/w3act/target/universal/stage/share/doc/api/uk/bl/export/WaybackExport.html
396127    4 -rw-r--r--   1 root     root         2676 Feb  3 17:00 /opt/w3act/app/uk/bl/export/WaybackExport.java
``` 
But still, the `waybackinstance_import.sh` doesn't execute:
```
/opt/w3act/waybackinstance_import.sh
:./target/scala-2.10/classes:./conf:./target/scala-2.10/classes_managed:./target/scala-2.10/src_managed:.
Error: Could not find or load main class uk.bl.export.WaybackExport
```

**Comment by kinmanli** [comment]
@GilHoggarth Try changing the classpath to this.

CLASSPATH=${CLASSPATH}:/opt/w3act/target/scala-2.10/classes:/opt/w3act/conf:/opt/w3act/target/scala-2.10/classes_managed:/opt/w3act/target/scala-2.10/src_managed:.

**Comment by GilHoggarth** [comment]
Now produces
```
:/opt/w3act/target/scala-2.10/classes:/opt/w3act/conf:/opt/w3act/target/scala-2.10/classes_managed:/opt/w3act/target/scala-2.10/src_managed:.
Exception in thread "main" java.lang.NoClassDefFoundError: play/db/ebean/Model
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
        at java.lang.Class.getMethod0(Class.java:2774)
        at java.lang.Class.getMethod(Class.java:1663)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: play.db.ebean.Model
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more
```

**Comment by kinmanli** [comment]
@GilHoggarth isn't that the same exception you got yesterday with the var REPO?

**Comment by GilHoggarth** [comment]
Yep, looks very similar...

**Comment by kinmanli** [comment]
@GilHoggarth what do you get when you

```
echo $CLASSPATH
```

**Comment by GilHoggarth** [comment]
You mean just in a xterm? Nothing, blank, no previously set values.

**Comment by GilHoggarth** [comment]
Ah, if you mean from the script when run - `:/opt/w3act/target/scala-2.10/classes:/opt/w3act/conf:/opt/w3act/target/scala-2.10/classes_managed:/opt/w3act/target/scala-2.10/src_managed:.`

**Comment by kinmanli** [comment]
@GilHoggarth this line is pulling in the play libs on your server

```
	CLASSPATH=$(find "${REPO}" -name '*.jar' | xargs echo | tr ' ' ':')
```

**Comment by GilHoggarth** [comment]
Added back in the ending slash on PLAY_HOME, plus your full path directories in CLASSPATH above.
Script now running (after opening 8080 on crawler03). Will schedule to run every night at 10pm.

**Comment by GilHoggarth** [comment]
@peterwebster Can you test this import wayback instances script tomorrow please (Thursday, or at least after tonight when it's scheduled to run via cron.)

**Comment by peterwebster** [comment]
Hi @GilHoggarth @kinmanli : I think I would expect to see some instance records showing up here

http://www.webarchive.org.uk/actdev/qa/list?f=bbc.co.uk

and then here:

http://www.webarchive.org.uk/actdev/instances/listbytarget/?s=title&t=2973

I'm not clear whether this means that (a) there are no instance records to show, or (b) there are, but the UI is not looking in the right place for them.

**Comment by kinmanli** [comment]
When I query my local DB there aren't any Instances for Target 2973. I assume it's be the same for prod? @GilHoggarth 

```
select * from instance where target_id=2973
```

**Comment by GilHoggarth** [comment]
Likewise, no instances for this target. And the instance table has 1233 records fyi.

**Comment by anjackson** [comment]
@GilHoggarth are there any crashes or logging when the cron job runs?

**Comment by GilHoggarth** [comment]
We're talking about `waybackinstance_import.sh` I believe. It generates `~/logs/application.log` and does not contain any [ERROR] or [WARN]. Cronjob starts at 11pm and log written 11.46pm.

**Comment by peterwebster** [comment]
@GilHoggarth @kinmanli is it possible to get some numbers of how many new instances it detected for the last few nights? @PsypherPunk will correct me, but I think we have a number of targets on daily schedules, so there should be at least some new targets each night.

**Comment by GilHoggarth** [comment]
Checking this on the new w3act potential production server, which builds the play application as a standalone application, I see that `waybackinstance_import.sh` fails to run because it can't find the necessary java class `uk.bl.export.WaybackExport`.
@kinmanli Another class needing identifying in the `play dist` version (and in this case, inclusion as well as mapping as this class really doesn't exist on the new server.)

**Comment by kinmanli** [comment]
@GilHoggarth 

Change 

CLASSPATH=${CLASSPATH}:/opt/w3act/target/scala-2.10/classes:/opt/w3act/conf:/opt/w3act/target/scala-2.10/classes_managed:/opt/w3act/target/scala-2.10/src_managed:.

to:

CLASSPATH=${CLASSPATH}:./lib/*:.conf:.

**Comment by GilHoggarth** [comment]
Currently this still isn't working:
```
[root@act05 act]# /root/bin/waybackinstance_import.sh
2015-02-12 16:32:39,824 [error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:FATAL: database "w3act2" does not exist
Exception in thread "main" Configuration error: Configuration error[Cannot connect to database [default]]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92)
        at play.api.Configuration.reportError(Configuration.scala:570)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at play.api.db.BoneCPPlugin.onStart(DB.scala:243)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
        at play.api.Play$.start(Play.scala:87)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:52)
        at uk.bl.export.WaybackExport.main(WaybackExport.java:84)
Caused by: org.postgresql.util.PSQLException: FATAL: database "w3act2" does not exist
        at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:471)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:112)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
        at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
        at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
        at org.postgresql.Driver.makeConnection(Driver.java:393)
        at org.postgresql.Driver.connect(Driver.java:267)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
        at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245)
        ... 17 more
```

**Comment by kinmanli** [comment]
@gilhoggarth this is because it is reading in application.conf (which contains w3act2 database). Need to figure out a way to pass in prod.conf to:

new play.core.StaticApplication(new java.io.File("."));

**Comment by anjackson** [comment]
Setting 

    -Dconfig.file=/path/to/file.conf

should always work, I think.

**Comment by kinmanli** [comment]
@anjackson that only works with play files. This is called within code

**Comment by kinmanli** [comment]
https://github.com/playframework/playframework/issues/876

**Comment by kinmanli** [comment]
https://github.com/playframework/playframework/issues/876

**Comment by kinmanli** [comment]
as @anjackson stated putting this in the script works. Checked in.

```
-Dconfig.file=conf/prod.conf
```

**Comment by GilHoggarth** [comment]
@kinmanli I changed this to `-Dconfig.file=/opt/w3act/conf/prod.conf` as full path is needed, and ran - looked like it was running (i.e., too ~20 seconds) then
```
[root@act05 act]# /root/bin/waybackinstance_import.sh
Working Directory = /root/git/act
Exception in thread "main" javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[ERROR: duplicate key value violates unique constraint "uq_instance_url"\n   Detail: Key (url)=(act-12668) already exists.]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97)
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:66)
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:82)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:452)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:365)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:308)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:280)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:248)
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1568)
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1558)
        at com.avaje.ebean.Ebean.save(Ebean.java:453)
        at play.db.ebean.Model.save(Model.java:91)
        at models.ActModel.save(ActModel.java:47)
        at models.Instance.save(Instance.java:35)
        at uk.bl.export.WaybackExport.bulkTargetImport(WaybackExport.java:71)
        at uk.bl.export.WaybackExport.main(WaybackExport.java:85)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uq_instance_url"
  Detail: Key (url)=(act-12668) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334)
        at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
        at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:55)
        at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:80)
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86)
        ... 16 more
```
PS I haven't checked this full path into github. Please do so if this eventually works.

**Comment by kinmanli** [comment]
@GilHoggarth I don't get that on here.

What happens after that?

**Comment by GilHoggarth** [comment]
Not sure what you mean - the script died at this point.

**Comment by kinmanli** [comment]
@GilHoggarth I guess that instance (act-12668) has already been imported?

**Comment by kinmanli** [comment]
@GilHoggarth  A current Instance already has an "act id" (i.e. act-12668). New ones are generated for the wayback import. Please checkout and redeploy

**Comment by kinmanli** [comment]
@GilHoggarth did you manage to re-run this?

**Comment by GilHoggarth** [comment]
I tried it on a redeployed and data imported /actdev but that reported `Could not find or load main class uk.bl.export.WaybackExport`.

Ran on w3act which as yet hasn't be redeployed and is of course using the original data imported a week ago, and it reported as nearest log dump above. Currently waiting for @peterwebster to tell me when I can redeploy w3act but it won't include a data import.

So, given you mention there's "A current instance already has an "act id" ...", is there another way around testing this that doesn't require a data import?

**Comment by anjackson** [comment]
I'm concerned there is some confusion here. Are we all clear that this Instance import function is entirely separate from the Target import function?

Target import has been done, and should not be repeated in the future, because instead of going to Andy's ACT we should be deploying test W3ACT versions on top of Postgres DB dumps from production W3ACT.

Instance import should run frequently on production W3ACT, and talks only to Wayback in order to pull in instances of existing Targets.

**Comment by kinmanli** [comment]
@gilhoggarth @anjackson yes as mentioned above it only imports from wayback and creates instances

**Comment by kinmanli** [comment]
Hi @GilHoggarth, did you manage to sort the classpath out? My settings are like this:

```
#!/bin/bash

JAVA_HOME=/usr

# Check envars
if [ ! -d "$JAVA_HOME" ]; then
    echo "JAVA_HOME not defined or not directory. Exiting."
    exit 1
fi

${JAVA_HOME}/bin/java -cp "lib/*" -Dconfig.file=conf/prod.conf uk.bl.export.WaybackExport
```

**Comment by peterwebster** [comment]
For me @gilhoggarth , you can redeploy the prod version of W3ACT (without
data import) whenever you like, if it's ok with @anjacks0n

**Comment by GilHoggarth** [comment]
@kinmanli It occured to me that /actdev, where I'm trying to test `waybackinstance_import.sh` wasn't built into a 'play dist', so I've added the classpath details back into the /actdev version. The script has now been running for ~5 minutes on /actdev and hasn't reported an issue.

@peterwebster w3act restarted just now, 4.56pm.

**Comment by peterwebster** [comment]
@GilHoggarth @kinmanli there seems to be many more instance records today, but I won't be able to test this until the Null Pointer error at #263 is fixed

**Comment by GilHoggarth** [comment]
@peterwebster @kinmanli That would be me, or at least my action. Ran the `waybackinstance_import.sh` script on w3act without a failure! It doesn't report anything so I don't know what I did but "many more instance records", assuming relating to wayback, sounds good!

**Comment by peterwebster** [comment]
So, the most recent instances I'm seeing in /actdev this morning are dated 13 Feb; does that sound about right @PsypherPunk ? I had thought there were some daily crawl schedules, but perhaps they won't have made it into the QA Wayback.

http://www.webarchive.org.uk/actdev/qa/list?f=www.guardian.co.uk

**Comment by anjackson** [comment]
It should be easy to check this by going to the QA Wayback and checking by hand if the Guardian is up to date.

**Comment by GilHoggarth** [comment]
Might this be because The Guardian changed their domain? http://www.webarchive.org.uk/actdev/wayback/*/http://www.theguardian.com lists to Feb 22 2015.

**Comment by peterwebster** [comment]
It may be as @GilHoggarth says that this target is a bad example, having multiple seeds, but it would be worth clarifying (at least) why there are more recent instances at:
http://www.webarchive.org.uk/actdev/wayback/*/http://www.theguardian.com/

than listed at http://www.webarchive.org.uk/actdev/instances/listbytarget/?t=790 (the first one in the list)

Any ideas @PsypherPunk @kinmanli @anjackson ?

**Comment by peterwebster** [comment]
And indeed, all three URLs have instances in Wayback to the 23rd Feb, but ACT think the most recent is 13 Feb.

**Comment by kinmanli** [comment]
@GilHoggarth when was the last time the instance import ran?

**Comment by GilHoggarth** [comment]
Guessing you mean /actdev and looking into this I wonder if it's suceeded - the script states prod.conf but of course on /actdev this should be application.conf.

If you mean w3act (https://act) then I think it was a few days ago. The script in github doesn't state the directory for the prod.conf and evidently has been failing. I thought I'd fixed this, but have now fixed it outside of the script.

Would you like the `/opt/w3act/waybackinstance_import.sh` script to be run now? On /actdev and/or /act?

**Comment by kinmanli** [comment]
yes please run on actdev @GilHoggarth

**Comment by kinmanli** [comment]
@peterwebster Does this look correct now? Latest 23/02/2015 after @GilHoggarth did a wayback import to actdev.

![screen shot 2015-02-25 at 17 42 00](https://cloud.githubusercontent.com/assets/1652105/6376440/b2154bf2-bd15-11e4-8e81-7f85604d8d47.png)

**Comment by peterwebster** [comment]
OK, this looks good to me. If @anjackson is happy, could he close the ticket ?

**Comment by anjackson** [comment]
@GilHoggarth could you add /opt/w3act/waybackinstance_import.sh to the test deployment script? Then this can be closed.

**Comment by kinmanli** [comment]
@GilHoggarth fixed (needed to run import)

**Comment by GilHoggarth** [comment]
/actdev is a "play target" service so it's libraries are scattered whereas w3act is a "play dist" service with all the libraries in one directory. So the triggering script (that runs the actual script) is slightly different on /actdev compared to w3act. Anyhoo, this is scheduled on both servers as a late night crontab, and both are being run at the moment to test that they work as expected.

**Comment by GilHoggarth** [comment]
/actdev script was referencing the prod.conf not application.conf, so changed this and rerunning. If run completes as expected, I'll close this ticket.

**Comment by GilHoggarth** [comment]
Import on /actdev worked as expected. Closing ticket.

**Comment by GilHoggarth** [comment]
Reopening so the same test is performed on w3act.

**Comment by GilHoggarth** [comment]
Ran the `waybackinstance_import.sh` script on w3act - it logged its progress and claimed "finished". @kinmanli As you know what this does, can you check that it has done what it should do via the UI please.

**Comment by kinmanli** [comment]
@GilHoggarth if you can make my user an archivist then I'll be able to see the results.

I've just checked the old listing code for instances and the results are only viewable by sysadm and archivist. Is this correct or should it be viewable by all roles @peterwebster?

**Comment by peterwebster** [comment]
@kinmanli at which point in the UI is the view you're talking about ?

**Comment by kinmanli** [comment]
@peterwebster 

http://www.webarchive.org.uk/actdev/instances/listbytarget/?t=790
https://www.webarchive.org.uk/act/instances/list/

**Comment by GilHoggarth** [comment]
@kinmanli Done, you're now an w3act archivist.

**Comment by kinmanli** [comment]
@GilHoggarth this looks good with the latest ones being 24/02/2015

![screen shot 2015-02-27 at 11 00 47](https://cloud.githubusercontent.com/assets/1652105/6411409/056be148-be70-11e4-87ee-fefb4cbd1203.png)

There are 3 from 25/02/2015 on http://www.webarchive.org.uk/actdev/wayback/*/http://www.theguardian.com/ but I guess they will get imported on the next run

**Comment by anjackson** [comment]
I think instances should be visible to everyone, surely?

**Comment by nicolabingham** [comment]
Yes, as users at all levels will want to see what has been crawled and when.

**Comment by GilHoggarth** [comment]
@kinmanli Following Nicola's above comment I've tested https://www.webarchive.org.uk/act/instances/listbytarget/?t=790 to be accessible by the admin user and by me (gil.hoggarth, just user!) I couldn't see the results as me

**Comment by kinmanli** [comment]
@GilHoggarth @nicolabingham my user with role 'viewer' can now view and search instances.

checked in

![screen shot 2015-02-27 at 13 00 24](https://cloud.githubusercontent.com/assets/1652105/6412835/bce2ba62-be80-11e4-860a-c359a6ca8ac6.png)
![screen shot 2015-02-27 at 12 58 54](https://cloud.githubusercontent.com/assets/1652105/6412836/bcf89aee-be80-11e4-8ee3-00b0c0e8fae1.png)

Also, I removed all trailing slashes '/' (after 'listbytarget'). So:

```
https://www.webarchive.org.uk/act/instances/listbytarget/?t=790
```

Is now:

```
https://www.webarchive.org.uk/act/instances/listbytarget?t=790
```

Same for:

```
https://www.webarchive.org.uk/act/instances/list?f=http%3A%2F%2Fwww.islamic-relief.or

**Comment by GilHoggarth** [comment]
Note **To be tested after new w3act deployment**

**Comment by GilHoggarth** [comment]
`https://www.webarchive.org.uk/act/instances/listbytarget?t=790` can now be viewed by a 'user' account, the admin account, but not by a not-logged-in visitor.
Running import script again to check new data still comes in...

**Comment by GilHoggarth** [comment]
Script run completed and new imports seen - closing ticket.
