### ISSUE TITLE
Validation error - contact persons when creating new crawl permission

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#233]
If a user tries to create a crawl permission where the 'Contact Person Name' does not match an existing record for the email address being supplied, there is some validation. Two issues with this:

(i) the alert message is wrong - in the example below, the given name "Manifesto Club" is being picked up from the field - it should come from Contact Person Name, not the name of the target.

"A contact person with email 'peter.webster@bl.uk' is already in the Contact Persons list, but with the Name 'Peter Webster' which is different from the given name 'Manifesto Club'. Please review the revised details below and click Save, or enter an alternative contact email address."

(ii) in these cases, the Contact Person Name supplied should be replaced by the existing one, and the user asked to check and Save. This isn't happening.

**Comment by peterwebster** [comment]
Also under issue (ii) - if I manually correct the input in the Contact Person Name field, it doesn't get saved (although the crawl permission does.)

**Comment by kinmanli** [comment]
@peterwebster 

with (ii) if alert message appears does the contact person which is already stored in the database overwrite the one in the browser or the other way round?

**Comment by peterwebster** [comment]
The one already stored should overwrite the one the user has just entered
in browser

On Tue, Jan 13, 2015 at 2:48 PM, kinmanli <notifications@github.com> wrote:

> @peterwebster <https://github.com/peterwebster>
>
> with (ii) if alert message appears does the contact person which is
> already stored in the database overwrite the one in the browser or the
> other way round?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/w3act/issues/233#issuecomment-69754557>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by kinmanli** [comment]
Fixed in next release

**Comment by peterwebster** [comment]
Hi @kinmanli  - that's fixed, many thanks.

For some reason, if the user does not populate the Position field, it gets populated with the login name of the ACT user. This shouldn't be happening - it isn't a required field.

**Comment by kinmanli** [comment]
@peterwebster the position field was in there previously. Do you want me to remove it altogether?

Thanks

**Comment by peterwebster** [comment]
@kinmanli no, the field should be there, but the W3ACT user is not required to populate it. It refers to the job title of the person being emailed, NOT the W3ACT user creating the permission.

**Comment by kinmanli** [comment]
@peterwebster which fields did/not you populate?

http://www.webarchive.org.uk/actdev/crawlpermissions/2

![screen shot 2015-01-14 at 16 41 42](https://cloud.githubusercontent.com/assets/1652105/5742766/71a3cbea-9c0c-11e4-9bdc-b3864fccd5c7.png)

**Comment by peterwebster** [comment]
@kinmanli

Position  http://www.webarchive.org.uk/actdev/crawlpermissions/1

On Wed, Jan 14, 2015 at 4:44 PM, kinmanli <notifications@github.com> wrote:

> @peterwebster <https://github.com/peterwebster> which fields did/not you
> populate?
>
> http://www.webarchive.org.uk/actdev/crawlpermissions/2
>
> [image: screen shot 2015-01-14 at 16 41 42]
> <https://cloud.githubusercontent.com/assets/1652105/5742766/71a3cbea-9c0c-11e4-9bdc-b3864fccd5c7.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/w3act/issues/233#issuecomment-69947026>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by kinmanli** [comment]
@peterwebster I can't seem to recreate. Have you tried logging in with a different user and recreating it?

**Comment by peterwebster** [comment]
OK, got it: it was populating the field with the value for the contact person it was matching to:
http://www.webarchive.org.uk/actdev/contactpersons/1
feeds the individual crawl permissions:  http://www.webarchive.org.uk/actdev/crawlpermissions/5 

My mistake @kinmanli : closing ticket now, all is well.
