### ISSUE TITLE
Unable to send UKWA licence permission from queue

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#234]
I've tried a couple of times to send the crawl permission issue from the queue here:

http://www.webarchive.org.uk/actdev/crawlpermissions/list

but it remains in the queue, and the email isn't getting sent.

Worth a look at this @kinmanli before the data is flushed out this evening, if you have time.  This is the permission in question:  http://www.webarchive.org.uk/actdev/crawlpermissions/1

**Comment by kinmanli** [comment]
@peterwebster has this worked before? Do you just create a crawl permission and then it will send it to the emailed you entered? I just created one on 'actbeta' and haven't received an email.

https://www.webarchive.org.uk/actbeta/crawlpermissions/act-2932390180724490841

**Comment by peterwebster** [comment]
Yes, this was working before - it might be that /actbeta isn't hooked up to
the email server ?

The ACT user identifies someone (outside the Library, at the website in
question) who could give permission > ACT user creates a crawl permission
with that external person's details, including email > email sent (there
are various templates) > that email has a link to the licence form which
the external person needs to complete

On Wed, Jan 14, 2015 at 4:36 PM, kinmanli <notifications@github.com> wrote:

> @peterwebster <https://github.com/peterwebster> has this worked before?
> Do you just create a crawl permission and then it will send it to the
> emailed you entered? I just created one on 'actbeta' and haven't received
> an email.
>
>
> https://www.webarchive.org.uk/actbeta/crawlpermissions/act-2932390180724490841
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/w3act/issues/234#issuecomment-69945548>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by kinmanli** [comment]
Can't seem to find where it emails the contact person on the 'save' in the old code

https://github.com/ukwa/w3act/blob/master/app/controllers/CrawlPermissions.java#L357-L547

**Comment by peterwebster** [comment]
Apologies, there's a missing step in my comment:

- crawl permission saved with contact person
- archivist visits queue, which lists queued crawl permissions, selects the
ones to send, and clicks Send
- then the email goes out

On Thu, Jan 15, 2015 at 2:56 PM, kinmanli <notifications@github.com> wrote:

> Can't seem to find where it emails the contact person on the 'save' in the
> old code
>
>
> https://github.com/ukwa/w3act/blob/master/app/controllers/CrawlPermissions.java#L357-L547
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/w3act/issues/234#issuecomment-70096995>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by kinmanli** [comment]
![screen shot 2015-01-15 at 15 02 50](https://cloud.githubusercontent.com/assets/1652105/5759735/9d0d42f0-9cc7-11e4-85e5-f57a68f649b8.png)

**Comment by peterwebster** [comment]
And it was on selecting Send from this view that I couldn't send the email.
Keep our NHS Public just stayed in the queued list.

On Thu, Jan 15, 2015 at 3:03 PM, kinmanli <notifications@github.com> wrote:

> [image: screen shot 2015-01-15 at 15 02 50]
> <https://cloud.githubusercontent.com/assets/1652105/5759735/9d0d42f0-9cc7-11e4-85e5-f57a68f649b8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/w3act/issues/234#issuecomment-70098108>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by kinmanli** [comment]
Fixed for next release

**Comment by peterwebster** [comment]
@kinmanli I tried this just now, and the same issue occurs - should it have deployed the change to /actdev on Friday ?

**Comment by kinmanli** [comment]
@GilHoggarth When was the last deploy? Thanks

**Comment by GilHoggarth** [comment]
It should be daily at 5pm with latest data being pulled in (and sequence reset). However, checking I see that there's a typo in the automated job, so I think that last redeploy was Wednesday Jan 14 at ~10am. Having fixed the typo, the next redeploy will be in 30 minutes - and I'll check it completes afterwards.

**Comment by peterwebster** [comment]
@kinmanli OK; I got the email successfully sent out, and one to you; but you should see in that that it doesn't include the text for the email, but just the string 'default.txt' (which is the file containing the text)

**Comment by kinmanli** [comment]
@peterwebster I got it working by reading the text from default.txt (as seen below) (next deploy). Also, I don't think some of the other buttons are working correctly such as (preview etc).

![screen shot 2015-01-20 at 16 40 56](https://cloud.githubusercontent.com/assets/1652105/5821334/25f1c43e-a0c3-11e4-875b-17c4ddf0b70e.png)

**Comment by kinmanli** [comment]
@peterwebster when you do an email preview, can you only do it on one email as you can multi-select the checkboxes. Thanks

**Comment by kinmanli** [comment]
@peterwebster other buttons should now work. Reworked it so it goes and gets the CrawlPermissions for the selected checkboxes.

**Comment by peterwebster** [comment]
@kinmanli on the email preview, you're right; the Preview option should only work when a single checkbox is selected; otherwise it makes no sense.

**Comment by peterwebster** [comment]
@kinmanli another thing:  in the drop-down for templates, there should only be templates with Type=Permission Request

**Comment by peterwebster** [comment]
Error message : 'Please select only one email to preview.'

**Comment by kinmanli** [comment]
Now only has template with Permission Request types

![2015-01-23 15-04-45_java - w3act_app_controllers_crawlpermissioncontroller](https://cloud.githubusercontent.com/assets/1652105/5876687/199347d0-a311-11e4-9109-f7d423e13eec.png)

**Comment by peterwebster** [comment]
On trying to send out a permission email from the queue, I get:

Execution exception[[RuntimeException: javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 587; nested exception is: java.net.ConnectException: Connection refused]]

@kinmanli

**Comment by kinmanli** [comment]
@GilHoggarth @peterwebster need to test if prod server's smtp server is working. 

I tested locally whilst using smtp.gmail.com with my gmail settings

**Comment by anjackson** [comment]
To respond to an earlier question, but perhaps on the wrong issue, the URL used to enter the license should be a temporary 'un-guessable' one that can be accessed by users who are not logged in.

**Comment by GilHoggarth** [comment]
Just received correct email from /actdev/contact using user@bl.uk (to wa-sysadm@bl.uk)

**Comment by peterwebster** [comment]
Great @kinmanli : just two outstanding things on this:

(i) as @anjackson says, the URL for the license form that is included in the email needs to be something unguessable, rather than  http://www.webarchive.org.uk/actdev/ukwa/licenseform/act-22 - which could be guessed and thus used by someone other than the intended recipient.

(ii) slight amendment to the error message about selecting only one email in the queue to preview, as above.

**Comment by kinmanli** [comment]
@peterwebster 

URL and email now uses a generated token, i.e. http://localhost:9000/actdev/ukwa/licenseform/69b964d8-3efd-46d1-b2b2-5f4d56b86946

![2015-02-02 14-09-06_w3act](https://cloud.githubusercontent.com/assets/1652105/6001775/06b10a4a-aae5-11e4-856c-f0a820e26742.png)

![2015-02-02 14-09-26_uk web archive - message plain text](https://cloud.githubusercontent.com/assets/1652105/6001774/06773cf2-aae5-11e4-944d-267e6cf9e2c0.png)

**Comment by peterwebster** [comment]
Looks great @kinmanli  ,cheers. Closing ticket now.
