### ISSUE TITLE
Description of fields to review

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#237]
Feedback from Nicola to be addressed under this ticket (referring to AIT's DDHAPT docs):

3.8 Can we remove the term “Open tag”? I am not sure if this is an instruction or a description of the type of tag (e.g as opposed to ‘Closed’ tag). I think this is what the suggested solution is advocating but just checking.  
3.14 Even the term “LookUps” is quite technical. Replace with a more user-friendly term such as “Report”? 
3.21 The terms “mid-term” and “archival” on the URL links are a bit technical, can these links have a more instructive name?
3.43 Do the assigned permissions names have to have underscores in them?

**Comment by peterwebster** [comment]
Suggest more natural language at http://www.webarchive.org.uk/actdev/targets/lookup : Annual, Domain Crawl, etc

**Comment by peterwebster** [comment]
Assigning this to @nicolabingham to take forward....

**Comment by nicolabingham** [comment]
@anjackson Commenting on DDHAPT_User_Interface_Design_V0 9_2014-11-25.docx 
3.8 Add Tag Workflow. In Taxonomies > Open Tags, can the term 'Open Tags' be changed to 'Tags'. Similarly in the Search/Add bar can the text be changed from 'Enter Open Tag Name' to 'Enter Tag Name' ?

**Comment by nicolabingham** [comment]
@anjackson Commenting on 3.14 User Language 
Settings > Export LookUps. 
Change 'LookUps' to 'Reports', so that the title is 'Export Reports' 
Suggested help text for users "

**Comment by nicolabingham** [comment]
I will discuss the reports with @anjackson before writing the help text.

**Comment by nicolabingham** [comment]
@anjackson Commenting on 3.21 Wording URL
Targets > Look up a URL
Can the term 'mid-crawl' be replaced with 'QA view' and 'archival' be replaced with 'UKWA' ?

**Comment by nicolabingham** [comment]
@anjackson Commenting on 3.43 
Users & Agencies > Roles > Role archivist
do the the assigned permission names have to have underscores in them? It would be better if they could be removed as they would look more user friendly, but this is only a very minor point and not worth changing if there are other implications
