### ISSUE TITLE
Import users email addresses too

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#238]
Judging by the 'curators' list, it seems that users names are imported okay, but not their email addresses:

https://www.webarchive.org.uk/act-ddhapt/curators/list?p=2

Could the import be reviewed to see if this can be improved? The User data can be found by UID, e.g.

http://www.webarchive.org.uk/act/user/1.json
http://www.webarchive.org.uk/act/user/1.xml

Also, I suspect the system is setting all the users' passwords to the same string. We need to do something better, but what we do depends on whether there is a password reset system. Is there?

**Comment by kinmanli** [comment]
@anjackson there doesn't seem to be an email address for the users using http://www.webarchive.org.uk/act/user/1.json or http://www.webarchive.org.uk/act/user.json (complete list)

**Comment by anjackson** [comment]
Weird, I can see it. Perhaps it's an account privilege thing because I can see email addresses when logged in as admin.

Okay, fixed now, by giving the robot account more permissions than before.

**Comment by kinmanli** [comment]
@anjackson can now import the emails.

Also done the password reset http://localhost:9000/actdev/resetpassword

**Comment by kinmanli** [comment]
@anjackson you mentioned yesterday about Act passwords. Do you know if you can export them?

**Comment by anjackson** [comment]
Nope, pretty sure you can't get to that data without doing something hacky. Happy to live with that.

**Comment by kinmanli** [comment]
fixed - password reset and emails importing from ACT

**Comment by peterwebster** [comment]
OK, so the import of email addresses looks great @kinmanli - thanks.

@anjackson  On the password reset: what will now happen when an existing user imported from Andy's ACT first comes to W3ACT?  At the minute the reset page asks them for their old (existing) password (as it should do) - but those passwords haven't been imported.

**Comment by peterwebster** [comment]
Also @anjackson @kinmanli all the imported curators are given the Archivist role. Next import, they should all come in as User, and then we can manually promote some of them.

**Comment by kinmanli** [comment]
@peterwebster which page asks for the old password?

http://www.webarchive.org.uk/actdev/resetpassword

@GilHoggarth are the email settings in application.conf?

**Comment by GilHoggarth** [comment]
Email settings in `accounts.yml`.

**Comment by kinmanli** [comment]
@GilHoggarth email server settings are in application.conf

What should they be as they are currently blank?

host=""
mail.user=""
mail.password=""
from="web-archivist@bl.uk"
port=587

**Comment by GilHoggarth** [comment]
The only set values I can find are
`host=juno.bl.uk`
The other two blank vars are blank elsewhere (so presumably okay) - guess you're about to test this theory!

**Comment by kinmanli** [comment]
@GilHoggarth I know the emailing system works as I've tested it using Gmail's smtp server.

**Comment by kinmanli** [comment]
Should work now. Settings back on:

host=juno.bl.uk
mail.user=""
mail.password=""
from="web-archivist@bl.uk"
port=25

**Comment by kinmanli** [comment]
Import curators as role type "User"

**Comment by peterwebster** [comment]
@anjackson on production, all users will need to reset password from the login page (so they don't need to know their old password)

**Comment by kinmanli** [comment]
Fixed imported Andy's Act Curators now have role of "User"

**Comment by peterwebster** [comment]
OK, this import looks good to me.

One query for @anjackson :  there are clearly two sysadmin accounts, with different email addresses - one native to W3ACT, one coming in from Andy's ACT. The latter is being set to User as it is imported, the one native to ACT retains the right role. Not sure if we need to do anything, but thought I'd mention it.

**Comment by anjackson** [comment]
I think that's ok.
