### ISSUE TITLE
Errors on submitting UKWA license form

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#239]
When filling in the form at  http://www.webarchive.org.uk/actdev/ukwa/licenseform/act-1, on saving, I get:

Execution exception[[MatchError: null]]

I imagine this is something to do with the field validation:  Some points:

(i) the name, and email do *not* have to match the contact person to whom the crawl permission was sent - it could be passed around within an organisation.

(ii) the Third Party Content question, the 'I/we agree' and the 'future publicity' question all must be answered.

**Comment by kinmanli** [comment]
@peterwebster When submitting a license form can you confirm that we need to assign the license to the crawl permission, add the license to the target and update the lower level target's licenses too?

Regards

**Comment by kinmanli** [comment]
fixed in next deploy

By using this functionality

> @peterwebster When submitting a license form can you confirm that we need to assign the license to the crawl permission, add the license to the target and update the lower level target's licenses too?
>
>Regards

**Comment by peterwebster** [comment]
Great @kinmanli : minor tweak to one of the error messages then we're done.

"The form cannot be submitted without checking the 'I/We agree' box, or without answering the questions about 'Third-Party Content' and 'Publicity for the Web Archive'. Please check your input and try again.'

**Comment by kinmanli** [comment]
Fixed next release

**Comment by peterwebster** [comment]
Great @kinmanli : closing ticket now.
