### ISSUE TITLE
Validation of 'No LD criteria' field in target record

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#240]
It should probably be impossible to set the 'No LD criteria met' to Yes if any of the other fields in that tab are positive [ie, show that one of the criteria *is* met.

**Comment by peterwebster** [comment]
@kinmanli also, on the first save of a new record, if:

(i) one of the three automated NPLD checks is passed;
AND
(ii) curator has set the 'No LD Criteria' to yes, 

it should throw an error message, saying: "One of the automated checks for NPLD permssion has been passed.Please unselect the 'No LD Criteria Met' field and save again.

**Comment by kinmanli** [comment]
Can do NPLD validation on save and flag up

**Comment by kinmanli** [comment]
@peterwebster what about ukPostalAddress and viaCorrespondence? What message do you want it to flag if those are flagged?

**Comment by peterwebster** [comment]
Sorry @kinmanli , my first error message was too specific. We just need one to cover both cases, reading ""One of the checks for NPLD permission has been passed.Please unselect the 'No LD Criteria Met' field and save again."

**Comment by kinmanli** [comment]
@peterwebster fixed

**Comment by peterwebster** [comment]
@kinmanli  Handing over to @nicolabingham to sign off , but I think that whenever another test is already passed, automated or manual, the error message should be: 

""One of the checks for NPLD permission has been passed.Please unselect the 'No LD Criteria Met' field and save again."

(at the minute it still refers to the *automated* tests, which isn't quite right.)

**Comment by kinmanli** [comment]
@peterwebster please post an example Target. Cheers

**Comment by nicolabingham** [comment]
Tested on target https://www.webarchive.org.uk/act/targets/17477, which meets the .uk domain name criteria. I changed the NPLD criteria to 'NO LD criteria' met and got the notification message ".....please unselect....". Seems to be working ok.

**Comment by peterwebster** [comment]
@nicolabingham try when using Postal Address...

**Comment by nicolabingham** [comment]
@peterwebster tested on the Guardian.com (postal address) Target https://www.webarchive.org.uk/act/targets/16608#metadata. I get the error message "....please unselect ..." so this appears to be working correctly

**Comment by kinmanli** [comment]
@GilHoggarth ready to close?

**Comment by GilHoggarth** [comment]
@nicolabingham Can you test this again on /actdev - it's a while since this was commented on and it's best to ensure that this still works correctly.

**Comment by nicolabingham** [comment]
@GilHoggarth This works for all of the NPLD criteria except for Professional Judgement. @peterwebster is this what is intended for this field?

**Comment by GilHoggarth** [comment]
Reassigned to @peterwebster as last question asked.

**Comment by anjackson** [comment]
I'll answer instead: A ticked Professional Judgement should also mean you can't select 'No LD Critera met'.

**Comment by kinmanli** [comment]
@GilHoggarth fixed 

![2015-03-27 15-01-46_w3act](https://cloud.githubusercontent.com/assets/1652105/6870204/6aac1b1c-d492-11e4-95e8-8311348c886b.png)

**Comment by GilHoggarth** [comment]
AFAI understand, this is done - ready to be tested after production deployment.

**Comment by GilHoggarth** [comment]
@nicolabingham Given there seems to be many variations to what is the criteria for Legal Deposit, can you test again please.

**Comment by nicolabingham** [comment]
@GilHoggarth this has been fixed including with the 'professional judgement' criteria, which is correct behaviour.

**Comment by GilHoggarth** [comment]
Closing.
