### ISSUE TITLE
Empty Start Dates

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#242]
A number of records in the current `/act-ddhapt` have empty start dates (i.e. `field_crawl_start_date` is blank).

I'll code around this for testing purposes but it shouldn't be possible to create records with empty start dates.

**Comment by anjackson** [comment]
Also F.A.O. @romankarl and @rcking as we are having to work around this to establish the test system.

**Comment by anjackson** [comment]
To clarify, every Target with a crawl frequency other than "Domain crawl only" should have a start date.

**Comment by kinmanli** [comment]
fixed in schemarefactor branch

**Comment by peterwebster** [comment]
Ah - the logic is the wrong way around at the minute @kinmanli  - the start date is required when the crawl frequency is set to a value *other than* Domain Crawl Only.

At the minute, it is enforced only when it is Domain Crawl Only.

@anjackson @PsypherPunk

**Comment by anjackson** [comment]
Fixed, and moving future work to a new ticket.
