### ISSUE TITLE
Unable to save new target record when logged in as Expert@

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#244]
When I try to create a new target (  http://www.webarchive.org.uk/actdev/targets/new?title=http%3A%2F%2FExpertTargetUser.co.uk#licensing ), I get an exception error.

Execution exception[[NullPointerException: null]]

I tried this twice, once completing every possible field, and the second time only the required ones, with the same result each time.

**Comment by peterwebster** [comment]
Also, user@bl.uk at the minute can't create a new target record. They should be able to create new records, but not edit records created by others.

**Comment by kinmanli** [comment]
As an expert User I get this screen on 'crawl permissions' (see below). The views seem to be restricted to 'sysAdmin' and 'archivist' roles. Please let me know which roles are restricted to what as certainly validation such as crawl permissions requiring a start date will break if the view isn't available.

![screen shot 2015-01-29 at 14 08 26](https://cloud.githubusercontent.com/assets/1652105/5958795/614c99c4-a7c0-11e4-991a-4046437ee930.png)

**Comment by peterwebster** [comment]
@kinmanli any user should be able to view. Only sysadm and archivist should be able to edit the fields.

I've raised a question with @anjackson on another ticket about what the defaults in this fields should be, as I've been having second thoughts.
Andy: what should the default position be in relation to a start date ? What will Heritrix do with the target if there is no date set ?

**Comment by peterwebster** [comment]
I see now that the answer is at #244 @anjackson 

When a new target record is created by an expert user or a user, they are not able to set a start date. However, they are *also* not able to set the frequency to anything other than the default (domain crawl only) - and so the validation should work. @kinmanli

**Comment by peterwebster** [comment]
@kinmanli See @anjackson 's comment at https://github.com/ukwa/w3act/issues/228#issuecomment-72060474

**Comment by peterwebster** [comment]
@kinmanli any user can view any part of a target record; it's with the Edits where the privileges kick in

**Comment by kinmanli** [comment]
1) All roles can view Target
2) All roles except 'view' can create a new Target
3) Sys Admin and Archivist can edit all Targets
4) Other roles (expert and user) can only edit their own Target

**Comment by peterwebster** [comment]
@kinmanli I've done some asking around, as this has needed us to change what we originally thought should happen.

On the crawl permissions tab:

(i) Expert can set Scope, Crawl Frequency, Start/End Date
(ii) only the Archivist can set the Cap, and Robots.txt

**Comment by kinmanli** [comment]
@peterwebster does the End Date also have a time?

**Comment by kinmanli** [comment]
@peterwebster Expert User

![2015-02-05 11-03-45_w3act](https://cloud.githubusercontent.com/assets/1652105/6059197/ad3a96a4-ad26-11e4-88c2-b16fe868e5dc.png)

for point (ii) only Archivist and not Sys admin?

**Comment by peterwebster** [comment]
@kinmanli assume that each higher role can do everything that lesser ones can, and that SysAdmin can do absolutely anything

**Comment by kinmanli** [comment]
@peterwebster can a time be set for end date too?

**Comment by peterwebster** [comment]
@kinmanli I would have thought that if there is a time for the start date, there ought to be a time for the end date. Would @anjackson agree ?

**Comment by peterwebster** [comment]
@kinmanli on another thing:  Expert Users *can* edit target record created by others

**Comment by kinmanli** [comment]
@peterwebster end date has js time, expert users can edit other user's targets

Fixed

**Comment by anjackson** [comment]
Agree, BTW, although the end-time might not have any effect at present.

**Comment by peterwebster** [comment]
This all looks good. Eventually, some validation such that the end date can't be earlier than the start date would be useful; but not now.   
http://www.webarchive.org.uk/actdev/targets/6#crawlpolicy

**Comment by nicolabingham** [comment]
@anjackson We are getting frequent requests from Expert_Users to edit robots.txt settings, which currently on Archivists can do. I think it would make sense to give Expert_Users the ability to do this. All Expert_Users are trained in the Robots protocol and so understand the consequences. Can we enable this in the Future Production Release or Second Production Deployment?

**Comment by anjackson** [comment]
Superceded by #355
