### ISSUE TITLE
Admin privilege to reset user passwords

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#245]
Hi @anjackson : would you agree that the system admin needs to be able to reset a user password without needing to input the old one ? 

At the minute, if a user forgets a password (and can't login), the admin can't reset it either (because it has been forgotten).  (Try it at  http://www.webarchive.org.uk/actdev/curators/29 )

Either that, or there needs to be a Forgotten Your Password option for users who are not logged in.  (Or both)

**Comment by anjackson** [comment]
I think @kinmanli added a 'forgotten PW' form. However, I agree that sysadmin should be able to set pwds.

**Comment by peterwebster** [comment]
@kinmanli @anjackson I think there's the facility to change a password once you're logged in, but I don't see a form from http://www.webarchive.org.uk/actdev/login for someone who isn't logged in.

**Comment by anjackson** [comment]
I think it's just missing a link to the form.

**Comment by kinmanli** [comment]
@peterwebster

Just need this on the main page  
http://www.webarchive.org.uk/actdev/resetpassword

**Comment by kinmanli** [comment]
@peterwebster Sys Admin only link to reset user passwords. Is this sufficient or do you want something different?

![screen shot 2015-01-30 at 12 31 18](https://cloud.githubusercontent.com/assets/1652105/5975759/ef730ac8-a87c-11e4-8426-ad30386aaa0e.png)

**Comment by kinmanli** [comment]
add "forgot password" on login page

**Comment by kinmanli** [comment]
![screen shot 2015-01-30 at 21 50 29](https://cloud.githubusercontent.com/assets/1652105/5984004/0af8c074-a8ca-11e4-83c7-c26ab9c773d7.png)

**Comment by kinmanli** [comment]
fixed

**Comment by peterwebster** [comment]
Minor tweak:  the text in the email has a stray <br> tag in it:


You asked for your password to be reset.  <br> Click on this link : http://www.webarchive.org.uk/actdev/reset/16832f6c-95b3-42ca-a5e7-8881e13aebc0 to change your password.

[and also]

Hello, <br><br> Your password has been reset.

**Comment by kinmanli** [comment]
Fixed @peterwebster 

![2015-02-05 12-18-29_w3act - new password - message plain text](https://cloud.githubusercontent.com/assets/1652105/6060078/360d4904-ad31-11e4-8089-6c1b4744d328.png)

![2015-02-05 12-19-27_w3act - new password - message plain text](https://cloud.githubusercontent.com/assets/1652105/6060082/3e241fb4-ad31-11e4-8f01-b41e13c97500.png)

**Comment by peterwebster** [comment]
Great @kinmanli : closing ticket now
