### ISSUE TITLE
Target record view drops Seed URL

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#246]
The UI shows no URL for this target:

http://www.webarchive.org.uk/actdev/targets/16182#overview

It has the knock-on effect that the URL does not flow on to the crawl permission process:

http://www.webarchive.org.uk/actdev/crawlpermissions/new?targetId=16182

The data is clearly stored, as it appears correctly here:
http://www.webarchive.org.uk/actdev/targets/lookup?f=Target+by+Peter

**Comment by kinmanli** [comment]
@peterwebster do you know which url you used for 16182?

**Comment by peterwebster** [comment]
@kinmanli just the one given above..

**Comment by peterwebster** [comment]
![image](https://cloud.githubusercontent.com/assets/5520710/5960847/17438f80-a7d0-11e4-9e45-d656d1b15a28.png)

**Comment by kinmanli** [comment]
@peterwebster I mean the seed URL. So I can see if I can replicate it.

**Comment by peterwebster** [comment]
@kinmanli   http://PGmailTarget.co.uk  - although weirdly there seems to be two records for it - 16182 and 16181, one with the URL and one without.

**Comment by kinmanli** [comment]
Hi @GilHoggarth, please can you run this query on the prod db and let me know the result?

select * from field_url where target_id=16182

Thanks

**Comment by kinmanli** [comment]
@GilHoggarth No need to do that now as I've just recreated it.

**Comment by kinmanli** [comment]
@peterwebster What should happen if someone creates a Target with the same seed url? duplicate entries?

**Comment by peterwebster** [comment]
@anjackson I think that there should be eventually some validation that disallows creating a second target for the same URL as one that exists. However, should it be possible to create a second target for a URL which is not the first-named in an existing target:

ie. when Target 1 has URLS abc.com, xyz.com, should we allow another target where xyz.com is the first URL ?

**Comment by peterwebster** [comment]
@kinmanli no new target record should be allowed for any URL in the seed URL field in any existing target. How difficult does this sound ?

**Comment by kinmanli** [comment]
@peterwebster I can query the DB for existing matching seed URLs and warn the curator on save?

**Comment by kinmanli** [comment]
@peterwebster 

Looks up to see if there is already an existing url for a target and throws a message if there is.

Also will look at variations of a url ie. http, https, www, ends in / etc.

![2015-02-04 16-16-34_w3act](https://cloud.githubusercontent.com/assets/1652105/6044251/fad69f90-ac89-11e4-9ae4-f5db1c089fdb.png)

**Comment by peterwebster** [comment]
This looks good to me @kinmanli 

At some point @anjackson an enhancement for this would be to provide a link to the existing target record referred to. However, not a priority now, so putting this one on hold.

**Comment by peterwebster** [comment]
Remaining enhancement transferred to new ticket #292 . Closing this ticket now.
