### ISSUE TITLE
Archivist should not be able to set Licence to Open UKWA Licence

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#247]
[not a priority before going into production this one @kinmanli ]

In the Licence field for the target there are different values:

Open UKWA Licence (2014-)
HLF WWI
UKWA Selective Archive

Only the Archivist can edit this field at all via the GUI. However, even they should not be able to set the value to Open UKWA Licence - because this can only be obtained via the email/licence form process - and once it is granted, the application updates the Licence field.

It would only be to prevent mistakes - but is it particularly difficult to implement ?

**Comment by kinmanli** [comment]
@peterwebster for the Archivist, do you want the 'Open UKWA Licence (2014-)' to be taken out of the list, or do you want it to be in there and a warning on save saying it cannot be selected?

**Comment by peterwebster** [comment]
Me to write error message

**Comment by kinmanli** [comment]
@peterwebster if sysadmin or archivist chooses 'Open UKWA Licence (2014-)' it will throw up an error. @peterwebster to provide the error message.

![screen shot 2015-02-22 at 19 28 35](https://cloud.githubusercontent.com/assets/1652105/6319957/09b1418a-bac9-11e4-883c-c9e1e9364857.png)

**Comment by peterwebster** [comment]
Error message:  "It is not possible to attach an Open UKWA Licence directly to a target in this way. Please initiate the licensing process using the green button below." @kinmanli

**Comment by kinmanli** [comment]
@peterwebster updated the error message and checked in.

**Comment by peterwebster** [comment]
Thanks @kinmanli this looks great to me. Over to @nicolabingham to check and close

**Comment by nicolabingham** [comment]
Tested this issue on target https://www.webarchive.org.uk/act/targets/4031. I am unable to change the license to 'Open UKWA Licence (2014-)' and get the error message above.
