### ISSUE TITLE
License requests refused, but not showing in queue

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#248]
[on hold for now @kinmanli ]

When we send out licence requests, sometimes they get refused - but this doesn't happen via the licence form, but often outside W3ACT via email.

The Archivist then sets the target record to reflect this (field: Open UKWA Licence Requests), as at:
http://www.webarchive.org.uk/actdev/targets/1 

but they should show up here (but isn't at the minute).
http://www.webarchive.org.uk/actdev/crawlpermissions/list?status=REFUSED

**Comment by peterwebster** [comment]
In fact, it remains as Pending at  http://www.webarchive.org.uk/actdev/crawlpermissions/list?status=PENDING

So: the change made to the target record isn't being applied to the crawl permission itself.

**Comment by peterwebster** [comment]
However, the Archivist *can* edit the crawl permission directly to set to Refused, which then flows through correctly to the target record - so, let's leave this as it is for now.

**Comment by kinmanli** [comment]
@peterwebster @anjackson 

Can a target hold more than one license of the same type at a time? Say if one user comes in and submits a license "Open UKWA License (2014-)" and another user afterwards does the same?

**Comment by anjackson** [comment]
No, and once a license has been added to a Target, it should not be possible to change it except for SysAdmin,

**Comment by peterwebster** [comment]
@peterwebster  specify how the cases work.

**Comment by peterwebster** [comment]
@kinmanli 

So, here's the rules:
(i) If there is a crawl permission Queued, Pending or Granted for a target, it should be impossible to create a new crawl permission for the same target.  

(ii) If a target has an associated crawl permission which is set to Refused, or Email Rejected, it *should* be possible to create a new crawl permission, but only the Archivist (who can understand the history) should be able to do this.
(Other users can request that this happens by flagging the record.)

The easiest way to show this in the UI is for the green button in the target record tab to be greyed out when it is unavailable.

What does @anjackson think ?

**Comment by peterwebster** [comment]
I think we've been dealing with the rules part of this ticket elsewhere. I think now thought @anjackson that the original part of this ticket should be on 1.1.0. 

To recap:  

(i) could @kinmanli check that changes to the status of a crawl permission (Granted, Refused etc) made in the crawl permission view are reflected in the UKWA Licensing tab of the target record.

Compare  http://www.webarchive.org.uk/actdev/crawlpermissions/2  and http://www.webarchive.org.uk/actdev/targets/act/act-9047641246754228950#licensing

(ii) to clarify things for users, I think we should make this field non-editable in the target record - requiring the Archivist to register any changes in this field directly in the crawl permission. @anjackson

**Comment by kinmanli** [comment]
@peterwebster @GilHoggarth 

Crawl Permission initially "Pending" in both crawl permission view and target view's license tab

![screen shot 2015-03-06 at 10 10 50](https://cloud.githubusercontent.com/assets/1652105/6523611/4399d384-c3e9-11e4-93ef-5f581579dc7c.png)

![screen shot 2015-03-06 at 10 11 09](https://cloud.githubusercontent.com/assets/1652105/6523608/43923f0c-c3e9-11e4-8408-b40beb13c942.png)

In the crawl permission edit/view updated the status...

![screen shot 2015-03-06 at 10 11 41](https://cloud.githubusercontent.com/assets/1652105/6523609/4394202e-c3e9-11e4-8a4b-dbcf118d2f7a.png)

... and changes are reflected in the target's view license tab

![screen shot 2015-03-06 at 10 11 55](https://cloud.githubusercontent.com/assets/1652105/6523610/43982476-c3e9-11e4-9d51-7548f1f1ac92.png)

**Comment by peterwebster** [comment]
@GilHoggarth May I suggest that @nicolabingham tests this one out (next week, once the change has been deployed to /actdev) ?

To summarise:  the value of the Open UKWA Licence Request in the target record should always match the Status field in a crawl permission for that target.

Also, could @kinmanli confirm that the field cannot be edited from the target record, only in the crawl permission ?

**Comment by kinmanli** [comment]
@peterwebster if you're talking about the open ukwa license field that has always been editable by sys admins and archivsts

**Comment by GilHoggarth** [comment]
@nicolabingham Ready to test in next deployment (which is midnight each night for /actdev)

**Comment by nicolabingham** [comment]
@GilHoggarth just to clarify - this is not ready to test now, but will be after midnight?

**Comment by GilHoggarth** [comment]
Yep :) So a task for Monday!

**Comment by nicolabingham** [comment]
Ok, reluctantly I'll leave it till then...

**Comment by peterwebster** [comment]
@nicolabingham @kinmanli Nicola's call, but I'm suggesting that no-one can edit that field directly in the target record, but should have to do so in the crawl permission itself. If there is more than one crawl permission for the target, then it will cause problems of attribution if the change is made in the target record.

**Comment by nicolabingham** [comment]
@kinmanli @peterwebster I can edit the license in the Target record and it rolls through to the crawl permission, the reverse is also true, editing the crawl permission rolls through to the target record. I think this is fine if it is just restricted to archivist and sys admin roles.

**Comment by peterwebster** [comment]
@nicolabingham if a record has two crawl permissions associated with it, to which of those does the change in the target record apply? The most recent?

**Comment by nicolabingham** [comment]
@peterwebster correct, the change applies to the most recent crawl permission.

**Comment by nicolabingham** [comment]
@peterwebster yes, agree that editing crawl permissions should only be done in the crawl permission not the target record to avoid confusion.

**Comment by peterwebster** [comment]
Assigning to @anjackson for milestone.

The requirement is that the status of a crawl permission (Granted, Pending etc) should only be editable in the crawl permission itself, and not from the target record view (because there can be a many-to-one relation between targets and crawl permissions

**Comment by kinmanli** [comment]
@peterwebster @nicolabingham so do you want this drop down to change to just text now ?

![2015-03-16 16-13-29_w3act](https://cloud.githubusercontent.com/assets/1652105/6670611/8d9260bc-cbf7-11e4-923a-6970828c2a0c.png)

**Comment by nicolabingham** [comment]
@peterwebster @kinmanli yes, changed to text please.

**Comment by kinmanli** [comment]
fixed @GilHoggarth 

![2015-03-23 10-29-55_w3act](https://cloud.githubusercontent.com/assets/1652105/6778095/b8b911d2-d147-11e4-8259-54fd46cd8cbe.png)

![2015-03-23 10-30-24_w3act](https://cloud.githubusercontent.com/assets/1652105/6778098/ba2c35e4-d147-11e4-9986-2229028ac911.png)

**Comment by GilHoggarth** [comment]
Tried reading ticket but lost plot! @nicolabingham can you test this on /actdev please.

**Comment by nicolabingham** [comment]
@GilHoggarth I am a bit lost on this ticket too but the latest requirement was to make the licencing uneditable in the Target record even by the Archivist. Licences can only be edited via Crawl permissions.The licence is no longer editable in the target record.
