### ISSUE TITLE
Include URL of target in acknowledgment email

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#249]
Minor point, but worth addressing before production.

The acknowledgment email that is sent out when someone completes the licence form should include the URL of the target, in order to identify the target concerned (it is possible that one user may give several licences.)

At the minute it arrives as:

Your completed licence form has been submitted successfully, thank you.

||LICENCE||

The British Library is very pleased to have received your submission [etc]

**Comment by kinmanli** [comment]
@peterwebster 

Currently shown as "localhost:9000", but will be the name of server wherever you deploy to.

![screen shot 2015-02-03 at 19 10 11](https://cloud.githubusercontent.com/assets/1652105/6027183/534c256c-abd8-11e4-9212-2ad6660d174e.png)

**Comment by peterwebster** [comment]
Sorry @kinmanli I wasn't very clear about this. I meant the Seed UR(s) from the target record, rather than the URL of the licence form. This allows them to see at a glance what content is being referred to.

**Comment by kinmanli** [comment]
@peterwebster 

![2015-02-05 13-30-04_british library ukwa licence received - message plain text](https://cloud.githubusercontent.com/assets/1652105/6060955/0281ce98-ad3b-11e4-8a3b-dada0899efef.png)

**Comment by peterwebster** [comment]
Great @kinmanli : closing ticket
