### ISSUE TITLE
Persistence exception when saving crawl permission

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#251]
When logged in as a User, I get:

Execution exception[[PersistenceException: Unique expecting 0 or 1 rows but got [2]]]

when trying to save

http://www.webarchive.org.uk/actdev/crawlpermissions/new?targetId=16681

**Comment by kinmanli** [comment]
@peterwebster There seems to be a contact person with the same email address in the table.

**Comment by peterwebster** [comment]
@kinmanli yes, this is going to happen in a small number of cases, and needs to be allowed.   It doesn't fail when I'm logged in as Archivist - but you do get the validation that forces the user to make sure that the details they are adding for the contact person match those in the table.

**Comment by kinmanli** [comment]
these with a User role

**Comment by kinmanli** [comment]
Still trying to make this fail

**Comment by peterwebster** [comment]
OK, I can't seem to replicate this now, so will close the ticket
