### ISSUE TITLE
Default password on user import should be configurable and/or random

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#252]
For the production release, we need to set all the user password to something unguessable and that is not/has not been check into the repository.  e.g. a default password from the command line, or an option that assigns a large random password as users are imported (should probably the default behaviour). Users can then use the PW reset functionality.

Furthermore, can we entirely avoid the 'hardcoded' user account being used at all (i.e. those in [users.yaml](https://github.com/ukwa/w3act/blob/master/conf/users.yml#L111)).

/cc @GilHoggarth

**Comment by kinmanli** [comment]
@anjackson I've now coded it so that when it imports from Andy' Act it generates a random password. Also, created a flag to switch on/off importing accounts/users.yml.

Is there anything else required?

**Comment by anjackson** [comment]
I think the only gap might be that there is no longer a sysadmin user with the sysadmin role, so we'd have trouble getting things started, (I think?). Perhaps an extra rule that spots the wa-sysadm@bl.uk user account and gives that the higher role during import?

**Comment by kinmanli** [comment]
@anjackson thinking of creating a admin.yml file and adding emails for whoever wants to be an admin user. Also, who has access to the wa-sysadm@bl.uk email account?

**Comment by GilHoggarth** [comment]
The issue about the sysadmin account regards setting the password doesn't it? That is, this needs to be done outside of the files - perhaps on first run it could randomly create its password and display it on the console?

I think wa-sysadm@bl.uk is Helen, Andy, Roger and I.

**Comment by kinmanli** [comment]
@GilHoggarth @anjackson 

I've added 2 values in application/prod.conf. 'use.accounts'  does not import the users from accounts.yml. 'admin.default.email' is self explanatory.

```
use.accounts=false
admin.default.email="wa-sysadm@bl.uk"
```

After a data import it will generate a sysAdmin user account and password (see below). If it already has this account (same email) in the DB it will not generate another.

2015-02-06 13:17:19,413 [debug] application - +++ Data import completed +++
2015-02-06 13:17:19,414 [info] application - Creating admin user: wa-sysadm@bl.uk
2015-02-06 13:17:19,430 [info] application - Email: wa-sysadm@bl.uk, password: 67a3286a-f30a-44b2-bdf2-39ff12b5c8b7
2015-02-06 13:17:19,475 [info] play - Application started (Dev)

**Comment by GilHoggarth** [comment]
Sounds good. To clarify, is the sysAdmin account password also generated when data isn't imported? I'm building a play dist version of w3act and it won't import data - instead the data is imported via postgres. So when this version starts for the first time, it won't do the import but will need the sysAdmin password generated.

**Comment by kinmanli** [comment]
If data isn't imported than the sysAdmin account password should still be the same as no import (which includes users) has take place.

**Comment by kinmanli** [comment]
check wa-sysadmin@bl.uk and assign admin role

**Comment by peterwebster** [comment]
@GilHoggarth are we in a position to close this ticket now ?

**Comment by GilHoggarth** [comment]
I think so but should do a final test to ensure so. @peterwebster Can I do this test on /actdev now?

**Comment by peterwebster** [comment]
@GilHoggarth sure, do whatever you need to.

**Comment by GilHoggarth** [comment]
Redeployed without & with data import on /actdev and checked the admin account setting. When data is imported the admin account role is correctly set; when data is not imported the role setting is unchanged from previous.

So if the admin role is correctly set, which it should be when the initial data import is done, then this setting is retained for further redeploys without data import and for restarts.

So ticket can be closed in my view, but I leave it to you to make that decision ;)

**Comment by peterwebster** [comment]
So, after @GilHoggarth testing, I successfully logged in with the adm account, which has the right privileges, and everyone else is a User. Yes, indeed, we should close this - and I shall, what's more...
