### ISSUE TITLE
All /act URLs need to be https

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#254]
I've set up a play dist version of w3act (https://www.webarchive.org.uk/act/), and separately imported the current/Andy's Act Postgres data via pg_dump (i.e., not via w3act import scripts).

I tried to log into the new system using my old Andy's Act password and failed - I think the authentication code is now different (which is good!) So I requested a new password via the Forgotten Password function and received an email that referred to http://.../act - not https.

As we're going to run both services in parallel, all links, comms, etc. in the new w3act service need to go over https. Specifically in this case, the emailed link to change a password needs to be https.

**Comment by kinmanli** [comment]
Reset passwords will now use the current protocol and hostname it is deployed on.

**Comment by GilHoggarth** [comment]
Almost! Password reset email now give host server IP:
`Click on this link : https://192.168.45.32:9000/act/reset/f74.... to change your password.`

**Comment by kinmanli** [comment]
Just checked in. Please deploy again @GilHoggarth

**Comment by peterwebster** [comment]
@GilHoggarth So the URL I used today to reset my password was formatted:  https://webarchive.org.uk/act/reset/b5c[........]
Does that look OK to you ?

@kinmanli can you check easily whether or not the URL for the Open UKWA licence form also begins https://... ? That's the only other email communication that ACT will send out.

**Comment by GilHoggarth** [comment]
Yep, that looks the same as the ones I've received and used. We've also used the 'Forgotten Password' mechanism to send out to an external gmail account and that worked fine too.

**Comment by peterwebster** [comment]
@kinmanli I checked, and the license email goes out (from /actdev) with http://

**Comment by kinmanli** [comment]
@peterwebster will now use current server's protocol and hostname.

![2015-02-11 14-09-27_uk web archive - message plain text](https://cloud.githubusercontent.com/assets/1652105/6148230/9387cd50-b1f7-11e4-9cc9-127e99268b5a.png)

**Comment by GilHoggarth** [comment]
@peterwebster I think this ticket can be closed as, as far as I'm aware, all referenced URLs are now as per the server (so if request is https, reference is https as well.) However, note I'm not commenting on the email reference here as that's #259.

**Comment by GilHoggarth** [comment]
Dah, assigning to Peter.

**Comment by peterwebster** [comment]
This is now sorted; closing ticket now. Thanks @kinmanli
