### ISSUE TITLE
'Instances' on the Target page

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#255]
Each Target page has 3 accordion section at the bottom: _Instances_, _Target revisions_ and _Instances_.

Firstly, the repetition of 'Instances' is confusing—what's the distinction (I haven't actually found a Target where the latter section does anything)?

Secondly, in the first section each set of 4 links can repeat multiple times. I'm presuming this happens, once for each seed URL but without indication that this is _why_ it just looks odd.

**Comment by kinmanli** [comment]
@PsypherPunk The top 2 is what was in originally (Roman). The bottom one are just instances of a Target which I added.

Yes if a target has multiple seed urls it will display it this way. @peterwebster any ideas of a better display?

**Comment by PsypherPunk** [comment]
Do you have an example of a Target where the bottom one is populated?

Apropos, do we have any documentation on how to create an Instance? The [wiki](https://github.com/ukwa/w3act/wiki/Technical-architecture#new-instance-api) says that:

> At the end of a successful crawl, the crawl system will attempt to inform w3act that there is a new instance of a given target available.

...but it doesn't say _how_.

Also, it states that:

> The link to the instance in QA Wayback has following form
> opera.bl.uk:8080/wayback/*/<URL>
>
> The link to the instance in Open UK Webarchive has following form
> http://www.webarchive.org.uk/wayback/archive/*/<URL>

However, that's a link to _every_ occurrence of `<URL>` in the respective archive, not a specific 'Instance'. An Instance occurs at a specific point in time—the above will return a list of every timestamp for that URL.

I'm not sure if we're misusing the word 'Instance', whether the links are incorrect or whether the description needs changing to _"The link to **all** the instances..."_

**Comment by peterwebster** [comment]
@kinmanli @PsypherPunk 

Firstly, I'm not sure what the third one is doing. If it is just a duplication of the first, then it can come out. Was it doing something else @kinmanli ?

**Comment by peterwebster** [comment]
@PsypherPunk @kinmanli on the terminology, in the UI at least I think it does what it says it does:  links to all the instances of this target in various locations. We could change the wiki to reflect that.

**Comment by peterwebster** [comment]
@PsypherPunk @kinmanli 
On the creation of instances, I don't think there should be any need to create a new instance record from within the ACT UI, as they should be created nightly once #231 is implemented - unless I've misunderstood something. @anjackson and I agreed that the use case of a user wanting to see instance record for instances crawled since the last running of that script (overnight) was so marginal that we shouldn't need to cater for it.

**Comment by peterwebster** [comment]
@kinmanli @PsypherPunk layout:

On the layout how about:

ExampleSeedURL#1.com  [in bold, probably]
[bullet] In QA Wayback
[bullet] In Open UK Web Archive
[bullet] In other web archives
[bullet] Live site

repeated either vertically or horizontally.

**Comment by kinmanli** [comment]
@peterwebster the third one is just a list of instances related to a target which I added whilst in development.

i.e.
for Target "Islamic Relief UK"
http://webarchive.org.uk/actdev/instances/1/edit
http://webarchive.org.uk/actdev/instances/7/edit
http://webarchive.org.uk/actdev/instances/19/edit

**Comment by peterwebster** [comment]
@kinmanli I see. This is useful, but could you comment it out for now until I figure out whether this is the best way of enabling the user to get to those records.

**Comment by kinmanli** [comment]
@peterwebster done

**Comment by peterwebster** [comment]
Assigning back to @kinmanli to look at the layout in the first Instances box. I see that the third one is commented out - thanks.

**Comment by kinmanli** [comment]
@peterwebster I thought you wanted the 3rd accordian commented out, which I did?

![screen shot 2015-02-24 at 08 23 12](https://cloud.githubusercontent.com/assets/1652105/6345484/7928fc16-bbfe-11e4-859d-7a6e27e223b3.png)

**Comment by peterwebster** [comment]
That's right - I'm talking about the format in the first accordion - see comment 12 days ago.

"On the layout how about:

ExampleSeedURL#1.com [in bold, probably]
[bullet] In QA Wayback
[bullet] In Open UK Web Archive
[bullet] In other web archives
[bullet] Live site

repeated either vertically or horizontally.

**Comment by kinmanli** [comment]
@peterwebster before I check in, please can you confirm this is what you are looking for?

![2015-02-24 09-53-04_w3act](https://cloud.githubusercontent.com/assets/1652105/6346844/093fcb52-bc0b-11e4-8bac-bc13c8244292.png)

**Comment by peterwebster** [comment]
Great..

On Tue, Feb 24, 2015 at 9:53 AM, kinmanli <notifications@github.com> wrote:

> @peterwebster <https://github.com/peterwebster> before I check in, please
> can you confirm this is what you are looking for?
>
> [image: 2015-02-24 09-53-04_w3act]
> <https://cloud.githubusercontent.com/assets/1652105/6346844/093fcb52-bc0b-11e4-8bac-bc13c8244292.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/w3act/issues/255#issuecomment-75727628>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by kinmanli** [comment]
@peterwebster checked in. MIGHT NOT be in @GilHoggarth he deployed this morning.

**Comment by peterwebster** [comment]
This now seems fine to me, although the pane has subsequently to page top right as well, possibly in a ticket I missed. Having transplanted the outstanding matter to #291 , closing this ticket now.  @anjackson FYI
