### ISSUE TITLE
Unable to create a crawl permission in the production deployment

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#256]
In the /act production deployment, when in the Edit view of the UKWA Licensing tab, I can't use the green Open License Request button even when editing a record that has previously been saved.

I'm seeing the 'Before you can request a...' message, which should only the visible when the user is creating a new record and hasn't yet saved it for the first time.

I haven't seen this issue in /actdev, but haven't yet replicated it this morning, as it is being redeployed.

**Comment by peterwebster** [comment]
It seems to be OK in /actdev :

**Comment by peterwebster** [comment]
Nicola, who has the same account privileges as me, *was* able to create a crawl permission and send it out - so the issue must be with these two records:  
https://webarchive.org.uk/act/targets/16926
https://webarchive.org.uk/act/targets/16928

**Comment by kinmanli** [comment]
@peterwebster can you recreate this on actdev?

**Comment by peterwebster** [comment]
@kinmanli never happened before on /actdev , and I don't know how to replicate it as I don't know what I've done to give rise to it.

**Comment by kinmanli** [comment]
@peterwebster just that /actdev and /act are deployed in different ways, so am trying to narrow it down.

**Comment by peterwebster** [comment]
All I did was create a new target record and populate some fields, and then Save, which I must have done hundreds of times on /actdev without any problems  @kinmanli  Will try to create an identical record in /actdev now

**Comment by peterwebster** [comment]
OK, weirdly it's behaving the same at http://www.webarchive.org.uk/actdev/targets/16926/edit#licensing   (the same record transposed)

**Comment by kinmanli** [comment]
@peterwebster there is some validation around that button from old code. (target does have any QA Issues and no licenses). What are the rules for enabling the button?

Thanks

![2015-02-11 16-51-48_w3act](https://cloud.githubusercontent.com/assets/1652105/6151530/5f1cb352-b20e-11e4-9e00-2244e49ddd1e.png)

**Comment by peterwebster** [comment]
@anjackson can you think of any reason why there should be any connection between QA Status for a target and whether or not you can create a crawl permission? I can't, and think that that validation can come out.
The existing validation of the relationship with existing licences is probably correct.

**Comment by anjackson** [comment]
I don't think this should depend on QA Status. No idea what's going on there.

**Comment by peterwebster** [comment]
So @kinmanli to remove the validation that is connected to the QA Status field

The validation in relation to existing crawl permissions should stay:  could you summarise what it currently does ?

**Comment by kinmanli** [comment]
@peterwebster are you talking about the validation on this 'crawl permissions' link? 

![screen shot 2015-02-16 at 09 45 15](https://cloud.githubusercontent.com/assets/1652105/6209706/9e583bee-b5c0-11e4-93c8-f7e9efdad39a.png)

**Comment by peterwebster** [comment]
@kinmanli : the issue was with the Open License Request button, not the link

**Comment by kinmanli** [comment]
@peterwebster the validation for the button checks if it has a current license or if it has a higher license

**Comment by peterwebster** [comment]
Hi @kinmanli :  the validation for the button should be: is the Open UKWA License Requests fields set to any of Granted, Queued or Pending ? If so, you can't create a new crawl permission using this button.

If that field is Not Initiated or None, all the users we expect can create a new crawl permission.

If it's Refused, Email Rejected or Superseded, then only the Archivist/SysAdmin can create a new  crawl permission.

Would @anjackson agree ?

**Comment by peterwebster** [comment]
Also @anjackson :  this field has a positive value, Not Initiated, but I think that both the records imported from Andy's ACT *and* new records in W3ACT are probably set to None/Null. We probably want to tidy this up, but the validation above will work in the meantime.

**Comment by kinmanli** [comment]
@peterwebster updated the validation for the button and checked in.

**Comment by peterwebster** [comment]
OK, a policy question for @anjackson :  can we think of any circumstances where a target might have some other type of licence already (an HLF one, or a pre-2014 UKWA one) but we might still want to initiate this process. If so, we need to extend this validation a little.
http://www.webarchive.org.uk/actdev/targets/4/edit#licensing 

I'm thinking UKWA Selective = no, other types = yes

**Comment by anjackson** [comment]
@peterwebster I think we should write that out of scope for now.

**Comment by peterwebster** [comment]
Validation correct when crawl permission=Queued; =Refused;

**Comment by peterwebster** [comment]
Can't complete testing until new ticket #271 resolved

**Comment by kinmanli** [comment]
@peterwebster for https://github.com/ukwa/w3act/issues/271 can not just login to continue?

**Comment by anjackson** [comment]
Peter is testing the end-to-end workflow so would probably rather keep the testing realistic.

**Comment by anjackson** [comment]
Assigned to @peterwebster to test when #271 is resolved.

**Comment by kinmanli** [comment]
@GilHoggarth fixed

**Comment by nicolabingham** [comment]
Two permission records have been sent successfully for http://www.webarchive.org.uk/actdev/targets/16927 and http://www.webarchive.org.uk/actdev/targets/16928. 
@GilHoggarth does this resolve this issue or it there more to be tested here?

**Comment by GilHoggarth** [comment]
@nicolabingham As this ticket mentions https://webarchive.org.uk/act/targets/16926, could you also check for this target please.

**Comment by nicolabingham** [comment]
I tested this on /actdev/ and it worked. Does it also need to be tested on /act/ ?

**Comment by GilHoggarth** [comment]
Yes, but after the latest code is released to /act (w3act) - which should be "shortly".

**Comment by GilHoggarth** [comment]
@nicolabingham w3act now deployed with latest code - could you test this please.

**Comment by peterwebster** [comment]
So, the issue has evolved over time. The remaining test wasn't whether or not it was possible to send a permission, but whether the validation was in place to stop users queuing another email when a licence had already been granted. @nicolabingham 

So, if you were to grant the licence associated with this one http://www.webarchive.org.uk/actdev/crawlpermissions/61 

and actdev stops you then from trying to queue another from http://www.webarchive.org.uk/actdev/targets/act/act-21888 ,  this can be closed.

**Comment by nicolabingham** [comment]
Testing on W3 ACT  https://www.webarchive.org.uk/act/ and unable to send permissions. i get the error message Execution exception[[PersistenceException: Unique expecting 0 or 1 rows but got [2]]]

**Comment by kinmanli** [comment]
@nicolabingham which contact person did you enter as there maybe a duplicate in the DB on /act?

**Comment by nicolabingham** [comment]
@kinmanli the contact person was Nicola Bingham, which would be a duplicate

**Comment by GilHoggarth** [comment]
@kinmanli I think we need to resolve the duplicate entries before Nicola can test again - am I correct?
@nicolabingham No action here until we resolve the duplicates.

**Comment by kinmanli** [comment]
@GilHoggarth can you send us a snapshot of the nicola contact persons before you do? I want to see before I add an extra check to the 'findbyemail' code as it was case sensitive when doing a lookup.

**Comment by kinmanli** [comment]
@GilHoggarth weird that it's only on prod. Yes please clean it out as I have a snapshot if it re-occurs again. I'm going to add some checks when search for a contact person by email.

**Comment by kinmanli** [comment]
@GilHoggarth same as https://github.com/ukwa/w3act/issues/271

**Comment by GilHoggarth** [comment]
@nicolabingham And this issue please, also on **/actdev/**

**Comment by GilHoggarth** [comment]
@nicolabingham Can you test this issue as well please, on w3act.

**Comment by nicolabingham** [comment]
actdev prevents me from sending out a licence request for a Target which already has Permission Granted. A notification appears 'there is already a licence request...' and the request licence button remains inactive

**Comment by GilHoggarth** [comment]
What about on w3act? Would you describe this behaviour as a new discovery or is it related to the testing in this ticket?

**Comment by nicolabingham** [comment]
I thought that this was correct behaviour as the licence has already been granted.

**Comment by GilHoggarth** [comment]
Therefore closing ticket.
