### ISSUE TITLE
Handling of defunct accounts

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#257]
Hi @anjackson : @GilHoggarth raises a good point about what to do with user accounts of staff who have left and who therefore should be inactive, but which have data associated with them in ACT (and so can't just be deleted.)

I would suggest adding a user role, called Closed or something similar., which still shows up in the data but cannot log-in. Archivist and SysAdmin can then demote users as and when they leave.
Would you agree ?

**Comment by anjackson** [comment]
I'd just re-classify them as 'Viewers', no?

**Comment by peterwebster** [comment]
@anjackson but what if we positively don't want them even to have access to the data as viewers ?

**Comment by anjackson** [comment]
Then yes, a Closed account type seems appropriate.

**Comment by peterwebster** [comment]
Hi @kinmanli : not urgent, but at some point we need to create a new type of user, called Closed. They can't log in or do anything, but their identity persists in the data, so they are still shown in target records as having created them, and also in the Curators list.

**Comment by kinmanli** [comment]
new Role closed. less access than viewer

**Comment by kinmanli** [comment]
@peterwebster 

Add 'closed' role on when data.import is set to true (won't touch existing data). If user with closed account logs in it will give error message

**Comment by peterwebster** [comment]
Will test changing a few test accounts when actdev is up, but looking at the screenshot, we should change the error message to read: 'This user account has been closed. Please contact the British Library web archiving team.'

**Comment by kinmanli** [comment]
@peterwebster fixed - error message changed to above

**Comment by peterwebster** [comment]
@kinmanli in the GUI, the new account type isn't shown as an option at:

http://www.webarchive.org.uk/actdev/curators/43/edit  

so the archivist can't change the user's status.

**Comment by kinmanli** [comment]
@peterwebster I can't see that as I don't have an archive or sys admin account.

This is on mine. What do you get?

![screen shot 2015-02-24 at 08 20 32](https://cloud.githubusercontent.com/assets/1652105/6345438/143560b0-bbfe-11e4-9bae-910ee792a39c.png)

**Comment by peterwebster** [comment]
Logged in as an archivist @kinmanli 

![image](https://cloud.githubusercontent.com/assets/5520710/6346237/1a6b91c2-bc06-11e4-9f41-05b5e283ec99.png)

**Comment by kinmanli** [comment]
@peterwebster 'closed' role has not been saved to the 'actdev' DB because data.import has been switched off. I have moved the 'closed' role insert into Global.java so you don't have to switch import on. Wil have to redeploy

**Comment by GilHoggarth** [comment]
Latest code deployed to /actdev.

**Comment by kinmanli** [comment]
@nicolabingham please can you test to see if the "closed" role is showing up in the user admin section?

**Comment by nicolabingham** [comment]
Yes, I can see the Closed role and can assign it to users.

**Comment by GilHoggarth** [comment]
Ditto - tested on /actdev: could log into user account; changed my user account to 'closed' (as still 'user'); couldn't log in; re-enabled account (removed 'closed'); could log in again.

**Comment by GilHoggarth** [comment]
Tested with my own account. As admin marked account as closed - couldn't log in. Re-enabled account and all back to normal.
