### ISSUE TITLE
UKWA License form not found

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#259]
In the production version of W3ACT, Nicola successfully sent a permission email (to me) for target 16933 .

When I click on the link in the email, I get Page Not Found  

http://www.webarchive.org.uk/act/ukwa/licenseform/ccfb1879-3975-42d5-bcf6-cad2f5582303

**Comment by peterwebster** [comment]
It looks like the URL should be https://, which may be the issue

**Comment by kinmanli** [comment]
@peterwebster yes, it's the https:// the new deployment may fix it or it may produce the IP address of the box?

@GilHoggarth is there anyway of giving the hostname instead of the IP address? As it will save me from having to manually send it through?

**Comment by peterwebster** [comment]
Basically the same issue as #254

**Comment by kinmanli** [comment]
Fixed here: https://github.com/ukwa/w3act/commit/50d1815011c14b2b464d4da96d519de0dba7030f

**Comment by GilHoggarth** [comment]
@kinmanli Not sure if the hostname is what you want - the hostname of the w3act server is act05.wa.bl.uk for example, that's no good as an external host.

For us (WA), our public address is always www.webarchive.org.uk, so can you just use this from the `server_name` prod.conf setting and amend the protocol as appropriate?

**Comment by kinmanli** [comment]
@GilHoggarth was just looking for alternative ways. But did end up using the server_name in the end.

@peterwebster fixed and checked in

![2015-02-11 15-17-34_uk web archive - message plain text](https://cloud.githubusercontent.com/assets/1652105/6149553/7eab517c-b201-11e4-8d6b-62347b759a6a.png)

**Comment by peterwebster** [comment]
Also fixed:  closing ticket
