### ISSUE TITLE
Inconsistent Timestamps During Migration?

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#261]
There seems to be some inconsistency in the way dates are being migrated into w3act.

In the old system, Target `106` (`act-106` in w3act) has a creation time of 13:00 but in w3act this is 14:00 (although the date is the same).

Is there some issue with the timezone?

**Comment by peterwebster** [comment]
@kinmanli @PsypherPunk AIT were an hour ahead in Vienna....

**Comment by kinmanli** [comment]
Using the Long values for "field_crawl_start_date" and "created" from:

http://www.webarchive.org.uk/act/node/106.json

Converted produces the following in a test.

Thu Mar 07 12:12:20 GMT 2013
Sat Apr 06 14:00:00 BST 2013

**Comment by anjackson** [comment]
Not clear which is which, but the latter one should be from the start_date field.

 Andy's ACT reports the start date as:

    06 Apr 2013, 01pm

i.e. in GMT. In the JSON it is 1365253200, which comes out as "Sat, 06 Apr 2013 13:00:00 GMT" when converted manually, which is "Sat Apr 06 14:00:00 BST 2013" if you convert to the correct time zone for April!

i.e. in the crawl feed and UI, we want the times to always be printed in the current time-zone (i.e. GMT or BST), rather than the time-zone that corresponds to the date.  I think.

**Comment by kinmanli** [comment]
1362658340 - Thu Mar 07 12:12:20 GMT 2013
1365253200 -  Sat Apr 06 14:00:00 BST 2013

@anjackson so we want the client's current timezone?

**Comment by anjackson** [comment]
No, we want to store and report them always in the same Timezone, UTC/GMT.

**Comment by kinmanli** [comment]
Currently changed it to convert to UTC and saves it.

```
2015-02-19 09:28:14,903 [debug] application - European College of Hypnotherapy - Fri Jun 13 04:00:00 UTC 2014
```
Posgresql Client shows it with DST

![screen shot 2015-02-19 at 09 31 52](https://cloud.githubusercontent.com/assets/1652105/6264262/30b73e62-b81a-11e4-8109-6c10c5f0bc2a.png)

**Comment by anjackson** [comment]
So, are the crawl feeds outputting in UTC yet?

**Comment by kinmanli** [comment]
@anjackson I've not checked it in yet.

Are you looking at http://localhost:9000/actdev/api/targets/11776 to check the dates/times?

**Comment by anjackson** [comment]
We need to check with @PsypherPunk but I believe he is trying to use the crawl feed exports, like this one (https://www.webarchive.org.uk/act/targets/export/ld/daily) but they seem to be broken.  The other API hook also seems to be broken: https://www.webarchive.org.uk/act/api/targets/1

**Comment by kinmanli** [comment]
```
[{"id":74,"url":"act-106","updatedAt":1424337699468,"title":"BBC News: Homepage",... "crawlStartDateText":"06-04-2013 13:00","crawlEndDateText":null......
```

**Comment by anjackson** [comment]
That looks good. Thanks.

**Comment by GilHoggarth** [comment]
From Roger:
"
Re. the above, can we get the date formats in the feeds changed (not sure if there's a ticket open for this)?
They're currently of the form: "06-04-2013 13:00"
However, could they be changed to ISO 8601 format and clearly UTC? i.e. 2013-04-06T13:00:00Z?
"
@kinmanli Can you investigate this date format issue please and tell us if it's a quick fix or a more substantial bit of work. If former it should be completed in Milestone 1.0.0, if latter we'll move this to 1.1

**Comment by GilHoggarth** [comment]
Reopening issue to get it onto the Milestone 1.0.0 list.

**Comment by kinmanli** [comment]
@GilHoggarth currently the view's use 'crawlStartDateText'. I can create another transient field 'crawlStartDateUTC' and 'crawlStartDateUTC' which @PsypherPunk can use? That sufficient?

**Comment by kinmanli** [comment]
@PsypherPunk @GilHoggarth 

Does this look okay? Is this good to go?

```
"crawlStartDateText":"08-04-2013 12:00","crawlEndDateText":"12-06-2014 01:15"
```
```
"crawlStartDateUTC":"2013-04-08T12:00:00+0000","crawlEndDateUTC":"2014-06-12T01:15:00+0000","subjectSelect":null,
```

**Comment by GilHoggarth** [comment]
@kinmanli @PsypherPunk How might this work when we're in BST?

**Comment by GilHoggarth** [comment]
Andy's answered saying that yes this should be fine, but has asked for confirmation - @kinmanli Can you tell Roger where the lines of code are that format the date, @PsypherPunk Can you review the code and clarify if you're happy with it.

**Comment by kinmanli** [comment]
@GilHoggarth @PsypherPunk 

All dates are independent of Timezones. Dates are formatted into Strings and set using UTC for the strings.

Code at:

https://github.com/ukwa/w3act/blob/schemarefactor/app/uk/bl/api/Utils.java#L706-L725

**Comment by PsypherPunk** [comment]
Just to be utterly pedantic, can we use the fields `crawlStartDateISO` and `crawlEndDateISO`?

If everything's UTC anyway and explicit in the `Z` suffix then it's the  ISO format which distinguishes it.

Other than that, yep: the format's fine and the code looks good.

**Comment by GilHoggarth** [comment]
@kinmanli Assigned back to Kinman to make code change.

**Comment by kinmanli** [comment]
This look okay? @PsypherPunk @GilHoggarth. Checked in.

```
"crawlStartDateISO":"2013-04-08T12:00:00Z","crawlEndDateISO":"2014-06-12T01:15:00Z",
```

**Comment by PsypherPunk** [comment]
Perfect!

**Comment by GilHoggarth** [comment]
Closing ticket as Andy happy with change and Roger happy with code.
