### ISSUE TITLE
Reports filtered by QA not being applied

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#262]
The Reports > QA view is not having the filter by the QA Status of associated instances applied properly (or at all).

This view should return targets where there are instance records with QA Status = Failed
http://www.webarchive.org.uk/actdev/reportsqa/targets/?s=title&status=FAILEDINSTANCES&curatorId=-1&organisationId=-1&startDate=12-02-2015&collectionId=-1

and this for QA Status = Awaiting QA
http://www.webarchive.org.uk/actdev/reportsqa/targets/?s=title&status=AWAITINGQA&curatorId=-1&organisationId=-1&startDate=12-02-2015&collectionId=-1

but they just return all target records.

NB:  this is the QA Status of any associated instances - NOT the QA Status of the _target_

The use case is that the user comes here to begin work on QA, and needs to locate targets where there are instances with work to be done on them.

There's also an exception error if you try to take off the date filter. If no date range is set, it should return results from all time.

**Comment by peterwebster** [comment]
@kinmanli on second thoughts, just leave this until I can check a couple of things about the logic

**Comment by kinmanli** [comment]
comment out from menu for prod

**Comment by anjackson** [comment]
And to re-instate the menu item for this once we're ready.

**Comment by kinmanli** [comment]
@peterwebster Commented out @ https://github.com/ukwa/w3act/issues/262

**Comment by peterwebster** [comment]
Hi @nicolabingham : could we find some time around the training next week to have a look at this? It was to fulfil one of Rav's reporting requirements, but I'm not sure that it does exactly what we want. It's visible on /actdev, but not in the production version.

**Comment by nicolabingham** [comment]
@peterwebster yes of course. I will look into it beforehand and catch up with you next week.

**Comment by nicolabingham** [comment]
@peterwebster @kinmanli is it possible to present the collection terms in the same way that they appear on this page http://www.webarchive.org.uk/actdev/collections/list?s=title i.e., nest the collection terms so that the main collection headings can be expanded to show sub-categories?

**Comment by nicolabingham** [comment]
@peterwebster the Reports QA view seems to cover all the reporting requirements included here https://intranet.bl.uk:8443/confluence/display/WAG/ACT+Requirements apart from 
(b) instances newly available in reading rooms
(c) new instances committed from ACT to UKWA
I don't know if ACT would be able to report on these or whether it would be generated from the access tools.

**Comment by nicolabingham** [comment]
No longer needed as we are not using QA flags or filters in ACT
