### ISSUE TITLE
Behaviour of QA Dashboard on load, and QA Status filter

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#263]
Firstly, this page http://www.webarchive.org.uk/actdev/qa/list on loading should default to showing the first ten records in the list of targets.  

Secondly, the QA Status filter is being wrongly applied. At the minute, it is looking at the QA Status of the *target*. What we need is the QA Status of the most recent instance.

**Comment by kinmanli** [comment]
filter on QA Status of the Instance

**Comment by peterwebster** [comment]
In Instance records, the default for new records being created on import from Wayback should be null. 

In the UI, null should be presented as Unknown.

**Comment by kinmanli** [comment]
@peterwebster 

1) shows paged results on load
2) filters on qa_status of instances and shows most recent instance for that target

**Comment by peterwebster** [comment]
@kinmanli paged results looking good, but there are two things:

(i) the Most Recent column in the table is empty - it should show the actual date of the most recent instance record;

(ii) if you click on any of the numbers in the Instances to Date column, there's a null pointer error.

**Comment by kinmanli** [comment]
@peterwebster 

Most Recent now shows date if there is an 'instance'. 

Clicking on 'instances to date' will now to go the view

![screen shot 2015-02-18 at 16 42 05](https://cloud.githubusercontent.com/assets/1652105/6251704/5c4c063a-b78d-11e4-8343-26943f373019.png)
![screen shot 2015-02-18 at 16 34 25](https://cloud.githubusercontent.com/assets/1652105/6251703/5c45147e-b78d-11e4-81ab-3ffab16e5c64.png)

**Comment by peterwebster** [comment]
Looks good @kinmanli : I'll have a look at this tomorrow after /actdev has redeployed - but I see in the screenshots that  there are more recent instances in the instance list than is suggested by the Most Recent date in the table.

Also, in the table, it probably doesn't need the time, or the day of the week. Just 21 Mar 2013 would do, and save space.

**Comment by kinmanli** [comment]
check latest date and timestamp of most recent

**Comment by kinmanli** [comment]
@peterwebster checked in. Tested below.

![screen shot 2015-02-19 at 16 02 57](https://cloud.githubusercontent.com/assets/1652105/6270303/d4b6d866-b850-11e4-942f-1f8ebdacda65.png)

Select the 2nd row number 8 link

![screen shot 2015-02-19 at 16 03 12](https://cloud.githubusercontent.com/assets/1652105/6270304/d645cb7e-b850-11e4-96f7-797f4fd1d38b.png)

**Comment by peterwebster** [comment]
Thanks, this looks great @kinmanli , but I'm now getting an null pointer error when clicking on any of the instance record links  (20130412.....)  at http://www.webarchive.org.uk/actdev/instances/listbytarget/?s=title&o=asc&t=7793

**Comment by kinmanli** [comment]
@peterwebster There is nothing there when I go to:

http://www.webarchive.org.uk/actdev/instances/listbytarget/?s=title&o=asc&t=7793

**Comment by peterwebster** [comment]
![image](https://cloud.githubusercontent.com/assets/5520710/6344370/9462a752-bbef-11e4-8d49-709a3ad190b0.png)
is what I see at http://www.webarchive.org.uk/actdev/instances/listbytarget/?s=title&o=asc&t=7793

A click on the first one 20130412153301 gives a Null Pointer Error

![image](https://cloud.githubusercontent.com/assets/5520710/6344379/be0d4742-bbef-11e4-9c1a-3de0f959f92a.png)

**Comment by anjackson** [comment]
Do we need to re-import instances? I'm seeing an empty list.

**Comment by kinmanli** [comment]
@GilHoggarth can you make my user kinman.li@bl.uk an archivist so I can check this?

**Comment by GilHoggarth** [comment]
Done for /actdev.

**Comment by kinmanli** [comment]
thanks @GilHoggarth 

Can you send me the last exception from the logs?

**Comment by GilHoggarth** [comment]
Last log sent.

**Comment by GilHoggarth** [comment]
@kinmanli In the Instances page (e.g., http://www.webarchive.org.uk/actdev/instances/listbytarget/?s=title&o=asc&t=7793), the (mid-crawl) URL is still referring to crawler03 - needs to be changed like the QA Instance URL.

**Comment by kinmanli** [comment]
@peterwebster working on actdev now.

![2015-02-24 13-54-07_w3act](https://cloud.githubusercontent.com/assets/1652105/6350540/b00a157a-bc2c-11e4-932e-da07e37eda84.png)

![2015-02-24 13-54-25_w3act](https://cloud.githubusercontent.com/assets/1652105/6350541/b00b953a-bc2c-11e4-9f0e-53e2b3e24db7.png)

@GilHoggarth 'mid-crawl' now points correctly

![2015-02-24 13-55-18_w3act](https://cloud.githubusercontent.com/assets/1652105/6350559/d8d0998e-bc2c-11e4-88bc-47d471fedbe6.png)

**Comment by peterwebster** [comment]
Could @GilHoggarth give a view on whether the links now direct where you expect them to?

**Comment by peterwebster** [comment]
@kinmanli null pointer error is sorted - thanks.

There is one more issue around this, but I'm going to create a new ticket for clarity.

**Comment by peterwebster** [comment]
@kinmanli null pointer error sorted - thanks.

There's a issue about the application of the QA Status filter at:  http://www.webarchive.org.uk/actdev/qa/list?f=eastsussex.gov.uk

This suggests that for eastsussex.gov.uk the *most recent* instance has Status=No QA Issues

If you look here, that isn't the case: http://www.webarchive.org.uk/actdev/instances/listbytarget/?t=1804

The filter needs to be on the QA Status of the *most recent* instance.

**Comment by GilHoggarth** [comment]
As far as I'm aware there are no more links to crawler03 that need to be changed to travel via the w3act service. However, the wayback UI is not showing the wayback logo (due to a mime type setting I'd assume). But, **more importantly** the QA Instance link isn't currently working.
http://www.webarchive.org.uk/actdev/wayback/*/http://www.active-east.co.uk redirects back to http://www.webarchive.org.uk/actdev

**Comment by kinmanli** [comment]
@peterwebster initial investigation maybe a data issue as local one shows as.

![2015-02-25 13-50-03_w3act](https://cloud.githubusercontent.com/assets/1652105/6371602/5057ae5c-bcf5-11e4-84af-7110e0508262.png)

**Comment by kinmanli** [comment]
![2015-02-25 14-42-20_w3act](https://cloud.githubusercontent.com/assets/1652105/6372504/9bd94690-bcfc-11e4-9ffd-a62bed0a02f0.png)

![2015-02-25 14-42-36_w3act](https://cloud.githubusercontent.com/assets/1652105/6372506/9d9706a2-bcfc-11e4-93bc-7eeae28104f3.png)

**Comment by kinmanli** [comment]
@peterwebster fixed and checked in... see above.

**Comment by kinmanli** [comment]
test the filter

**Comment by peterwebster** [comment]
This looks good to me (the QA Status filtering, that is) so closing this ticket and moving the one remaining issue to #275
