### ISSUE TITLE
Creating New Targets in Bulk

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#266]
We frequently need to create numerous Targets en masse. Previously, this made use of ACT's REST API and external scripts for this.

Ideally, w3act should have similar functionality. Either:

1. A similar API for the creation of single targets and we script the process.
2. A means for uploading spreadsheets with all new Target information and having w3act handle the creation.

If the Play framework makes the creation of an API simple enough then the first would be preferable. The latter might cause problems as we'd have to define the field format of the spreadsheet. Alternatively, if uploading a JSON/XML/etc. would be simpler we could do the conversion before uploading.

**Comment by peterwebster** [comment]
I'd like to discuss this one with @anjackson on Friday, as one of the requirements identified at the beginning of the project and then parked was the facility *also* to do this from within the GUI (as well as administratively within the WAT)

**Comment by peterwebster** [comment]
Part 1 to be done now; part 2 later.

@kinmanli the API needs to replicate what is current for Andy's ACT. Validation needed against targets with the same URLs.

**Comment by anjackson** [comment]
I think we should do (1) under the 1.1.0 milestone and put (2) in a new ticket for a later date.

Part 1 should accept the same JSON as W3ACT produces per target, and refuse to create Targets if the URL is already known to the system.

@PsypherPunk can you supply an example of the client code, so it's clear how this used to work in Andy's ACT?

**Comment by PsypherPunk** [comment]
I think this was the most complete version used:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-

    import sys
    import act
    import csv
    import json
    from dateutil import parser

    a = act.ACT()
    with open(sys.argv[1], "rb") as i:
        c = csv.reader(i, delimiter=",", quotechar='"')
        for title, url, subject, org, coll, freq, start in c:
            data = {}
            data["type"] = "url"
            data["title"] = title
            data["field_url"] = [{"url": url}]
            data["field_crawl_frequency"] = freq
            data["field_crawl_start_date"] = start
            data["field_collection_categories"] = []
            for coll in coll.split("|"):
                data["field_collection_categories"].append({"uri": "http://www.webarchive.org.uk/act/taxonomy_term/%s" % coll, "id": "%s" % coll, "resource": "taxonomy_term"})
            data["field_nominating_organisation"] = {}
            data["field_nominating_organisation"]["uri"] = "http://www.webarchive.org.uk/act/node/%s" % org
            data["field_nominating_organisation"]["id"] = org
            data["field_nominating_organisation"]["resource"] = "node"
            data["field_subject"] = {}
            data["field_subject"]["uri"] = "http://webarchive.org.uk/act/taxonomy_term/%s" % subject
            data["field_subject"]["id"] = subject
            data["field_subject"]["resource"] = "taxonomy_term"

            print json.dumps(data)
            a.send_data("", json.dumps(data))

**Comment by kinmanli** [comment]
@PsypherPunk do you have the format of the input?

**Comment by PsypherPunk** [comment]
Here's y'go:

    {
      "title": "Your Thurrock",
      "field_subject": {
        "resource": "taxonomy_term",
        "uri": "http://webarchive.org.uk/act/taxonomy_term/192",
        "id": "192"
      },
      "field_crawl_frequency": "monthly",
      "field_nominating_organisation": {
        "resource": "node",
        "uri": "http://www.webarchive.org.uk/act/node/101",
        "id": "101"
      },
      "field_url": [
        {
          "url": "http://yourthurrock.com"
        }
      ],
      "field_collection_categories": [
        {
          "resource": "taxonomy_term",
          "uri": "http://www.webarchive.org.uk/act/taxonomy_term/297",
          "id": "297"
        }
      ],
      "type": "url",
      "field_crawl_start_date": "1417255200"
    }

**Comment by kinmanli** [comment]
@PsypherPunk is the Python code you supplied a CSV to Json parser? 

So am I writing a parser to taking an json input file and converting it to targets?

**Comment by PsypherPunk** [comment]
Yes: the former ACT had a REST endpoint where we'd POST JSON similar to the above and it would produce a Target (or an error).

As we're writing the submitter in Python we're flexible as to the exact format of the JSON though, the above was largely dictated by the Drupal system.

**Comment by anjackson** [comment]
@kinmanli We can switch to W3ACT's 'native' JSON serialisation if that makes this easier.

**Comment by kinmanli** [comment]
@GilHoggarth currently working on this

**Comment by kinmanli** [comment]
@PsypherPunk how are you sending the json? Via curl or other means?

**Comment by PsypherPunk** [comment]
Yes, it'll be a HTTP POST, probably using Python.

**Comment by kinmanli** [comment]
@PsypherPunk so it's literally this we are importing? http://www.webarchive.org.uk/act/node.json?type=url

**Comment by PsypherPunk** [comment]
That URL seems to contain data for _every_ Target; the POST submission would contain _one_ of those Target records.

In the existing system, to create a new record, we'd POST to: `http://www.webarchive.org.uk/act/node/`

The POST would contain JSON like the above (a subset of the data contained in an [individual record](http://www.webarchive.org.uk/act/node/21593.json)).

**Comment by anjackson** [comment]
So, note that we already have this API (GET only): 

* Get a Target: http://www.webarchive.org.uk/actdev/api/targets/1

I imagined the JSON format would be the same, except:

* POST JSON to http://www.webarchive.org.uk/actdev/api/targets
* If same URL as existing Target, ERROR (409 (Conflict) sounds about right).
* If not, create a new Target and return return a 201 (Created) with a Location header of the new resource.

**Comment by kinmanli** [comment]
Tested using:

curl -v -H "Content-Type: application/json" -X POST -d '{"body":[],"field_scope":"root","field_url":[{"url":"http:\/\/www.electionwatch.co.uk\/","attributes":[]}],"field_subject":{"uri":"http:\/\/webarchive.org.uk\/act\/taxonomy_term\/227","id":"227","resource":"taxonomy_term"},"field_depth":"capped","field_via_correspondence":false,"field_uk_postal_address":false,"field_uk_hosting":false,"field_description":[],"field_uk_postal_address_url":[],"field_nominating_organisation":{"uri":"http:\/\/webarchive.org.uk\/act\/node\/101","id":"101","resource":"node"},"field_crawl_frequency":"daily","field_suggested_collections":[],"field_collections":[],"field_crawl_start_date":"1422943200","field_crawl_end_date":"1431057600","field_uk_domain":"Yes","field_license":[],"field_crawl_permission":"","field_collection_categories":[{"uri":"http:\/\/webarchive.org.uk\/act\/taxonomy_term\/300","id":"300","resource":"taxonomy_term"},{"uri":"http:\/\/webarchive.org.uk\/act\/taxonomy_term\/305","id":"305","resource":"taxonomy_term"}],"field_special_dispensation":false,"field_special_dispensation_reaso":null,"field_live_site_status":null,"field_notes":[],"field_wct_id":null,"field_spt_id":null,"field_snapshots":[],"field_no_ld_criteria_met":false,"field_key_site":false,"field_uk_geoip":"Yes","field_professional_judgement":false,"field_professional_judgement_exp":null,"field_ignore_robots_txt":false,"field_instances":[],"nid":"21593","vid":"34746","is_new":false,"type":"url","title":"Election Watch - UK General Election 2015 ","language":"en","url":"http:\/\/webarchive.org.uk\/act\/node\/21593","edit_url":"http:\/\/webarchive.org.uk\/act\/node\/21593\/edit","status":"1","promote":"0","sticky":"0","created":"1422887984","changed":"1422887984","author":{"uri":"http:\/\/webarchive.org.uk\/act\/user\/61","id":"61","resource":"user"},"log":"","revision":null,"comment":"2","comments":[],"comment_count":"0","comment_count_new":"0","feed_nid":null}' -u kinman.li@bl.uk:password http://localhost:9000/actdev/api/targets

**Comment by kinmanli** [comment]
@GilHoggarth checked in.

**Comment by GilHoggarth** [comment]
Deployed onto /actdev, Roger testing.

**Comment by PsypherPunk** [comment]
Any documentation? Which fields are mandatory?

Fields like `field_nominating_organisation`, `field_subject`, etc. reference old-ACT URIs which I presume don't exist in the w3act...?

**Comment by kinmanli** [comment]
@PsypherPunk I'll tidy it up a bit more. Give a me a couple of minutes.

**Comment by kinmanli** [comment]
@PsypherPunk is this the complete input?

```
{
  "title": "Your Thurrock",
  "field_subject": {
    "resource": "taxonomy_term",
    "uri": "http://webarchive.org.uk/act/taxonomy_term/192",
    "id": "192"
  },
  "field_crawl_frequency": "monthly",
  "field_nominating_organisation": {
    "resource": "node",
    "uri": "http://www.webarchive.org.uk/act/node/101",
    "id": "101"
  },
  "field_url": [
    {
      "url": "http://yourthurrock.com"
    }
  ],
  "field_collection_categories": [
    {
      "resource": "taxonomy_term",
      "uri": "http://www.webarchive.org.uk/act/taxonomy_term/297",
      "id": "297"
    }
  ],
  "type": "url",
  "field_crawl_start_date": "1417255200"
}
```

**Comment by PsypherPunk** [comment]
Yep, that was taken from an actual (working) submission.

**Comment by kinmanli** [comment]
@nicolabingham Do you know if "selector" is a mandatory field?

![2015-03-02 11-12-05_w3act](https://cloud.githubusercontent.com/assets/1652105/6439692/17454c60-c0cd-11e4-884d-b8200556894c.png)

**Comment by nicolabingham** [comment]
@kinmanli yes, this should be mandatory.

**Comment by kinmanli** [comment]
@PsypherPunk 

Mandatory fields for Target in W3ACT
Title, URL(s), Selector.

**Comment by kinmanli** [comment]
@GilHoggarth please redeploy to actdev. Working with the json above.

**Comment by kinmanli** [comment]
@PsypherPunk 

I tested it locally and used my actdev email and password:

curl -v -H "Content-Type: application/json" -X POST -d '{"title": "Your Thurrock","field_subject": {"resource": "taxonomy_term","uri": "http://webarchive.org.uk/act/taxonomy_term/192","id": "192"},"field_crawl_frequency": "monthly","field_nominating_organisation": {"resource": "node","uri": "http://www.webarchive.org.uk/act/node/101","id": "101"},"field_url": [{"url": "http://yourthurrock.com"}],"field_collection_categories": [{"resource": "taxonomy_term","uri": "http://www.webarchive.org.uk/act/taxonomy_term/297","id": "297"}],"type": "url","field_crawl_start_date": "1417255200"}' -u kinman.li@bl.uk:password http://www.webarchive.org.uk/actdev/api/targets

**Comment by GilHoggarth** [comment]
Latest deployed onto /actdev

**Comment by PsypherPunk** [comment]
Getting a `401` error in /actdev:

    curl -v -H "Content-Type: application/json" -X POST -d '{"title": "Your Thurrock","field_subject": {"resource": "taxonomy_term","uri": "http://webarchive.org.uk/act/taxonomy_term/192","id": "192"},"fiequency": "monthly","field_nominating_organisation": {"resource": "node","uri": "http://www.webarchive.org.uk/act/node/101","id": "101"},"field_url": [{"url": "http://yourthuxrrock.com"}],"field_collection_categories": [{"resource": "taxonomy_term","uri": "http://www.webarchive.org.uk/act/taxonomy_term/297","id": "297"}],"type": "url","field_crawl_start_date": "1417255200"}' -u roger.coram@bl.uk:XXX http://www.webarchive.org.uk/actdev/api/targets

Additionally, the above shouldn't work; the example JSON is from the old system and looks like:

    "field_subject": {
        "resource": "taxonomy_term",
        "uri": "http://webarchive.org.uk/act/taxonomy_term/192",
        "id": "192"
      }

However, in w3act there's no subject with that ID so it _should_ fail. Also, URLs look like: 

    http://www.webarchive.org.uk/actdev/subjects/24

Same for `field_nominating_organisation` and `field_collection_categories`.

**Comment by kinmanli** [comment]
@PsypherPunk I think this ticket needs to include all of those

**Comment by kinmanli** [comment]
@PsypherPunk I get the following as there is already one in there.

```
About to connect() to www.webarchive.org.uk port 80 (#0)
*   Trying 194.66.232.82...
* Connected to www.webarchive.org.uk (194.66.232.82) port 80 (#0)
* Server auth using Basic with user 'kinman.li@bl.uk'
> POST /actdev/api/targets HTTP/1.1
> Authorization: Basic a2lubWFuLmxpQGJsLnVrOnBhc3N3b3Jk
> User-Agent: curl/7.30.0
> Host: www.webarchive.org.uk
> Accept: */*
> Content-Type: application/json
> Content-Length: 531
>
} [data not shown]
* upload completely sent off: 531 out of 531 bytes
< HTTP/1.1 409 Conflict
< Date: Mon, 02 Mar 2015 12:09:55 GMT
< Content-Length: 0
< Connection: close
< Content-Type: text/plain; charset=UTF-8
```

**Comment by anjackson** [comment]
Yes, I'd more or less expect the JSON API for things like subject, categories, organisations etc. to look quite different to the old one, and just reference the new ID's of subjects etc. directly.

e.g. if field_subject is single-valued:

    "field_subject": "24",

...or if it's multi-valued:

    "field_subject": [ "24" ],

i.e. the REST client should be expected to know the IDs of the referenced entities.

**Comment by PsypherPunk** [comment]
Yep, so to use the above:

    {
      "title": "Your Thurrock",
      "field_subject": ["24"],
      "field_crawl_frequency": "monthly",
      "field_nominating_organisation": "101",
      "field_url": ["http://yourthurrock.com"],
      "field_collection_categories": ["297"],
      "field_crawl_start_date": "1417255200"
    }

So, essentially flatten `field_subject`, `field_url` and `field_collection_categories` to just a list in each case.

If we send through a value for `field_subject`, `field_nominating_organisation` or `field_collection_categories` which doesn't exist (or even invalid values for `field_crawl_frequency`,  `field_crawl_start_date` or `field_crawl_end_date`) then it should probably error.

**Comment by kinmanli** [comment]
@PsypherPunk does it have to be those names ("field_subject", etc)?

This is because we were using those when importing from old ACT and already have objects for that.

i.e.
"field_subject": {"resource": "taxonomy_term","uri": "http://webarchive.org.uk/act/taxonomy_term/192","id": "192"}

**Comment by PsypherPunk** [comment]
Doesn't have to be those, no: can change them to something else if it's easier...?

**Comment by kinmanli** [comment]
@PsypherPunk does this look okay to you with the names? Just using it with corrects subjects and collections

```
{
	"title": "Turok 2",
	"field_subjects": ["13","14"],
	"field_crawl_frequency": "monthly",
	"field_nominating_org": "1",
	"field_urls": ["http://turok99.com"],
	"field_collection_cats": ["8","9"],
	"field_crawl_start_date": "1417255200"
}
```

**Comment by PsypherPunk** [comment]
That looks good to me.

**Comment by kinmanli** [comment]
@PsypherPunk what error code do you want it to produce when no subject, collection, etc is found based on the incoming ID?

**Comment by PsypherPunk** [comment]
I think the only one that sounds right is `400`...?

**Comment by kinmanli** [comment]
@GilHoggarth please can you redeploy to actdev? Thanks

**Comment by GilHoggarth** [comment]
@kinmanli  Done.

**Comment by PsypherPunk** [comment]
I managed to break it (`500` error; `NullPointerException: null content`) with the following:

    {
      "field_collection_cats": [
        "188"
      ],
      "field_crawl_frequency": "daily",
      "field_urls": [
        "http://www.independent.co.uk/news/uk/politics/"
      ],
      "field_nominating_org": "1",
      "title": "Independent, The: UK Politics"
    }

**Comment by kinmanli** [comment]
Added additional validation for title, urls etc.

Please redeploy @GilHoggarth, please test @PsypherPunk

**Comment by PsypherPunk** [comment]
Tested using existing data; entered the `field_collection_cats` as above which correctly adds it to the Collection _News and Commentary_ but not the parent Collection _UK General Election 2015_.

Otherwise looks good. Managed to catch a duplicate URL too.

**Comment by PsypherPunk** [comment]
Parent Collections being picked up correctly.

I've put through a submission like this:

    {
      "field_urls": [
        "http://www.dailymail.co.uk/news/article-2943512/Labour-s-500k-help-tax-avoidance-firm-Party-urged-stop-taking-advice-company-accused-controversial-schemes.html"
      ],
      "title": "Daily Mail: Labour's 500k help from 'tax avoidance' firm",
      "field_nominating_org": "1",
      "field_collection_cats": [
        "188"
      ],
      "field_crawl_frequency": "annual",
      "field_crawl_end_date": "1425877200",
      "field_crawl_start_date": "1425790800"
    }

The Target `/actdev/targets/17190` has been created, however, the `field_crawl_end_date` hasn't been carried through.

**Comment by kinmanli** [comment]
@PsypherPunk can you post the complete json for a Target so I can test which ones are optional?

**Comment by PsypherPunk** [comment]
To re-use the above, I think the following contains all the fields we might want to include:

    {
        "field_urls": [
            "http://www.dailymail.co.uk/news/article-2943512/Labour-s-500k-help-tax-avoidance-firm-Party-urged-stop-taking-advice-company-accused-controversial-schemes.html"
        ],
        "title": "Daily Mail: Labour's 500k help from 'tax avoidance' firm",
        "field_nominating_org": "1",
        "field_collection_cats": ["188"],
        "field_crawl_frequency": "annual",
        "field_crawl_end_date": "1425877200",
        "field_crawl_start_date": "1425790800",
        "field_subjects": [],
        "field_uk_postal_address": false,
        "field_via_correspondence": false,
        "field_professional_judgement": false,
        "field_professional_judgement_exp": ""
    }

There's also the `selector` (i.e. the user who owns the Target) but I'm not sure what the corresponding field would be (can't seem to see it in the exports).

**Comment by kinmanli** [comment]
@PsypherPunk 'selector' is stored as 'author'.

Will you be passing in the 'selector' ID?

**Comment by PsypherPunk** [comment]
Yes, we'll pass through the ID.

**Comment by kinmanli** [comment]
Hi @GilHoggarth, please redeploy

**Comment by GilHoggarth** [comment]
@kinmanli Redeployed.

**Comment by PsypherPunk** [comment]
If I want to set the Selector, what should the field key be? `selector` or `field_selector`?

**Comment by kinmanli** [comment]
@PsypherPunk "selector":"99"

**Comment by PsypherPunk** [comment]
Submitted further samples; created successfully with start/end dates passed through.

**Comment by GilHoggarth** [comment]
@PsypherPunk As you were submitting data into production w3act via this mechanism, can this issue now be closed as tested and working?

**Comment by PsypherPunk** [comment]
In addition to the above, we'll also need to pass `field_uk_postal_address_url` through.

In fact, can we add a validation step? If `field_uk_postal_address` is set to `true`, `field_uk_postal_address_url` _must_ be passed through too?

**Comment by anjackson** [comment]
Can you add this as a new ticket for 1.1.0 and reference back to this one? It'll help keep the history clear I think?
