### ISSUE TITLE
Wrong QA Wayback link in W3ACT

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#267]
The QA Wayback links points to Opera, and it should point to Crawler03. So that should be fixed pronto.

However, we got the go-ahead to make the QA Wayback available externally, with some constraints. In particular, it needs to be authenticated, using the same credentials as the users use for W3ACT itself.

/cc FYI @peterwebster

**Comment by GilHoggarth** [comment]
Reassigning to @kinmanli

**Comment by anjackson** [comment]
Once @kinmanli has fixed the initial problem, we need to adapt this approach: http://stackoverflow.com/a/13703606

**Comment by kinmanli** [comment]
@GilHoggarth @anjackson Changed to crawler03 in prod.conf. This commit should fix it. https://github.com/ukwa/w3act/commit/eca7a2a603b0c0858276bd4464e99c5065552b9d

**Comment by GilHoggarth** [comment]
@kinmanli I'll try this but it's already crawler03 in prod.conf, so this might be coming back to you!

**Comment by kinmanli** [comment]
@GilHoggarth what's it in application.conf?

**Comment by GilHoggarth** [comment]
@kinmanli It's crawler03 in application.conf - https://github.com/ukwa/w3act/blob/schemarefactor/conf/application.conf

**Comment by kinmanli** [comment]
@GilHoggarth Are you running it via the waybackinstanceimport.sh script?

**Comment by GilHoggarth** [comment]
@kinmanli Don't think we're talking about `waybackinstance_import.sh` here, just the links in w3act UI that point to a QA Wayback instance. Currently under last week's deployment these point to opera.

**Comment by kinmanli** [comment]
@GilHoggarth  which link? I thought the link to the wayback instance was removed? Anyway, that uses the conf file too.

**Comment by GilHoggarth** [comment]
@kinmanli For example, https://www.webarchive.org.uk/act/targets/2672#crawlpermission > bottom on UI page > Instances > "In QA Wayback" URL is http://opera.bl.uk:8080/wayback/*/http://acommonreader.org/

Think we've looked at this before and discovered that the setting in prod.conf isn't making a difference to this URL value.

**Comment by kinmanli** [comment]
@GilHoggarth ah I got you. that's hardcoded into the pages.

**Comment by kinmanli** [comment]
@GilHoggarth Now uses wayback url from config file instead of hardcoded in view/edit. Updated in both application.conf and prod.conf

**Comment by anjackson** [comment]
Okay, I'm going to move the other bits to an internal ticket. Thanks all.
