### ISSUE TITLE
Presenting QA wayback content only to w3act authenticated users

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#268]
The new w3act service should be able to present QA wayback content to people outside of BL – specifically to those curators who are at the other Legal Deposit Libraries (so that they can clarify the crawled website is correct before it goes ‘public’). [BL trac ticket 2463 (http://tickets.wa.bl.uk/trac/ticket/2463).]

I can think of two ways of doing this. Either:
1)	Proxy https://www.webarchive.org.uk/wayback/ to a new Apache web service running on the w3act server. This would receive the /wayback request, challenge the w3act service to see if the client provided login details are valid, and if so proxy the crawler03 wayback content to the client (so Apache handles the proxying). This seems messy to me as the user would need to enter their credentials twice.
2)	Use a w3act sub-level URL for wayback, such as https://www.webarchive.org.uk/act/wayback/. As this is within /act, users will have already authenticated onto the /act service – no extra authentication to view the wayback content. In this approach though, w3act will have to act as a proxy to the crawler03 wayback service.

@kinmanli The latter seems much more desirable to me, but as I don’t know play or java I don’t know if it’s feasible. Can you investigate please and clarify if you think this is possible.

**Comment by kinmanli** [comment]
@GilHoggarth so you want me to find out if I can may a URL and redirect it to crawler03 with it's parameters?

**Comment by GilHoggarth** [comment]
Well not redirect but proxy, i.e., the URL remains unchanged (www.webarchive.org.uk/act) as opposed to crawler03.bl.uk. But basically yes.

**Comment by anjackson** [comment]
Yes, presumably via the [Play Framework WS API](https://www.playframework.com/documentation/2.2.x/JavaWS), the idea would be that calls to "https://www.webarchive.org.uk/act/wayback/" would be authenticated and then proxied to crawler03. 

Note that, if the basic authentication and proxying works, we will probably need to tweak the Wayback installation on Crawler03 to use the new URI. I think @PsypherPunk knows how this goes.

**Comment by kinmanli** [comment]
@anjackson when 'proxying' to the wayback url, is this how you want play to handle the exceptions?

![screen shot 2015-02-19 at 10 24 21](https://cloud.githubusercontent.com/assets/1652105/6265042/80166634-b821-11e4-8cdc-cfa6e4d6c4c6.png)

**Comment by GilHoggarth** [comment]
As a matter of understanding, can you browser crawler03 from outside the office (BL network)?

**Comment by kinmanli** [comment]
@GilHoggarth no I cannot

**Comment by anjackson** [comment]
You can use use the public Wayback for testing, I think? http://www.webarchive.org.uk/wayback/archive/20100906204014/http://www.london2012.com/

**Comment by anjackson** [comment]
@kinmanli that's fine for the errors, btw.

**Comment by anjackson** [comment]
Note, from the policy:

* The connection must be over SSL, e.g.https://ldwa-qa.ldls.org.uk/wayback/
* The connection must need a login, using actively-maintained, individual credentials.
* The server will use [cache-control headers](http://stackoverflow.com/questions/9884513/avoid-caching-of-the-http-responses) to prevent resources from being cached locally.

So, it is possible to add/override the headers along these lines:

    Expires: Tue, 03 Jul 2001 06:00:00 GMT
    Last-Modified: {now} GMT
    Cache-Control: no-store, no-cache, must-revalidate, max-age=0
    Cache-Control: post-check=0, pre-check=0
    Pragma: no-cache

**Comment by anjackson** [comment]
Also, just in case it's not clear, all users with access to this need training to ensure that they know they should not print or save-as etc. @peterwebster

**Comment by kinmanli** [comment]
@GilHoggarth @anjackson @peterwebster Checked in 'proxying' from actdev to wayback

http://localhost:9000/actdev/wayback/archive/20100906204014/http://www.london2012.com/
(https://www.webarchive.org.uk/act/wayback/archive/20100906204014/http://www.london2012.com/)

http://www.webarchive.org.uk/wayback/archive/20100906204014/http://www.london2012.com/

**Comment by GilHoggarth** [comment]
@kinmanli Checking the last two URLs above, the /act/wayback/ link fails but the /wayback/ link works. 

Does this mean that currently the github code is configured to point to webarchive.org.uk/wayback? That would I think be incorrect as that's serving public website content for UKWA. The /act/wayback/ URL should proxy to crawler03.bl.uk, which isn't available publicly (so to allow ACT archivists to review the crawled websites before they go live.)

I'll deploy this new code on /actdev so we can clarify this.

**Comment by kinmanli** [comment]
@GilHoggarth it depends how you've set it up in your config file.

w3act won't work yet until you've deployed it.

**Comment by GilHoggarth** [comment]
@kinmanli Okay, I've amended /actdev application.conf to set:
```
#application.wayback.url="http://crawler03.bl.uk:8080/wayback"
application.wayback.url="http://www.webarchive.org.uk/actdev/wayback"
```
Which I understand to mean that a target Instance "QA wayback" link might read http://www.webarchive.org.uk/actdev/wayback/*/http://www.active-east.co.uk but should actually proxy content from http://crawler03.bl.uk:8080/actdev/wayback/*/http://www.active-east.co.uk

Having restarted /actdev I do get this url (http://www.webarchive.org.uk/actdev/wayback/*/http://www.active-east.co.uk) but clicking it only gives me the /actdev login page even though the browser URL is still correct and that I am logged in (I had to be to see the target page and to be able to click the QA wayback link.

I'm now deploying the new github code to w3act as I wonder if some internal server issue is happening here.

**Comment by GilHoggarth** [comment]
Rats, same. Redeployed github code; amended prod.conf to:
```
#application.wayback.url="http://crawler03.bl.uk:8080/wayback"
application.wayback.url="https://www.webarchive.org.uk/act/wayback"
```
Logged in, viewed target https://www.webarchive.org.uk/act/targets/15536 - QA wayback URL = https://www.webarchive.org.uk/act/wayback/*/http://www.active-east.co.uk but this only opens a new browser window showing this correct URL but the login page UI.

**Comment by GilHoggarth** [comment]
PS no information is captured in crawler03's wayback log.

**Comment by kinmanli** [comment]
@gilhoggarth you need to be logged in for the proxing to work. Are you using prod.conf? It is only using that property to proxy. It is not in the code

**Comment by GilHoggarth** [comment]
Logged into where? I am logged into w3act (or /actdev), otherwise I wouldn't be able to see the target. /actdev is using application.conf and w3act is using prod.conf, both amended as above. 
I don't understand what you mean about *only using that property to proxy. It is not in the code*

**Comment by kinmanli** [comment]
When I'm logged into act and put this in the browser. I get the screenshot below (see the browser's url)

https://www.webarchive.org.uk/act/wayback/*/http://www.active-east.co.uk 

![screen shot 2015-02-20 at 16 39 18](https://cloud.githubusercontent.com/assets/1652105/6304852/2c09da90-b91f-11e4-93c0-00d204180d88.png)

**Comment by GilHoggarth** [comment]
The image's URL is from your local deployment, which may well mean that this deployment is different from the w3act service. Did you try the https... URL immediately above? If so, what did it show?

**Comment by kinmanli** [comment]
It working okay now @GilHoggarth?

**Comment by kinmanli** [comment]
@GilHoggarth added '/*/' prefix to waybackcontroller - checked in.

**Comment by kinmanli** [comment]
@GilHoggarth actually I might have to revert this as urls specified like below will stop working

```
https://www.webarchive.org.uk/act/wayback/archive/20100906204014/http://www.london2012.com/
```

**Comment by kinmanli** [comment]
@GilHoggarth updated edit/view target and instance pages to include /*/

**Comment by GilHoggarth** [comment]
Re. cache control - http://httpd.apache.org/docs/2.2/caching.html#security covers authenticated content. As the w3act material is being handled by an isolated service, the above mentioned cache control headers have been added for all content for this w3act service.

**Comment by kinmanli** [comment]
@GilHoggarth Checked in the content type setting

​https://github.com/ukwa/w3act/commit/6ae69b1bd0a5040151569937b4d071b5af56cc2e

**Comment by anjackson** [comment]
So, there seem to be two issues. Firstly, and most importantly, the current proxying code does not handle redirects. If the Wayback response is a 303, the proxy code should also emit a 303, but re-writing the Location so that it points to the ACT proxy.

The second issue is that failing to handle the 303 seems to cause an error, and for some reason, going to the error page actually produces a login page. Have we made the error page admin-only or something?

**Comment by kinmanli** [comment]
@anjackson there is .```setFollowRedirects(true)``` option. Do you have a url I can use as a test case?

Thanks

**Comment by anjackson** [comment]
Unfortunately, that would hide what's going on from the end user, and would make QA difficult. For example, you could request an item from 2050 and it would appear to work! I think we have to re-write the redirect instead.

**Comment by kinmanli** [comment]
@anjackson Can you post a url so I can use as a test case?

Thanks

**Comment by anjackson** [comment]
https://www.webarchive.org.uk/act/wayback/20140611000704js_/http://bl.uk/scripts/jquery-1.5.1.min.js which redirects to a different timestamp.

**Comment by GilHoggarth** [comment]
@anjackson @kinmanli /actdev now configured to use crawler03.bl.uk:8081, a new wayback tomcat with different settings (in application.conf; w3act uses prod.conf)

**Comment by kinmanli** [comment]
Very strange my local one redirects to "https://www.webarchive.org.uk/act/login"

**Comment by anjackson** [comment]
I mean the Wayback back-end for https://www.webarchive.org.uk/act/wayback/20140611000704js_/http://bl.uk/scripts/jquery-1.5.1.min.js redirects to a different timestamp. ACT mishandles the situation, and directs you to the login.

I'm concerned this is not critical functionality for the first production release of W3ACT and it's holding other things up. There are more serious problems under this milestone, like the null pointers when viewing instances. https://github.com/ukwa/w3act/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.0.0+W3ACT+Production+Release+%26+Deployment%22

Perhaps we should push this back to 1.1.0 (which was the original idea anyway)?

**Comment by kinmanli** [comment]
Fixed other ticket https://github.com/ukwa/w3act/issues/263 and deployed to actdev awaiting testing from @peterwebster.

For this ticket the above js script redirects to. Still working on it.

![2015-02-24 14-40-14_mozilla firefox](https://cloud.githubusercontent.com/assets/1652105/6351438/986e834a-bc33-11e4-83a5-334ccc03fb26.png)

**Comment by kinmanli** [comment]
This:
http://crawler03.bl.uk:8080/wayback/20140611000704js_/http://bl.uk/scripts/jquery-1.5.1.min.js

Redirects to:
https://www.webarchive.org.uk/act/wayback/20140611000731js_/http://www.bl.uk/scripts/jquery-1.5.1.min.js

**Comment by anjackson** [comment]
Aha, of course, Wayback already knows the right URL  prefix, so you just need to hand the redirect back to the browser (without re-writing it). Phew.

**Comment by peterwebster** [comment]
Very happy to move this back to 1.1.0 @anjackson - will do so now.

**Comment by anjackson** [comment]
Okay, I see this in the application configs:

ws.followRedirects=true

It turns out not only would this hide information from the user (as I said above), it also fundamentally breaks what we're trying to do. It means W3ACT attempts to resolve the redirect, and so tries to make a HTTP request to itself. W3ACT is not logged into itself, so it fails.

I have checked in an alternative, that I think should work, but am having problems setting up the dev system.

**Comment by anjackson** [comment]
This seems to work okay, but I'd rather cleanly pass all the headers through:
```java
		                    public Result apply(WS.Response response) {
		
		                    	Logger.debug(wayback + " (" + response.getStatusText() + " " + response.getStatus() + ") " + response.getUri());
		                    	
		                    	String contentType = response.getHeader(CONTENT_TYPE);
		                    	Logger.debug("content type: " + contentType);
		                    	if ( response.getHeader(LOCATION) != null ) {
		                    		response().setHeader(LOCATION, response.getHeader(LOCATION));
			        			}
		                    	return status(response.getStatus(), response.getBody()).as(contentType);
		                    }
```

I'm removing all the login code around the edges, and reverting to the original security annotation, as I'm pretty sure that's all we need.

**Comment by GilHoggarth** [comment]
@anjackson Deployed as the daily rollout on /actdev - this revised code works up to http://www.webarchive.org.uk/actdev/wayback/20141220010852/http://www.active-east.co.uk/ but then the wayback attempt to redirect to http://www.webarchive.org.uk/actdev/wayback/20141220010852/http://www.active-east.co.uk/Pages/default.aspx doesn't respond, presumably with a redirect loop going on.
The wayback logo still doesn't show btw.

**Comment by kinmanli** [comment]
is ``` ws.followRedirects=true ``` still in your application.conf/prod.conf?

**Comment by GilHoggarth** [comment]
Nope. Not in /actdev application.conf or w3act prod.conf.

**Comment by anjackson** [comment]
Weird. I seems to work okay for me, although the Wayback deployments are slightly different, which might be confusing things.

I checked in a change to the Location redirect response logic, which seems to work locally.

More alarmingly, for me, ACTDEV is encoding my password in the cookie name IN PLAIN TEXT. Where was this added? I wonder if this is causing problems elsewhere?

**Comment by kinmanli** [comment]
@anjackson this was added last night when I was looking at other ways of authentication and made it's way in to applicationcontroller.

**Comment by kinmanli** [comment]
Does your URL get masked when there is a "redirection" from crawler03 back to /actdev?

**Comment by anjackson** [comment]
I found something odd - if I created a 'private browser' window and logged in afresh it worked, whereas before that it did not. I wonder if the change to the cookie is causing issues.

i.e. if you log out and log in again, or perhaps better still, manually clear the cookie, does it work?

**Comment by anjackson** [comment]
Seems the proxy handler was munging binary files and was not carrying through query parameters. Should all work fine now, I think.

**Comment by GilHoggarth** [comment]
Works on /actdev - waiting for testing on next w3act deployment.

**Comment by GilHoggarth** [comment]
Tested with https://www.webarchive.org.uk/act/wayback/*/http://apracticeforeverydaylife.com/ and https://www.webarchive.org.uk/act/wayback/20150101011008/http://apracticeforeverydaylife.com/- can view when logged in, can't view when not logged in.

@kinmanli Can you repeat this test as you're outside of the BL network please.

**Comment by kinmanli** [comment]
@GilHoggarth works outside of BL network

![screen shot 2015-03-05 at 13 54 42](https://cloud.githubusercontent.com/assets/1652105/6505992/350c222c-c33f-11e4-942b-6f3c19919c98.png)

![screen shot 2015-03-05 at 13 55 22](https://cloud.githubusercontent.com/assets/1652105/6506017/671981d8-c33f-11e4-8a96-8e9113c04174.png)

**Comment by anjackson** [comment]
@kinmanli can you edit your post to remove the screenshot please? We're not allowed to publish screenshots of this material.

**Comment by kinmanli** [comment]
@anjackson removed

**Comment by anjackson** [comment]
@kinmanli thanks.
