### ISSUE TITLE
Sorting in QA target lists

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#269]
The list of instances here would be better sorted in reverse chron order, giving *most recent* first

http://www.webarchive.org.uk/actdev/instances/listbytarget/?p=1&s=title&o=asc&t=2973

**Comment by niladreeb** [comment]
The list of instances are already sorted in reverse chronological order giving the most recent first. Wherever it can be reversed into showing the old record first by clicking the 'Title' header.

**Comment by niladreeb** [comment]
Working properly in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Failed.
- Targets > List Instances
- Entered "http://www.bbc.co.uk" to get a sufficiently large result set
- Clicked 'Organisation' to see  An unexpected error has occurred.
 "Execution exception[[PersistenceException: java.util.concurrent.ExecutionException: javax.persistence.PersistenceException: Query threw SQLException:ERROR: column "fieldnominatingorganisation" does not exist "

Having repeated this check on the other search order options - Title and URLs - these work on /actstage.

**Comment by niladreeb** [comment]
Sorting  with organisation working fine.

**Comment by niladreeb** [comment]
Moreover as per the url example given in the first comment, this ticket need to be tested from this link Targets>List Targets>Clicking on any target>Clicking on Instances on the right hand side of the page.

**Comment by GilHoggarth** [comment]
Works on /actstage (will log a separate issue for the Targets > List Instances java exception).

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Repeated test as above `Targets > List Targets > (select a target) > (select title or URL for list order) - works as expected.

**Comment by GilHoggarth** [comment]
Taking an inordinate amount of time to generate list of instances for gov.uk publications - raised act05 VM to 16GB, 14GB to w3act.
Sorting works in live.
