### ISSUE TITLE
Not possible to filter targets for those without a license

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#270]
At http://www.webarchive.org.uk/actdev/targets/list?s=title , if one searches with 'None' as the value for the License filter, it returns the whole list.

**Comment by peterwebster** [comment]
@anjackson this is because for all the other filter options for this list, filtering on None isn't a real use case (there are no target records where Curator=None, and no-one should search for records that are *not* flagged for attention.) However, looking for records without a licence yet is a real use case.

Not sure what, if anything, to do, as to change the None behaviour for just one filter upsets the logic of the view in the GUI. It also affects the default behaviour when the page first loads - "all filters set to none, except Licence which equals ANY"
Not sure it's a priority.

**Comment by anjackson** [comment]
I guess it's not a priority, but filtering on 'ANY' should be different than filtering on 'EMPTY'. Maybe we need better names, so we can add 'filter for UNSET/EMPTY/NULL' and keep it's meaning separate from 'filter is NONE' (meaning no filter applied).

**Comment by peterwebster** [comment]
Pinging to @nicolabingham for comment, and assigning to @anjackson for assignment of milestone.

**Comment by nicolabingham** [comment]
@peterwebster @anjackson yes, it is necessary to search for Targets without a license. Would it be acceptable to use 'Targets without a license' as the filter? If we use this we can probably keep 'None' (no filter applied).

**Comment by kinmanli** [comment]
@nicolabingham are we leaving this page as it is?

![2015-03-16 15-59-38_w3act](https://cloud.githubusercontent.com/assets/1652105/6670250/7b33ec26-cbf5-11e4-95c8-820620bae974.png)

**Comment by nicolabingham** [comment]
@kinmanli can we remove "None" from the filters for Curator, Organisation, Crawl Frequency, Depth and Flag. Retain "None" as a filter for License. @peterwebster I think "None" equals filter for sites that do not have a licence?

**Comment by crarugal** [comment]
No way of filtering targets that have no UKWA Licence

![image](https://user-images.githubusercontent.com/18530934/53090585-cd7bda00-3507-11e9-9dad-e8c07c7d2a8e.png)

An example where permission for an UKWA Licence has not been initiated: https://www.webarchive.org.uk/act/targets/51572#licensing

![image](https://user-images.githubusercontent.com/18530934/53090613-e3899a80-3507-11e9-97cf-0cb0a529dbb1.png)

**Comment by min2ha** [comment]
I'll try to clarify situation from my point of view.
It's all about interpretation.
Andy mentioned already that the term 'NONE' in **FILTER context** could be interpret as 'DO NOT FILTER' or in other words 'SHOW UN-FILTERED LIST' or 'SHOW ALL'.
If it is acceptable, I'd prefer to leave it but for convenience add **new Licence type** - 'Empty' or 'No licence'. Any suggestions are welcome.

**Comment by crarugal** [comment]
@min2ha Would it be possible to keep "NONE" and then perhaps as you suggest, add a new Licence filter: "Not Initiated" or "No Licence".

**Comment by min2ha** [comment]
@crarugal okay, it seems it's optimal solution, let's try that on beta and see if it works.
So, initial solution would be: keep 'NONE' together with adding new type of licence type 'No Licence'.
