### ISSUE TITLE
URL for Open UKWA Licence granting directs to password-protected ACT

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#271]
This link is included in the email, but resolves to the ACT login page

"If you are happy for your site to be archived, please complete the online licence form http://www.webarchive.org.uk/actdev/ukwa/licenseform/4e13ed50-ba47-411c-ae32-ba9ad4127d89 that will permit us to proceed."

**Comment by kinmanli** [comment]
@peterwebster Thought this used to work?

**Comment by kinmanli** [comment]
@peterwebster which other pages do not need authentication to besides this and the login page? The controller for this page always required authentication to gain access.

@Security.Authenticated(SecuredController.class)

**Comment by anjackson** [comment]
This and the login pages are the only non-auth pages as far as I know. Please implement that for now.

**Comment by kinmanli** [comment]
@GilHoggarth fixing this as we speak

**Comment by kinmanli** [comment]
@GilHoggarth fixed now

**Comment by GilHoggarth** [comment]
The URL listed in the first message of this ticket was tested whilst the Admin user was logged in and out; both accessible. http://www.webarchive.org.uk/actdev/collections/list?s=title was tested whilst logged in and out, the former was accessible the latter wasn't.

**Comment by GilHoggarth** [comment]
Reopening so the same test is performed on w3act.

**Comment by GilHoggarth** [comment]
The above UKWA licence URL isn't valid on w3act so I haven't found the licence form, but I have tested successfully that a page (https://www.webarchive.org.uk/act/targets/15536) can only be viewed when logged in.

@nicolabingham Can you test this please, by doing whatever's necessary to be sent the UKWA licence URL in an email and checking that it viewable which you are both logged into w3act and logged out.

**Comment by nicolabingham** [comment]
I am unable to send the licence when logged in. I get the error message: Execution exception[[PersistenceException: Unique expecting 0 or 1 rows but got [2]]]

**Comment by kinmanli** [comment]
@nicolabingham @GilHoggarth 

Looks like the same issue as https://github.com/ukwa/w3act/issues/256 "duplicate contact person in contact_person table"

**Comment by GilHoggarth** [comment]
@kinmanli You're correct, these tables differ. /actdev has 4 rows, Nicola's with full details, Peter's website but missing details, and two test data entries. w3act has 5 rows - one for grahamclark.co.uk, and one complete and one missing detail for both Nicola and Peter.

**Comment by GilHoggarth** [comment]
@nicolabingham Can you test again please on w3act, just to check if your noted problem was/wasn't due to the java memory problem.

@kinmanli Would you like me to clean out the incorrect contact_person table entries?

**Comment by kinmanli** [comment]
@GilHoggarth weird that it's only on prod. Yes please clean it out as I have a snapshot if it re-occurs again. I'm going to add some checks when search for a contact person by email.

**Comment by GilHoggarth** [comment]
@kinmanli The incomplete contact_person entries are older - is there any ID/key join from this table to others? I'm just wanting to ensure that deleting the older entries isn't going to break a join to other data.

**Comment by kinmanli** [comment]
@GilHoggarth please can you check in crawl_permission table where contact_person_id=?

**Comment by GilHoggarth** [comment]
@kinmanli Doing that now and talking with Andy about this - seems a bit odd. (crawl_permissions table looks okay btw). Andy testing now...

**Comment by kinmanli** [comment]
@GilHoggarth please can you check actdev table contact_person for my email = 'kinman.li@bl.uk'. I'm hoping there are multiples now?

**Comment by GilHoggarth** [comment]
Yep, there are.

**Comment by kinmanli** [comment]
@GilHoggarth it's in the license form

**Comment by GilHoggarth** [comment]
@kinmanli Are you working on fixing it?

**Comment by kinmanli** [comment]
@GilHoggarth yes, the licenseform looks up by 'name' instead of email. I don't know if there was a ticket for the validation of the licenseform?

**Comment by GilHoggarth** [comment]
@peterwebster Are you aware if there's been a ticket for the validation of the licence form? Otherwise, @kinmanli I suggest you just add the detail to this ticket.

**Comment by kinmanli** [comment]
@GilHoggarth fixed. When you are in the license form I've changed it so it looks up by email instead of name. 

Please test in actdev when you are ready.

**Comment by kinmanli** [comment]
@GilHoggarth this is related to https://github.com/ukwa/w3act/issues/256.

Also, as there are still duplicate email's in contact person's table in 'act'/prod. These need to be rectified as it will still throw that exception. Probably 'reassign' those crawl permissions to the contact person you want to keep?

**Comment by GilHoggarth** [comment]
Understood - I'll remove the contact_person duplicates and ensure crawl_permissions are correctly ID'd. Restarting /actdev now.

**Comment by GilHoggarth** [comment]
Duplicate contact_person removed from /actdev. @nicolabingham Can you test this issue on **http://www.webarchive.org.uk/actdev** please.

**Comment by nicolabingham** [comment]
In actdev tried to create a permission request with contact email nicola.bingham@bl.uk and got the notification "A contact person with email 'nicola.bingham@bl.uk' is already in the Contact Persons list...."
Clicked save and the permission was sent successfully. Record has been updated to Permission Pending. Completed licence form in email and had submission successful message. Received Thankyou email. Target record has been updated to Permission Granted.
Successful completion of permissions process on actdev.

**Comment by nicolabingham** [comment]
Successfully sent permission request on W3ACT. Permission completed and Target record updated to Granted.

**Comment by GilHoggarth** [comment]
Sounds like a closed issue to me, so closing. Please reopen if I'm wrong.
