### ISSUE TITLE
Subject should not be a required field.

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#272]
The Subject field should no longer be a required field.

**Comment by kinmanli** [comment]
@GilHoggarth fixed and checked in.

**Comment by nicolabingham** [comment]
Successfully removed subject metadata from target http://www.webarchive.org.uk/actdev/targets/16935/ and saved it.

**Comment by nicolabingham** [comment]
Created a new target http://www.webarchive.org.uk/actdev/targets/16996 without subject terms. Saved and updated successfully.

**Comment by GilHoggarth** [comment]
Reopening so the same test is performed on w3act.
