### ISSUE TITLE
Issue for users with more than 1 'type'

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#274]
Even though Nicola's account is an 'Archivist', Nicola wasn't able to save a target, the Save button was 'greyed out'. In checking her account, I saw that her account type was both 'Archivist' and 'User'. By removing the 'User' setting, Nicola logging out and back in again, she was able to Save the same target. 

In discussion, it sounds like user account types are exclusive - a user can only be of one type. 

Assigning this issue to Peter for his consideration.

**Comment by peterwebster** [comment]
@kinmanli I'd understood it that if a user has two roles, they should be default be able to act in line with the higher role. Is that not right ?

**Comment by kinmanli** [comment]
@peterwebster yes they can

**Comment by peterwebster** [comment]
@kinmanli it might be worth double-checking that, as if that's the case, Nicola's issue is something else.

**Comment by kinmanli** [comment]
@peterwebster if that user has that role in the list then they are allowed to proceed

**Comment by peterwebster** [comment]
Already raised and put on hold at #225

**Comment by peterwebster** [comment]
I just closed #225 which was substantially the same issue as this.

As this now has a milestone, let's confirm that a user should only have one role. @anjackson 

Assigning to @kinmanli

**Comment by anjackson** [comment]
Yes - users should only have one role.

**Comment by kinmanli** [comment]
Now using radio buttons and only allowed to select a single role. 

![screen shot 2015-03-06 at 23 36 03](https://cloud.githubusercontent.com/assets/1652105/6538399/96509714-c459-11e4-9856-22c0756574a2.png)

**Comment by anjackson** [comment]
Will follow this up in #370

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Issue concentrating on integrity of data - i.e., no user should have more than 1 role. Checking the postgres database `role_user` table, there are not users will more than 1 role.

Database also check on production service - no users will more than 1 role there either. Ticket consequently closed.
