### ISSUE TITLE
Differential browser behaviour when loading QA Wayback

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#275]
[transferred from #263 as raised originally by @GilHoggarth ]

"The wayback UI is not showing the wayback logo (due to a mime type setting I'd assume). 

But, more importantly the QA Instance link isn't currently working.
http://www.webarchive.org.uk/actdev/wayback/*/http://www.active-east.co.uk redirects back to http://www.webarchive.org.uk/actdev "

Subsequent investigation with @kinmanli and @anjackson suggests that this is fine in Chrome but not in IE.

Adding this to 1.0.0

**Comment by kinmanli** [comment]
@peterwebster isn't this just related to https://github.com/ukwa/w3act/issues/268?

**Comment by kinmanli** [comment]
@peterwebster just tested this and it seems to be working after you login (or already logged in)

**Comment by kinmanli** [comment]
The link (mentioned in OP) http://www.webarchive.org.uk/actdev/wayback/*/http://www.active-east.co.uk  seems to be working?

![2015-03-03 09-53-44_internet archive wayback machine](https://cloud.githubusercontent.com/assets/1652105/6459967/40af3e4e-c18b-11e4-82b5-115ed3628458.png)

**Comment by anjackson** [comment]
Yes, I think I've fixed this. There were two outstanding problems:

* Binary files were getting treated as UTF-8. This, oddly, seems to have lead to GIFs that IE could read but others could not!
* URL query parameters were not being proxied through, which cause the query failures that @PsypherPunk saw.

I believe these have been fixed now.

**Comment by GilHoggarth** [comment]
Tested on /actdev, works for me. Waiting to be tested on next w3act deployment.

**Comment by GilHoggarth** [comment]
Now works in Chrome but not in BL IE (9.0.8112.16421 64-bit)

**Comment by GilHoggarth** [comment]
Having cleared my BL IE browser cookies et al (everything in Tools > Delete Browsing History...), I can now use the site via IE.

Same UI homepage to QA wayback instance display walkthrough performed in Chrome, looks fine.
