### ISSUE TITLE
Execution exception when populating manual NPLD tests

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#276]
When populating this:  http://www.webarchive.org.uk/actdev/targets/16976/edit#crawlpermission

and trying to record Yes in the UK Postal Address field, it throws:

Execution exception[[PersistenceException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_subject_target" Detail: Key (target_id, subject_id)=(16976, 24) already exists.]]

**Comment by kinmanli** [comment]
@peterwebster Is this doing an update or new record?

**Comment by anjackson** [comment]
Is this ready to test, @kinmanli ?

**Comment by kinmanli** [comment]
@anjackson @GilHoggarth yes ready to test.

I think @peterwebster is thinking of reverting back to what it was before as there maybe an issue with the way users select parent subjects. https://github.com/ukwa/w3act/issues/191

**Comment by nicolabingham** [comment]
Tested this target http://www.webarchive.org.uk/actdev/targets/16976 - added a postal address to the NPLD criteria and checked the postal address box. This was saved successfully (no error message). 

Added subject terms to the same target. Selected 'Arts & Humanities' top level subject heading and saved the record. This was added successfully without the system adding any child terms. 
I then removed this subject metadata and started again adding just a child term, 'Art & design' without adding the top level subject term. After saving the child subject group had been saved and the top level subject term was checked by the system automatically. 
This seems to be the correct behaviour and can be signed off.

**Comment by GilHoggarth** [comment]
Reopening so the same test is performed on w3act.

**Comment by peterwebster** [comment]
As with #191 @GilHoggarth , should we expect this to behave differently when deployed to the production version? If not, this can be closed ...

**Comment by GilHoggarth** [comment]
@nicolabingham Can you test again please on w3act.

**Comment by nicolabingham** [comment]
Tested on W3ACT - Target https://www.webarchive.org.uk/act/targets/7793. Subject metadata is performing as in tests on actdev yesterday.
Closing this issue.
