### ISSUE TITLE
Wayback uses IA logo and 'home' returns error page

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#277]
If /act/wayback/ link is used, the user is shown the IA logo (which I think might confuse users and lessen our effort). If this logo is clicked (or if the 'Home' link is clicked), the user sees:
```
Sorry, that page does not exist.
    /act/wayback/
```

**Comment by GilHoggarth** [comment]
On /actdev, selecting the IA logo now shows the expected wayback "home page".
Waiting for testing on next w3act deployment.

**Comment by GilHoggarth** [comment]
w3act wayback still uses IA logo but at least it now links to the expected wayback query page.

**Comment by GilHoggarth** [comment]
@PsypherPunk to amend wayback logo.

**Comment by PsypherPunk** [comment]
Deployed to `/actdev`. As per Trac #2480, I've made it look _"like UKWA"_. Can someone verify that this is what we want?

**Comment by anjackson** [comment]
Pretty much, but I think we should override the banner with something that says "Web Archive QA Wayback - please do not download or distribute content from here!" or something similar. It looks a bit too much like the real thing.

**Comment by PsypherPunk** [comment]
I sense the need for a `<blink/>` tag...

**Comment by PsypherPunk** [comment]
Banner now reads _"Legal Deposit QA OpenWayback; please do not download or distribute content from here."_

Calendar display now shows _"Legal Deposit QA OpenWayback"_.

**Comment by GilHoggarth** [comment]
GilHoggarth to test on /actdev.

**Comment by GilHoggarth** [comment]
Tested on /actdev and seen as complete.

**Comment by GilHoggarth** [comment]
Guess the necessary changes need to be rolled out onto the live /act wayback server, i.e., not part of the w3act deployment. Assigning to Roger for the necessary changes.

**Comment by anjackson** [comment]
I think this has all been lost following upgrade of OpenWayback. Pushing back to future release.

**Comment by PsypherPunk** [comment]
Changes rolled out to w3act's OpenWayback installation (changes in the `wayback-qa` subdirectory of the `waybacks` project).
