### ISSUE TITLE
Remove unnecessary accounts and details from code and documentation

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#279]
In the code there's still some users defined (such as user@bl.uk), database admin defined, and AIT defined. Would be good clear these out of both the code and the documentation.

**Comment by anjackson** [comment]
Related to #280.

Certainly we don't want any DB details or other 'real' credentials in there.

**Comment by kinmanli** [comment]
@GilHoggarth fixed - stopped importing from drupal. Removed flag from application/prod.conf.
Separated the accounts.yml import. Fixed the same time as https://github.com/ukwa/w3act/issues/280

**Comment by GilHoggarth** [comment]
Removed account and organisation details from conf/ files.

**Comment by GilHoggarth** [comment]
Removed details from documentation, and added deployment insertion. Tested on /actdev, works.

Now waiting for testing on production w3act when all 1.0.1 milestone tickets verified on /actdev.

**Comment by GilHoggarth** [comment]
As a "documentary" issue, not testing this on v1.0.1 release.
