### ISSUE TITLE
Remove ability to import data from Drupal /act

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#280]
Just to ensure we never accidently import data from the old Drupal /act service, the code that does this should be commented out.

Consequently, in the future all data imports will have to be done via the database export/import services.

**Comment by kinmanli** [comment]
@GilHoggarth trash the users in accounts.yml, the import code and the flag?

**Comment by anjackson** [comment]
I was wondering about just commenting out the Drupal import part. The accounts.yml is useful when setting up a test system for development.

**Comment by GilHoggarth** [comment]
How about: remove the current users in accounts.yml but keep the code that reads them; comment out the data import code; and keep the flag?

**Comment by anjackson** [comment]
See also point in #279 about leaving a few accounts there for spinning up a test server.

**Comment by kinmanli** [comment]
@GilHoggarth 
https://github.com/ukwa/w3act/commit/8a06db9bb0714a4286f3a7ead2dd40ae59656902

**Comment by anjackson** [comment]
Is that code still capable of importing from Drupal? That's what we want to disable. The accounts.yml is actually useful for testing.

**Comment by kinmanli** [comment]
@anjackson this bit does the whole data import and is now commented out. 

https://github.com/ukwa/w3act/commit/05695dc6db71cb7c6228fa029dee772118c363e2

**Comment by kinmanli** [comment]
@GilHoggarth Stop importing from drupal. Removed flag from application/prod.conf.
Separated the accounts.yml import

**Comment by GilHoggarth** [comment]
With Kinman's import code commented out, and with the configuration settings set to "don't import", re-ran the w3act deployment script on /actdev that should import data - it did not import any data.

**Comment by GilHoggarth** [comment]
Ran deployment script (that doesn't try to import data) with the "use.accounts" field in application.conf set to true - a new account (testing@bl.uk) was added.
