### ISSUE TITLE
Logging into /actdev using Chrome results in blank screen

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#281]
Using the chrome web browser, when I log into /actdev I see a blank screen (using the admin account for this test.)

**Comment by kinmanli** [comment]
@GilHoggarth Fixed and checked in. When logging in it checks if "url" is blank or null.

**Comment by GilHoggarth** [comment]
Tested on /actdev and seen to work correctly. Waiting for next w3act deployment for official test.

**Comment by GilHoggarth** [comment]
Tested on v1.0.1 w3act, now works fine in Chrome.
