### ISSUE TITLE
Nominations Failing

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#283]
We're testing the nominations hook at `/actdev/nominations/load/json`. We're POSTing data and although we're getting positive responses (see below) the Targets aren't searchable.

    {"status":"OK","message":"Nomination Nomination Test Name 00"}
    {"status":"OK","message":"Nomination Nomination Test Name 01"}
    {"status":"OK","message":"Nomination Nomination Test Name 02"}
    {"status":"OK","message":"Nomination Nomination Test Name 03"}
    {"status":"OK","message":"Nomination Nomination Test Name 04"}
    {"status":"OK","message":"Nomination Nomination Test Name 05"}
    {"status":"OK","message":"Nomination Nomination Test Name 06"}
    {"status":"OK","message":"Nomination Nomination Test Name 07"}
    {"status":"OK","message":"Nomination Nomination Test Name 08"}
    {"status":"OK","message":"Nomination Nomination Test Name 09"}

An example of the data we're sending:

    {
        "name": "Nomination Test Name 00",
        "title": "Nomination Test Title 00",
        "website_url": "http://www.webarchive.org.uk/00",
        "email":"",
        "tel":"",
        "address":"",
        "nominated_website_owner":"",
        "justification":"",
        "notes": "Nomination Test Note 00",
        "nomination_date":""
    }

**Comment by anjackson** [comment]
Note that Nominations do not automatically create Targets. There should be a list of Nominations in W3ACT, as candidates for becoming Targets, and your POSTs should be adding to that list.

**Comment by PsypherPunk** [comment]
Ah, okay; I see that now (/actdev/nominations/list). In which case it's working.
