### ISSUE TITLE
Add .wales and .cymru to the TLD whitelist

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#284]
As well as .uk, .scot and .london, .wales and .cymru should also be whitelisted TLDs. Please make it so.

**Comment by kinmanli** [comment]
updated and checked in.

**Comment by GilHoggarth** [comment]
@kinmanli How can I test this works correctly?

**Comment by GilHoggarth** [comment]
Checked on /actdev and works well. Waiting for w3act deployment for final test.

**Comment by GilHoggarth** [comment]
Tested and .wales and .cymru are automatically recognised as whitelisted TLDs - DONE.
However, trying to delete my test record (http://suffix-test.cymru) after the test didn't result in the target being removed - so raising this as a bug.
