### ISSUE TITLE
Deleting a target doesn't remove it

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#286]
In testing #284 I tried to delete my test target after this issue test, but it isn't removed - I can still find the record via the Browse Targets UI.

**Comment by GilHoggarth** [comment]
Note, added test target is http://suffix-test.cymru

**Comment by nicolabingham** [comment]
I also experienced this same issue c.20 mins ago when I tried to delete https://www.webarchive.org.uk/act/targets/14877 from W3ACT. The target is still visible.

**Comment by GilHoggarth** [comment]
Comment from Nicola to add, this did work in a past test, though I don't think we know exactly when.

**Comment by kinmanli** [comment]
@GilHoggarth 
Originally it was showing this error. 

```
2015-03-05 14:24:20,543 [debug] application - deleting
2015-03-05 14:24:20,562 [debug] play - Unable to parse part of media range header 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
```

So I refactored and moved the delete function. Delete works and also deletes it's related reference objects/entries. Instances, Crawl Permissions etc.

**Comment by GilHoggarth** [comment]
@anjackson Sounds like the delete function removes much information - is this all appropriate?

**Comment by GilHoggarth** [comment]
@kinmanli Which account types can perform the delete?

**Comment by nicolabingham** [comment]
@GilHoggarth @kinmanli should only be archivist and sys admin who can delete targets

**Comment by kinmanli** [comment]
@GilHoggarth @nicolabingham from what I see it is sys admin, archivist and the owner/selector of the target record

**Comment by nicolabingham** [comment]
@GilHoggarth @kinmanli Yes, it should be ok to allow the owner/selector of the target record to delete targets as well as sys admin and archivist

**Comment by GilHoggarth** [comment]
@nicolabingham Does the delete action of removing lots of stuff ("reference objects/entries. Instances, Crawl Permissions etc" as Kinman mentioned above) sound appropriate?

**Comment by nicolabingham** [comment]
@GilHoggarth @kinmanli the main reason for deleting a target would be that it had been entered in error, e.g. a duplicate, in which case it would be appropriate to delete "lots of stuff" as specified. However deleting instances and crawl permissions sounds a bit risky. We certainly would not want to delete a crawl permission. Perhaps we should restrict this ability to just Sys Admin and Archivist?

**Comment by GilHoggarth** [comment]
@anjackson Your thoughts on Nicola's comment?

**Comment by kinmanli** [comment]
@GilHoggarth @nicolabingham a Target has many things related to it, such as licenses, crawl permissions etc. If the target gets deleted and if some dependencies (such as crawl permissions) are left floating around then there is nothing related to it.

**Comment by anjackson** [comment]
One alternative would be to not-really-delete Targets, but put them into a 'Closed' state instead and hide them. But that brings a lot of additional complications.

Perhaps a better solution is to check if there is a license associated with the Target, and refuse to delete a Target that still has a license. Similarly, it should not be possible to delete a Target that is in a Collection.

**Comment by GilHoggarth** [comment]
@kinmanli Assigned to you so you're aware Andy suggested a further check for this issue.

**Comment by kinmanli** [comment]
@anjackson do we include "higher level" licenses in this check?

**Comment by anjackson** [comment]
Yes.

**Comment by kinmanli** [comment]
@GilHoggarth will not delete if it has license(s) (inc higher level ones) and/or collection(s).

![2015-03-10 13-33-40_w3act](https://cloud.githubusercontent.com/assets/1652105/6575798/1cde49a2-c72a-11e4-98a9-45ca1cdc1aa0.png)

**Comment by GilHoggarth** [comment]
GilHoggarth to test on /actdev.

**Comment by GilHoggarth** [comment]
Succeeded in deleting http://www.nicelife from /actdev. However, there's a whole bunch of variations above, when to delete, when to not delete etc., so @nicolabingham can you test this to ensure you're happy with the current solution.

**Comment by nicolabingham** [comment]
@GilHoggarth I want to be able to delete my test sites e.g. 'nicola's test site 1' 	http://www.nicolatest1.co.uk/ and 'Test to be deleted again again' 	http://www.nicolawebsite.cymru but am unable to.

**Comment by GilHoggarth** [comment]
@nicolabingham What's the problem that's means you're unable to delete this sites?

(Personally I think this deletion of targets is complicated and maybe a clearer statement of the conditions when a target can and cannot be deleted is needed?)

**Comment by nicolabingham** [comment]
@GilHoggarth in this instance it's mainly for housekeeping. There may be situations when a user wants to delete a target created in error, although we could handle this with 'never crawl' and adding appropriate notes.

**Comment by GilHoggarth** [comment]
@nicolabingham Given that the duff URLs (www.nicelife etc.) are on /actdev, do you think the deletion solution works as required?
@kinmanli Given that the duff URLs (www.nicelife etc.) are on /actdev, do you think that Nicola can't delete her test sites above because effectively the tables have broken key data in them due to different code versions?

Basically, do we think this is a working solution ready to be tested on live?

**Comment by kinmanli** [comment]
@GilHoggarth it cannot be removed if it has a license (or higher license) and/or belongs to a collection

**Comment by GilHoggarth** [comment]
I've just added a new test site (http://gilhtest.wales), saved it, browsed it, then deleted it. However, afterwards I'm still able to see it via Browse Targets.
@kinmanli Are any values set automatically that would not allow a target to be deleted? (I.e., is a default licence set?) I didn't set anything other than the site title and URL but see that it logically matched the LD Criteria being `.wales`.
@nicolabingham Should any values be automatically set for new targets?

**Comment by kinmanli** [comment]
@GilHoggarth just checked in and tested it locally. Should delete now (honest)

**Comment by GilHoggarth** [comment]
Checked on /actdev and now seems to be working - removed  http://gilhtest.wales and http://www.nicolawebsite.madeup

**Comment by nicolabingham** [comment]
@GilHoggarth if a Target has a Granted licence then we should not be able to delete it.

**Comment by GilHoggarth** [comment]
@nicolabingham This detail (not being able to delete a granted licence) hasn't been mentioned before so I don't know if this is correctly implemented in the code or not. I assume this is difficult to test as we wouldn't want to test and discover we actually have deleted a granted licence.
I'll raise this as a question outside of this milestone.

**Comment by GilHoggarth** [comment]
Tested on live /act with http://giltest.wales - created and then deleted target without issue.
