### ISSUE TITLE
'Instances' Pane on Mobile

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#287]
When viewed on a mobile device, the new Instances pane doesn't shift/resize as it probably should:

![mobie](https://cloud.githubusercontent.com/assets/722120/6505640/0b082bc2-c33c-11e4-8f5d-5fffde6f3f8d.png)

**Comment by anjackson** [comment]
Should be fine now. Can await 1.1.0.

**Comment by kinmanli** [comment]
references #287

**Comment by kinmanli** [comment]
references #255

**Comment by GilHoggarth** [comment]
@anjackson Please test on /actdev.

**Comment by anjackson** [comment]
Works. Now appears at the bottom of the page.
![screen shot 2015-03-26 at 10 42 05](https://cloud.githubusercontent.com/assets/87843/6844643/c50084e8-d3a4-11e4-9843-fa5c0d844444.png)

**Comment by GilHoggarth** [comment]
Ready for test after release.

**Comment by GilHoggarth** [comment]
Tested and working on live /act.
