### ISSUE TITLE
License form does not show the URL

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#288]
When going to the license form, the URL is not shown properly. It appears to repeat the website title rather than show the URL.

![license form error](https://cloud.githubusercontent.com/assets/87843/6506374/9627baf0-c342-11e4-9f67-4f64f905bad3.png)

**Comment by kinmanli** [comment]
@GilHoggarth fixed and checked in.

**Comment by GilHoggarth** [comment]
Note, ready to test in next deployment.

**Comment by GilHoggarth** [comment]
GilHoggarth to test on /actdev.

**Comment by GilHoggarth** [comment]
Sorry @nicolabingham , I can't find the licence form that Andy mentions to test if this is resolved. Can you test please.

**Comment by nicolabingham** [comment]
@GilHoggarth the link is the one that the website publisher receives in an email to their online licence form. Tested - the form now shows the URL in the correct field.
