### ISSUE TITLE
Implement 'Update' API

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#289]
Similar to #266, would it be possible to implement an _update_ API?

That is, a HTTP PUT containing a Target's `id` field plus any field values which are to be updated.

e.g. to update the `Postal Address URL`, we'd PUT:

    {
        "id": "74",
        "field_uk_postal_address_url": "http://www.bbc.co.uk/"
    }

We also need this to update collections.

Other API changes:
* Collections key should not be quoted, i.e. "1" not "\"1\""
* Collections API could include the full collections properties
* Targets do not report collection_cats
* The /api/targets/bycollection/X hook appears to be fully recursive. We need another hook that only reports Targets that are in exactly that category, not one of its children.
* The instances are not available via the API (fix checked in)
* Collection.updatedAt appears to be in milliseconds rather than the usual seconds since epoch.

**Comment by anjackson** [comment]
By convention, [PUT is usually used for updates to known resources](http://tools.ietf.org/html/rfc2616#section-9.6), not POST. Good idea though, and we'll need this for Instances at some point too.

**Comment by PsypherPunk** [comment]
Edited :stuck_out_tongue_winking_eye:

**Comment by anjackson** [comment]
Response edited also 😇

**Comment by GilHoggarth** [comment]
Is that the Pillsbury Doughboy, now in heaven? http://www.homeschooloasis.com/storehs_obituary_of_pillsbury.htm

**Comment by kinmanli** [comment]
@PsypherPunk 

Done the Target update. For "put" updates are via an end point like the following:

https://webarchive.org.uk/act/api/targets/74

```
{
    "field_uk_postal_address_url": "http://www.bbc.co.uk/"
}
```

**Comment by PsypherPunk** [comment]
Excellent; will test.

**Comment by kinmanli** [comment]
collections update still to do though

**Comment by kinmanli** [comment]
@anjackson 

> Targets do not report collection_cats

Do you mean the first level of the collection tree?

> The /api/targets/bycollection/X hook appears to be fully recursive. We need another hook that only 

reports Targets that are in exactly that category, not one of its children.
Do you need the recursive one with the children, as I can just ignore the 'children' field?


![2015-03-19 13-38-52_mozilla firefox](https://cloud.githubusercontent.com/assets/1652105/6731524/528201b0-ce3d-11e4-8eb0-7325687dbf05.png)

**Comment by PsypherPunk** [comment]
I've made a PUT to http://www.webarchive.org.uk/actdev/targets/17356 with these data:

    {
        "uk_postal_address_url": true,
        "id": 17356,
        "field_uk_postal_address_url": "http://www.theguardian.com/"
    }

However, I get a 404, `Sorry, that page does not exist.`.

**Comment by kinmanli** [comment]
@GilHoggarth when was the last deploy to actdev?

**Comment by GilHoggarth** [comment]
Earlier this morning, ~1am?

**Comment by GilHoggarth** [comment]
Think this issue is still being worked on, but can @PsypherPunk test on /actdev when ready.

**Comment by kinmanli** [comment]
@PsypherPunk @GilHoggarth I get the following on /actdev. It seems to work locally and probably on /act. It maybe the same issue as this ticket regarding /actdev https://github.com/ukwa/w3act/issues/316
```
$ curl -v -H "Content-Type: application/json" -X PUT -d '{"field_collection_cats": ["2","4"]}' -u kinman.li@bl.uk:password http://webarchive.org.uk/actdev/api/targets/74
* Adding handle: conn: 0x6bd208
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x6bd208) send_pipe: 1, recv_pipe: 0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to webarchive.org.uk port 80 (#0)
*   Trying 194.66.232.82...
* Connected to webarchive.org.uk (194.66.232.82) port 80 (#0)
* Server auth using Basic with user 'kinman.li@bl.uk'
> PUT /actdev/api/targets/74 HTTP/1.1
> Authorization: Basic a2lubWFuLmxpQGJsLnVrOnBhc3N3b3Jk
> User-Agent: curl/7.30.0
> Host: webarchive.org.uk
> Accept: */*
> Content-Type: application/json
> Content-Length: 36
>
} [data not shown]
* upload completely sent off: 36 out of 36 bytes
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 25 Mar 2015 14:08:47 GMT
* Server Apache/2.2.3 (Red Hat) is not blacklisted
< Server: Apache/2.2.3 (Red Hat)
< Location: http://www.webarchive.org.uk/actdev/api/targets/74
< Content-Length: 341
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
<
{ [data not shown]
100   377  100   341  100    36  22733   2400 --:--:-- --:--:-- --:--:-- 22733<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.webarchive.org.uk/actdev/api/targets/74">here</a>.</p>
<hr>
<address>Apache/2.2.3 (Red Hat) Server at webarchive.org.uk Port 80</address>
</body></html>

* Closing connection 0

```

**Comment by kinmanli** [comment]
@GilHoggarth same issue as this comment onwards https://github.com/ukwa/w3act/issues/316#issuecomment-86903618

**Comment by PsypherPunk** [comment]
Made a successful PUT using the earlier data. It returns a `200` but the data [here](http://www.webarchive.org.uk/actdev/targets/17356) are not updated. The log, however, says `bean is unchanged`.

**Comment by PsypherPunk** [comment]
PUTting these data:

    {
      "uk_postal_address_url": "http://www.theguardian.com/",
      "id": 17516,
      "field_uk_postal_address": true
    }

Seeing this in the log:

    error: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class models.Target] from String value; no single-String constructor/factory method

**Comment by kinmanli** [comment]
@PsypherPunk Did you do it with this endpoint? http://www.webarchive.org.uk/actdev/targets/17516

**Comment by PsypherPunk** [comment]
Okay, tested in on [17516](http://www.webarchive.org.uk/actdev/api/targets/17516) and [17356](http://www.webarchive.org.uk/actdev/api/targets/17356) and now they both work.

**Comment by PsypherPunk** [comment]
Tested, fixing Trac#2472 in the process.
