### ISSUE TITLE
Collections page does not show Published status

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#290]
The Collection view does not show the 'Published' status, e.g. https://www.webarchive.org.uk/act/collections/22

It should.

**Comment by kinmanli** [comment]
@anjackson I see a 'yes'. Is this incorrect?

![screen shot 2015-03-06 at 13 49 57](https://cloud.githubusercontent.com/assets/1652105/6526257/c438da76-c407-11e4-89f5-78c0bb273e74.png)

**Comment by anjackson** [comment]
Ah, I guess this is a privilege thing? I can't see it.

**Comment by kinmanli** [comment]
@anjackson yes it only shows as sys admin and archivist

**Comment by anjackson** [comment]
Ah, this should only be editable by them, but visible to all.

**Comment by kinmanli** [comment]
@anjackson @GilHoggarth should be viewable to all on next redeploy

**Comment by GilHoggarth** [comment]
Note, ready to test in next deployment.

**Comment by GilHoggarth** [comment]
GilHoggarth to test on /actdev.

**Comment by GilHoggarth** [comment]
Tested on /actdev, Publish status seen by 'user'.

**Comment by GilHoggarth** [comment]
Tested on live /act; seen working as expected.
