### ISSUE TITLE
Additional link in warning message for duplicate seed URL for new target record

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#292]
When a user attempts to save a new target when one or more URLs is already associated with an existing target, it throws this message. It could also provide a link to that other target record.

![image](https://cloud.githubusercontent.com/assets/5520710/6527083/a5495764-c40f-11e4-8a54-020f0e7b476a.png)

cc @anjackson for information. Transplanted from #246

**Comment by kinmanli** [comment]
new message

![2015-03-09 13-00-55_w3act](https://cloud.githubusercontent.com/assets/1652105/6555486/77ce53f6-c65e-11e4-97de-9776d65f3048.png)

**Comment by anjackson** [comment]
@niladreeb could you check this is resolved, please?

**Comment by niladreeb** [comment]
Working as expected.

**Comment by niladreeb** [comment]
Tested on actstage and its working fine.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
Working fine.
