### ISSUE TITLE
'Archive This Now' Messages Aren't Persistent

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#293]
The `Archive This Now` button addressed in #120 doesn't appear to create persistent messages. Both the creation of the queue and each subsequent message need to be marked as `durable` in order to survive a restart.

We're creating the queue correction (the second parameter specifies `durable`):

    //queueDeclare(queue, durable, exclusive, autoDelete, arguments)
    channel.queueDeclare(queueName, true, false, false, null);

...we're not sending the messages marked as `durable`:

    //basicPublish(exchange, routingKey, props, body)
    channel.basicPublish(exchangeName, routingKey, null, message.getBytes());

Here `props` is `null`, whereas it should be a `BasicProperties` with a `deliveryMode` of `2`, I believe.

**Comment by kinmanli** [comment]
@PsypherPunk does this look good to you?
```
BasicProperties.Builder propsBuilder = new BasicProperties.Builder();
propsBuilder.deliveryMode(2);
channel.basicPublish(exchangeName, routingKey, propsBuilder.build(), message.getBytes());
```

**Comment by PsypherPunk** [comment]
Yes, that looks correct.

**Comment by kinmanli** [comment]
@GilHoggarth checked in. Ready for @PsypherPunk to test

**Comment by PsypherPunk** [comment]
Can confirm this is working in /actdev.

**Comment by PsypherPunk** [comment]
Confirmed working on live.
