### ISSUE TITLE
Expose 'Add Organisation' feature on the Organisations page

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#294]
The ability to add Organisations (http://www.webarchive.org.uk/actdev/organisations/new) should be added as a link/button on the Organisations page, for those users who can access it.

**Comment by kinmanli** [comment]
Only sys admin users can add new organisations. Steps are:

Search for an organisation. If one isn't found then the 'Add' button should appear.

**Comment by anjackson** [comment]
Should this already work? It didn't seem to work for me. Perhaps I'm not a sys-admin, but if not, I should not have been able to get to the form and use it, which I could.

**Comment by kinmanli** [comment]
Yes, I've changed it so non-sys admins cannot save organisations.

**Comment by kinmanli** [comment]
@anjackson now cannot access that page if you don't have the correct role (sys adm).

**Comment by anjackson** [comment]
@niladreeb could you check this is resolved, please?

**Comment by niladreeb** [comment]
This enhancement is implemented.

**Comment by niladreeb** [comment]
Tested in actstage and its working fine.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
The feature is running successfully. Now only admin users can add organisations in the Organisations page.
