### ISSUE TITLE
Bulk Import: field_uk_postal_address_url

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#295]
Further to #266, we'll also need to pass field_uk_postal_address_url through.

In fact, can we add a validation step? If field_uk_postal_address is set to true, field_uk_postal_address_url must be passed through too?

**Comment by kinmanli** [comment]
@PsypherPunk can we call it "uk_postal_address_url" as the other one (field_uk_postal_address_url) was used for importing from Andy's Act?

**Comment by PsypherPunk** [comment]
Yes, that's fine.

**Comment by kinmanli** [comment]
@GilHoggarth fixed.

Please use "field_uk_postal_address" and "uk_postal_address_url" @PsypherPunk

**Comment by GilHoggarth** [comment]
@PsypherPunk Please test on /actdev.

**Comment by PsypherPunk** [comment]
I'm POSTing the following to: http://www.webarchive.org.uk/actdev/api/targets

    {
      "field_subjects": [
        "189"
      ],
      "field_crawl_frequency": "annual",
      "field_urls": [
        "http://www.nottheguardian.com/commentisfree/2015/feb/10/tories-britain-democracy-auction-party-funds-donors"
      ],
      "field_crawl_end_date": "1425877200",
      "title": "Guardian, The: The Tories are putting Britain's democracy up for auction",
      "uk_postal_address_url": "http://www.theguardian.com/",
      "field_collection_cats": [
        "188"
      ],
      "field_nominating_org": "4",
      "field_crawl_start_date": "1425790800",
      "field_uk_postal_address": true
    }

...but it's returning a `404`, _Sorry, that page does not exist_.

**Comment by kinmanli** [comment]
@PsypherPunk I think it's the ' apostrophe in the title.

**Comment by GilHoggarth** [comment]
@PsypherPunk I wonder if this was troublesome because /actdev had picked up the wrong https protocol? That's been corrected overnight so please retest.

**Comment by PsypherPunk** [comment]
Still getting a `404` PUTting the above (get a `401` if POSTing).

**Comment by PsypherPunk** [comment]
Scratch that: no idea what's going on but I'm just getting `401` errors when trying to POST _any_ new data, with or without the new fields.

**Comment by PsypherPunk** [comment]
Finally remembered to use Basic authentication; verified that the new fields are passed through.

**Comment by GilHoggarth** [comment]
@PsypherPunk Please test on live /act.

**Comment by PsypherPunk** [comment]
Tested, fixing Trac#2496.
