### ISSUE TITLE
Duplicate values in Selection Type field

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#296]
In the  target record, the drop-down picker for this field has the Selection option in twice, the first of which doesn't work.

Assigning to @anjackson for milestone etc

**Comment by kinmanli** [comment]
@peterwebster is that in edit Target?

**Comment by peterwebster** [comment]
@kinmanli it was while editing a record. Assigning to @nicolabingham to test or close as appropriate.

**Comment by nicolabingham** [comment]
This has been fixed now, the options are selection or nomination but the default is selection, which is correct.
