### ISSUE TITLE
Exception error when applying date filter in Reports

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#297]
When applying the date filter to the Open UKWA Licences at https://webarchive.org.uk/act/reports I get

Execution exception[[RuntimeException: java.lang.StackOverflowError]]

cc @anjackson for info: have added this to the next milestone

**Comment by kinmanli** [comment]
@GilHoggarth fixed https://github.com/ukwa/w3act/commit/eab89548adda3243a24cc2c403268fab1dad71df

**Comment by anjackson** [comment]
@niladreeb could you check this is resolved, please?

**Comment by niladreeb** [comment]
Working as expected.

**Comment by niladreeb** [comment]
Tested in actstage and working fine.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
Working fine.
