### ISSUE TITLE
Reports>Target Creation page: default behaviour of date filter

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#298]
At the minute, when the user first loads this page, the start date defaults to today.

https://webarchive.org.uk/act/reportscreation/targets/?s=createdAt&o=desc&curator=-1&organisation=-1&startDate=11-03-2015&tld=either

This is one of the least likely uses of the filter, and so I'd suggest that it defaults to <no date set>. As a result, the user will get the full list of all targets.

If @nicolabingham agrees, do please assign and prioritise.  cc @anjackson

**Comment by nicolabingham** [comment]
agree with @peterwebster's suggested change above

**Comment by kinmanli** [comment]
Fixed, please deploy @GilHoggarth 

Now defaults with no start date and a full list of targets @peterwebster @nicolabingham 

![2015-03-16 16-35-54_w3act](https://cloud.githubusercontent.com/assets/1652105/6671047/8b30450c-cbfa-11e4-81f1-0e6b103a08b2.png)

**Comment by GilHoggarth** [comment]
@nicolabingham Please test on /actdev.

**Comment by nicolabingham** [comment]
@GilHoggarth fixed, the default start date has been removed and the full list of targets is returned.

**Comment by GilHoggarth** [comment]
@nicolabingham Fraid I don't understand this ticket - can you test please.

**Comment by nicolabingham** [comment]
@GilHoggarth this is fixed, the start date for the reports is empty. The use case scenario is that when generating reports on targets created there is never a use case when the report should start from today's date.

**Comment by GilHoggarth** [comment]
Closing.
