### ISSUE TITLE
Open UKWA Licence requests from 2012?

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#299]
Can @anjackson think where the pre-production crawl permissions reported here could have come from ?

https://webarchive.org.uk/act/reports

**Comment by GilHoggarth** [comment]
@anjackson I'm not seeing this as a question that will be fixed in 1.0.2, but if it is, could more detail/understanding be added to this ticket.

**Comment by GilHoggarth** [comment]
Closing as out of date, I think we've moved past this issue.
