### ISSUE TITLE
Script checking for new instances in QA Wayback running correctly in /act ?

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#300]
@anjackson @GilHoggarth 

Could we check that this script is running overnight as intended ? I ask because there are later instances at:
https://www.webarchive.org.uk/act/wayback/*/http://www.actionaid.org.uk/

which are not reflected at:
https://webarchive.org.uk/act/instances/listbytarget?t=4137

**Comment by anjackson** [comment]
That script is currently disabled, as it turned out that W3ACT isn't supposed to know about ALL of the Instances. It makes more sense for the crawlers to tell W3ACT about selected Instances instead.

**Comment by PsypherPunk** [comment]
Being handled in #278, FYI.

**Comment by anjackson** [comment]
Closing this in that case.
