### ISSUE TITLE
Search term should not be required on QA Dashboard

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#302]
https://webarchive.org.uk/act/qa/list

It isn't possible just to filter the list here by collection/QA Status without also entering a search term.

Archivists may want just to see all the targets in a collection, or all targets with a particular QA Status, without a search term.

Does @nicolabingham agree?

**Comment by nicolabingham** [comment]
@peterwebster yes, agree, we would also want to filter on those terms.

**Comment by kinmanli** [comment]
Fixed. added an apply button for the filters too for convenience. @peterwebster @nicolabingham.

Needs redeploying @GilHoggarth 

![2015-03-16 16-53-50_w3act](https://cloud.githubusercontent.com/assets/1652105/6671533/c3e19164-cbfd-11e4-993e-0eaf78f52fe7.png)

**Comment by GilHoggarth** [comment]
@kinmanli Has this been tested on /actdev?

**Comment by GilHoggarth** [comment]
@nicolabingham Please test on /actdev.

**Comment by nicolabingham** [comment]
@GilHoggarth Tested on /actdev. The apply button works on the filters, you do not have to enter a search term to return results. Can be closed.
