### ISSUE TITLE
External links to open in new windows

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#303]
https://webarchive.org.uk/act/instances/listbytarget?t=2902

The archival and live links here should open in a new browser window/tab, I think. The mid-crawl one is OK.

Does @nicolabingham agree?

**Comment by nicolabingham** [comment]
@peterwebster yes, opening the links in a new browser window is preffered.

**Comment by nicolabingham** [comment]
sp *preferred*

**Comment by peterwebster** [comment]
Assigning for @anjackson for milestone

**Comment by kinmanli** [comment]
@peterwebster @nicolabingham this has now been fixed with:

```
rel="external"
``

Any other pages need doing?

**Comment by nicolabingham** [comment]
@kinmanli could we make the links to the Targets listed on these pages open in a new tab please?
https://webarchive.org.uk/act/reports - >  Target URL
https://webarchive.org.uk/act/reportscreation/targets/ - > Target URL
https://webarchive.org.uk/act/crawlpermissions/list - > Target URL
and the mementos link from here?
https://webarchive.org.uk/act/instances/list?f=bbc - > Mementos link

**Comment by kinmanli** [comment]
@nicolabingham @GilHoggarth fixed and checked in

**Comment by GilHoggarth** [comment]
@kinmanli Has this been tested on /actdev?

**Comment by kinmanli** [comment]
@GilHoggarth think we need to test all of these on actdev

**Comment by GilHoggarth** [comment]
GilHoggarth to test.

**Comment by GilHoggarth** [comment]
@nicolabingham The destination of the mid-crawl link, e.g., https://www.webarchive.org.uk/actdev/wayback/*/http://www.38degrees.org.uk/, doesn't work - it instead redirects to the UKWA website. What should this do?

Nicola's list of 4 links to open in a new tab work correctly.

**Comment by nicolabingham** [comment]
@GilHoggarth It looks like the mid-crawl and archival links are the wrong way round. 
Mid-crawl should link to: http://www.webarchive.org.uk/wayback/archive/*/http://www.conservatives.com/
Archival should link to: http://www.webarchive.org.uk/ukwa/target/101940/source/search 

Where the Target is not to be published (we don't have a license) in the case of http://www.38degrees.org.uk/, Archival should ideally go to an error message "website not in UKWA" or just http://www.webarchive.org.uk/ukwa/

**Comment by GilHoggarth** [comment]
Ah, @kinmanli The mid-crawl link is going to https on /actdev again - the URL above works as expected when http is used.

**Comment by kinmanli** [comment]
@GilHoggarth I'm sure it pulls out the server_name from the .conf file?

**Comment by GilHoggarth** [comment]
@kinmanli Aha, yes, the application.conf again says https!

**Comment by GilHoggarth** [comment]
Have amended on github but will wait until after redeploy tonight to test again.

**Comment by GilHoggarth** [comment]
Tested http://www.webarchive.org.uk/actdev/instances/listbytarget?t=2902 
* mid-crawl "stays in window" and goes to the Legal Deposit QA Openwayback search results page
* archival opens in a new tab and goes to the UKWA wayback search results page
* live opens in a new tab and goes to the live site

@nicolabingham I think these are correct and as required - can you just confirm please (no need to test, just read this comment and consider if I've got it correct!)

**Comment by nicolabingham** [comment]
@GilHoggarth correct except can mid-crawl open in a new window please?

**Comment by GilHoggarth** [comment]
@kinmanli Think this is an easy one, can you add your `rel="external"` for the mid-crawl Instance List link please.

**Comment by kinmanli** [comment]
@GilHoggarth done https://github.com/ukwa/w3act/commit/6956268d190ca84a5193074f489c5c3b6cc669e6

**Comment by GilHoggarth** [comment]
GilHoggarth to test on March 26 after overnight /actdev redeploy.

**Comment by GilHoggarth** [comment]
Tested on live /act - mid-crawl, archive, and live all open in a new window.
