### ISSUE TITLE
Non .uk domain checking error

### ISSUE THREAD

**Issue by hhockx** [ukwa/w3act#304]
http://www.ukbiologycompetitions.org/, using a non .uk domain is showing as UK top-level domain in ACT, which is incorrect.
![nonukdomain](https://cloud.githubusercontent.com/assets/6706274/6620255/a630aae4-c8c7-11e4-9f6f-58fdd1efd689.PNG)

**Comment by kinmanli** [comment]
to change url.contains('.uk') to url.endsWith('.uk')

**Comment by PsypherPunk** [comment]
Not sure you can use `endsWith()` either as a seed might not necessarily be a slash-page. i.e. `http://www.blah.org/something.uk` would match incorrectly.

**Comment by kinmanli** [comment]
@PsypherPunk but you can do it on the domain level???

**Comment by PsypherPunk** [comment]
Yeah, if you can parse out just the host then yes, that'll work (I presume it takes into account all in-scope TLDs; `.london`, `.wales`, etc.?).

**Comment by kinmanli** [comment]
@PsypherPunk there is a domain field in FieldUrl's table.

**Comment by kinmanli** [comment]
@GilHoggarth fixed and ready for redeploy

**Comment by anjackson** [comment]
Well, this is pretty serious. Adding a bug-fix 1.0.2 milestone for this and any other minor fixes.

**Comment by kinmanli** [comment]
Fixed, also @GilHoggarth to run:
```
 ./updateFieldUrlDomains.sh
```
The same way as he ran the other .sh files for Act. This is because some old data URL's didn't have the domain name extracted and saved to the domain column. This should do it as 'top level domain' uses it now. https://github.com/ukwa/w3act/blob/master/app/uk/bl/export/UpdateFieldUrlDomains.java

**Comment by kinmanli** [comment]
[topleveldomain_check.feature](https://github.com/ukwa/w3act/blob/master/test/bdd/topleveldomain_check.feature)

**Comment by GilHoggarth** [comment]
@kinmanli Has this been tested on /actdev?

**Comment by kinmanli** [comment]
@GilHoggarth not tested on actdev

**Comment by GilHoggarth** [comment]
@kinmanli Please test on /actdev.

**Comment by kinmanli** [comment]
@GilHoggarth fixed and working on actdev

![2015-03-27 13-04-18_w3act](https://cloud.githubusercontent.com/assets/1652105/6868238/ce6bcd70-d481-11e4-91a3-5573aced1fd2.png)

**Comment by GilHoggarth** [comment]
Solve update... script

**Comment by GilHoggarth** [comment]
Created https://gilsfictiousukurl.org on live - it didn't identify it as a UK top-level domain. Target deleted, ticket closed.
