### ISSUE TITLE
Export Button on Target Results page not working

### ISSUE THREAD

**Issue by kinmanli** [ukwa/w3act#305]
Export Button on Target Results page not working

**Comment by kinmanli** [comment]
Hi @romankarl checked in the code for the export. But will not work with https://github.com/ukwa/w3act/tree/ddhapt as it has a different model. Also, after clicking on export you need to send it back in the response and there are areas in the app where exporting needs to do that.

**Comment by kinmanli** [comment]
[exporting_targets.feature](https://github.com/ukwa/w3act/blob/master/test/bdd/exporting_targets.feature)

**Comment by kinmanli** [comment]
Fixed @GilHoggarth

**Comment by kinmanli** [comment]
@nicolabingham

**Comment by nicolabingham** [comment]
@kinmanli thanks, this is working in actdev

**Comment by GilHoggarth** [comment]
Labelled '1 - Ready' as tested and working on /actdev.

**Comment by GilHoggarth** [comment]
@nicolabingham Another - as you tested on /actdev can you test on live /act please.

**Comment by nicolabingham** [comment]
@GilHoggarth tested on live act, working as expected.

**Comment by GilHoggarth** [comment]
Closing.
