### ISSUE TITLE
Unable to edit schedule in target

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#306]
I am unable to edit the schedule in this Target https://www.webarchive.org.uk/act/targets/9449. When selecting a different schedule and then saving I get the error message "It is not possible to attach an Open UKWA Licence directly to a target in this way. Please initiate the licensing process using the green button below"

**Comment by kinmanli** [comment]
@nicolabingham do you want to try and replicate it on actdev? It should work on there. I don't think act has the latest code.

**Comment by nicolabingham** [comment]
@kinmanli it works on actdev, thanks. Should I leave this ticket open till the next deployment of code onto /act/ ?

**Comment by kinmanli** [comment]
@nicolabingham yes, then we can confirm it with @GilHoggarth

**Comment by GilHoggarth** [comment]
@nicolabingham Another test for live.

**Comment by nicolabingham** [comment]
@GilHoggarth tested on live act, works as expected.

**Comment by GilHoggarth** [comment]
Thus ticket closed.
