### ISSUE TITLE
Target URL not showing in license form

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#307]
In the web form (within production W3ACT) that a site owner needs to populate to grant a licence, the URL field shows the target title, not the URL.

@kinmanli I'll see whether I can't replicate it again, in order to get a screenshot.

**Comment by kinmanli** [comment]
Is it this one @peterwebster? https://github.com/ukwa/w3act/issues/288

**Comment by peterwebster** [comment]
@kinmanli yes ! Perhaps I should just stop....
