### ISSUE TITLE
Missing link to privacy statement in licence form

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#308]
![image](https://cloud.githubusercontent.com/assets/5520710/6640085/fc3adcf0-c98c-11e4-9013-7c5f39438800.png)

**Comment by peterwebster** [comment]
I'm not sure where the text for this is @nicolabingham ?

**Comment by nicolabingham** [comment]
@peterwebster I think it's this one: http://www.webarchive.org.uk/ukwa/info/privacy

**Comment by kinmanli** [comment]
![2015-03-16 10-05-52_w3act](https://cloud.githubusercontent.com/assets/1652105/6664190/a55cfe78-cbc5-11e4-9067-c80dcc027bcd.png)
![2015-03-16 10-06-05_uk web archive](https://cloud.githubusercontent.com/assets/1652105/6664189/a55cae6e-cbc5-11e4-9fda-dfee18b452dd.png)

**Comment by GilHoggarth** [comment]
@nicolabingham I think this needs to be tested in the process of adding a new licence - can you test please.

**Comment by nicolabingham** [comment]
@GilHoggarth tested in a new licence form. the link is now correct.

**Comment by GilHoggarth** [comment]
Closing.
