### ISSUE TITLE
Create new Flag for video content

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#310]
Curators commonly request that video content on a website is archived. This is often picked up through a manual process outside the normal workflow/crawling. Could Sys Admin add a new Flag in Taxonomies -> named 'Video Content to add'. 
The selectors would then have option to use this on the Target page in the metadata tab under 'Flag(s): To flag record for attention by a web archivist: http://www.webarchive.org.uk/actdev/targets/1/edit#metadata'. 
I will cascade this information to the curators and ask them to use the 'Flag notes' field to enter the video details.

**Comment by niladreeb** [comment]
New flag is successfully added to the db.

**Comment by niladreeb** [comment]
Flag added in my local db and in live W3ACT through UI.

**Comment by niladreeb** [comment]
Added the flag in actstage also.

**Comment by niladreeb** [comment]
New flag addition in actstage is tested successfully.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Dorota, , please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it works ok.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.
