### ISSUE TITLE
Add bookmarklet to the lookup page footer

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#311]
I'd like us to add a hyperlink that can be used as a bookmarklet, like the one [published here by Delicious](https://delicious.com/tools), but pointing to W3ACT, like this:
```
javascript:void(location.href='https://www.webarchive.org.uk/act/targets/lookup?f='+escape(location.href)+'&referrer='+escape(document.referrer))
```

**Comment by kinmanli** [comment]
@anjackson so you want it to add a "lookup/search" to your bookmarks?

**Comment by GilHoggarth** [comment]
@kinmanli to test on /actdev.

**Comment by kinmanli** [comment]
@GilHoggarth this one is not ready yet. Need @anjackson answer to the above.

**Comment by anjackson** [comment]
For an example, see the  'installing the bookmarklet' section on this page: http://www.webarchive.org.uk/mementos/search

**Comment by niladreeb** [comment]
@anjackson Added the bookmarklet to the footer of the lookup page. Let me know if further enhancements are required.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by niladreeb** [comment]
Link was hard coded. Resolved and pushed to git by andy.
