### ISSUE TITLE
Set English as default language selection in Target tab

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#312]
Could we make the language field ('Language (The predominant language in which the page is written):)'  in the Metadata tab of the Target record default to English? The selector can then expand the drop down menu to select a different language if it is not English.

**Comment by niladreeb** [comment]
Now English is the default language in the Metadata tab of the target record.

**Comment by niladreeb** [comment]
Tested in actstage and running fine

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Tested it and it works ok in the edit mode, but in the view mode the field is 'None'. It can only be changed after saving.

**Comment by nicolabingham** [comment]
@dorotawalker just discussing this with @niladreeb . This is another issue in which the enhancement will not affect existing data. New entries in W3ACT will correctly be marked however we need to look at what we want to happen to existing records. It may be that we can do a global change (i.e. change None to English) but the consequences should be assessed. We will discuss this offline along with the other data issues

**Comment by dorotawalker** [comment]
@nicolabingham thanks for the explanation. In this case the ticked is working fine.
