### ISSUE TITLE
Bilingual website language settings

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#313]
@peterwebster @kinmanli There is a requirement, particularly from NLW, to assign more than one language to a website. Could we have a second Language field in the Target record for dual language sites?

**Comment by niladreeb** [comment]
Implemented a second language in target metadata tab. Also changed the data model accordingly.

**Comment by niladreeb** [comment]
Tested successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket.

**Comment by nicolabingham** [comment]
tested on act stage and working fine

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Option to enter second language is now possible, but there's only a choice of English and Deutsche. Agreed with @nicolabingham that this is acceptable at this point - Nicola will create a new ticket to extend the list of languages choices for a future milestone.

**Comment by GilHoggarth** [comment]
Option seen on /act - no data saved so recording of setting not clarified.
