### ISSUE TITLE
Increase window in browse Collections view

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#314]
Could the window for displaying the Collections on this page https://webarchive.org.uk/act/collections/list?s=title be made any bigger so that the Collections are displayed more effectively? There is a lot of blank space that could be made use of on this page.

**Comment by niladreeb** [comment]
The windows in Collection and Subject view are auto adjustable now.

**Comment by niladreeb** [comment]
Tested in actastage and it works properly.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.

**Comment by nicolabingham** [comment]
tested and working in actstage
