### ISSUE TITLE
Remove justification field

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#315]
@kinmanli @peterwebster can we remove the Justification field from the Metadata tab in the Target records? The original purpose of this field in pre-LD days was to justify archiving a site in case we were challenged about the legality of web archiving. Now, the Selector Notes and Archivist Notes fields give more than enough space for notes.

**Comment by niladreeb** [comment]
Justification field removed.

**Comment by niladreeb** [comment]
Tested in actstage and is working fine.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, .test.

**Comment by GilHoggarth** [comment]
Justification field no longer displayed on target metadata tab on /actstage.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.

**Comment by nicolabingham** [comment]
Tested and worked on actstage
