### ISSUE TITLE
Duplicate URL Detection & HTTP(S)

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#316]
When testing for the existence of a URL (including just in the search box) w3act should ignore the protocol—i.e. it should match both `http://bl.uk/` and `https://bl.uk`.

**Comment by kinmanli** [comment]
@PsypherPunk you talking about this search box?

![2015-03-18 16-02-34_w3act](https://cloud.githubusercontent.com/assets/1652105/6713105/36a4ce6a-cd88-11e4-90c4-fe5d7f054816.png)

**Comment by anjackson** [comment]
Note that this also applies to whatever checks are in place when someone tries to create a Target with the same URI as an existing Target. Same URL but different http/https should count as a match there too.

**Comment by PsypherPunk** [comment]
That's the one I meant (although if there's any other place you can search for a URL the same should apply).

**Comment by kinmanli** [comment]
Added Feature here:
https://github.com/ukwa/w3act/blob/master/test/bdd/features/url_check.feature

and test data here: https://github.com/ukwa/w3act/blob/master/conf/targets.yml

**Comment by kinmanli** [comment]
Needs deploying @GilHoggarth

**Comment by GilHoggarth** [comment]
@kinmanli Has this been tested on /actdev?

**Comment by kinmanli** [comment]
@GilHoggarth I've only tested it locally

**Comment by GilHoggarth** [comment]
Assigned to @PsypherPunk for testing on /actdev.

**Comment by PsypherPunk** [comment]
Testing this on /actdev; appears to be a regression. If I enter a existing URL in the search box, no results are shown in the drop-down:

![error](https://cloud.githubusercontent.com/assets/722120/6798994/340e071c-d20a-11e4-92da-482df2fc8e81.png)

However, in the current /act deployment it finds results:

![okay](https://cloud.githubusercontent.com/assets/722120/6799033/71c67760-d20a-11e4-997c-21c9b6151fe2.png)

**Comment by kinmanli** [comment]
@PsypherPunk that target available on actdev? Have you tried the creating a new target and entering that url?

**Comment by PsypherPunk** [comment]
Yes, the URL's the first in the list:

![error](https://cloud.githubusercontent.com/assets/722120/6800203/3d58bd80-d214-11e4-92ad-7b1eb8046fb8.png)

If I search for it, it finds the result and correctly flags that it already exists with `http` or `https` but it's just that initial drop-down that's seemingly failing to match full URLs. It does, however, seem to find partial matches, although any `/` present seems to throw it:

![error](https://cloud.githubusercontent.com/assets/722120/6800285/d94e257c-d214-11e4-8e5e-f968585e3c04.png)

**Comment by kinmanli** [comment]
@PsypherPunk I'm sure that's how an autocomplete is meant to work according to your pictures

**Comment by PsypherPunk** [comment]
See earlier picture re. _"current /act deployment"_—the current, live version of w3act will match full URLs, the version deployed to actdev does not.

**Comment by kinmanli** [comment]
@GilHoggarth When was the last deployment on /act?

**Comment by GilHoggarth** [comment]
@kinmanli Last night (cronjob every night at midnight.)

**Comment by kinmanli** [comment]
@GilHoggarth @PsypherPunk so there shouldn't be a difference between actdev and act?

**Comment by GilHoggarth** [comment]
@kinmanli @PsypherPunk  Ah, my mistake - nightly cronjob is for /actdev (didn't spot that you were asking about /act.) /act, our production service, was last started March 5.

**Comment by kinmanli** [comment]
@PsypherPunk are you saying that /act is working as expected and /actdev isn't for the lookups?

Creating new and edit Targets - url check on save should be working correctly though.

**Comment by kinmanli** [comment]
trimmed off http:// and https:// when it's entered.

![2015-03-25 10-32-42_w3act](https://cloud.githubusercontent.com/assets/1652105/6822791/48060d02-d2da-11e4-965c-758a59d4ec32.png)

**Comment by kinmanli** [comment]
@GilHoggarth may need redeploying on actdev?

/actdev is erroring on lookup

![2015-03-25 10-41-04_w3act](https://cloud.githubusercontent.com/assets/1652105/6822946/7f5692da-d2db-11e4-967c-f3b4f87983d5.png)

/act is working okay.
![2015-03-25 10-42-03_w3act](https://cloud.githubusercontent.com/assets/1652105/6822957/96df6a76-d2db-11e4-8d5e-adeff5030e45.png)

locally

![2015-03-25 10-43-44_w3act](https://cloud.githubusercontent.com/assets/1652105/6822994/e97b25cc-d2db-11e4-94ce-f8ccb5f7507a.png)

**Comment by kinmanli** [comment]
@GilHoggarth do you know why this request...

"NetworkError: 404 Not Found - http://www.webarchive.org.uk/actdev/targets/filterbyjson/http%3A%2F"

...is not working on actdev but okay on the others?

**Comment by GilHoggarth** [comment]
Hmm. @kinmanli Can you give me a complete URL that 404s and the equivalent that works please.

**Comment by kinmanli** [comment]
if you type in '/' it 404s on actdev

**Comment by GilHoggarth** [comment]
@kinmanli I'm not getting what you mean, complete URLs please

**Comment by kinmanli** [comment]
@GilHoggarth any url that has a '/' in it gives a 404 on /actdev such as http://bbc.co.uk

**Comment by GilHoggarth** [comment]
http://www.webarchive.org.uk/actdev/wayback/20131218131116/http://1000schools1000girlscclef.blogspot.co.uk/ works for me...

**Comment by kinmanli** [comment]
@GilHoggarth I think this is a different thing now as it only happens on /actdev

**Comment by kinmanli** [comment]
@GilHoggarth there seems to be an issue with /actdev. Seems to be fine locally and on /act

![2015-03-27 11-10-20_w3act](https://cloud.githubusercontent.com/assets/1652105/6866604/f4e444c4-d471-11e4-911d-caf8e7a93013.png)

**Comment by anjackson** [comment]
Has /actdev/ got the same Apache proxy config? e.g. that directive that stops it Apache over-sanitising the URLs.

**Comment by GilHoggarth** [comment]
/actdev is configured on firefox over http, /act is done over https. /act also has several cache control headers set. Beyond this though, both /actdev and /act are configured the same.

**Comment by GilHoggarth** [comment]
Checked on just live released v1.0.2 with "https://" in the target input box; offered both http and https gov.uk sites.
Considered working correctly.
