### ISSUE TITLE
Report on Licences by Date Granted 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#319]
In Reports http://www.webarchive.org.uk/actdev/reports -> Open UKWA Licences -> Granted could we report on Date Granted? At the moment the report gives the Date Requested.  
Assigning to @GilHoggarth in the first instance.

**Comment by GilHoggarth** [comment]
@kinmanli Note no milestone defined as yet.

**Comment by kinmanli** [comment]
this is currently reporting on target createdAt date. Will need to add another column to the link entity license_target for the date.

**Comment by anjackson** [comment]
Whut? The system is not recording the date the license was granted?!

**Comment by GilHoggarth** [comment]
For clarity, Andy asks if this situation is correct - does the w3act service record anywhere the date a licence is granted, or not?

**Comment by kinmanli** [comment]
@GilHoggarth No it doesn't. The view was using the Target's created date. It will probably need a date/timestamp field added to the license_target table.

**Comment by GilHoggarth** [comment]
Assigned to Andy for further action/change of milestone?

**Comment by anjackson** [comment]
Also, the license form supplies a 'Date' field, the purpose of which should be clarified. This is presumably the 'signing' date.

**Comment by anjackson** [comment]
Date is in the crawlPermission object, so can be exposed.

**Comment by niladreeb** [comment]
Now targets can be listed as per their licence requested and granted dates. For this two new columns have been added in table crawl_permission.

**Comment by niladreeb** [comment]
Testted successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket if you can - reassign to Nils if not.

**Comment by nicolabingham** [comment]
@GilHoggarth @niladreeb I just need to check what to expect from this report, will the date granted column be populated only for targets with permissions granted once we deploy this to production, i.e. for future permissions? or will the date granted be shown for existing targets in W3ACT? There are some targets with permission in this list on act stage but nothing is shown in the date granted column.

**Comment by GilHoggarth** [comment]
@nicolabingham @niladreeb Well, as you submitted this request originally you should expect what you asked for :) However, currently I don't think that's what you're getting. 
Viewing https://www.webarchive.org.uk/actstage/reports#granted I can see that there's a new column called "Date granted" but that's the only change I'm aware of. In this Granted report and in the other two, there are no actual dates shown, not even the original 'date requested' value. On the live service, these values exist for the Requested and Granted reports (there's no titles in the Refused report so logically no dates).
Nils - can you clarify please, there should be date values displayed shouldn't there? (It is a copy of the live database after all.)

**Comment by niladreeb** [comment]
@nicolabingham @GilHoggarth The requested date and granted date are new facilities which were not there before. Initially there was created date and updated date. Now when a permission will be sent to author of a site and the status will be 'Pending', then the requested date gets filled with the current time. Similarly when the author grants the permission and the status changes to 'Granted' then the granted date gets filled. This option will work for new records. For the existing records there is no data as we don't know when the permission was requested for and when it was granted.
Please let me know if it is possible to get those data.
So from this ticket we expect requested date and granted date for permissions to be shown in the list and also filtering against them.

**Comment by GilHoggarth** [comment]
@nicolabingham I consequently suggest that you create a new target and go through the permission granting process, checking that these report values get set as expected along the way.
@niladreeb I assume there's no way of gaining the old dates given what was shown before wasn't correct data.

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Tested for a new record and it works fine.
