### ISSUE TITLE
Record last logged in time of users

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#320]
The ability to know when users have logged in was very useful in the original Drupal version of /act. Could the new w3act version record the last logged in date/time, in perhaps the creator database table?

This needn't be any more complicated than this - it doesn't have to be visible via the UI or reportable via an API etc.

**Comment by niladreeb** [comment]
Now last login time of users is recorded in table creator.

**Comment by niladreeb** [comment]
Works fine in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Values seen in /actstage postgres db - could be useful to see last login times in production.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Working on /actstage.

**Comment by GilHoggarth** [comment]
Working on /act.
