### ISSUE TITLE
sorting curators by role shows an SQLException

### ISSUE THREAD

**Issue by romankarl** [ukwa/w3act#322]
If you try to sort curators by role you get an SQLException.

http://www.webarchive.org.uk/actdev/curators/list?s=roles

So either the sorting should be fixed or the sorting link should be removed.

**Comment by GilHoggarth** [comment]
Assigning to Andy for inclusion in appropriate milestone.

**Comment by anjackson** [comment]
Cannot reproduce this. Has it been fixed, @romankarl?

**Comment by romankarl** [comment]
Yes, it has beed fixed the same day I reported it (8ce781cee36c74baa3047f620b6b0dd08b38efe2).
