### ISSUE TITLE
Expected behaviour when a 'user' is editing a target

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#324]
When I, a mere 'user', edits a Target's 'Crawl policy and schedule', I see this:

![editing-crawl-freq](https://cloud.githubusercontent.com/assets/87843/6916138/956e55b6-d791-11e4-9634-3bb96e137b5f.png)

Just wanted to check that that was the expected behaviour. Also, given that I can't select anything other than 'Domain Crawl Only', I'm not sure this should be shown as a drop-down list? Or indeed at all, given the other non-editable fields are simply hidden?

**Comment by kinmanli** [comment]
@anjackson if the user is NOT sys admin, archivist or an expert user it will show this view. There was a ticket about this which @peterwebster raised.
