### ISSUE TITLE
Target's 'created_at' Field in Exports

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#325]
A Targets `updatedAt` field is currently exposed in the frequency-based exports:

    {
        id: 74,
        url: "act-106",
        updatedAt: 1423490850064,
        title: "BBC News: Homepage",
        language: null,
        revision: "initial revision",
        ...

Can we also expose the `createdAt` field in the same way?

**Comment by kinmanli** [comment]
@PsypherPunk @GilHoggarth createdAt field now exposed

![2015-03-31 14-46-58_mozilla firefox](https://cloud.githubusercontent.com/assets/1652105/6920234/34155a98-d7b5-11e4-82d7-1f2193f7893c.png)

**Comment by GilHoggarth** [comment]
Assigned to Andy for milestone.

**Comment by GilHoggarth** [comment]
Assigned to Reporter for testing on actdev. When testing successful, please add the label "1 - Ready" to this ticket.

**Comment by PsypherPunk** [comment]
Verified on /actdev.

**Comment by PsypherPunk** [comment]
Confirmed working in live.
