### ISSUE TITLE
'End date' Not Editable

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#326]
As seen [here](https://www.webarchive.org.uk/act/targets/84), although an _End date_ is present in the Target, it doesn't show when editing and thus can't be changed/removed.

**Comment by PsypherPunk** [comment]
It looks like the field _is_ editable but the stored value isn't displayed in the _Edit_ view.

However, there's seemingly no way to clear the current value.

**Comment by romankarl** [comment]
It is fixed in ddhapt-merge. You may want to cherry-pick it in master.

**Comment by romankarl** [comment]
It was even more complex but now removing the end date is also possible.

**Comment by GilHoggarth** [comment]
Checked in live /act - End date is now an editable box (via a calendar), though i didn't actually use it to test it.
Considered fixed.
