### ISSUE TITLE
Robots.txt checkbox missing from UI

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#328]
In the Crawl Policy and schedule tab in a Target record there should be a checkbox against "Ignore Robots txt". The options, we *think* should be "true or "false". 
Assigning to @GilHoggarth to assign

**Comment by GilHoggarth** [comment]
Assigning to Andy for milestone inclusion.

**Comment by GilHoggarth** [comment]
Assigned to Reporter for testing on actdev. When testing successful, please add the label "1 - Ready" to this ticket.

**Comment by nicolabingham** [comment]
@GilHoggarth The check box is available in an existing Target record but is not available in a new Target record. In the new Target record the robots.txt field still appears as a text input box, it should be available as a check box here also.

**Comment by nicolabingham** [comment]
@GilHoggarth I just created another Target record. On completing the first Overview tab of the Target record and then hitting save, the robots.txt check box is available in the Crawl Policy Tab. It is a bit annoying to have to save the record then open it up again to bring up the check box. Is it possible to make the check box available without saving the record?

**Comment by GilHoggarth** [comment]
Assigned back to 'developer' for further work.

**Comment by anjackson** [comment]
Updated. I didn't realise the 'edit' and 'new' code for Targets was separate. Massive duplication of fiddly template logic. Logging as #346 for future attention.

@GilHoggarth - please redeploy latest changes to /actdev/ for testing.

**Comment by anjackson** [comment]
Looks good to me. Over to Nicola.

**Comment by nicolabingham** [comment]
This works in a new Target now.

**Comment by nicolabingham** [comment]
Tested on live for both new and existing targets. This is fixed now.
