### ISSUE TITLE
Nominating Organisation Missing in Export

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#329]
Although two fields, `field_nominating_organisation` and `field_nominating_org` are present in the export their values are always `null`.

We need this information to correctly generate statistics.

**Comment by GilHoggarth** [comment]
Assigned to Reporter for testing on actdev. When testing successful, please add the label "1 - Ready" to this ticket.

**Comment by PsypherPunk** [comment]
Information showing under the `nominating_organisation` field.

**Comment by PsypherPunk** [comment]
Confirmed working in live.
