### ISSUE TITLE
Implement report on crawled instances on 'Look up a URL' screen 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#331]
In Andy's ACT the system reported on crawled instances in addition to whether a Target record existed or not from the 'Look up URL' screen. Could this be implemented in W3ACT please?

![act_small](https://cloud.githubusercontent.com/assets/11210500/7176049/c5c3cf1a-e412-11e4-9a68-13b224c1e918.png).
This information is only currently available by searching Wayback separately.

**Comment by anjackson** [comment]
So, the logic here is that the Controller should go and talked to a web service to find our what's been crawled. For the Open UK Web Archive, it looks like this:

http://www.webarchive.org.uk/wayback/archive/xmlquery.jsp?url=http://www.bl.uk/

which tells how often a given page has been archived, or 

http://www.webarchive.org.uk/wayback/archive/xmlquery.jsp?type=prefixquery&url=http://www.bl.uk/

which lists the URLs that have been archived under that URL prefix.

So, the idea of this is to take the URL that has been passed to W3ACT and then query the Wayback service for how many copies we have, and how many other URLs on the same host. These numbers can then be reported on the search screen.

**Comment by anjackson** [comment]
Note that the Wayback location is in the dev config, but is now correct! https://github.com/ukwa/w3act/blob/master/conf/dev.conf#L48 should read:

    application.wayback.query.url="http://www.webarchive.org.uk/wayback/archive/xmlquery.jsp?url="

**Comment by PsypherPunk** [comment]
Similarly, can the "Crawled URL(s)" (3rd column in the screenshot above) be implemented? It currently shows as zero for everything.

Also, is the parenthetical 's' really necessary?

**Comment by anjackson** [comment]
It depends. Yes, if we have X pendant(s) around.

**Comment by niladreeb** [comment]
The Target Look Up tab is enhanced. Now there are two tabs "Crawled URL(s)" and "Crawl Number" which gives the value of total no of URLs crawled and the exact number that specific URL is crawled respectively. On click of the numbers the respective www.webarchive.org site is opened.

Implemented this for the open UK web archive.

**Comment by anjackson** [comment]
Looks pretty good. I suggest you change the 'Crawl Number' to 'Crawled Instances', and modify the method names from show and show1 to match, e.g. getTotalCrawledUrls and getTotalCrawledInstances.

**Comment by niladreeb** [comment]
Its done

**Comment by anjackson** [comment]
Looks good. There is one more piece of functionality that was implemented on the old system that I think we should include now. Underneath the search bar, but above the result table, it would be good to show the Wayback results for the query URL.  The idea is that, even if we don't have that precise URL in a Target already, you still get to see what holdings we have in Wayback.

A simple horizontal layout that shows 'Crawled Instances: X - Crawled URL(s): Y' Would be enough.

Final thing: Note that the hyperlinks for 'Crawled URL(s)' should probably link to the corresponding Wayback query, e.g.

 http://www.webarchive.org.uk/wayback/archive/query?type=prefixquery&url=http://www.bl.uk

rather than the /*/URL form used to view instances.

**Comment by niladreeb** [comment]
The new piece of functionality is implemented. Now below the search bar, 'Crawled Instances: X and Crawled URL(s): Y' are shown for the searched URLs even if the URL is not in a Target.

**Comment by anjackson** [comment]
Minor tweaks - Crawled instances should point at the wayback/*/URL page not the prefix query.  The table columns have the opposite problem, so the Crawled URL(s) column should point to the prefix query.

Also, consider centring the new block, and not showing it at all if there is no URL query.

**Comment by niladreeb** [comment]
Tweaks implemented and code pushed in git

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by nicolabingham** [comment]
Tested on /actstage. This is now working as expected.
