### ISSUE TITLE
Cannot edit exisiting targets

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#332]
When trying to add an additional seed to an existing W3ACT record we get the error message:

“Seed URL already associated with a current Target https://www.webarchive.org.uk/act/targets/5101” 

The target is the record we want to edit meaning we are unable to save the record. 

Two Targets where this has occurred are:

https://www.webarchive.org.uk/act/targets/22041

https://www.webarchive.org.uk/act/targets/5101

The same error is found with both mine and Dorota’s log ins.

**Comment by GilHoggarth** [comment]
Assigned to Andy for milestone consideration.

**Comment by nicolabingham** [comment]
Cannot add Description to an existing Target in the Description field in the Metadata tab. I tried to add a description to this Target [22226] (https://www.webarchive.org.uk/act/targets/22226) but on saving I get the error message "Seed URL already associated with a current Target https://www.webarchive.org.uk/act/targets/22226"

**Comment by nicolabingham** [comment]
@anjackson Svenja Kunze, Bodleian Library reports that she can add records but not edit them after saving. An example is [Target 22104] (https://www.webarchive.org.uk/act/targets/22104). After saving the record she cannot edit the crawl frequency or NPLD criteria. 
The same is also true for this [Target 22269] (https://www.webarchive.org.uk/act/targets/22269) none of the fields can be edited after saving.

**Comment by dorotawalker** [comment]
It's the same for the https://www.webarchive.org.uk/act/targets/2902. Originally the crawl was set with an end date, but I would like to set a new crawl without an end date. After deleting the end date and saving, the system still shows the end date.

**Comment by GilHoggarth** [comment]
Assigned to Reporter for testing on actdev. When testing successful, please add the label "1 - Ready" to this ticket.

**Comment by nicolabingham** [comment]
I tried to add an additional seed (https://supporters.labour.org.uk/) to Target record, http://www.webarchive.org.uk/actdev/targets/5101. I still get the error message "Seed URL already associated with another Target http://www.webarchive.org.uk/actdev/targets/5101". The error is referencing the Target that I am trying to add the seed to.

**Comment by nicolabingham** [comment]
I cannot add a description to this target http://www.webarchive.org.uk/actdev/targets/22226. When adding a description (Description field, Metadata tab) and saving I get the error message "Seed URL already associated with another Target http://www.webarchive.org.uk/actdev/targets/22226"

**Comment by anjackson** [comment]
Running a re-deploy to test.

**Comment by anjackson** [comment]
okay, I think that's fixed now.

**Comment by nicolabingham** [comment]
Tested again. Am able to save the Targets tested above.

**Comment by nicolabingham** [comment]
Tested again. Is fixed now.
