### ISSUE TITLE
Licences do not roll through to sub domains

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#333]
When entering a URL which is a sub-section of a site for which we already have permission, the UKWA Licencing tab in the W3ACT record does not reflect the fact that we have a Granted licence. 

We have a licence for the site http://www.thebureauinvestigates.com/ Target [14804] (https://www.webarchive.org.uk/act/targets/14804) 

For the sub-section of the same site (Target record [22093] (https://www.webarchive.org.uk/act/targets/22093) “Bureau for Investigative Journalism: General Election 2015: Lib Dems lead... http://www.thebureauinvestigates.com/2015/04/09/general-election-2015-lib-dems-lead-list-of-donations-in-britains-top-20-marginal-seats-tories-third/”)  

there is a message "There is already a licence request..." but the licence tab does not have a green plus symbol and the licence request status does not say “Granted”. 

The same is true for the Canterbury Cathedral Targets. 
We have permission for http://www.canterbury-cathedral.org/ Target [5350] (https://www.webarchive.org.uk/act/targets/5350) but this is not rolled through to any Target records which are sub-sections of the same site. Targets [15802] (https://www.webarchive.org.uk/act/targets/15802), [18822] (https://www.webarchive.org.uk/act/targets/18822) - [19000] (https://www.webarchive.org.uk/act/targets/19000)  (licence status changed manually)

**Comment by anjackson** [comment]
I've updated the code to ensure that the green (+) turns up when there is an inherited license.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by nicolabingham** [comment]
@anjackson should we expect that this has fixed existing child Targets licence inheritance, or is it just that Targets added from now on will pick up licences correctly?

**Comment by anjackson** [comment]
So, any new Targets and any Targets not 'infected' by the earlier problems should be fine and should work as expected (although you might have to edit and re-save them to get them working as expected).

However, the 'bad' targets, like the Twitter ones, are more complicated, and will have to be cleaned up.

**Comment by anjackson** [comment]
Okay, so this now basically works, e.g.

https://www.webarchive.org.uk/actstage/targets/22093#licensing

inherits from 

https://www.webarchive.org.uk/actstage/targets/14804#licensing

However,  the Canterbury case is on of the Selective archive import cases, where there is a data quality issue - the thing has a license, but the status field is not set. These ones also have no permissions data in W3ACT.

That data-quality problem will be followed up in a separate ticket.

For this issue, I've ensured the system still 'counts' the license even if there is no Status.

**Comment by anjackson** [comment]
okay, tested and okay on stage.
