### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#334]
The link to the licence form we sent to a website publisher does not work (https://www.webarchive.org.uk/act/ukwa/licenseform/7dec446a-46c7-4930-98c9-825c9597f0c6). We are unable to send the permission request again. 
Although the permission status says Queued, the Crawl Permission has disappeared from the Queue.
![pcs](https://cloud.githubusercontent.com/assets/11210500/7298213/02ea3d94-e9c6-11e4-86ed-827635018580.png)
We are unable to send another Open Licence Request from the Target as the Permission request is marked as queued

**Comment by nicolabingham** [comment]
Changing this to high priority. We have had another two reports today of the licence form links not working. The first example is: https://www.webarchive.org.uk/act/crawlpermissions/1147(we've asked for a screen grab of the error message). I can't view the other crawl permission due to the bug about crawl permissions disappearing from the queue reported above.

**Comment by anjackson** [comment]
Could you add some links to all the targets for which licence forms have failed? Maybe they have something in common.

**Comment by nicolabingham** [comment]
@anjackson Thanks. I have asked Dorota to provide this information.

**Comment by dorotawalker** [comment]
I've got three examples:

https://www.webarchive.org.uk/act/targets/17903 has the licence link https://www.webarchive.org.uk/act/ukwa/licenseform/608134a3-9c47-41af-958a-f7c78ffa5598. I've got the screenshot as well:


![tmpccef](https://cloud.githubusercontent.com/assets/12541602/7744238/798a3646-ff99-11e4-9b14-b2d145cd0036.jpg)


https://www.webarchive.org.uk/act/targets/21326 has the licence link https://www.webarchive.org.uk/act/ukwa/licenseform/43ebe30f-4930-4b78-9049-79f7ac70e672;

https://www.webarchive.org.uk/act/targets/2972 has the licence link https://www.webarchive.org.uk/act/ukwa/licenseform/247fde91-62cf-484b-bc52-ff1273cc7439

**Comment by nicolabingham** [comment]
@dorotawalker Many thanks Dorota. Could you add any further examples to this ticket in the same way please.

**Comment by anjackson** [comment]
How odd.

* For Target 17903 there is a crawl permission entry but with a different token.
* For Target 21326 there is no log of any crawl permission at all!
* For Target 2972 (BBFC) the licence URL works fine (AFAICT).

I'll keep digging.

**Comment by dorotawalker** [comment]
That's the screenshot for the https://www.webarchive.org.uk/act/targets/21326 

![screenshot](https://cloud.githubusercontent.com/assets/12541602/7746941/5e19b534-ffae-11e4-8aae-3d22deb2f9af.jpg)

**Comment by nicolabingham** [comment]
@dorotawalker do we have any granted licences coming back successfully?

**Comment by dorotawalker** [comment]
There are some. In May we have received licences for:

https://www.webarchive.org.uk/act/targets/23200 (1st May);
https://www.webarchive.org.uk/act/targets/23328 (6th May);
https://www.webarchive.org.uk/act/targets/26248 (18th May);
https://www.webarchive.org.uk/act/targets/26296 (19th May);
https://www.webarchive.org.uk/act/targets/26299 (19th May).

**Comment by anjackson** [comment]
Okay, sorry for the continuing silly questions from me - where are you getting the license links from? These are emails returned from the website owners?

Also, did the UI throw any errors while you were creating and sending the requests?

**Comment by nicolabingham** [comment]
@anjackson no problem. @dorotawalker can confirm this - we are getting the links in emails forwarded to us from website owners. Not sure about the error when creating/sending requests but I don't think we get any.

**Comment by dorotawalker** [comment]
I haven't seen any errors when sending requests, but for some records the status doesn't change, so they are 'Queued' instead of 'Pending'.

**Comment by anjackson** [comment]
The status shown on the Crawl Permissions tab of the Target, right? For some reason, that comes from a separate part of the database than the actual status of the crawl permission request.

I've been working on improving the UI and the logging, and I think we might have to push out a minor bugfix release and wait for it to happen again so we can try to work out what's happening.

**Comment by anjackson** [comment]
I've changed the UI so that Archivist can reset the Target License Status in cases where it's gone awry completely. See 04668c8

**Comment by anjackson** [comment]
Okay, moving this back to following bugfix release, as we need an intermediate release to allow us to debug. See #344

**Comment by dorotawalker** [comment]
Today's permissions:

https://www.webarchive.org.uk/act/targets/15452 went through without any problems;

https://www.webarchive.org.uk/act/targets/19273 problems with the link https://www.webarchive.org.uk/act/ukwa/licenseform/4c10f3e9-ee00-42ad-92ad-165fae8af73f  -    Execution exception[[ActException: CrawlPermission Not Found found for token: 4c10f3e9-ee00-42ad-92ad-165fae8af73f]]

**Comment by anjackson** [comment]
Argh, right I think I've got it.

Please don't edit any Targets right now.

It seems that editing a Target after a Crawl Permission has been sent out causes the Crawl Permission to get lost - disconnected from the Target.  After this, it will then get deleted! This is very bad.

**Comment by nicolabingham** [comment]
@anjackson thanks. Should I send a message to all W3ACT users telling them not to edit Targets, or is it just permissions we have to stop?

**Comment by dorotawalker** [comment]
Ok, thanks Andy.

**Comment by anjackson** [comment]
Do not edit targets. Permissions can be sent, but editing targets will wipe them out.

**Comment by nicolabingham** [comment]
@anjackson Ok, does this mean we can't edit any aspect of Targets?

**Comment by anjackson** [comment]
Yes, if they have a crawl permission underway.

**Comment by nicolabingham** [comment]
@anjackson OK, I will communicate this to the W3ACT users. Just to clarify: creating Targets at the moment is ok, but editing (changing a Target after saving it) is to be stopped for the time being. How long should we keep off editing Targets for?

**Comment by anjackson** [comment]
It will be at least a few working days.

**Comment by anjackson** [comment]
Okay, going to split the lost-crawl-permissions off into a separate ticket for 1.0.3, and we'll leave this open on 1.0.4 in case the other class of problem (mysteriously changed licence URL rather than lost license URL) reappears.

**Comment by anjackson** [comment]
Note that this bug means that we are going to have to check for GRANTED licences that have lost their crawl permissions and either try to re-created them from backups, or go back to the website owners again, as we currently have no records that verify the licenses were given to us.

**Comment by anjackson** [comment]
To confirm, once 1.0.3 is released, we should go back to using W3ACT as normal, and keep an eye on things in case there is another bug.

**Comment by dorotawalker** [comment]
I've just sent a couple of permission requests and one came back with an error:

![error message](https://cloud.githubusercontent.com/assets/12541602/7838241/bf4f3bf6-0483-11e5-9399-671c64618bb3.jpg)

**Comment by dorotawalker** [comment]
That's for the record https://www.webarchive.org.uk/act/targets/2993.

**Comment by dorotawalker** [comment]
Also we to have the Green Party in the OUKWA, but the permission is not in ACT https://www.webarchive.org.uk/act/targets/3061
http://www.webarchive.org.uk/ukwa/target/108088/source/search

**Comment by anjackson** [comment]
Do we also have a separate issue here, where Targets owned by BL and imported from WCT do not have any kind of license set up correctly?

**Comment by nicolabingham** [comment]
@dorotawalker do we have a licence for the Green Party on WCT/ SPT? some sites on display in the Open UKWA were archived under a n&t basis.

**Comment by nicolabingham** [comment]
regarding the Green Party licence issue, it looks like we have permission for http://www.greenparty.org.uk/ (migrated from WCT) but the Target in W3ACT has additional seeds for which I think we don't have licences, for: https://www.greenparty.org.uk/ and http://greenparty.org.uk/,

**Comment by dorotawalker** [comment]
There is a licence in STP ID 143878 and it was Migrated From Access Database and there is a record in WCT ID 108088.
What's n&t :)?

**Comment by nicolabingham** [comment]
@dorotawalker, sorry, "notice and takedown"

**Comment by anjackson** [comment]
So, I don't actually know if _any_ of the data imported form WCT/SPT has the License field set correctly. It may well only be the content that's had permissions processed through ACT that have been set up right.

**Comment by anjackson** [comment]
Okay, going to roll out a fix for the exception Dorota noticed, as 1.0.4.

**Comment by anjackson** [comment]
So, there have been extensive changes to the permissions system, see #356, #333, #343. I think the changes we need are now implemented, so we'll see how the testing goes and then decide what to do next.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by nicolabingham** [comment]
@anjackson saving a permissions request form results in an Execution exception. In Target https://www.webarchive.org.uk/actstage/crawlpermissions/new?targetId=27026 entering the contact email address and pressing save results in the error: 
![execution_exception](https://cloud.githubusercontent.com/assets/11210500/8202025/15e519ae-14ce-11e5-9acb-a14f98e1bc64.png)

**Comment by anjackson** [comment]
Okay, I think this should work okay now. Testing needed once @GilHoggarth can deploy the updated code to live.

**Comment by nicolabingham** [comment]
Tested on /actstage. Works ok now. A permission request was successfully sent, returned and the licence status updated to Granted in the Target record.
