### ISSUE TITLE
Multiple mmdbs open

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#335]
Production /act was unresponsive this morning (Wed May 6). Running `lsof -p ....` showed that there were many (~20) handles open for `/opt/w3act-1.0/GeoLite2-City.mmdb`. This suggests to me that these aren't being closed after use; alternatively W3ACT should open once and reuse.

**Comment by GilHoggarth** [comment]
@romankarl Checking this issue on DDHAPT, at the current moment I checked, there wasn't any usage of this `GeoLite2-City.mmdb` file - has the DDHAPT usage of this file been worked upon?
If yes, might DDHAPT improve the closing of this file thus not leave them left open?
If no, does DDHAPT not typically use this file for document harvesting?

**Comment by romankarl** [comment]
Yes, I've fixed this issue already in DDHAPT.

**Comment by GilHoggarth** [comment]
Was it a difficult problem to fix or could we easily add this correction into the older W3ACT service?

**Comment by romankarl** [comment]
It was not such a complex change. You should be able to fix this by just using the current version of
https://github.com/ukwa/w3act/blob/ddhapt-merge/app/uk/bl/scope/Scope.java also in W3ACT. The specific changes were made in commit https://github.com/ukwa/w3act/commit/e423f0c23bd4b5feab8dd96d0c7a0ec563c30cdd.

**Comment by GilHoggarth** [comment]
Assigned to Andy for consideration of implementation.

**Comment by GilHoggarth** [comment]
Assigned to Reporter for testing on actdev. When testing successful, please add the label "1 - Ready" to this ticket.

**Comment by GilHoggarth** [comment]
Checking this issue again on actdev01 shows just 2 listings for this mmdb file. From reading the lsof manpage I believe these 2 represent the data handle for the mmdb in memory and the data handle of the directory file. Thus this looks fixed on actdev01.

**Comment by GilHoggarth** [comment]
I believe this issue appears mainly under significant load so this is difficult to test. However, whilst the WA team are testing the v1.0.3 release, the mmdb file is only held open in memory twice (which is the expected number.) Closing.
