### ISSUE TITLE
Test to ensure not possible to delete target with granted licence

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#337]
Related to #286 and #327, this ticket is to test and verify that it is indeed not possible to delete a target that has a granted licence.

**Comment by nicolabingham** [comment]
@GilHoggarth tested on live /act. 
I was unable to delete this Target: https://www.webarchive.org.uk/act/targets/22082. After selecting the delete button, the error message 'are you sure?' appears. Clicking 'ok' brings up the error message 'Unable to delete Target as it references License(s) and/or Collections(s)'. This is correct behaviour.

**Comment by GilHoggarth** [comment]
Sounds successful to me - closing.
