### ISSUE TITLE
Unable to add new types of licence to W3ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#338]
We have a requirement to attribute granted permissions to sites that are covered by external licences such as the Open Government Licence. Currently there is no option for the Archivist to create these in W3ACT so that they appear in the UKWA Licencing tab of a target record e.g. https://www.webarchive.org.uk/act/targets/2887/edit#licensing for selection.

**Comment by nicolabingham** [comment]
This function should apply to the Archivist role so that all agencies, BL, NLS and NLW can create their own licence types, e.g. NLS have an MoU to archive Scottish Government websites. The MoU is held out side of W3ACT but we should be able to record the fact that there is a granted licence within W3ACT against Targets.

**Comment by anjackson** [comment]
Superseded by #360
