### ISSUE TITLE
Execution Error when generating reports

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#339]
Attempting to generate a report of web archiving licences granted results in an Execution error "Execution exception[[RuntimeException: java.lang.StackOverflowError]]". This is from the reports page https://www.webarchive.org.uk/act/reports. Adding filters in any combination and selecting 'Apply' or 'Download' returns the error.

**Comment by anjackson** [comment]
Can't reproduce this on local dev. Will await @GilHoggarth's work on making /actdev/ more realistic before attempting to continue.

**Comment by anjackson** [comment]
I'll test this first.

**Comment by anjackson** [comment]
Works for me.

**Comment by nicolabingham** [comment]
Works on /actdev/

**Comment by nicolabingham** [comment]
Working on live
