### ISSUE TITLE
"Back" Behaviour Inconsistent

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#340]
When clicking on some search results, going *back* from the resulting page does not take you to the previous page. This suggests we're not implementing simple GETs; given the fun this caused in WCT this is *bad*.

* Go to any Target.
* Go to *Look Up URL*.
* Enter a search term.
* When the list of possible matches appears, click on one of the Target (NB. do *not* click "Search" or press return).
* Press the browser's back button.

This will take you back to the Target in the first step, not back to the "Look Up URL" page.

**Comment by anjackson** [comment]
Appears to be because the JavaScript is using ```window.location.replace()``` (http://stackoverflow.com/questions/11844430/back-button-fails-after-window-location-replacehref)

Solution is to replace with ```window.location.href =""```

**Comment by anjackson** [comment]
Should be testable once actdev has deployed.

**Comment by GilHoggarth** [comment]
Assigned to Reporter for testing on actdev. When testing successful, please add the label "1 - Ready" to this ticket.

**Comment by PsypherPunk** [comment]
Working on /actdev.

**Comment by PsypherPunk** [comment]
Confirmed working in live.
