### ISSUE TITLE
License Information Not Exposed

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#341]
For sites exposed via the `/by` exports, the license information does not display in the export. There are two fields, `licenseStatus` and `field_license` which should presumably be affected by the presence of license information but both are empty or `null` in every case.

Where license information is present, that information should be visible in the feed.

Additionally, when building SIPs for crawled content, we require information about each license, e.g.:

    <wct:Permission>
      <wct:State>Granted</wct:State>
      <wct:StartDate>2013-04-06</wct:StartDate>
      <wct:HarvestAuthorization>
        <wct:Name>The Legal Deposit Libraries (Non-Print Works) Regulations 2013</wct:Name>
        <wct:IsPublished>True</wct:IsPublished>
      </wct:HarvestAuthorization>
    </wct:Permission>

Although we store the name in w3act, we'll need to make sure the other fields are present somewhere (although we'll also need to check the exact meaning of the terms *State* and *IsPublished*.

**Comment by PsypherPunk** [comment]
This is currently how we store information for Selective crawls:

    <mets:amdSec ID="amdPermission">
      <mets:rightsMD ID="rmPermission">
        <mets:mdWrap MDTYPE="OTHER" OTHERMDTYPE="wctpermissions">
          <mets:xmlData>
            <wct:Permissions>
              <wct:Permission>
                <wct:State>2</wct:State>
                <wct:StartDate>2010-03-10 00:00:00</wct:StartDate>
                <wct:HarvestAuthorization>
                  <wct:Name>Ms. Harvest Authorization</wct:Name>
                  <wct:IsPublished>t</wct:IsPublished>
                </wct:HarvestAuthorization>
                <wct:AccessStatus>Open (unrestricted) access</wct:AccessStatus>
                <wct:FileReference>01010101</wct:FileReference>
                <wct:AuthorizingAgent>
                  <wct:Name>Ms. Harvest Authorization</wct:Name>
                  <wct:Contact>Ms. Harvest Authorization</wct:Contact>
                </wct:AuthorizingAgent>
                <wct:Patterns>
                  <wct:Pattern>http://subdomain.domain.uk/*</wct:Pattern>
                </wct:Patterns>
                <wct:SeedsURLs>
                  <wct:SeedURL>http://subdomain.domain.uk/</wct:SeedURL>
                </wct:SeedsURLs>
              </wct:Permission>
            </wct:Permissions>
          </mets:xmlData>
        </mets:mdWrap>
      </mets:rightsMD>
    </mets:amdSec>

Ideally these data would be exposed too. Potentially this would allow us to store multi-licensed content in the same SIP.

**Comment by GilHoggarth** [comment]
Assigned to Reporter for testing on actdev. When testing successful, please add the label "1 - Ready" to this ticket.

**Comment by PsypherPunk** [comment]
Going to need a little more information here. The `licenseStatus` and `field_license` are still seeminly blank—what _should_ be appearing in the export?

**Comment by anjackson** [comment]
e.g. http://www.webarchive.org.uk/actdev/api/targets/2998 - see crawl_permission field and the licence beneath.

**Comment by PsypherPunk** [comment]
Confirmed working in live.
