### ISSUE TITLE
licenses are not inherited to child targets

### ISSUE THREAD

**Issue by romankarl** [ukwa/w3act#343]
The current behaviour for inherited licenses does not seem to be appropriate:

For a child target where the parent has a license assigned there is an information banner displayed but the child target

1. still shows  “UKWA Licensing (-)” and
2. is not added to the By-Permissions Crawl Feed

**Comment by nicolabingham** [comment]
@romankarl I think this is the same as the issue raised in #333? https://github.com/ukwa/w3act/issues/333

**Comment by romankarl** [comment]
Almost. The second point is a supplement to #333.

**Comment by anjackson** [comment]
Says something along the lines of 'no need to apply for a license because...', like the Twitter ones (e.g. https://www.webarchive.org.uk/act/targets/16194#licensing).

**Comment by anjackson** [comment]
I've updated the code to ensure that the green (+) turns up when there is an inherited license. I've also modified the crawl feeds to take inherited licenses into account.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by anjackson** [comment]
Tested and working well on stage.
