### ISSUE TITLE
Better Validation for Target Titles

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#349]
It appears to be possible to create Targets with seemingly blank titles (e.g. [this one](https://www.webarchive.org.uk/act/targets/26535)). It looks like the title is actually a single space character; whether created by the web interface or the API, we need to make sure that mandatory fields are better validated to avoid this.

**Comment by niladreeb** [comment]
Now this bug is resolved in the web interface. On entering blank spaces it gives a warning message of "Blank Title".

**Comment by niladreeb** [comment]
Tested successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Tested and only spaces not allowed. However, single characters are such as '\', '.' so will submit new ticket proposing a block on meaningless text in manually edited fields.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Spaces only not allowed. Single characters still allowed but that isn't part of this ticket.

**Comment by GilHoggarth** [comment]
Single and multiple space not allowed.
