### ISSUE TITLE
Problems with Start-date?

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#352]
Jennie has reported that when attempting to set a start-date at to 28th May 2015 at 16:00 the system is saving the time as 15:00.

Looking in the export both the `StartDate` fields are showing 15:00:

    crawlStartDateText: "28-05-2015 15:00",
    crawlStartDateISO: "2015-05-28T15:00:00Z"

If the system's converting it to UTC that should be fine but it's causing confusion when being displayed back to a user.

Not sure that this is necessarily a DDHAPT-specific issue.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by anjackson** [comment]
Checked, fixed now.
