### ISSUE TITLE
Ensure API/code is sufficient to allow full import of data

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#354]
We need to import all Targets, Collections, and Permissions from WCT and SPT. I'd like to import the audit trail from SPT too, if possible.

This relates to this internal milestone: http://tickets.wa.bl.uk/trac/milestone/Decommission%20WCT/SPT

**Comment by anjackson** [comment]
This should work now, so we can review this on actdev.

**Comment by PsypherPunk** [comment]
Just looking at the [routes](https://github.com/ukwa/w3act/blob/master/conf/routes) file: there's

**Comment by anjackson** [comment]
I think the subjects tree is fixed and in-place already?

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by nicolabingham** [comment]
Tested on /actstage. works as expected

**Comment by nicolabingham** [comment]
@niladreeb sorry I commented on this ticket by mistake...

**Comment by anjackson** [comment]
Probably best if @PsypherPunk looks at this.

**Comment by PsypherPunk** [comment]
Regarding the WCT->w3act export, we need to be able to set the `field_wct_id`.

**Comment by anjackson** [comment]
I'm going to push finalising this off to the next bug-fix release, as we need to release 1.0.5

**Comment by PsypherPunk** [comment]
We need to be able to create `crawl_permission` and `contact_person` records via the API.

This might currently be possible but the `crawlPermission` attribute of the `Target` object has a `@JsonIgnore` decorator which I presume means it gets omitted from the JSON export?

**Comment by anjackson** [comment]
Yes, I added crawl_permission and crawl_permissions, but I should have just added the latter and made it JsonY

**Comment by PsypherPunk** [comment]
POST'd the following to actstage:

    {
        "field_urls": [
            "http://www.XXX.co.uk/"
        ],
        "field_uk_postal_address": true,
        "field_wct_id": "132884",
        "title": "XXX",
        "field_collection_cats": [],
        "field_nominating_org": 3,
        "field_subjects": [
            294,
            158
        ],
        "selector": "23",
        "crawlPermissions": [
            {
                "license": {
                    "id": 295
                },
                "contactPerson": {
                    "name": "",
                    "phone": "+44 (0) XXX",
                    "contactOrganisation": "XXX",
                    "postalAddress": "XXX,
                    "email": "info@XXX.org",
                    "description": ""
                },
                "createdAt": 1202428800
            }
        ]
    }

There seems to be an issue whereby `field_uk_postal_address` is now mandatory (this definitely _wasn't_ the case as all the spreadsheet imports we've been doing often don't have this field)—not including it results in a `NullPointerException`.

After adding that field the above returned a `201`:

* The licence ('295', above) doesn't appear to be selected in the web interface. However, dumping the JSON for the Target shows that the `license` is correctly selected...?
* A `crawl_permission` database entry //has// been created but clicking on `Crawl Permissions` in the web interface results in a `NullPointerException`.
* No `contact_person` entry has been created (and is omitted from the JSON export).

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by GilHoggarth** [comment]
Basically this functionality isn't in the code yet - @anjackson I suggest this gets bumped to 1.0.7 unless it ties in with another dependency.

**Comment by anjackson** [comment]
Code in commit cec264d should address this.

**Comment by PsypherPunk** [comment]
Confirmed that both the new (POST) and update (PUT) mechanisms are working for the creation of Targets and license information.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by PsypherPunk** [comment]
API code implemented correctly for new and existing records. There is an issue whereby a `crawl_permission` `createdAt` value can't be set but this is an issue with the data model, not the API per se. I'll raise a separate ticket for that.
