### ISSUE TITLE
Expert Users able to edit robots.txt settings

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#355]
From #244, Expert_Users should be able to edit robots.txt settings.

**Comment by niladreeb** [comment]
Fixed. The permission to edit the Robots.txt setting is now available to expert_users.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by niladreeb** [comment]
Expert_users can edit robots.txt setting.
