### ISSUE TITLE
Review inherited permissions system

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#356]
We have mis-attributed permissions from Twitter accounts (see #334) and erroneous inheritance behaviours (see #333 and '343). The permission inheritance system need to be reviewed and any erroneously assigned permissions should be revoked.

Additional requirements:

* When editing a target that has a unlicensed parent, the UI should encourage the license to be sought at the parent level.
* When permissions gathering is underway (e.g. QUEUED), the UI should show an amber signal (~) rather than a red (-).

**Comment by anjackson** [comment]
Okay, so this was really rather a mess. Code was inheriting licenses based on things like QA Status and URL length (the latter being why the Twitter ones are messed up).

The actual License field appears only to be updated when the parent license is submitted, which is obviously nonsense, as new children may be added later. So that code has been removed. Other 'higher' or 'lower' licences code was also found in the FormHelper, but it was rather wrong, so has been commented out.

So, now the plan is to add a new method to the Target class that checks for an inherited license - i.e. the License Status  in the database model should only refer to the status of that target, and the inherited form is always determined dynamically. This should then be used for user feedback and for the exports. If this performs badly, we could add an INHERITED form to the License Status, and disambiguate accordingly.

Once this is done, we need to clear up the Twitter ones, where the License Status got set accidentally.

**Comment by anjackson** [comment]
So, I've made some headway, adding a new slightly over-simplistic system for inheriting licenses, in commit d4ece25.

**Comment by anjackson** [comment]
I'm going to hand this over to @niladreeb to see if we can some up with some decent tests for this. I'd like tests at two levels:

1 - at a mocked-up database level, I'd like a test that looks for an inherited license before and after adding licensed 'parent' to a DB.
2 - ideally, I'd like a browser-based test that actually adds Targets and checks the state makes sense.

(2) might be too much for the moment, as we need a bugfix release next week.

**Comment by anjackson** [comment]
Note also that when editing a target that has a unlicensed parent, the UI should encourage the license to be sought at the parent level.

**Comment by anjackson** [comment]
There were some errors in my code, but I just pushed 66e1645 and I think it works okay now. Ready for test code.

**Comment by niladreeb** [comment]
@anjackson--- Tested on browser level and got some issues. Attached the doc file in slack

**Comment by anjackson** [comment]
So, these tests have illustrated the following problems with the current implementation:

* No distinction between inheritance of NPLD or permissions-based licensing. This means 'children' of NPLD-scoped targets can't have additional licenses granted.
* 'child'-'parent' relationship determined only on the basis of whether the child URL starts with the exact same URL as the parent. i.e. http://example.com/child/ would be determined to be a child of http://example.com/ but not of http://example.com/index.html or indeed of http://www.example.com/.

I think this covers all the problems we have seen. So, first job is to separate out the NPLD and License-based inheritance, so that the two tabs behave differently and appropriately. The second job will be to review licensing scope rules and work out how best to enforce them. Note that the system allows various different scopes (https://github.com/ukwa/w3act/blob/2e3e72bc952dc676f16b36ca0bf23939573b4f5f/app/uk/bl/Const.java#L584-L588), but these should probably be simplified as we can't really support ```plus1``` and it's not clear if the other three are all necessary (do we really want per-URL licensing?).

**Comment by anjackson** [comment]
Okay, so 1f5bd2d should resolve the first point, although it a very repetitive (low-performance) implementation. Next step would be to improve it to be computed once and re-used in the template.

**Comment by anjackson** [comment]
Right, I just updated the code, and it now does two things differently:

1. It relies on the database cached output of the various checks rather than re-running e.g. whois over and over.
2. It lower-cases and strips any "www." out before comparing domains under the 'starts with prefix' rule.

Does not support 'any subdomain' scoping, if we ever use that.

Note also that the scoping code is, frankly, a mess. There's various other cruft mixed in, the core sequence of 'is in scope' checks is repeated here and there, and the logic/distinction over when e.g. a fresh whois check is carried out (rather than relying on the DB-cached result) is very unclear. The system also has a hook to store the output of these checks (LookupEntries), but it's all mixed in with the checking.

**Comment by niladreeb** [comment]
Yes andy in the present code there are lot of functions to get the scope checked, so for the unit test I've used one of them. But whenever I'm trying to access methods from the java classes with enum return type like "Scope.java" it is giving authentication error

**Comment by niladreeb** [comment]
Implemented a JUnit test to check the license inheritance.

**Comment by anjackson** [comment]
Right, there were LOTS of mistakes in the old scoping code. I've reduced the duplicated logic, and fixed things like the whois stuff (which I don't think has ever worked). I've also extended @niladreeb's test class with a few more tests, especially the 'inheriting from subdomain scope' rule which I've just implemented.

**Comment by anjackson** [comment]
And now (fa23571) reviewed the exports and ensured inherited (fast) methods are used.

**Comment by anjackson** [comment]
I think the main problems are covered and we can move towards testing now.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by nicolabingham** [comment]
tested on /actstage. Created a new Target https://www.webarchive.org.uk/actstage/targets/28047 which correctly inherited the Granted Licence status from the parent Target record

**Comment by nicolabingham** [comment]
Created another child Target (https://www.webarchive.org.uk/actstage/targets/28048) which correctly inherited the Granted licence status from the parent record when saved and in View mode. 
![peterwebstertest2](https://cloud.githubusercontent.com/assets/11210500/8202400/772265e8-14d1-11e5-850e-9487a9614b29.png)


However, when going into Edit mode of the Target the licence status is lost, i.e. the green (+) changes to a red (-) and the licence status is "None" 
![peterwebstertest1](https://cloud.githubusercontent.com/assets/11210500/8202405/83e75c3e-14d1-11e5-8a27-4f20a14cc28c.png)

**Comment by anjackson** [comment]
I think this is fixed in the code. @GilHoggarth to re-deploy the latest version before testing.

**Comment by nicolabingham** [comment]
The View/Edit tabs are behaving consistently now.
