### ISSUE TITLE
Exceptions when viewing and editing instances

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#357]
When we go to the instance list of a target, it gives the option of viewing and editing the instance. As per the standard if we try to view or save the instance without setting the value, it should show 'None', but the page is giving Null Pointer Exception.

**Comment by niladreeb** [comment]
The error was happening because of the qaIssue tag in the view.scala html page. The Null check condition was erroneous. Now its solved.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by niladreeb** [comment]
Works fine.
