### ISSUE TITLE
Can all users access QA Wayback?

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#359]

**Comment by niladreeb** [comment]
As per the code expert_users , users and viewers don't have the permission to access QA Wayback. In general admin can give the all_qa_actions permission to everyone, but the role tab is invisible for them. So need to edit the role tab permission setting

**Comment by anjackson** [comment]
Which code? I can't see a hook in WaybackController that prevents access like that.

**Comment by niladreeb** [comment]
Sorry for the mistake. I meant to say, they can access the Wayback but those roles don't have the all_qa_actions permission.

**Comment by niladreeb** [comment]
So do we need to change the access permission?

**Comment by anjackson** [comment]
So, only users who are members of organisations 1,2,3,4,5,6 should be able to get content via WaybackController.wayback(url) - Others should get an access denied error  that explains that only LDL staff can access the QA Wayback instance.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by niladreeb** [comment]
Working as expected.

**Comment by GilHoggarth** [comment]
Tested, closing.
