### ISSUE TITLE
Properly support multiple licenses

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#360]
Basic support for multiple licenses was covered in #318, but we need to review in and make sure any and all relevant text is presented for each license.

Note that this refers to making it possible to add new licenses to the code, rather than through the GUI as in #338.

**Comment by anjackson** [comment]
Looks reasonable. Licence itself will need to be inserted manually, but after that we can extend the templates to change the content/text based on the license.

**Comment by anjackson** [comment]
This is now added, and can be tested via #467.

**Comment by anjackson** [comment]
Okay, this has now been done and can be tested under #467

**Comment by GilHoggarth** [comment]
Don't see how to test if this works or not as issue seems to be a question more than a problem. Closing.

**Comment by anjackson** [comment]
Now used in production by @nicolabingham so all good.
