### ISSUE TITLE
Unable to edit Collection Title

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#361]
I'm not sure if this been reported or not but I am unable to edit a collection title in live W3ACT. 
I tried to edit this Collection in W3ACT https://www.webarchive.org.uk/act/collections/449 
I tried to edit the title from 'Venues' to 'Venues and festivals' but the edit is not saved. Also the revision log I entered has not been saved.

**Comment by anjackson** [comment]
Verified in local testing - editing collections does not work.

**Comment by niladreeb** [comment]
It is now working fine. The issue was in the http method of routes file.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by GilHoggarth** [comment]
Checking on /actstage, this looks to be resolved. @nicolabingham is there more outstanding for this ticket?

**Comment by nicolabingham** [comment]
@GilHoggarth no, it appears to have been dealt with.

**Comment by GilHoggarth** [comment]
@nicolabingham Edited collection on live to 'Venues and Festivals'.
