### ISSUE TITLE
URL fails when ending slash included

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#362]
When trying to go the W3ACT service, if https://www.webarchive.org.uk/act/ is used - with an ending slash - "Sorry, that page does not exist." is reported.

This isn't a major problem but may well confuse/annoy users.

**Comment by anjackson** [comment]
This seems to be really difficult to fix from within Play, for reasons unknown.

I recommend that we add an Apache rule to fix this instead, redirecting to the version without a slash.

**Comment by GilHoggarth** [comment]
Moved to X.X.X future milestone as not at all relevant to 1.1.0.

**Comment by ldbiz** [comment]
...

**Comment by ldbiz** [comment]
It used to work in previous versions of play with a simple route definition; now it needs that and a handler; both implemented here.

**Comment by GilHoggarth** [comment]
Tested on /act-ddhapt/ and seen to still be failing. As a long standing issue, pushed to future milestone.
