### ISSUE TITLE
Target mid-crawl instance shows Java dump

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#363]
Using /actstage, Home > Browse Targets > Selecting a target > Instances > mid-crawl - display Java dump.

On /act the same steps show the LD QA openwayback.

**Comment by GilHoggarth** [comment]
Java dump is

An unexpected error has occurred.

    Execution exception[[NullPointerException: null]]

       play.api.Application$class.handleError(Application.scala:293)
       play.api.DefaultApplication.handleError(Application.scala:399)
       play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261)
       play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261)
       scala.Option.map(Option.scala:145)
       play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261)
       play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257)
       scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
       scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:411)
       scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:408)
       scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43)
       scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37)
       scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133)
       scala.concurrent.Promise$class.complete(Promise.scala:55)
       scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58)
       scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254)
       scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249)
       scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
       scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by GilHoggarth** [comment]
Ditto for "Search QA wayback" link on Target page, who's URL is https://www.webarchive.org.uk/actstage/wayback/*/http://www.bishop-hill.net/

**Comment by GilHoggarth** [comment]
As this is wayback related, could you investigate please.

**Comment by anjackson** [comment]
@GiHoggarth can you test this please?
