### ISSUE TITLE
Normal user can remove license

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#365]
A normal user can select a licence of --None--, which may overwrite the granted license.

**Comment by niladreeb** [comment]
Bug resolved.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by GilHoggarth** [comment]
@niladreeb Can you test this please.

**Comment by niladreeb** [comment]
Tested in actsatge and it is working fine. Now only admin and archivist can  remove licence and for expert_user it is disabled.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
Working fine.
