### ISSUE TITLE
NPLD scope shows as negative 

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#367]
NPLD scope shows as negative for the .uk or UK hosted targets. After saving it corrects, only to 'go back' to the negative sign after another search:

https://www.webarchive.org.uk/act/targets/2972;
https://www.webarchive.org.uk/act/targets/19273;
https://www.webarchive.org.uk/act/targets/21188.

Works fine for the others though:

https://www.webarchive.org.uk/act/targets/2993;
https://www.webarchive.org.uk/act/targets/17903.

**Comment by anjackson** [comment]
Are you using the back button to go back?

**Comment by dorotawalker** [comment]
No, just a new search.

**Comment by anjackson** [comment]
Weird. Can't reproduce this. These are all now showing as NPLD (+) for me:

https://www.webarchive.org.uk/act/targets/2972
https://www.webarchive.org.uk/act/targets/19273
https://www.webarchive.org.uk/act/targets/21188

Can you do a search at we'll see if they drop out again?

**Comment by dorotawalker** [comment]
Works fine now! I checked them three times  - I guess the system needed a morning coffee as well.

Thanks for checking.

**Comment by dorotawalker** [comment]
The same happened with a new record https://www.webarchive.org.uk/act/targets/28242. It came with all 'no' answers, only after editing and saving again it changed to the positive NPLD.

**Comment by dorotawalker** [comment]
and another one:

![untitled](https://cloud.githubusercontent.com/assets/12541602/8280482/865ed19c-18d5-11e5-91f9-01e409a0f518.png)

**Comment by anjackson** [comment]
Ah, understood.

In 1.0.5, the scoping will only be updated properly if you edit and resave. This is fixed in 1.0.6, where just looking at a Target will revalidate the scope.

**Comment by dorotawalker** [comment]
It's happening for the new records as well. Is it how it's supposed to be?

**Comment by anjackson** [comment]
Unfortunately, yes. I think 1.0.5 also failed to update this properly when a Target is first saved. This has been fixed and will be working properly when we release 1.0.6.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by dorotawalker** [comment]
Works fine for the existing records. Unable to test new records due to the same issue as ticket #373.

**Comment by dorotawalker** [comment]
Tested it on the new records https://www.webarchive.org.uk/actstage/targets/28248 and https://www.webarchive.org.uk/actstage/targets/28247. The NPLD scope is assessed correctly. The ticket was implemented successfully.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by nicolabingham** [comment]
This is working correctly on /act. Tested on existing targets and new.
