### ISSUE TITLE
New permission gives HLF licence as default

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#368]
![untitled](https://cloud.githubusercontent.com/assets/12541602/8278730/cfe51ca0-18c5-11e5-8498-f4c7eb9822f2.jpg)

**Comment by niladreeb** [comment]
Now the default licence is changed to Open UKWA Licence (2014-).

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by dorotawalker** [comment]
Tested and works fine on:

https://www.webarchive.org.uk/actstage/targets/15794/
https://www.webarchive.org.uk/actstage/targets/16059
https://www.webarchive.org.uk/actstage/targets/16071

The ticket was successfully implemented.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by nicolabingham** [comment]
This is working fine on live act now.
