### ISSUE TITLE
Viewing Licence form of crawl permission gives null pointer exception. But some of them are working fine.

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#369]
![2015-06-22 10-09-05_](https://cloud.githubusercontent.com/assets/12607939/8278911/43c4b4cc-18c7-11e5-861c-59f19616c575.png)

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
All of the licence forms are tested in actstage and they are working fine.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
Working fine in live w3act.
