### ISSUE TITLE
Add report listing users with multiple roles

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#370]
Following #274, users are now allowed only one role. We need to add a section to the 'consistency check' report page where users with multiple roles are enumerated so that they can be changed.

**Comment by niladreeb** [comment]
No such section found.

**Comment by anjackson** [comment]
Indeed - so please add one.

**Comment by niladreeb** [comment]
A new section added to consistency report to check users with multiple roles and if found remove all but the highest role.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by GilHoggarth** [comment]
@niladreeb Ditto, can you test this one too please.

**Comment by niladreeb** [comment]
The new section is added properly in reports where it was supposed to be, but the functionality can't be tested as of now as there is no such user with multiple role. It is worthy of mention that this bug was tested locally with virtual users having multiple roles and it worked perfectly.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by niladreeb** [comment]
The enhancement is working fine.
