### ISSUE TITLE
Unique Email Field for contact_person?

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#372]
`contactperson_id` is a mandatory field on `crawl_permission` and the only mandatory field on the former  is `email`. Perhaps this field should have a unique restriction? It would make things simpler when creating records via the API.

**Comment by niladreeb** [comment]
Unique key restriction added to contact_person table. Moreover W3ACT gives warning message when email is same but name different while updating or creating licence form.

**Comment by niladreeb** [comment]
Tested on actstage and it works fine.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by niladreeb** [comment]
Works fine in actstage.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Now a warning message is generated when  I try to add different names for a registered email. The unique key restriction is working fine in actstage.

**Comment by niladreeb** [comment]
Done on live
