### ISSUE TITLE
Invalid URL in Live System

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#375]
There's a Target with a URL of `http://The%20Queen's%20message%20following%20Scotland's%20referendum` which is causing problems. Attempting to view the Target or the export in which it appears (`domaincrawl`) returns the following error:

    Execution exception[[IllegalArgumentException: Not a valid domain name:
    'the%20queen's%20message%20following%20scotland's%20referendum']]

Somehow this has been entered and improperly validated. In addition to fixing the erroneous data we need to check that URL validation is correcly in place.

**Comment by PsypherPunk** [comment]
In addition to validation, the system should probably handle the error a little more gracefully—displaying a warning rather than dropping a huge stack-trace and rendering the web interface unusable.

**Comment by niladreeb** [comment]
The invalid URL is already removed.

**Comment by niladreeb** [comment]
URL validation is working fine.

**Comment by PsypherPunk** [comment]
If URL validation is working fine how did the offending URL get into the system?

We can't test this at the moment as this problem is currently affecting /actstage—which is why I said that the system should cope more gracefully with these errors. If you try to add a Target in /actstage you get this:

![untitled](https://cloud.githubusercontent.com/assets/722120/8495100/c130ee14-2162-11e5-8ce7-19d64ef979fb.png)

Another URL with an invalid domain has been entered into the system and the web interface just displaying a stack trace, which is _bad_.

**Comment by niladreeb** [comment]
I've tested in live w3act and there if we try to add this url: http://The%20Queen's%20message%20following%20Scotland's%20referendum-- it gives Invalid URL error message.
Even my local w3act is also behaving similarly,but actstage have no such implementation.

![img jpg](https://cloud.githubusercontent.com/assets/12607939/8497039/d52f9f6e-2171-11e5-9d76-2ffde481567a.png)

![image](https://cloud.githubusercontent.com/assets/12607939/8497059/ff887c5e-2171-11e5-9177-2d63d7730cd2.png)

**Comment by anjackson** [comment]
Did it come in via the API? (I expect not)

Was it entered a while ago, when the validation was not as good?

Are bad urls allowed when you edit, but not when you create a new target?

**Comment by niladreeb** [comment]
Bad urls are allowed when we edit existing urls

**Comment by PsypherPunk** [comment]
It looks like the Target that b0rked actstage was done via the API. The particular Target (which is indeed present in WCT) has a name of "!!!!" and a seed of "http://../".

**Comment by niladreeb** [comment]
Resolved [#bug381](https://github.com/ukwa/w3act/issues/381). Now bad urls are not allowed during editing.

**Comment by niladreeb** [comment]
Added domain validation in OverallLicenceStatus to avoid showing error page due to bad domain name.

**Comment by niladreeb** [comment]
Tested successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by niladreeb** [comment]
Tested and retested in actstage. The page do not fail due to the invalid URL.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
The two duff URLs above from Roger were tested and were not allowed. URLs with 2 or more sequential periods were allowed, but were highlighted as invalid in the target Edit mode when trying to save. Not the best solution but acceptable for release.

**Comment by GilHoggarth** [comment]
Ditto on live - acceptable for current production.
