### ISSUE TITLE
Collection date range in W3ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#377]
@anjackson I cannot find a relevant GitHub or Trac ticket for this one ...although that's not to say that it isn't in here somewhere already....
In WCT we set a date range at Collection level meaning all Target Instances falling within the range were exposed as members of the Collection. It doesn't look like we have this functionality in W3ACT yet. 
@anjackson and @PsypherPunk do you know whether this has been listed as a requirement anywhere? and if not, could this be implemented please?

**Comment by anjackson** [comment]
The fields are now in the DB and should be accessible from the API, but are not exposed to the user yet. We need optional date range pickers in the Collection editor.

**Comment by niladreeb** [comment]
Optional date range pickers added to Collection editor.

**Comment by niladreeb** [comment]
Tested in actstage and its working fine.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket.

**Comment by nicolabingham** [comment]
tested on act stage, works fine

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Working fine on actstage.

**Comment by niladreeb** [comment]
Done on live.
