### ISSUE TITLE
No communication_logs Raises NullPointerException

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#378]
For some Targets (see [here](https://www.webarchive.org.uk/act/target/28688) as an example) if there are no corresponding `communication_log` entries against the `crawl_permissions` then clicking the "Communication Logging" button raises a NullPointerException.

Unless the error's coming from somewhere else, a lack a `communication_log` entries is valid so the system should cope more gracefully.

**Comment by niladreeb** [comment]
Communication Logging not  giving the null pointer exception now. It was happening because of null crawl permissions which is now handled properly.

**Comment by niladreeb** [comment]
Twerks added for null permission.

**Comment by niladreeb** [comment]
Works absolutely fine in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
@niladreeb Don't know how to test this. Can you please.

**Comment by niladreeb** [comment]
@GilHoggarth sure.

**Comment by GilHoggarth** [comment]
Nils showed me where the communication log was - not part of target page as I understood from original description. Seen to work fine on /actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Checking the example Roger gave (understood to be https://www.webarchive.org.uk/actstage/communicationlogs/28688), this still fails.

**Comment by GilHoggarth** [comment]
Nils has informed me that example 28688 isn't actually valid data (perhaps any longer?) The other values checked in the Communications Log didn't show a Java null pointer so issue considered resolved.

**Comment by GilHoggarth** [comment]
Same as /actstage - NullPointerException when attempting to view non-existing log, but this shouldn't be directly possible so accepted as completed.
