### ISSUE TITLE
Setting the crawl_permission Date

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#379]
When adding `crawl_permission` records via the API, for example:

    {
        "crawlPermissions": [
            {
                "status": "GRANTED",
                "license": {
                    "id": 295
                },
                "requestFollowup": false,
                "contactPerson": {
                    "name": "Bruce Wayne",
                    "phone": "735-185-3801",
                    "contactOrganisation": "Wayne Enterprises",
                    "email": "bruce@waynetech.org"
                },
                "createdAt": 1109980800000
            }
        ]
    }

...the `createdAt` timestamp is seemingly ignored in favour of the current datetime. We need to be able to add the effective date of the `crawl_permission` which may be in the past—either this field needs to be editable, or we need another field which holds the "valid from" date.

**Comment by anjackson** [comment]
Hm, ```createdAt``` should allow this AFAICT. https://github.com/ukwa/w3act/blob/c0a82c59e7d1ae5a77096274a8fee4e3fe8459a4/app/models/ActModel.java#L45

Is it expecting the date in a different format? What does it look like when you GET an item that has a ```createdAt``` date?

**Comment by niladreeb** [comment]
the first date is in milliseconds

**Comment by niladreeb** [comment]
but createdAt date is the requested date. Is there any field that saves the licence granted date?

**Comment by PsypherPunk** [comment]
Doing a GET for a record in w3act gives:

    {
        "id": 22276",
            crawlPermissions: [
                {
                    id: 867,
                    url: "act-867",
                    createdAt: 1429798295872,
                    ...

...which has millisecond precision. I think.

However, if `createdAt` is in fact the requested date as @niladreeb suggests then firstly, it has a confusing name (is creation time the same as request time?) and secondly, no: we don't seem to have another field for storing the effective date of the license.

**Comment by niladreeb** [comment]
The title i guess need to be changed in the portal as presently it shows like this:

![image](https://cloud.githubusercontent.com/assets/12607939/8522410/b81dde4c-23e5-11e5-8f4b-671c77e8a040.png)

**Comment by niladreeb** [comment]
This bug is resolved. Please review https://github.com/ukwa/w3act/issues/319 .

**Comment by niladreeb** [comment]
Targets can be filtered by granted and requested date in actstage.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Tested successfully on actstage for requested date and granted date and the results are as follows:
'requestedAt': 1441293345681L
'grantedAt': None
'requestedAtISO': u'2015-09-03T15:15:45Z'
'grantedAtISO': None

**Comment by GilHoggarth** [comment]
Nil, please test on /actstage.

**Comment by niladreeb** [comment]
Working fine on actstage.

**Comment by niladreeb** [comment]
Done on live.
