### ISSUE TITLE
Improve API Error Messages?

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#380]
Currently when attempting to add Targets via the API, if a URL already belongs to another Target, w3act returns a `409` error ("Conflict"). While this is correct, the response body is empty; it would be useful to have some context in the response body as to _why_ there's a conflict (e.g. `URL XXX already assigned to Target XXX`).

This holds true for any other possible errors.

**Comment by niladreeb** [comment]
Is it similar to https://github.com/ukwa/w3act/issues/292  ?

**Comment by PsypherPunk** [comment]
Not as such. #292 refers to presentation of an error message when adding Targets via the web interface. Here, I'm referring to the API (although the logic—and code—behind both might be the same).

**Comment by PsypherPunk** [comment]
Tested and working on @niladreeb's test system. Will re-test once deployed to actstage.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Tested on actstage and it is giving a proper result.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Ah, I don't know how to use the API to attempt to test this. @niladreeb can you test please.

**Comment by niladreeb** [comment]
The API is giving proper message when I try to add existing data like 'Seed URL already associated with a current Target <a href="http://www.webarchive.org.uk/act/targets/10">http://www.webarchive.org.uk/act/targets/10</a>'. Passed on actstage.

**Comment by niladreeb** [comment]
Done on live.
