### ISSUE TITLE
Editing existing urls with invalid urls gave ActException

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#381]
![image](https://cloud.githubusercontent.com/assets/12607939/8499640/c1f1ec84-218c-11e5-9d2f-31a3c7595283.png)

**Comment by niladreeb** [comment]
Resolved.
![image](https://cloud.githubusercontent.com/assets/12607939/8499770/fd0e5bd0-218d-11e5-82d0-ed828beceddf.png)

**Comment by niladreeb** [comment]
Tested successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, test

**Comment by GilHoggarth** [comment]
@anjackson @niladreeb Is http://www..giltest.co.uk acceptable? I mean legally? It is in actstage.

**Comment by niladreeb** [comment]
@GilHoggarth No it is not acceptable.

**Comment by GilHoggarth** [comment]
Then ticket not passed.

**Comment by niladreeb** [comment]
A new UrlValidator implemented to block the entry of invalid url. Working fine locally.

**Comment by nicolabingham** [comment]
I tried to create a Target with Gil's invalid URL http://www..giltest.co.uk and got the error message "The URL entered is not valid. Please check and correct it, and click Save again". Also tried a few other invalid characters e.g. "!" and "," and got the error message. This seems to be working fine in /actstage/

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Tried using various invalid formats and it gave a warning message. Working fine in actstage.

**Comment by niladreeb** [comment]
Done on live.
