### ISSUE TITLE
Merge DDHAPT branch but limit access to the new functionality

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#386]
We need to make DB changes for various reasons, but the DDHAPT branch already contains new DB changes, so to keep development from getting too complicated we should merge the branches. Any new DB changes can then be added as ```3.sql```.

However, to avoid confusion, we should limit access to the new functionality for all but the sys-admin. This can then re-enabled via #385 and then #384.

**Comment by anjackson** [comment]
Note that I've pulled together the issues that appear to need database changes under this tag: https://github.com/ukwa/w3act/labels/needs-db-changes

**Comment by anjackson** [comment]
We've merged, but need to configure the system so that we can hide or show the document harvester stuff as we need. We'll switch it back on again under #385 and then #384.

**Comment by niladreeb** [comment]
ok thats fine.

**Comment by niladreeb** [comment]
Configurations for document harvester is in position now.

**Comment by niladreeb** [comment]
Actstage showing no sign of DDHAPT successfully as now DDHAPT is disabled in the configuration.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
As the admin, expert or normal user, I can't see any evidence of the DDHAPT menu or features. @anjackson Is this okay, i.e., not even visible as the admin or should this be visible to the admin as described in the first ticket comment?

**Comment by anjackson** [comment]
I did mean it to be visible to sysadmin, but it's not critical for this release. Maybe make a new ticket for 1.2.0?

**Comment by GilHoggarth** [comment]
Ticket fix accepted for this milestone. I'll create a new ticket to capture the need to expose the DDHAPT services to the admin user.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Working fine as it is expected to be for this release in actstage.

**Comment by niladreeb** [comment]
Done on live.
