### ISSUE TITLE
HLF licence as default after editing

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#387]
When going to the Edit Mode in the Crawl Permissions HLF licence appears as default. It has to be manually changed and saved. Every time you go to Edit the default changes.

![untitled](https://cloud.githubusercontent.com/assets/12541602/8568138/102e22a8-2563-11e5-94c0-ad830c6f7dec.png)

**Comment by niladreeb** [comment]
Open UKWA Licence (2014-) is now the default licence

**Comment by niladreeb** [comment]
Tested successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it works fine.

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Tested and it works fine.
