### ISSUE TITLE
Crawl end date cannot be removed

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#389]
When editing records with a crawl end date, you can't get rid of it. Some were set up more often for the General Election, but now it would be good to change the crawl frequency with the open end. The end date stays the same.

https://www.webarchive.org.uk/act/targets/3982

**Comment by anjackson** [comment]
@niladreeb I'm suspecting that the code is not un-setting the end date when it's null or empty from the form?

**Comment by niladreeb** [comment]
This problem is also occurring with the start date. Once both these values are set they are not getting reset to null. Moreover the end crawl date is always showing blank value in edit mode.

**Comment by niladreeb** [comment]
crawl start date and crawl end date can both be removed now.

**Comment by anjackson** [comment]
BTW, it should be impossible to remove the start date if the crawl frequency is anything other than Domain Crawl Only.

**Comment by niladreeb** [comment]
Yes, we can make the field uneditable for other options

**Comment by niladreeb** [comment]
Enhancement added. Now start date cannot be removed for options other than Domain Crawl

**Comment by niladreeb** [comment]
Tested in actstage. Crawl start date and end date both can be removed successfully.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Removed the end date from the https://www.webarchive.org.uk/actstage/targets/3061. When hitting save an error comes up:

![untitled](https://cloud.githubusercontent.com/assets/12541602/9636061/7f102d60-5191-11e5-8f88-cccf6705389a.png)

**Comment by anjackson** [comment]
The stack trace goes away if you remove some of the URLs (e.g.  http://greenparty.org.uk/, https://www.greenparty.org.uk/)

So, what's happening here is that the check for whether a URL is already attached to a target is wrong here. It is aggressively replacing with/without www. hostnames but it should keep what the users enters.

**Comment by niladreeb** [comment]
Now working fine on actstage.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.

**Comment by nicolabingham** [comment]
Tested and working on actstage
