### ISSUE TITLE
Remove Key sites check box for general users

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#390]
Can we remove the ability for users of 'Expert User' status and below to check the 'Key sites' check box which is in the Overview tab of the Target record?
![key_site_check_box](https://cloud.githubusercontent.com/assets/11210500/8646737/41579b12-294a-11e5-8058-d5bc675987bd.png)
'Key sites' are not really what the field implies here and it is confusing for users. The list of Key sites is moderated by the Legal Deposit Web Archiving Sub Group and should only be available for the Archivist to use so that the list is properly controlled.

**Comment by niladreeb** [comment]
The key sites option is now only available to admin and archivist.

**Comment by niladreeb** [comment]
Tested successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Checked as Expert and Key site value couldn't be edited. Checked as Archivist and successfully managed to amend the Key site value. Passed.

**Comment by GilHoggarth** [comment]
Example of a key site is target ID 805 - National Institute for Health and Care Excellence (NICE). 
Checked as Archivist and could amend, checked as expert and hmm, still could.

**Comment by GilHoggarth** [comment]
Issue probably due to swapping between accounts of different roles - definitely nothing to do with human error. Considered accepted as tested again and seen as satisfactory.
