### ISSUE TITLE
If last saved crawl end date is not null it becomes invisible in edit mode

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#391]

**Comment by niladreeb** [comment]
The bug is resolved.

**Comment by niladreeb** [comment]
Tested successfully in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Nils, another that only you'll understand. Please test in /actstage.

**Comment by niladreeb** [comment]
If any target have crawl end date != null, it was visible in view mode but invisible in edit mode. This problem is resolved and it is working fine in actstage.

**Comment by niladreeb** [comment]
Done on live.
