### ISSUE TITLE
URL search is case-sensitive

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#393]
When search for a URL the search appears to be case-sensitive. This makes it difficult to find matching URLs when the original has been entered in upper case (Twitter handles are especially problematic).

Can we change this so that the search is case-insensitive?

**Comment by PsypherPunk** [comment]
Correction: this works after clicking `Search`; it's the dynamic-search-results-drop-down that doesn't work.

Which is worrying as they should probably be using the same query...?

**Comment by niladreeb** [comment]
now the dynamic search is case insensitive.

**Comment by niladreeb** [comment]
Insensitive dynamic search working fine in actstage.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Using Targets > Lookup a URL and https://twitter.com/aasmahmir", both before pressing Search (i.e., auto suggest) and the search results have https://twitter.com/AasmahMir.
Accepted as passed.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Working on /actstage.

**Comment by GilHoggarth** [comment]
Tested with same twitter account as above and seen to suggest upper case URL for lowercase input.
