### ISSUE TITLE
Editing a Target title does not roll through to crawl permission

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#394]
I moderated the titles of two Target records that had been created by another user. The original user had requested crawl permissions. The title of the crawl permissions has not been updated to reflect the changes I made at Target level. 
The crawl permission records are: 
![bug_reporting1](https://cloud.githubusercontent.com/assets/11210500/8698400/c530c5c4-2af5-11e5-8f47-fbee2cfae454.png)
and the target records are:
![bug_reporting2](https://cloud.githubusercontent.com/assets/11210500/8698402/cded3878-2af5-11e5-9c47-e27dff182097.png)

**Comment by niladreeb** [comment]
To resolve this issue, first the name in new crawl permission is changed to read only.

**Comment by niladreeb** [comment]
Edited titles now reflect in crawl permission.

**Comment by niladreeb** [comment]
Tested on actstage and its working fine.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket.

**Comment by nicolabingham** [comment]
tested on act stage and working fine

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.
