### ISSUE TITLE
Expert user problems with crawl frequency

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#395]
Joan Francis, who is an expert user has problems with setting any frequency except for the domain crawl. The drop down menu opens, but there is no calendar when clicking in the 'start date' or 'end date' field. When filling the field manually or leaving empty and hitting save button, the system doesn't save and in practice she can only use 'domain crawl' which doesn't require a date.

**Comment by niladreeb** [comment]
Hi, Dorota I checked this issue with an expert user but it is working fine. Can the user provide some screenshot.

**Comment by anjackson** [comment]
This might be a browser dependency?

**Comment by niladreeb** [comment]
In IE this issue is happening.

**Comment by niladreeb** [comment]
Working fine in IE 9 and IE 10. Verified by Andy.

**Comment by dorotawalker** [comment]
Hi Nil,
If it's a single user issue do we still have to wait for a new deployment to see the changes?

**Comment by dorotawalker** [comment]
Hi @niladreeb 
If it's a single user issue do we still have to wait for a new deployment to see the changes?

**Comment by niladreeb** [comment]
@dorotawalker There is no such change for this bug. You can check this issue in Chrome, Firefox or Internet Explorer(latest version).

**Comment by niladreeb** [comment]
Tested in actstage and working fine

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Tested on /actstage using IE 9.0.8112.16421 64bit. Had to refresh most pages to see any content but didn't see this frequency/date issue. Marking ticket as passed therefore but @dorotawalker @nicolabingham I see that Joan Francis has a few tickets mentioning her name (I think.) Perhaps it would be best to contact her directly and clarify if she's still suffering problems after this 1.1.0 release. If so we should try to work out what's different about her usage - maybe her account, or her PC, or some other setting/s.

**Comment by GilHoggarth** [comment]
Repeat test with my IE and as an Expert user and didn't see any date issues. Difficult to confirm for Joan with current information so suggest again that she's contacted and asked.
