### ISSUE TITLE
Expert user problems with UKWA licencing tab

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#396]
Joan Francis, an expert user is able to save the UKWA licencing tab without giving the email address:

https://www.webarchive.org.uk/act/crawlpermissions/1854
https://www.webarchive.org.uk/act/crawlpermissions/1863
https://www.webarchive.org.uk/act/crawlpermissions/1843

I've tried to do it, but with my log in, the system asks for the email and doesn't proceed.

I don't know if it is just her account or a wider expert user issues.

**Comment by niladreeb** [comment]
Hi dorota, I also checked this issue but found no such error. Bug 395 and 396 is just for her account only.

**Comment by anjackson** [comment]
Is this some kind of browser variation? Or is this actually not empty, but a space character or similar?

**Comment by niladreeb** [comment]
Validation of the email field is properly done, so space characters are not allowed.

**Comment by anjackson** [comment]
What about just entering 'None'? Does it check for an '@'?

**Comment by anjackson** [comment]
Seems like the validation is done in Javascript only?

**Comment by niladreeb** [comment]
Yes it checks for @ and data before and after it.

**Comment by niladreeb** [comment]
I tested the issue in IE and providing None is accepting it. So it is a browser dependency issue.

**Comment by dorotawalker** [comment]
Thanks for looking into it. Joan's account also gives 'Nominations' as default in the Metadata Type->Selection Type. The default should be 'Selections'.

**Comment by anjackson** [comment]
@niladreeb can you see why this might be at all?

**Comment by niladreeb** [comment]
Email validation implemented on server side.

**Comment by niladreeb** [comment]
Both the issues are working fine in actstage.

**Comment by niladreeb** [comment]
Retested and works fine

**Comment by GilHoggarth** [comment]
Nils, , please test this ticket.

**Comment by niladreeb** [comment]
Server side email validation and default selection type is working fine in actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by niladreeb** [comment]
Email validation and default selection type is working fine in actstage.

**Comment by niladreeb** [comment]
Done on live.
