### ISSUE TITLE
Updating Licence status from target page does not update the crawl_permission table

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#398]

**Comment by niladreeb** [comment]
If the licence status is updated from the licence form then only the status is updated in db but not from the target page.

**Comment by anjackson** [comment]
Some data is duplicated at the Target level - that might be the issues.

**Comment by niladreeb** [comment]
I checked it with new data. But only this path "Quality Control > Crawl Permissions > Crawl Permission " and db is in sync not this path "Targets > Target".

**Comment by niladreeb** [comment]
Now updating the licence status from target page will update both the target and crawl_permission table.Moreover the granted date will also be updated accordingly.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
The bug is resolved from one scenario i.e changing from Granted to other status is getting reflected. But after discussing with Nicola the other scenarios I had in mind like changing from Queued to others status etc, this bug stands not ready.

**Comment by niladreeb** [comment]
Resolved properly.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Working properly in actstage for all status

**Comment by niladreeb** [comment]
Done on live.
