### ISSUE TITLE
Target page shows two 'Not Iniated' status of licence

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#399]

**Comment by niladreeb** [comment]
Licence status options modified after confirming from Nicola.

**Comment by niladreeb** [comment]
Tested on actastage and its working fine

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Nils, only you will understand the issue here!  Please test on /actstage.

**Comment by niladreeb** [comment]
In target page under UKWA Licencing, the Licence status dropdown used to show two 'Not Initiated' status. Now working fine in actstage.

**Comment by niladreeb** [comment]
Done in live.
