### ISSUE TITLE
Set SIP METS to TYPE=Issue for issues

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#400]
I’ve spotted a problem that seems to have re-occurred in the harvester. I’m sure that it had been fixed previously after one of our workshops with AIT.

If we process an issue level item and select “issue level” within the metadata form the output metadata is defaulting to “article”. This is a problem for the down-stream workflow and item discovery. Is it possible to get a fix in place?

----

I asked Roman about this, and he said:

I'm not sure if I understand the problem correct. The METS file should have the value
- "Monograph" for Books
- "Article" for Journal Articles
- "Issue" for Journal Issues
in the argument TYPE of structMap/div. Was that was Claire meant?

Currently this value is "Article" for both Journal Articles and Journal Issues, but it can easily be changed in the template file. Should I change that?
Claire: Can you clarify that this is what you meant, i.e. the template should be changed for issues? To TYPE=”Issue”?

----
Yes, it is this section that needs changing:

```xml
<mets:structMap TYPE="LOGICAL">
	<mets:div ADMID="amd0002-rights01" CONTENTIDS="@document.ark"
	DMDID="dmd0001" ID="log0001"
	TYPE="@if(document.isWholeBook) {Monograph} else {Article}">
	<mets:fptr FILEID="file0001"/>
	</mets:div>
	</mets:structMap>
	</mets:mets>
```

At the moment it provides a value of “article” whether article or issue is selected as the document type.

**Comment by niladreeb** [comment]
Issue already fixed.
