### ISSUE TITLE
Status tab in admin login gives NullPointerException

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#402]
![image](https://cloud.githubusercontent.com/assets/12607939/9004523/a202414c-376e-11e5-928f-28a01b0d3432.png)

**Comment by niladreeb** [comment]
Resolved. Implemented Null Check.

**Comment by niladreeb** [comment]
Working fine in actstage

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
What status tab? Assigning to Nils!

**Comment by niladreeb** [comment]
Its the 'System Status'  in home page after admin login. Works fine in actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Status page now displays correctly, assuming that the stati of all but Wayback not being available is correct. This should be tested once live to ensure these services are correctly configured.

**Comment by GilHoggarth** [comment]
Status doesn't produce NullPointerException. However, to note, live/production also only has Wayback reported as a responding service.
