### ISSUE TITLE
Limit the displayed with of columns in DDHAPT

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#405]
If you look at the columns in this page, the Document column occasionally causes great trouble with the table width:

![limit-widh](https://cloud.githubusercontent.com/assets/87843/9064592/31320b50-3ac5-11e5-9792-42b1e3dfd8a0.png)

The width of this column should be controlled by truncating the displayed text before it gets that long.

**Comment by anjackson** [comment]
Note that it's actually this line that is causing the problem:

```
https://www.london.gov.uk/sites/default/files/010914%20Amended%20and%20Restated%20Standby%20Refinancing%20Facility%20Agreement%20Execution%20Copy.pdf
```

**Comment by niladreeb** [comment]
The display width of the document column is now limited.

**Comment by anjackson** [comment]
Can you add a 'title' attribute to the links so that the non-truncated version is displayed as an on-hover tool tip?

Also, I'd prefer the last part be displayed rather than the first. i.e. something like:

    ...@document.documentUrl.substring(document.documentUrl.length() - 40)

**Comment by niladreeb** [comment]
On-hover tool tip added and in spite of front part the last part of the truncated URL is shown.
