### ISSUE TITLE
Edit button not showing

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#407]
We have reports that an expert user logged in cannot see the Edit button on targets they do not own. Requesting further information from user.

**Comment by niladreeb** [comment]
@anjackson Its true. Expert users cannot edit targets which they don't own. Let me know if any changes required.

**Comment by niladreeb** [comment]
Now expert_users can edit targets they don't own.

**Comment by niladreeb** [comment]
Tested on actstage and its working fine.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.

**Comment by nicolabingham** [comment]
Tested on actstage and working fine

**Comment by nicolabingham** [comment]
Tested using an Expert User account. Working fine.
