### ISSUE TITLE
URL lookup not normalising properly

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#408]
This search https://www.webarchive.org.uk/act/targets/lookup?f=work+foundation reveals that the same host has been registered twice, once with and once without a slash.  This should not happen.

**Comment by niladreeb** [comment]
@anjackson This URL do exist twice. But now if we try to create similar record if gives a warning message and show the existing record. So should we remove one of the record of TheWorkFoundation.

**Comment by nicolabingham** [comment]
@niladreeb I have asked Sally about the additional record. I will remove it when I hear back from her. Thanks.

**Comment by nicolabingham** [comment]
@niladreeb unless you need to remove it to complete the testing - then go ahead

**Comment by niladreeb** [comment]
@nicolabingham I've already tested with a different URL keeping the same scenario. So no worries. Just let me know at your ease which data is getting removed finally. Thanks.

**Comment by anjackson** [comment]
@niladreeb I think in this case, where the only difference between the records is the trailing slash at the host level, we should consider preventing a new Target being created. We do generally allow the user to override the matches in order to handle more subtle cases, but this seems nonsensical.  We could also consider moving the Add Target button to  be underneath the list, so that the user has to 'pass over' the list in order to get to the button.

**Comment by niladreeb** [comment]
@anjackson Now the present state is when we put a same URL with slash it gives the add button, but  when we try to save it it stops us by providing a warning message with a link to the previous target.

**Comment by niladreeb** [comment]
Both the dynamic search and the normal search is optimized.

**Comment by niladreeb** [comment]
Works fine in actstage.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Andy, please test this ticket.

**Comment by anjackson** [comment]
Tested on actstage and it works.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
URL normalising is working properly on actstage. But the duplicate work foundation is still there in the system.

**Comment by niladreeb** [comment]
Done on live.
