### ISSUE TITLE
Opening Edit page on clicking Instances for a target record.

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#410]
Instances link should open View page

**Comment by niladreeb** [comment]
Labels in View and Edit page of Instances are not similar.

**Comment by niladreeb** [comment]
Labels in View and Edit page now synced. Instances link in target record opens the View page.

**Comment by niladreeb** [comment]
Works perfectly fine in actstage.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Works fine in actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Nils, can you test this please, I don't understand what the issue is or how to test.

**Comment by niladreeb** [comment]
On clicking the link 'Instances' in the target page and then any of the instance from the instance list used to open the specific instance in edit mode. Now it is solved and it opens in view mode. Moreover the labels in view mode and edit mode are in sync. Passed on actstage.

**Comment by niladreeb** [comment]
Done in live.
