### ISSUE TITLE
Error message when trying to create new user on W3ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#411]
I tried to create a new user as follows: 
![lindar](https://cloud.githubusercontent.com/assets/11210500/9169674/ca8e2cd2-3f54-11e5-8093-450824c4975e.png)
but when I press Save, I get the following error message. 
![errormsg](https://cloud.githubusercontent.com/assets/11210500/9169682/db740440-3f54-11e5-8b15-fc331319db12.png)

**Comment by nicolabingham** [comment]
sorry agency should be 'Jersey Heritage', not 'The British Library'

**Comment by niladreeb** [comment]
@nicolabingham The new user creation is working properly in the live system as well as local. 

![image](https://cloud.githubusercontent.com/assets/12607939/9170907/ec7dc6fe-3f5e-11e5-94b5-1ff79fe813eb.png)

**Comment by nicolabingham** [comment]
@niladreeb thanks, this is working now :)

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Tested and works fine
