### ISSUE TITLE
Getting rid of the tick boxes in the NPLD scope tab.

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#412]
They are easy to omit and it adds an extra click. It allows for too many omissions in the NPLD criteria, therefore targets are not being crawled. Perhaps making the explanation as compulsory field.

**Comment by anjackson** [comment]
Do you mean the 'UK Postal Address', 'via Correspondence' and 'Professional Judgement' checkboxes? i.e. that we should effectively 'tick the box behind the scenes' if something is put in the 'Postal Address URL' field?

**Comment by dorotawalker** [comment]
Yes, I think that would be the best solution.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by anjackson** [comment]
Working fine on actstage.

**Comment by GilHoggarth** [comment]
@niladreeb Can you check this please. My understanding of the ticket is that the NPLD scope tick boxes for 'UK Postal Address', 'via Correspondence' and 'Professional Judgement' should be removed, and that their value should be set internally if text is entered in the corresponding text boxes.

However, looking at a target, these tickboxes are still visible. (e.g., https://www.webarchive.org.uk/actstage/targets/14167/edit#crawlpermission)

**Comment by niladreeb** [comment]
@GilHoggarth As of now for this ticket we are checking that if the text fields are filled then the checkboxes get auto ticked. A new ticket https://github.com/ukwa/w3act/issues/448  have been raised to resolve the issue in a better way. Done in live.
