### ISSUE TITLE
Adding the creation date of a record 

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#413]
Adding the creation date of a record may be useful (after changing the crawl frequency, it is quite difficult to see when we started crawling the site). Perhaps the field could be in Overview tab -> Title of field = “date created”.

**Comment by anjackson** [comment]
There is already a createdAt field in the database - it's just a matter of exposing it in the Overview tab.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket.

**Comment by nicolabingham** [comment]
working in act stage

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Tested and it works ok.
