### ISSUE TITLE
Clearer workflow for adding new Targets

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#417]
The lookup-and-add workflow was not working well, and had allowed near-duplicate Targets to be created. I propose we simplify the workflow and try to make everything more explicit:

1. No direct Add Target button on the Target List page - redirect to the Lookup page instead first. (This is largely because the filters on the Target List page can obscure the lookup results).
2. On the Lookup page, make the Add button clearer and place it at the end of the page, so the user has to pass over the list of matches before adding a new Target.

**Comment by anjackson** [comment]
Will need feedback from @nicolabingham @dorotawalker *et al* once this is deployed on actstage for testing.

**Comment by anjackson** [comment]
new Add button allows exactly the same URL to be re-added. This makes sense longer term (as really a new Target record should be allowed to supersede an old Target record on the same URL), but right now it's just confusing. The Add button should not show if there are clear matches.

**Comment by anjackson** [comment]
Okay, should work as expected once we'vre redeployed.

**Comment by GilHoggarth** [comment]
Andy, please test this ticket.

**Comment by anjackson** [comment]
Tested on actstage and it works.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.

**Comment by nicolabingham** [comment]
Tested on actstage

**Comment by nicolabingham** [comment]
search for "http://www.bl.uk/" and the results are returned correctly. (other records are returned correctly e.g. BBC articles etc)

Search for "http://www.bl.uk/magna-carta/" and the target for this URL is not returned.

**Comment by niladreeb** [comment]
Issued new ticket https://github.com/ukwa/w3act/issues/449

**Comment by niladreeb** [comment]
Issue fixed and tested locally.

**Comment by niladreeb** [comment]
Working fine on actstage.

**Comment by dorotawalker** [comment]
@GilHoggarth I think some features were added in the last deployment (add button at the bottom). I'm not quite following the issue that caused problems last time. It may need to wait for @nicolabingham as she tested it.

**Comment by niladreeb** [comment]
Retested and working fine on actstage.

**Comment by GilHoggarth** [comment]
Nicola, please test again on /actstage

**Comment by nicolabingham** [comment]
Tested and working on /actstage

**Comment by nicolabingham** [comment]
tested on live and working fine
