### ISSUE TITLE
Crawl Permission contact allows URL instead of email address - check for an @

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#418]
When entering a Contact Person, the email is not validated at all, so a URL was allowed through. We should check that there's an '@'.

----
In Crawl Permissions tab when selecting records to be sent and clicking 'Send' button the error comes up:

![untitled](https://cloud.githubusercontent.com/assets/12541602/9225190/c4137d10-40ff-11e5-81b8-86050c70fb2f.png)

It worked fine until today. I haven't made any changes and I don't know about any updates. I normally use Firefox.

Please do not send permissions for the following records:

Cork Spring Poetry Festival 
Cúirt International Festival of Literature
Guernsey Literary Festival

**Comment by nicolabingham** [comment]
@dorotawalker what is the URL for the website and the email address that you are using?

**Comment by dorotawalker** [comment]
https://www.webarchive.org.uk/act/crawlpermissions/list
@nicolabingham is it what are you asking? I'm trying to send permission to all required records' owners.

**Comment by nicolabingham** [comment]
@dorotawalker Could you try sending the list again but excluding http://19162016.com/ ?

**Comment by nicolabingham** [comment]
@dorotawalker this is not a valid email address

**Comment by anjackson** [comment]
We should add a validation step to check there is an '@' in the email address.

**Comment by dorotawalker** [comment]
@nicolabingham that worked. and you are right, it's not a valid email address. How could they enter it though? It normally shouts at you if you don't give a proper email address?

**Comment by nicolabingham** [comment]
@dorotawalker thanks for this. I think @anjackson will add a validation check.

**Comment by anjackson** [comment]
I'm going to rename this issue accordingly.

**Comment by niladreeb** [comment]
Email check implemented in Crawl Permission form.

**Comment by niladreeb** [comment]
Email check working fine in actstage.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it works fine

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.

**Comment by nicolabingham** [comment]
Tested and working on actstage
