### ISSUE TITLE
Adding new target gives null pointer exception

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#419]
![image](https://cloud.githubusercontent.com/assets/12607939/9228619/3d0da3c4-4111-11e5-89cc-4e9350c720de.png)

**Comment by anjackson** [comment]
I assume this is on stage, right?

**Comment by niladreeb** [comment]
No I tested it in my local system

**Comment by anjackson** [comment]
Should work now.

**Comment by niladreeb** [comment]
Working fine.

**Comment by niladreeb** [comment]
Tested on actstage and it is working fine.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Fails.
    From homepage, selected Lookup & Add a Target
    Searched for given example, http://www.giltest.co.uk - No target found
    Clicked Add target - Execution exception[[NullPointerException: null]]

**Comment by niladreeb** [comment]
Issue resolved.

**Comment by GilHoggarth** [comment]
Test repeated and successful. Able to create giltest.co.uk

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Working fine on actstage. Able to create http://hello.com .

**Comment by niladreeb** [comment]
Done on live.
