### ISSUE TITLE
Parent cannot be unset in Collection-->Edit tab

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#420]

**Comment by niladreeb** [comment]
Now parent can be unset for a specific collection.

**Comment by niladreeb** [comment]
Tested on actstage and working fine.

**Comment by niladreeb** [comment]
Retested and works fine.

**Comment by GilHoggarth** [comment]
Andy, please test this ticket.

**Comment by anjackson** [comment]
Verified

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Working properly on actstage.

**Comment by niladreeb** [comment]
Done on live.
