### ISSUE TITLE
Targets > Look up an Instance shows no data

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#421]

**Comment by anjackson** [comment]
Actually, lets push this back to the next version, as instances are not heavily used yet and we could use some feedback about how they should work.

**Comment by ldbiz** [comment]
I am unable to reproduce this, perhaps it has been fixed or was a data issue? Instance lookups do return data now, however they have the slight drawback of killing the entire application, for which I've raised a new issue #500.

**Comment by GilHoggarth** [comment]
Closed as issue undocumented.
