### ISSUE TITLE
In target overview the labels in View and Edit tab are not in sync.

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#422]
This need to be checked for all the tabs of target.

**Comment by anjackson** [comment]
Actually, I think this is okay to push back to 1.2.0 - we should see what users want first, because I think the UI could use more serious modification.

**Comment by min2ha** [comment]
Hi @anjackson, just wanted to clarify what exactly "are not in sync" means. 
Together with @ldbiz we noticed, that there are differences of VIEW and EDIT forms in **static fields ONLY**.
Data of **static fields'** (on the right side of form) are in sync. 

And what about **hints**? Should we sync static fields in **edit form** together with **view form** with same **hints** ?

Picture is attached where problems are pointed. 
Would it be enough to fix what is mentioned above for this issue? 

![issue 422](https://cloud.githubusercontent.com/assets/15713396/24711664/81e68af6-1a18-11e7-923b-1e7428732c5c.png)

**Comment by min2ha** [comment]
Hi, this is first version of Target's View and Edit tab sync. Let me know if it is acceptable. Field details on View tab makes no sense, so I fields with details are on Edit tab only.
![target_view_mod_1](https://cloud.githubusercontent.com/assets/15713396/25277732/d30af08a-2697-11e7-9598-dc0fd8cfa1a8.png)
![target_edit_mod_1](https://cloud.githubusercontent.com/assets/15713396/25277736/d5efdc02-2697-11e7-8ef9-07a4f97e9291.png)

**Comment by anjackson** [comment]
Hm, looks okay, but would you mind putting the changes on your own fork and doing this via a pull request? That will expose the code changes clearly.

**Comment by nicolabingham** [comment]
There is a small modification to make to the Watched Target page which I will raise as a separate ticket for a future release. Apart from this, I am happy to mark this as done.
