### ISSUE TITLE
In Targets > Look up an Instance adding instances give NullPointerException

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#423]
![image](https://cloud.githubusercontent.com/assets/12607939/9250183/eee5cd18-41c2-11e5-8a24-193a231ac9cd.png)

**Comment by anjackson** [comment]
How did you make this happen again? Just trying to add an instance?

**Comment by niladreeb** [comment]
Yes just trying to add an instance from the lookup.

**Comment by niladreeb** [comment]
Add Instance option is disabled for now.

**Comment by niladreeb** [comment]
Works fine in actstage.

**Comment by niladreeb** [comment]
Retested and works fine

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Option to add an instance if not found in 'Lookup instances' not disabled, so I can't test (basically test passed in this case - bah humbug).

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Tested and working on /actstage.

**Comment by GilHoggarth** [comment]
Now works on live.
