### ISSUE TITLE
Professional Judgement check box under NPLD Scope cannot be unset

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#424]

**Comment by anjackson** [comment]
It can't be unset if the Judgement explanation field is filled, by design. Or is that empty too?

**Comment by niladreeb** [comment]
When the explanation field is empty and check box unchecked, then after saving the view shows it is still checked.

**Comment by anjackson** [comment]
Fixed now - BTW we're still building up to 1.1.0 release proper, so we don;t need to push this on to 1.2.0.

**Comment by niladreeb** [comment]
Tested on actstage and it works fine.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Me, test - consider roles?

**Comment by GilHoggarth** [comment]
Tested and working on /actstage.

**Comment by GilHoggarth** [comment]
Seen to be possible now.
