### ISSUE TITLE
Adding target urls with invalid character crashes the page.

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#427]
Example: http://www.adoptionuk.org/&*%$&

**Comment by niladreeb** [comment]
Working fine in local system

**Comment by niladreeb** [comment]
Tested in actstage and issue is resolved.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Fails.
- From homepage, selected Lookup & Add a Target
- Searched for given example, http://www.adoptionuk.org/&*%$& - No target found
- Clicked Add target - Execution exception[[NullPointerException: null]]

**Comment by GilHoggarth** [comment]
Tested again, works in this newer release on /actstage.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
After adding the invalid url the page is not crashing on actstage. When tried to save the invalid url it gave a warning message. Passed on actstage.

**Comment by niladreeb** [comment]
Done on live.
