### ISSUE TITLE
'Hidden' flag need for Targets and Instances

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#428]
Much as we did with WCT, we need a flag for both Targets and Instances to indicate whether an item should be _publically_ shown.

Ideally, this should be a field called `hidden` or similar, defaulting to `False`.

**Comment by niladreeb** [comment]
@PsypherPunk Is it going to be editable by all users or restricted to admin and archivist?

**Comment by PsypherPunk** [comment]
It should be editable by the owner plus admin/archivist.

Also, it shouldn't be editable _at all_ if there's no licence information.

**Comment by anjackson** [comment]
Well, maybe we want to hide things that are only in the NPLD collection?

**Comment by PsypherPunk** [comment]
At which point it starts getting complicated: what if we want to hide it publicly but not from NPLD? Or vice versa?

**Comment by anjackson** [comment]
Hm, okay, then I suggest we just do the simplest thing first and see how it goes. Just add the flag and don't worry about whether there's any kind of license at all.

**Comment by niladreeb** [comment]
Flag named 'Hidden' placed in overview of target and in instance.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Working fine on actstage.

**Comment by niladreeb** [comment]
Done on live.
