### ISSUE TITLE
KeySite and Hidden checkboxes once checked cannot be unset

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#429]

**Comment by anjackson** [comment]
Ah, yes. If they are null you have to set them explicitly to False before they are saved/updated.

**Comment by niladreeb** [comment]
Ok.  Hidden and key site flag set explicitly to False when null.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage - especially regarding appropriate role.
