### ISSUE TITLE
Curators' list in alphabetical order

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#430]
In the Targets -> Reports -> Open UKWA tab -> Requested/Granted/Refused: Filter by curator to be arranged in alphabetical order.

**Comment by niladreeb** [comment]
Curator's list is now arranged in alphabetical order.

**Comment by GilHoggarth** [comment]
Nils, please test this ticket.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Seen to be done in /actstage.

**Comment by GilHoggarth** [comment]
Done on live.
