### ISSUE TITLE
Look up url page

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#431]
At the moment the alphabetical list of URLs is loaded on the 'Look up the URL'. It is not necessary as the same function exists in the 'List Targets'. I may cause confusion for users. Please remove the list.

**Comment by anjackson** [comment]
So, if there is no URL search term, then no list should be shown. The lookup page should only show very close matches or identical target entries when a URL query is given.

Does that sound about right?

**Comment by dorotawalker** [comment]
The list of all existing records below the search box appears with or without actual search:

![untitled](https://cloud.githubusercontent.com/assets/12541602/9516676/1e0b7f18-4ca2-11e5-8540-980e2de5c86d.png)

**Comment by niladreeb** [comment]
The entire list of URLs under Lookup URL is removed. Now it shows only exact or similar URL matches.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it works ok.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.
