### ISSUE TITLE
Spelling of the word LICENCE

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#432]
The word LICENCE is spelt in American English as License, e.g. Open License Request. Please change it.

**Comment by niladreeb** [comment]
Spelling of LICENCE changed everywhere.

**Comment by GilHoggarth** [comment]
Nicola, please test this ticket.

**Comment by nicolabingham** [comment]
working in act stage

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Tested and it has been changed everywhere except Targets -> List -> Filters. The filter still has a wrong spelling.

**Comment by dorotawalker** [comment]
@GilHoggarth not sure which label to add.

**Comment by GilHoggarth** [comment]
@dorotawalker Given this spelling correction has been added in some places, can we bump this remaining fix to the next milestone? (Please :) If this is okay, this issue can be labelled "2 - Tested and working on stage".

**Comment by dorotawalker** [comment]
@GilHoggarth that's absolutely fine.

**Comment by GilHoggarth** [comment]
Shifted issue to next milestone, to get the Targets -> List -> Filters spelling mistake corrected.

**Comment by niladreeb** [comment]
Found one more spelling mistake in admin login under Taxonomy tab. Resolved all 'LICENCE' spelling  mistakes.

**Comment by niladreeb** [comment]
Change of Licence spelling  involved change of few data in database. Working fine on actstage.

**Comment by GilHoggarth** [comment]
Confirm licence spelling fixed at Targets > List Targets as one of the filter names and under the Taxonomies menu drop down.

**Comment by GilHoggarth** [comment]
Gil test

**Comment by GilHoggarth** [comment]
All done (that I could find!)

**Comment by GilHoggarth** [comment]
Completed on /act.
