### ISSUE TITLE
Spellcheck is not available in the title field

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#434]
Please add automatic spellcheck in the title field.

**Comment by anjackson** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTML/Controlling_spell_checking_in_HTML_formsControlling_spell_checking_in_HTML_forms

**Comment by niladreeb** [comment]
Added the spellcheck parameter but it is not working properly in all browsers as it is a browser dependent issue . Spellcheck is supposed to work fine in chrome and firefox, but currently it is working fine in firefox only.

**Comment by nicolabingham** [comment]
Thanks @niladreeb I will write up the spellcheck issue and browser dependency and put it in the user guide.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it works ok in Firefox, not working in IE. I don't have Chrome on my PC, so unable to test that.

**Comment by GilHoggarth** [comment]
Speaking to Nils, I understand that this spell check feature only works in firefox currently and won't be implemented in chrome, unless we get significant requests for this.

**Comment by anjackson** [comment]
I think it should work on all browsers if the correct language packs/dictionaries are installed. It's a browser feature not a W3ACT feature. See http://www.wufoo.com/html5/attributes/17-spellcheck.html

**Comment by nicolabingham** [comment]
This will be dealt with by way of notes in the user guide.

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Spelling is not working, but the issue is resolved.
