### ISSUE TITLE
Status in the record UKWA licence tab

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#436]
After sending a permission request, the status is still seen as 'Queued', not 'Pending' in the target record (both view and edit modes).

**Comment by niladreeb** [comment]
Licence status is getting updated to 'Pending' in both view and edit mode.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it does not seem to have worked. 'Queued' status in both view and edit mode for the records where permission requests have been sent. I have checked the following:

https://www.webarchive.org.uk/actstage/targets/30024
https://www.webarchive.org.uk/actstage/targets/30020
https://www.webarchive.org.uk/actstage/targets/30007

**Comment by niladreeb** [comment]
@dorotawalker The bug was resolved in such a manner that to see the changes the targets need to be sent again. For new targets it will work directly.

**Comment by dorotawalker** [comment]
@niladreeb works ok for new targets. @nicolabingham is there anything you would like to do with the existing ones?

**Comment by nicolabingham** [comment]
@dorotawalker I think it is the case that ALL existing Queued crawl permissions on W3ACT should be correctly tagged as Pending? The only Queued crawl permissions will be those that have recently been submitted by curators, probably only a day's worth as you deal with this list every day?

**Comment by dorotawalker** [comment]
@nicolabingham I agree, especially if the bug is not fixed now, we will forever have a non-existing backlog of 'queued' permissions. I think it would be good to sort it out.

**Comment by nicolabingham** [comment]
@dorotawalker I'm not sure if this was a bug or a question of how the original requirement document expressed how these states (Queued, Pending etc) should be marked. Once this code has been released to production any new crawl permissions will be correctly marked as Pending once they are sent out (so the bug part is fixed). What we are concerned about is the backlog of Queued permissions on the system that should be marked Pending. This may need a global update to production which @niladreeb and @anjackson may not like....or it may be that the number of Queued permissions is manageable enough that we can manually change them.

**Comment by nicolabingham** [comment]
Going to mark this as Done as the bug has been fixed. @dorotawalker we can ask @niladreeb to look at the legacy Queued crawl permissions in a separate ticket after we have reviewed the scope of the problem. It may be that @niladreeb can write code to fix this but it is not a priority for 1.1.0.

**Comment by GilHoggarth** [comment]
Dorota, please test on /actstage.

**Comment by dorotawalker** [comment]
Tested and it works ok for new records.
