### ISSUE TITLE
Web form information

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#438]
Sometimes we don't have an email address to send a permission request and we fill in a web form on the website. It would be useful, if the target record had a field to tick or fill in, preferably with a date, so we can keep track. It would be also useful for the statistics. It would be best placed in the Target record -> UKWA Licensing

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it works ok.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Web form date seen under UKWA Licencing.

**Comment by GilHoggarth** [comment]
Web form field and date seen on live.
