### ISSUE TITLE
Deselect all option

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#439]
Crawl Permission List: When clicking ‘Deselect all’ on page 2 (or any other than page 1 for that matter) it redirects to page 1. All records on page 1 are unticked, but when clicking ‘next page’ the records on page 2 are all ticked.

**Comment by ldbiz** [comment]
It's also reverting the selected status in the filter.

**Comment by ldbiz** [comment]
Now, on Select/Deselect All, the following are no longer discarded:

1. Current Page.
2. Select/Deselect state.
3. Status filter.

**Comment by GilHoggarth** [comment]
Seen to be working on /actstage.

**Comment by GilHoggarth** [comment]
Seen on live, closing.
