### ISSUE TITLE
‘Archive it now’ button 

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#440]
Crawl policy and Schedule: the ‘Archive it now’ button active in the view mode, but inactive in the edit mode. Requires the user to come out of edit mode and into view mode before the button becomes active. This adds unnecessary mouse clicks.

**Comment by niladreeb** [comment]
This facility is provided to prevent lose of data. If any value is edited in the Edit mode, and then the Archive it now button is pressed then the new values will not be saved.

**Comment by niladreeb** [comment]
@nicolabingham please confirm if its fine?

**Comment by nicolabingham** [comment]
@niladreeb ok, we better leave this as it is for the moment. Will think about adding a message for users to inform them to save their data before hitting Archive this now.

**Comment by niladreeb** [comment]
@nicolabingham, i can add the message now only, if you want. In that case please give the content of the message.

**Comment by nicolabingham** [comment]
@niladreeb great thank-you. Message should read "Please save the record before hitting 'Archive this now' otherwise your data may be lost."

**Comment by niladreeb** [comment]
@nicolabingham thanks. 'Archive this now' button now active in edit mode with warning message.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
The 'Archive it now' button is now active in both 'view' and 'edit' modes and I am not sure whether it was the intention. @nicolabingham could you please comment?
Also when hitting the button it comes with an error, but I guess we'll raise it as a separate issue:

![untitled](https://cloud.githubusercontent.com/assets/12541602/9635427/547f7496-518e-11e5-95d7-6bfde2c2aa9c.png)

**Comment by nicolabingham** [comment]
Yes, it is fine to have the 'Archive this now' button in Edit mode so long as we have the error message requesting users save their data first to prevent loss of data as @niladreeb mentions.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
@nicolabingham As an archivist, the "Archive this now" button exists in both View and Edit mode - selecting the button in View presents the message "There was a problem queuing this crawl instruction. Please refer to the system administrator." and selecting the button in View mode presents the message "
Sorry, that page does not exist.
    /actstage/targets/30148/@routes.TargetController.archive(id)", which suggests to me that the target details haven't yet been saved and therefore the action to archive couldn't attempt to begin.
"Archive this now" button no longer visible in Edit mode for an Expert. 
Checked User role and there's no option to "Archive this now". 

Plus, Andy raised that it should also be tested that this button is only available when a target is in scope.

**Comment by nicolabingham** [comment]
@GilHoggarth after understanding the consequences a bit more I think this button should only be available in Edit mode even to Archivists (in other words rescinding this ticket).

**Comment by GilHoggarth** [comment]
Resolution to this ticket is to remove the "Archive this now" button entirely in this milestone release. Andy has checked deeper into the W3ACT code and it doesn't check if a target is in scope, so could allow the collection of out of scope content. @niladreeb Please remove/comment out this button from the code.
A new ticket will be created for a future milestone to enable this conceptual functionality.
