### ISSUE TITLE
Tags cannot be added

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#442]
When trying to create a new tag https://www.webarchive.org.uk/act/tags/new, there is no 'save' button on the screen. When hitting enter instead an error appears: 
![untitled](https://cloud.githubusercontent.com/assets/12541602/9601711/61710d8e-509b-11e5-8ddc-0448b1d517d9.png)

**Comment by niladreeb** [comment]
Checked in live system, and its working fine. Please check the screenshots:
![image](https://cloud.githubusercontent.com/assets/12607939/9601856/30460326-509c-11e5-973e-b15d49cec5ce.png) 

Test data getting saved:
![image](https://cloud.githubusercontent.com/assets/12607939/9601890/6d9da97c-509c-11e5-8c61-e86118029b0c.png)

**Comment by niladreeb** [comment]
@dorotawalker Only sys_admin is given permission. Do you want me to extend it to archivists also?

**Comment by dorotawalker** [comment]
@nicolabingham what do you think?

**Comment by nicolabingham** [comment]
@dorotawalker @niladreeb yes please give permission for Archivists to add tags (not any wider than this for the time being)

**Comment by niladreeb** [comment]
@nicolabingham @dorotawalker sure. Thanks

**Comment by niladreeb** [comment]
Now tags can be added and deleted by archivists.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
Tested and it works.

**Comment by GilHoggarth** [comment]
Nicola, please test on /actstage.
