### ISSUE TITLE
Filter on crawl permissions page isn't actionable

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#445]
Although there's a filter of crawl permissions statuses on https://webarchive.org.uk/actstage/crawlpermissions/list?s=updatedAt&status=PENDING, there's no way of making a change of selection affect the data. I.e., it needs something like an Apply button.

**Comment by anjackson** [comment]
The Search button does apply the filter, so maybe that's good enough for now?

**Comment by nicolabingham** [comment]
Yes, the search button applies the filter.
