### ISSUE TITLE
URL search fails to retrieve URLs with a child path and a trailing slash

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#449]

**Comment by niladreeb** [comment]
The '/ ' in the middle of the url was getting replaced. Fixed and tested locally. Same as https://github.com/ukwa/w3act/issues/417 .

**Comment by niladreeb** [comment]
Working fine on actsatge.

**Comment by GilHoggarth** [comment]
Confirmed as fixed on /actstage - https://www.webarchive.org.uk/actstage/targets/lookup?f=http%3A%2F%2Fwww.bl.uk%2Fblpac%2F

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage

**Comment by niladreeb** [comment]
Confirmed fixed on actstage.

**Comment by niladreeb** [comment]
Working fine on live.
