### ISSUE TITLE
QA status invisible in view mode

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#450]
QA status is invisible in the view mode. It is ok in the edit mode and it was working before the 1.1.0 deployment. 

https://www.webarchive.org.uk/act/targets/21132 (OK to publish status)
https://www.webarchive.org.uk/act/targets/9338 (QA issue found)

**Comment by niladreeb** [comment]
Issue resolved.

**Comment by GilHoggarth** [comment]
Two example URL checked on /actstage and confirmed as now displaying WA status information as expected.

**Comment by GilHoggarth** [comment]
Gil test

**Comment by GilHoggarth** [comment]
Above URLs checked (on /actstage), working now.

**Comment by GilHoggarth** [comment]
Working on /act
