### ISSUE TITLE
Second option of Scope under Crawl Policy and Schedule is incorrect.

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#454]
Second option is 'All URLs that match match this host or any subdomains.'. The word match is used twice.

**Comment by niladreeb** [comment]
The minor error in the sentence is corrected.

**Comment by GilHoggarth** [comment]
Confirmed corrected on a target edit Crawl Policy and Schedule tab - https://www.webarchive.org.uk/actstage/targets/9338/edit#crawlpolicy

**Comment by GilHoggarth** [comment]
Gil test

**Comment by GilHoggarth** [comment]
Above URL checked, working on /actstage.

**Comment by GilHoggarth** [comment]
Working on /act.
