### ISSUE TITLE
Editing QA Status of any instance under Instances > Instances List gives NullPointerException .

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#456]
Please refer https://github.com/ukwa/w3act/issues/263 .

**Comment by niladreeb** [comment]
qaIssue.name was creating the issue as qaIssue.name.length() was in the null check condition. The bug is resolved.

**Comment by GilHoggarth** [comment]
Viewed on /actstage but couldn't determine area of issue with confidence.

Tried:
- /actstage homepage > Targets menu > Look up an Instance
- Entered http://www.bl.uk and saw a list 1 to 10 of 129 showing no QA statuses.

Tried:
- /actstage homepage > Targets menu > Look up a URL
- Entered http://www.bl.uk and saw a list 1 to 10 of 10 showing two QA statuses of “QaIssue(null), id:190”

Should highlight here that the counts of crawled instances and URLs don’t tally.

Tried version of originally mentioned URL of https://www.webarchive.org.uk/actstage/qa/list but this didn’t respond and log recorded a JHS error.

Can’t test as can’t find the problem either on /actstage or erroring on production /act.

**Comment by dorotawalker** [comment]
@GilHoggarth as the instances are not available in the production, I've got no idea what @niladreeb refers to.

**Comment by niladreeb** [comment]
@GilHoggarth this issue need to be viewed by opening the instances link on the right hand side of any target.

**Comment by GilHoggarth** [comment]
Nils - please test this NPE on /actstage

**Comment by niladreeb** [comment]
Working fine in actstage. Issue resolved perfectly.

**Comment by niladreeb** [comment]
Tested on live and the issue is resolved.
