### ISSUE TITLE
Editing sub-collections

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#459]
After editing a sub-collection and clicking save the sub-collection is created as a separate collection, even though the bullet point on the collection list is ticked (automatically). It needs editing again to put in the right place.

**Comment by nicolabingham** [comment]
@dorotawalker could you give an example of a sub-collection you were editing please?

**Comment by dorotawalker** [comment]
@nicolabingham I did it with the IT collection -> UK IT Business (changed the name from UK IT Companies), but I've noticed it before and it should be the same for all of them.

**Comment by nicolabingham** [comment]
@dorotawalker yes I see. @anjackson the Parent collection data fails to save when saving an edited sub-collecton record.

**Comment by anjackson** [comment]
I suspect this may be the same issue as seen in #453.

**Comment by niladreeb** [comment]
Tested on actstage and its working fine. Requesting @dorotawalker to check.

**Comment by niladreeb** [comment]
Tested on live and working fine.
