### ISSUE TITLE
Improved API for Collections Tab generation

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#461]
Various fixes and extensions have been made to the API and serialisations to support the generation of a collection browser from the content held in W3ACT. Including:

* ac8cbd1d8c3c2467dc442b3bf837708871d92ffe
* ecce90a180593a297f889ee9b834dbdce8eb03c2
* 3ba628ffdcefd2dfc1eb15bb3fc9ffa10ce1e178
* 3eea71a99757e9dca894d7390bd300e1b55635c6
* 1be12e20c389a3951235365569bb7d914c6d1de4
* a0318b061eaf44d63506469b68b1c72fc386f8fb
* 8f9baa740b0890b3b590522a710267244e69271c
* 13a1e98b3e3afb2c7d9394ff8470a6e03ec2f517
* 4e4d78df3deecddea9f56e7e7d79fd9ca2323286
* 08ee45dc57ce7789942b7eeb95e1d897bd598dda

**Comment by GilHoggarth** [comment]
Andy - please test this API issue on /actstage.
