### ISSUE TITLE
Date of licence granted changed by system

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#464]
Reported by @dorotawalker 
When opening a Target record, the granted licence date is being changed by the system to the date/time of the last edit of the Target.

Example: Target record :
https://www.webarchive.org.uk/act/targets/43 Early Days of a Better Nation
Permission was granted by the site owner 22/09/2015. However after Dorota opened the target record the recieved date: https://www.webarchive.org.uk/act/target/43/crawlpermissions has been changed to the date/time of the last edit (today's date. 
In View log, the dates of sending and granting permission are correct https://www.webarchive.org.uk/act/communicationlogs/link/bc2614ec-02a1-456b-96ae-690139f67d31

**Comment by anjackson** [comment]
Oh dear. I think we need to do more whole-system testing prior to release, on actstage. We should have caught this earlier.

**Comment by anjackson** [comment]
Okay, problem is in commit 569871a3ac0500a1c3f8f416bf79d2e4fb652144 which updates dates even if nothing had been changed. /cc @niladreeb

**Comment by niladreeb** [comment]
sorry my mistake. The condition check was not exhaustive i guess.

**Comment by anjackson** [comment]
Don't worry - the logic is sadly rather fiddly. I think the best idea may be to simply remove this logic and update those dates in other ways if required. We should be able to do that via the API.

**Comment by anjackson** [comment]
Okay, so I think this is fixed, in that editing the Target should not modify the Crawl Permissions. Repairing the grantedAt will have to be done via the DB for now.

I suggest we roll this fix our to production ASAP. I'll ask Gil to get it on stage. Also, we should come up with a longer set of basic operations to test on actstage before we roll to production.

**Comment by anjackson** [comment]
On closer examination, the problem is like #465, in that the form is not displaying the correct date.

**Comment by anjackson** [comment]
Okay so, @dorotawalker, was it the Crawl Permissions page where you were seeing these erroneous dates?  I think so.

It turned out that the page was reporting the date the Target was last updated (which changed even if nothing has changed but the Target is saved).

I've modified it to report the dates of the permission request and the granted date.  It's live on actstage now.

**Comment by GilHoggarth** [comment]
@dorotawalker Can you check please that this now works correctly.

**Comment by dorotawalker** [comment]
@GilHoggarth I'm trying to get to act/stage, but it's taking a very long time to log in or to click through the links. Thanks

**Comment by GilHoggarth** [comment]
@dorotawalker Sorry Dorota, looking into it... (service memory problem)

**Comment by GilHoggarth** [comment]
@dorotawalker Right, please try again - should work this time!

**Comment by dorotawalker** [comment]
Tested and working OK. @anjackson would you like me to raise a new ticket for cleaning up data for the targets that were affected?

**Comment by GilHoggarth** [comment]
Grand, thanks - yes, please raise a new ticket for data clean up.

**Comment by dorotawalker** [comment]
Tested on live act and works fine.
