### ISSUE TITLE
Display tick against 'Agree' clause in licence form

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#465]
Could the tick be made visible in the “I/we agree” checkbox on the licence form please? Currently the tick is not made visible. (e.g. https://www.webarchive.org.uk/act/ukwa/licenseformview/913017a9-b687-476b-8c32-515fb74790ce)

**Comment by GilHoggarth** [comment]
Nicola, can you check what you wanted to correctly done please.

**Comment by nicolabingham** [comment]
The flag is visible in the checkbox as requested.

**Comment by nicolabingham** [comment]
Tested and working on live
