### ISSUE TITLE
Add joint LDL licence type to W3ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#467]
The Joint LDL Web Archiving licence has been approved by the LDLs and by LDIG (18/11/2015). Can the new licence be added to W3ACT, in addition to the existing licence templates. We will also need to add a Welsh version of this document which I will add once I have the translation. 
[Joint Web Archiving Access Licence - draft 2015 07 10 FS_PC_NJB (3).docx](https://github.com/ukwa/w3act/files/38763/Joint.Web.Archiving.Access.Licence.-.draft.2015.07.10.FS_PC_NJB.3.docx)

**Comment by anjackson** [comment]
Given how infrequently we add other licensing options, I think it doesn't make sense to implement #338, for now at least. However, under #360 we can support adding new licenses to the application directly (rather than as GUI process), starting with this new LDL license (which will also become the new default license).

**Comment by anjackson** [comment]
Okay, I've added the back-end template for this new license, but we'll need to add the  Joint LDL Web Archiving Licence as an option before it can be tested. Once this looks good, we can switch it to be the default.

**Comment by anjackson** [comment]
To test this, we need to deploy the code and then add a License that starts with the string 'Joint LDL Web Archiving Licence'. This is the signal used by the code to show the correct form. Once that's done and checked (from the licenses listing page), we can check the licensing workflow works okay.

**Comment by anjackson** [comment]
Tested, fixed a couple of issues, and now looking good. Set the new license to be the default one from now on.

**Comment by GilHoggarth** [comment]
@nicolabingham I'm unsure of the workflow for this issue, so could you please test this works satisfactorily on /actstage - https://www.webarchive.org.uk/actstage - and change the label to "2 - Testing and working on stage" for you're happy with this fix.

**Comment by GilHoggarth** [comment]
@nicolabingham The new licence has been added to /actstage as you can see at https://www.webarchive.org.uk/actstage/licences/list. Does this now complete this ticket? What about the Welsh version mentioned above?

**Comment by GilHoggarth** [comment]
Seems to work now https://www.webarchive.org.uk/actstage/licences/list, agreed @nicolabingham ?

**Comment by nicolabingham** [comment]
@GilHoggarth it does indeed.

**Comment by GilHoggarth** [comment]
Seen on live, closing.
