### ISSUE TITLE
Unticking flags not working

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#469]
When unticking flags in the Metadata tab and saving the target, the ticks are still there e.g. https://www.webarchive.org.uk/act/targets/29658. There were QA problems, but now the harvest is ok and the flags can be removed.

**Comment by niladreeb** [comment]
If all flags were removed they were not getting saved. Similar issue happened with the tags. Now they are working properly.

**Comment by niladreeb** [comment]
Tested on actstage and its working as expected.

**Comment by GilHoggarth** [comment]
Tested on /act and /actstage and seen to be working fine on both. Consequently closing issue.
