### ISSUE TITLE
Compare WCT/SPT and W3ACT data models and prepare for migration

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#472]
The WCT 1.6.1 data model is described [here](http://webcurator.sourceforge.net/docs/1.6.1/Web%20Curator%20Tool%20Data%20Dictionary%20%28WCT%201.6.1%29.pdf). The goal is to augment the W3ACT DB model so that we can include the important data from WCT/SPT.

Currently reviewing the WCT model and looking for gaps, of which there seem to be a few. Planning a staged process, by entity type.
- Organisations/Agencies
- Users/People
- Collections
- Subjects
- Targets
- Instances

Ideally needs to be done in a way that allows re-sync, or at least clarity over the gaps.

**Comment by chrispeacockbl** [comment]
Work so far is currently committed at http://git.wa.bl.uk/chrispeacock/wct-data-migration

**Comment by nicolabingham** [comment]
@chrispeacockbl I'm getting a 404 for this page http://git.wa.bl.uk/chrispeacock/wct-data-migration . Could you just check it please?

**Comment by chrispeacockbl** [comment]
Hi @nicolabingham, the link does work for me but I don't think I was clear about the content - this is a link to the source code (i.e. database script) so you're probably not interested in it. The instance of w3act running against the data isn't available yet.

**Comment by nicolabingham** [comment]
@chrispeacockbl ah ok, thanks for the update!

**Comment by anjackson** [comment]
Well, the migration is done now, so I think we can close this.!
