### ISSUE TITLE
Allow for the addition of different permission request templates in W3ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#474]
Currently when a licence request is sent from W3ACT, the website publisher recieves an introductory email containing a link to the licence form. The system only allows for one email template, the "General Permissions" template. We now need to send different permission letters, tailored to different situations, for example when asking for permission to *harvest* a website out of scope for NPLD, as opposed to asking permission for open access to a website crawled under LD. Also NLW need to send a Welsh version of the email. 
We should have the ability to create new email templates and couple them to licence forms - restricted to the Archivist role and higher.

**Comment by GilHoggarth** [comment]
@nicolabingham Closing this issue as I understand it will be resolved via #513.
