### ISSUE TITLE
Add filter for Targets that do not have a Licence 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#475]
Can we add further options to the Licence filter on the Targets List page https://www.webarchive.org.uk/act/targets/list?s=title so that we can see a list of Targets that do not have a licence.  
Ideally the filters should allow us to create three reports: 

1) All Targets that do not have a licence

2) All Targets with the Licence Status = Pending
3) All Targets with the Licence Status = Not Initiated

**Comment by GilHoggarth** [comment]
Would suggest that this filter page should use 'Any' not 'None' by default in drop down boxes (so 'None' can be used to specify targets with for example 'none' licences.

**Comment by nicolabingham** [comment]
@GilHoggarth Yes, 'any' would be more meaningful than 'none' in this context

**Comment by nicolabingham** [comment]
This has been implemented
