### ISSUE TITLE
QA status of search results

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#477]
When getting a list of search results the QA status is presented as QaIssue(null), id:190 
![untitled7](https://cloud.githubusercontent.com/assets/12541602/11557960/b68dca64-99a7-11e5-874f-36063a47aacc.png)

**Comment by GilHoggarth** [comment]
Tested on pre-release https://www.webarchive.org.uk/act2/targets/lookup?f=British+Academy+of+Film+and+Television+Arts and seen to be working.

**Comment by GilHoggarth** [comment]
Also checked on actstage - https://www.webarchive.org.uk/actstage/targets/lookup?f=British+Academy+of+Film+and+Television+Arts - seem to be working.

**Comment by GilHoggarth** [comment]
Seen on live, closing.
