### ISSUE TITLE
Crawl feed should only contain items in time scope

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#478]
To avoid having to filter the list in the client, it would make more sense if the crawl feed only contained items relevant to the current time.

Additionally - it would make sense to add simpler feeds that are just just of Target IDs or resource URLs, to avoid large feeds causing problems.

_UPDATE:_ Necessary fields:
- ID
- Title
- Seeds (from all fieldUrl.url)
- Depth
- Scope
- Ignore robots?
- Schedule (start_date, end_date, frequency)
- Watched?
- And watchedTarget.\*

**Comment by GilHoggarth** [comment]
@anjackson Is this issue about getting data out of W3ACT via the API and thus should have no effect on the GUI users of the system? If so, can you provide an example API URL for me to test on /act and /actstage please.

**Comment by anjackson** [comment]
Hey hey, should be e.g. here: https://www.webarchive.org.uk/act-ddb/targets/export/ld/daily

(but I note it does not work!)
