### ISSUE TITLE
Submit to DLS

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#479]
To aid the process by which the DLS picks up the Document Harvester eBooks the following system need to be implemented.

Each mets file produced by the Document Harvester is placed in a separate folder with the folder name being the mets filename with the .xml extension removed.

Whilst the folder is being created and the mets file is being copied could the suffix _ be added to the folder name. Once the copy of the file has been successfully completed can the “_“ be removed from the folder name.

So for the above example the folder would be initially called _enablingPC and after a successful copy it would be renamed enablingPC

Please check #476 for further details,

**Comment by anjackson** [comment]
Note URLs to METS are of this form: https://www.webarchive.org.uk/act-ddhapt/documents/41680/sip

**Comment by niladreeb** [comment]
Code snippet added to  download  the mets file in the server.

**Comment by anjackson** [comment]
That code doesn't seem to implement the 'download with this name then change the name' part of the spec? Also, recommend you test the file is not obviously wrong (not there or zero length) before submitting it.  Note you can use File.tempFile if you need a temporary file.

**Comment by niladreeb** [comment]
Changed to Java 7 compatible version and implemented the file naming code snippet.

**Comment by anjackson** [comment]
I've reviewed this and tweaked it. Looks good to go.
