### ISSUE TITLE
Multiple records for the same URL

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#480]
I've noticed there are three target records created on the same day for the same URL (26/11/2015, so it's not the data migration issue):

https://www.webarchive.org.uk/act/targets/32963
https://www.webarchive.org.uk/act/targets/32964
https://www.webarchive.org.uk/act/targets/32965

It shouldn't have happened so I wonder if it's a bug.

**Comment by anjackson** [comment]
I thought this might be a back-button problem. i.e. the user uses the back button to edit a new Target, rather than the edit button, and that accidentally created new items.

Except that that doesn't work on actstage, so it's not that.

Could you ask Brendan Power about how he did this? (and also confirm which one he wants and delete the others, of course).

**Comment by dorotawalker** [comment]
Will do. Thanks.

**Comment by dorotawalker** [comment]
@anjackson that's the reply from Brendan:

Dear Dorota,

I seem  to recall an issue with this site but did not know that it created three individual targets. As I remember it, the ACT tool was being very slow and sometimes unresponsive when saving, or trying to add to the revision log which necessitated closing and re-opening the tool to discover that the target had not saved. In this case I had to create the record from scratch and it eventually saved but when I checked it there was only one target record instead of the three that there are now. Apologies for the confusion and hope that this information helps in some way. 

Regards,

Brendan

**Comment by dorotawalker** [comment]
There are two more examples of duplicate target records. They were added by our new staff Helena Byrne and she said she did not realise she added it twice. There were not any problems with ACT when she was working on them:

https://www.webarchive.org.uk/act/targets/33940

https://www.webarchive.org.uk/act/targets/33941

**Comment by anjackson** [comment]
Okay, so it seems e.g. hitting save twice can maybe hit a problem/race condition where the record gets created after the second Save Action checks for existence of a record. Not sure how best to resolve this.

**Comment by chrispeacockbl** [comment]
Am I correct in saying that a target URL should be unique, i.e. that there ought never to be two targets containing the same URL? 

If this is the case, a database constraint should form the basis of the fix. An error would then occur in the above situation which the application could handle.

**Comment by nicolabingham** [comment]
There are situations where two or more Targets can have the same URL. For example if a new website appears at an existing URL. The user should be informed clearly if a Target record exists with the URL they want to enter. This requirement has been covered in #380, #316 and #417

**Comment by chrispeacockbl** [comment]
The fix made involves a table lock on the 'field_url' table. Please bear this in mind when testing: there might be a knock-on effect on any other applications that could be accessing this table at the same time that curators are creating targets.

**Comment by GilHoggarth** [comment]
@chrispeacockbl Can you state please how this can be tested, or at least how we can be confident the issue is fixed.

**Comment by chrispeacockbl** [comment]
It's a tricky one; I'd perhaps recommend just a regression test to see that everything functions as it should around this. In order to test this myself I had to temporarily change code to cause database concurrency problems. The alternative might be to have several sessions open at once on the edit page for a target and submit them as simultaneously as is possible, but this is likely to be more miss than hit. 

Ignore my comment on 28/4 about other applications accessing the table. I was ignorant to how the crawler acquires its targets.

**Comment by GilHoggarth** [comment]
Ah, interesting. Perhaps a script outside of W3ACT could be developed to analyse the data, to check if any duplicates have happened again. Testing by observation I suppose this might be called.

**Comment by anjackson** [comment]
This could be done in much the same way as the launcher script, downloading the feeds and performing sanity checks.

Or, we could add an API call that runs some self-checks on the database (which would be higher performance).

**Comment by chrispeacockbl** [comment]
Yes, good idea(s).

**Comment by GilHoggarth** [comment]
Not tested but awaiting further examples of issue.
