### ISSUE TITLE
Proxied URLs broken and rather too open in DDHAPT

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#481]
The DDHAPT PDF iframe (post submission) is not working, it seems due to a missing slash and some kind of cookie/login problem.

https://www.webarchive.org.uk/act-ddhapt/site/http:%2F%2Fcrawler03.bl.uk:8080%2Fwayback20150718231934%2Fhttps:%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F119178%2FACMD-BZP-Report.pdf/

Also, this allows any URL to be proxied - it should be stripped back to only proxy the required endpoint.

**Comment by chrispeacockbl** [comment]
I have a fix ready to commit but I need clarification of the original problem to be certain that I've addressed it.

**Comment by anjackson** [comment]
Looking at this again. I think before I was thinking about tightening this up so that instead of full URLs being passed to ```/site/```, i.e. ```/site/<absolute-url>```, it would be better to use ```site/<key>/<path>``` and map the ```key``` to an internal host (via the config file). e.g.

   /site/wayback/20150718231934%2Fhttps:%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F119178%2FACMD-BZP-Report.pdf

is proxied through to 

   http://wayback:8080/wayback/20150718231934/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/119178/ACMD-BZP-Report.pdf

Hm, in fact, now I think of it, that should use the existing ```act/wayback``` mapping!  The other case is the pdf2html transformed version, e.g.

   /site/pdf2html/20150718231934%2Fhttps:%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F119178%2FACMD-BZP-Report.pdf/

getting mapped to

   http://pdftohtml/convert?http://wayback:8080/wayback/20150718231934/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/119178/ACMD-BZP-Report.pdf

Note we could also use

   /site/pdf2html?ts=20150718231934&url=https:%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F119178%2FACMD-BZP-Report.pdf

if that makes encoding/decoding easier.

**Comment by anjackson** [comment]
Okay, tightened this up so it only allows pdf2htmlex URIs.
