### ISSUE TITLE
Deleting target records

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#484]
The 'Delete' button in the existing target records (in the edit mode) does not work. When clicked it redirects to the List Targets and the target record still exists. There is a target recor that should be deleted and can be used for testing purposes https://www.webarchive.org.uk/act/targets/33813.

**Comment by anjackson** [comment]
The system cannot delete the Target because it has Instances that need to be removed first: https://www.webarchive.org.uk/act/instances/listbytarget?t=33813

So, the system should give a meaningful error in this case, rather than silently failing.

**Comment by ldbiz** [comment]
Check for existing instances inserted with updated deletion error.

**Comment by GilHoggarth** [comment]
Tested on /actstage and seen to work. Couldn't delete target 21040 as instances exist but could and did delete new test target.

**Comment by GilHoggarth** [comment]
Not tested on live as would be removing data. Assumed to work.
