### ISSUE TITLE
Permission granted doesn't roll onto pages on subdomains

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#487]
Permission granted doesn't roll onto pages on subdomains. For example: 
https://www.webarchive.org.uk/act/targets/23191 Campaign for Real Ale (CAMRA): GE2015 is on http://ge2015.camra.org.uk/. In the UKWA Licence tab, there is information that there is already a licence for the main host, but it was only added after changing the scope of the main host's target record https://www.webarchive.org.uk/act/targets/5224 to 'All URLs that match this host or any subdomains.'.

The sign is still the red (-) for the individual page https://www.webarchive.org.uk/act/targets/23191.

**Comment by nicolabingham** [comment]
@dorotawalker is this issue affecting new Targets or is it just legacy Targets? #333 fixed the issue going forward but the data clean up is being taken care of separately.

**Comment by dorotawalker** [comment]
@nicolabingham that one is a legacy target and I haven't come across any more examples. I'll keep an eye on that.

**Comment by ldbiz** [comment]
Can be closed according to @nicolabingham.
