### ISSUE TITLE
'List targets' listing of target records not always in the same order

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#488]
When using the option of listing targets from the link 'List targets' and ticking a collection or subject, the list is presented differently every time. It's not alphabetical or ordered in any other way, so it's difficult to keep track. Could we arrange the target records alphabetically?

**Comment by anjackson** [comment]
n.b. there's been a lot of changes since this ticket was submitted, so the first step will be to verify that the problem still exists.

**Comment by nicolabingham** [comment]
This appears to have fixed the list, i.e. when filtering by Curator, Collection etc the order of the list (Targets > List) remains the same when logging out and in again and performing the same search. This fixity is helpful when the curator is performing a task on target records by collection, user etc. 

How is the list currently ordered please?

**Comment by chrispeacockbl** [comment]
Hi,

The list is ordered by target title (as denoted by the glyph against the title column header). It may be ordered ascending or descending by clicking the column header to switch.

**Comment by nicolabingham** [comment]
Thanks for this, I was wondering how the results are ordered, it is not alphabetical, is it for example, by the date the record was created or is it just random?

**Comment by chrispeacockbl** [comment]
Do you mean prior to this change? It will be random - kind of. It may be determined by the order in which the records are added.

**Comment by nicolabingham** [comment]
Thanks. It would be good if this list could be presented alphabetically but that may not be appropriate for this ticket?

**Comment by chrispeacockbl** [comment]
Sorry, I misunderstood - it should now, after this change, be alphabetical.

**Comment by nicolabingham** [comment]
Great, thank-you.

**Comment by GilHoggarth** [comment]
webarchive.org.uk/act-ddb updated with latest github code.

**Comment by nicolabingham** [comment]
This has fixed the Targets list from the Taxonomies (Collections) menu, e.g. https://webarchive.org.uk/act-ddb/targets/collectiontargets?s=title&collectionId=329 
Could we have alphabetical ordering for any of the results returned from filtering on this page please? https://webarchive.org.uk/act-ddb/targets/list?s=title 
For example, if the user applies any filters to search by (Curator, Organisation, Collection etc) the resulting list of Targets should be ordered alphabetically. I realise that we did not explain this clearly in the original ticket. Happy to discuss.

**Comment by chrispeacockbl** [comment]
Issue was only checked into a feature branch. I've now merged it into 'master' - please try it again.

**Comment by GilHoggarth** [comment]
Master branch redeployed, please test.

**Comment by nicolabingham** [comment]
OK, this is working as expected now.
