### ISSUE TITLE
Lists only 10 records at a time

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#489]
When going to target records using the path: Taxonomies > Collections > Targets they are presented 10 at a time and going down the list requires too many clicks. Adding extra filters would help e.g.:

Page size
Jump to (either page number or letter)

It is possible to get to the same targets list through 'List Targets', but there are listing issues (the order of appearance changes) and it is difficult to keep track. See #488

**Comment by ldbiz** [comment]
I've done the Page Size. Haven't looked at the Jump To yet.

**Comment by ldbiz** [comment]
The pagination request separated off into a new task, #504.

**Comment by GilHoggarth** [comment]
Page size seen to work at https://www.webarchive.org.uk/actstage/targets/collectiontargets?pageSize=5&s=title&collectionId=331

**Comment by GilHoggarth** [comment]
Seen on live, closing.
