### ISSUE TITLE
An additional QA status

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#490]
Could we please add a new QA status: 'QA issues, but OK to publish', which would cover known, but unsolvable QA issues? @nicolabingham could you please comment?

**Comment by ldbiz** [comment]
@nicholabingham confirmed the new status can be implemented as requested and relates to QA Status Type "Issues Noted".

**Comment by ldbiz** [comment]
Changes made, working in development; guidance needed on committing data changes with code, awaiting feedback from Gil.

**Comment by ldbiz** [comment]
Code committed and ready for testing, but still needs new data adding; will consult with AJ when he's back.

**Comment by GilHoggarth** [comment]
Checked on https://www.webarchive.org.uk/actstage/targets/21040/edit#overview and I don't see a new QA status of 'QA issues, but OK to publish'. @ldbiz please check if this correctly pushed into repo, or that my understanding is correct?!

Note milestone and low priority, not for immediate attention.

**Comment by ldbiz** [comment]
Has the data fix been run (createNewQAStatus.sql)? It's referenced in the commit above, but should probably have been explicitly noted here by me, in lieu of a standard process (see closed issue #522 ) to handle it.

**Comment by ldbiz** [comment]
I've added the needs-db-changes label; suggest we communicate the message that all issues with data fixes/db changes have that applied to make the migration process smoother.

**Comment by GilHoggarth** [comment]
Running script on actstage worked, and as a standalone single database data change, I've also run it on all w3act systems including live! So done, and thus closing.
