### ISSUE TITLE
Adding another crawl frequency

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#491]
Could we please add another crawl frequency, so we can address the target records, which have to be crawled more often for the special collections, but after they can 'go back' to the ususal frequency? For example the political parties during the campaign are crawled weekly with an end date, but after the election it's monthly. At the moment the curators/archivists have to go back to the target records and change them manually as there's a threat of not capturing them often enough.

**Comment by nicolabingham** [comment]
This is covered in #121
