### ISSUE TITLE
DDB Wayback erroring

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#493]
The DDB wayback service, on wayback.ddb.wa.bl.uk, displays via https://www.webarchive.org.uk/act-ddb/wayback/, however any query returns a 404 error (which feels more like a 500 error).

**Comment by anjackson** [comment]
This part is the problem, I think:

        <property name="accessPointPath" value="${wayback.url.prefix}/wayback/"/>

This should not be set to the url prefix, I believe. If should be:

        <property name="accessPointPath" value="${wayback.port}:wayback"/>

Not sure why this was set wrong - probably something I got away with under the Docker setup.

**Comment by GilHoggarth** [comment]
:( Nope. Made change in wayback.ddb.wa VM /opt/tomcat_instances/wayback/webapps/ROOT/WEB-INF/wayback.xml <property name="accessPointPath" value="${wayback.url.port}:wayback"/> but this hasn't made a change to the wayback query - still returns a 404.

**Comment by GilHoggarth** [comment]
Wayback now presenting calendar view, changes in:
* ddb.wa /opt/w3act-ddhapt/conf/prod.conf: application.wayback.url="http://wayback.ddb.wa.bl.uk:8080/wayback"
* wayback.ddb.wa /etc/sysconfig/tomcat-wayback WAYBACK_URL_PREFIX=https://www.webarchive.org.uk/act-ddb
* (firefox.bl.uk just proxies /act-ddb to ddb.wa:9000
