### ISSUE TITLE
URL with Invalid ID Crashes the App

### ISSUE THREAD

**Issue by ldbiz** [ukwa/w3act#499]
Example:

OK: 
https://www.webarchive.org.uk/actstage/roles/1

Unhandled exception:
https://www.webarchive.org.uk/actstage/roles/8

**Comment by ldbiz** [comment]
Committed: Issue [499](https://github.com/ukwa/w3act/commit/c7ba3bce0ab3efdce2e8398eab32c695479a3bc8)

**Comment by ldbiz** [comment]
Ah, also occurring for Organisations, Documents, ... etc.

**Comment by ldbiz** [comment]
[Committed](https://github.com/ukwa/w3act/commit/ac2ab433bf27ae157e1e242f0462dd1910a87e6e).

The View and Edit operations have had validation enhanced to catch incorrect identities. This won't catch other actions; there is likely more work to be done. 

Also, if this is revisited, we should look at implementing an override or hook; there is a lot of duplicated code here, and there must be a better way of doing it, but it was considered after discussion that the changes here were the pragmatic choice.

List of entities to be tested:

CommunicationLog
ContactPerson
CrawlPermission
Flag
Instance
MailTemplate
Nomination
Organisation
Permission
PermissionRefusal
Role
Subject
Tag
Taxonomy
User
WatchedTargets

**Comment by GilHoggarth** [comment]
Assigned back to Lee for testing.

**Comment by GilHoggarth** [comment]
Tested on live /act, seen to not NPE.
