### ISSUE TITLE
Modify column type from VARCHAR(255) for URL fields

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#508]
Documents are failing to be uploaded because the ```document_url``` and ```landing_page_url``` fields are ```VARCHAR(255)``` which is frankly ridiculous for URL fields. We need to:

* Scan for any other URL fields that are too short.
* Verify that we can convert them to ```TEXT``` without loosing any data.
* Update ```4.sql``` accordingly.
* Trial it on the BETA (DDB) system (with DB backups in place)

**Comment by chrispeacockbl** [comment]
watched_target also contained 3 URLs that have been expanded to 'text', these are document_url_scheme, login_page_url, and logout_url.

**Comment by anjackson** [comment]
Note that there's an error with the Downs script: https://github.com/ukwa/w3act/commit/000ab72d1d12ff107a798d39a61f7cb8a7d1f2c3#commitcomment-17380127

**Comment by GilHoggarth** [comment]
Database on new release of /act seen to have these updated 'text' fields.

**Comment by anjackson** [comment]
This should have been part of DB upgrades, so presumably that's how the changes made it there.

**Comment by GilHoggarth** [comment]
Changes seen in database, closing.
