### ISSUE TITLE
Execution error when browsing subject subcategories from Taxonomies

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#511]
An Execution error is generated when browsing subject subcategories. 

Eg. https://webarchive.org.uk/act-ddb/subjects/23

Taxonomies > Browse Subjects > Arts & Humanities > Architecture > Targets 

The same error is generated when selecting any subcategory under the top level subject terms. 

![execution_error](https://cloud.githubusercontent.com/assets/11210500/15287502/3925c1fe-1b5b-11e6-9c60-0c6cb9ba38fc.png)

**Comment by anjackson** [comment]
Can you take a look at this @chrispeacockbl?

**Comment by GilHoggarth** [comment]
Tested on https://www.webarchive.org.uk/actstage/targets/subjecttargets?s=title&subjectId=23 and seen to be working.

**Comment by GilHoggarth** [comment]
Seen on live, closing.
