### ISSUE TITLE
Presentation of time of last edit in Target records.

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#512]
This ticket is to seek clarification about how we present the 'last recorded time' an edit was made to a Target record to the user. I edited a Target record at 09:17 today and the Target shows the time of the edit as 08:17, i.e. an hour behind when the edit was made.
![time_error](https://cloud.githubusercontent.com/assets/11210500/15352378/c9f8a2b0-1cdb-11e6-8867-2e3d022468a0.png)

Could we check whether the recorded time of edits adjusts to BST and GMT please (I think this should be the case)? This is separate to the timestamps of the crawls which follow the UTC standard. Thanks.

**Comment by ldbiz** [comment]
Looks like a display bug. We need to do two things:

1. Verify the update time-stamp is being stored as UTC.
2. Correct the rendering issue here, and display according to the user's local time.

**Comment by ldbiz** [comment]
The correct way to implement 2 above, is arguably to convert a UTC string in javascript in the user's browser so we render according to the user's locale. However, results are apparently very browser-dependent, and @anjackson is happy with us using the application locale, as for the near future, that's pretty much the same thing in most cases.

**Comment by ldbiz** [comment]
Testing notes: the change made is small in actual code, but more significant in dependencies as they are used in various places, and the majority of time on this task has been spent checking there are no unintended consequences.

In particular, most displayed timestamps (not just the ones described here) will be changed. Additionally the methods affected are used to generate the exported data.

So testing needs to ensure the change only affects rendering (not data updates), and that the consequences for the export process are acceptable. e.g. in a later process do these timestamps get imported into something else, or get used for comparisons and filtering, and will the changes cause issues there?

**Comment by ldbiz** [comment]
@anjackson assigned for review

**Comment by GilHoggarth** [comment]
Addition and removal of a comment to the BAFTA target on /actstage, https://www.webarchive.org.uk/actstage/targets/3009, recorded the updated time as BST as recorded by Lee. That is, 15.18 recorded as 15.18.

Also tested on live /act and saw the recording of the UTC not BST value.

**Comment by GilHoggarth** [comment]
Seen on live, closing.
