### ISSUE TITLE
Add FAST subject headings to ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#514]
Can we update the FAST subject headings (https://webarchive.org.uk/act-ddb/fastsubjects/list) as per the attached list? 
[FAST_subject_headings.xlsx](https://github.com/ukwa/w3act/files/277388/FAST_subject_headings.xlsx)

**Comment by chrispeacockbl** [comment]
I can confirm that this will be just a data change.

**Comment by chrispeacockbl** [comment]
The attached zip file contains an SQL script and the new headings as a CSV file. To import the new headings, the CSV file must be placed on disc and the file path within the SQL script amended to point to the file, before backing up the table 'public.fast_subject' and then executing the SQL. 

[FAST subject headings.zip](https://github.com/ukwa/w3act/files/287036/FAST.subject.headings.zip)

Do we need to store these files within the project in the Git repository? If so, where?

**Comment by anjackson** [comment]
@chrispeacockbl could you also update the list in https://github.com/ukwa/w3act/blob/master/conf/fast-subjects.yml as this is the one that will be used when we deploy on production.  Thanks.

**Comment by chrispeacockbl** [comment]
@anjackson  Done.

**Comment by chrispeacockbl** [comment]
New attachment with some subject IDs corrected. 
[FAST subject headings.zip](https://github.com/ukwa/w3act/files/300570/FAST.subject.headings.zip)

**Comment by GilHoggarth** [comment]
Checked on test /act and number of FAST subjects seen to have increased to 170 as per Excel spreadsheet (previously FAST subjects numbered 89).

**Comment by GilHoggarth** [comment]
Seen on live, closing.
