### ISSUE TITLE
Verify the enableDDAPT switch still works

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#518]
It looks like we need to deploy W3ACT 2.0.0 but with the DDHAPT part entirely switched off/disabled. Can you verify that the existing switch (the enableDDHAPT configuration property) will still do the job (as it originally did)?

**Comment by chrispeacockbl** [comment]
Yes, the switch successfully enables / disables:

- Redirection of the home page to the Watched Targets page.
- Menu items for FAST subjects and Document Harvesting.
- Watched Target option when viewing or editing targets.
- Show DDHAPT Start Page option when creating, editing, or viewing users.

**Comment by GilHoggarth** [comment]
No evidence of DDHAPT that I can see on live, closing.
