### ISSUE TITLE
Relax URL validation to allow new TLDs to be crawled

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#519]
As new TLDs become more common, we need to relax the URL validation in ACT so that we can add Targets for websites on new TLDs. Currently only a limited set of TLDs are allowed. 
A recent example is .football. One of our curators would like to add a Target for http://brorarangers.football/ but ACT does not recognise the URL as valid.

**Comment by anjackson** [comment]
I'd like to sneak this into 2.0.0 if we can.

**Comment by chrispeacockbl** [comment]
Are you sure that we want to validate against a list of TLDs (I haven't looked at the code at this point, so this is an assumption) rather than just pattern match for a valid by definition domain name?

**Comment by anjackson** [comment]
That's the thing - we want to stop validating against a list of TLDs (if that's what's happening), because they can now be literally anything.

**Comment by anjackson** [comment]
Can we sneak this in, @chrispeacockbl? or is it too fiddly?

**Comment by chrispeacockbl** [comment]
The problem was that the version of Apache commons-validator that was in use had a bug / was too restrictive with its domain name matching. Patterns were already being used to check the URL rather than a hard list.

**Comment by GilHoggarth** [comment]
Checked on test /act and seen to allow example URL above.

**Comment by GilHoggarth** [comment]
Seen to work on live.
