### ISSUE TITLE
Control of Upgrade Process

### ISSUE THREAD

**Issue by ldbiz** [ukwa/w3act#522]
It would be useful for us to have a standard process to handle data/script one-offs that need to be run when we build. Along the lines of Evolutions, but for stuff that doesn't fit in that.

**Comment by ldbiz** [comment]
I've created the task as we are relying a bit too much on memory and emails to make sure stuff doesn't get missed. If there's already a mechanism to handle it, please point me to it, I'll take a look-see.

**Comment by GilHoggarth** [comment]
Not specifically a W3ACT development ticket so closing. Suggest putting this sensible request on whiteboard backlog.
