### ISSUE TITLE
Open UKWA Licence template NPE

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#524]
As an archivist (which is the key role for this feature), attempting to view the Open UKWA Licence (2014-) template https://www.webarchive.org.uk/act/ukwa/license/view/295 from https://www.webarchive.org.uk/act/licenses produces a Java NullPointerException error.

**Comment by anjackson** [comment]
I believe this is resolved?

**Comment by GilHoggarth** [comment]
Checking the example URL in the description suggests otherwise, the page still NPEs.

**Comment by GilHoggarth** [comment]
Tested on /act-ddhapt, seen to not NPE.

**Comment by GilHoggarth** [comment]
Tested on live /act, seem to not NPE.
