### ISSUE TITLE
Permission request has disappeared from system

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#526]
We sent a permission request for this Target: https://www.webarchive.org.uk/act/targets/44030#licensing at 14:40 today. The Licence Request Status is still 'Not Initiated' whereas it should be 'Pending', the UKWA Licencing tab has a green (+) whereas it should be a yellow (~) and we can't see the permission request on the system - we should see it in Archivist Tasks - > Crawl Permissions -> Pending

**Comment by anjackson** [comment]
Weird, no trace of the permission. Any idea if they accepted/rejected?

**Comment by anjackson** [comment]
@GilHoggarth can you look for logs from W3ACT for this timeframe?

**Comment by GilHoggarth** [comment]
@nicolabingham Can you clarify please if other crawl permissions are being processed correctly? I.e., does this particular target have this issue or are all/most/some/any others also showing the same lack of action?

**Comment by nicolabingham** [comment]
@anjackson its a bit wierd. I don't think the permission was sent out. Helena completed the permission form (the contact form in the UK Licencing tab) and hit save. At this point the UK Licencing tab incorrectly changed to a green +ve. In the Archvists Tasks - > Crawl permissions there was no, and is no record of a crawl permission.

**Comment by anjackson** [comment]
Okay, so I've change the licensing tab so that only sysadm can directly change the licensing, just to rule that our while we try to work out what happened.

As we can't reproduce this, I think we may have to just keep an eye on things and wait to see if it happens again?

**Comment by GilHoggarth** [comment]
@anjackson @nicolabingham What action should we have for this issue? If it can't be reproduced then should it just be closed?

**Comment by nicolabingham** [comment]
I can create the Target on ddb and test it there.

**Comment by nicolabingham** [comment]
I set up the Target on ddb and went through the permission process. Everything is working as expected, i.e. the permission status is correct and the communication log can be seen on the system. Closing ticket.
