### ISSUE TITLE
NPLD tab shows different results in edit/view mode

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#529]
I added a couple of .eu domains to see if they were UK in scope, by server location. 
When editing the Target record (https://www.webarchive.org.uk/act/targets/44079) the NPLD symbols change randomly. The screen shots below were taken during the process of completing the Target record. 
![npld_error](https://cloud.githubusercontent.com/assets/11210500/16578434/748bf958-4292-11e6-8aff-0dd999391fa7.png)
![npld_error2](https://cloud.githubusercontent.com/assets/11210500/16578435/75dad478-4292-11e6-8efc-c9aafdb17688.png)
![npld_error3](https://cloud.githubusercontent.com/assets/11210500/16578437/772c9b36-4292-11e6-8c7d-ac9e1218f8f5.png)
![npld_error4](https://cloud.githubusercontent.com/assets/11210500/16578439/78f823a4-4292-11e6-9b69-03380e5301f5.png)
![npld_error5](https://cloud.githubusercontent.com/assets/11210500/16578440/7a8f79d8-4292-11e6-9648-ccdf20ec93a7.png)
![npld_error6](https://cloud.githubusercontent.com/assets/11210500/16578442/7ca888a4-4292-11e6-8655-4ff5f480e887.png)

**Comment by anjackson** [comment]
Is this just when editing? ie is the status stable when viewing the entry?

**Comment by nicolabingham** [comment]
yes, status is stable when in view mode.

**Comment by chrispeacockbl** [comment]
Would you like me to take this one @anjackson ?

**Comment by anjackson** [comment]
Oh go on then, though if it turns out to be nasty, we can leave it 'till later.

**Comment by chrispeacockbl** [comment]
Also made changes so that the instant checks when editing the target now work, although it's not perfect as all 3 statuses are set in unison to the overall scope check result.

**Comment by GilHoggarth** [comment]
@nicolabingham Please test on /act-ddhapt

**Comment by nicolabingham** [comment]
Tested and working on ddb

**Comment by nicolabingham** [comment]
working on /act/
