### ISSUE TITLE
Only check top-level licences when building By/OA feeds

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#530]
When building the by-permission feed, only check licence/NPLD status of 'top-level' Targets (not inherited ones) as this is very slow and unnecessary, as the results are transformed into SURTs that describe the scope anyway.

Also adding a OA feed that includes all licenced Targets, even NPLD ones, as this is what we need for open access Wayback.

**Comment by anjackson** [comment]
Done in 3fec490

**Comment by GilHoggarth** [comment]
@anjackson to test on /act-ddhapt

**Comment by anjackson** [comment]
@GilHoggarth you mean /act-ddb, right?

**Comment by GilHoggarth** [comment]
Yes (so it doesn't look like you're waiting for me to reply...)

**Comment by anjackson** [comment]
Hmm, so, the functionality requested in this ticket has been implemented, but I'm not convinced the outcome is exactly what we need. I'll follow-up with a new ticket under 1.2.2

**Comment by anjackson** [comment]
What we have is sufficient for the collections browser/licensed content in Wayback. See e.g. $ACT_SERVICE/api/crawl/feed/oa/all

**Comment by anjackson** [comment]
Tested and working.
