### ISSUE TITLE
Additional changes to DDHAPT UI and SIP for eBooks

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#531]
We need a few more fields for eBooks, as specified in the attached document.

[20160317ebooksloadspec(3)_MarcXMLmapping.docx](https://github.com/ukwa/w3act/files/352315/20160317ebooksloadspec.3._MarcXMLmapping.docx)

**Comment by anjackson** [comment]
@chrispeacockbl if you can take a look at this too, as we'll need to do some testing with this fairly soon.

**Comment by chrispeacockbl** [comment]
@anjackson Files are checked in now if you would like to look at the diffs. There are DB changes, placed in 4.sql - I don't know whether this is correct or whether a new Evolutions file is needed.

**Comment by anjackson** [comment]
@chrispeacockbl given we've released 1.2.1, can you pop the new stuff into a ```5.sql``` please?

**Comment by chrispeacockbl** [comment]
@anjackson Done.

**Comment by anjackson** [comment]
Unfortunately, we missed some of the fields. @nicolabingham can we ask Jennie to make it clear exactly what fields are missing.

**Comment by chrispeacockbl** [comment]
Code wasn't merged with master - doing that now.

**Comment by chrispeacockbl** [comment]
[EnhancedBookMetadataFormSketch1.pdf](https://github.com/ukwa/w3act/files/415343/EnhancedBookMetadataFormSketch1.pdf)
[EnhancedBookMetadataFormSketch2.pdf](https://github.com/ukwa/w3act/files/415342/EnhancedBookMetadataFormSketch2.pdf)
