### ISSUE TITLE
API method required to provide paged target list

### ISSUE THREAD

**Issue by chrispeacockbl** [ukwa/w3act#532]
The API methods currently provided in W3ACT mean that the new UKWA-UI, aka the Collections Browser, has to perform a separate web service call to obtain each target. We need a means to obtain a list of targets in one call, with paging - that is, the start position and length of the list must be specifiable.

**Comment by anjackson** [comment]
Works okay,  but note moved target IDs API, so this may affect your code @chrispeacockbl for the UKWA Solr instance. Also, the handling of Subjects has been changed to behave more like Collections, so handling of that may also need to change.

**Comment by chrispeacockbl** [comment]
@anjackson Everything still works OK for loading the Solr index.

**Comment by anjackson** [comment]
Thanks @chrispeacockbl
