### ISSUE TITLE
Add filter to Crawl Permissions list 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#533]
Could we add a filter ("Filter by Agency") to this page https://www.webarchive.org.uk/act/crawlpermissions/list, Archivist Tasks > Crawl Permissions > Permissions Queue ?
![crawl_permission_filtering](https://cloud.githubusercontent.com/assets/11210500/16798821/cffc66ac-48e5-11e6-95cf-5550cb31a60b.png)

This page shows a list of permission requests queued by ACT users. Archivists check the permissions and then send them out from this page. Each Archivist reviews their 'own' users permission requests but currently there is no easy way to distinguish which crawl permission requests have been initiated by which agency's users. 

This might also work if we added an 'Agency' column to this page but the filter would be preferable.

**Comment by anjackson** [comment]
I added this to the 2.0.7 milestone @min2ha - hope that's okay.

**Comment by nicolabingham** [comment]
@min2ha @anjackson this now looks like I expectd on https://beta.webarchive.org.uk/act/ but I can't see a 'submit' or 'enter' button to run the filter, after selecting the agency from the drop down menu.

**Comment by nicolabingham** [comment]
@min2ha @anjackson OK so you hit Search after running the query. That's fine. thanks.

**Comment by nicolabingham** [comment]
Happy to mark as done.
