### ISSUE TITLE
Add Welsh Translation of Joint LDL Web Archiving Licence

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#534]
Could we add a Welsh translation of the Joint LDL Web Archiving Licence (2016-) so that website publishers recieving the licence have an option to view it in Welsh? The licence should open in the recipient's browser with the default, English version but with a button at the top of the page displaying the text 'Cymraeg'. Clicking on this button will take the user to the Welsh version. 

[Joint Web Archiving Licence (Welsh_Final).pdf](https://github.com/ukwa/w3act/files/361244/Joint.Web.Archiving.Licence.Welsh_Final.pdf)

This ticket is related to #467

**Comment by anjackson** [comment]
@chrispeacockbl I was hoping we could make a modified License page that just uses JavaScript to switch to the Welsh version of the text? i.e. both languages in the page, but only one displayed at once, with a simple *Cymru/English* toggle?

**Comment by chrispeacockbl** [comment]
@nicolabingham I've spotted a couple of missing bits in the translation - there's the Postal Address label and text for the Submit button. Please do you have the Welsh text for these?

**Comment by nicolabingham** [comment]
Thanks @chrispeacockbl 
cyfeiriad post = postal address
cyflwyno = submit

**Comment by chrispeacockbl** [comment]
@nicolabingham Thanks.

**Comment by chrispeacockbl** [comment]
This is done as per the spec, but note that there is other text that appears when the form fails to validate and once it is submitted, that is still only in English. When validation fails and the form reappears, currently the selected language is not remembered, but this is perhaps not so much of a priority until the validation messages are translated.

**Comment by chrispeacockbl** [comment]
Note for deployment: there is an amendment to the application configuration file, present in 'prod.conf.template'.

**Comment by anjackson** [comment]
Now live, but should be reviewed.
