### ISSUE TITLE
Error message when editing seeds in DDHAPT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#537]
Jennie would like to edit the starting seed of one of her Watched Targets, Arts Council England, https://webarchive.org.uk/act-ddb/targets/36038 however when editing the seed and saving the record, an error message is returned. Could you take a look please? 
![error_msg](https://cloud.githubusercontent.com/assets/11210500/16988313/edc8ac2a-4e87-11e6-9dcc-9fbb7234ae6d.png)
ed.

**Comment by anjackson** [comment]
Could you take a look  at this please, @chrispeacockbl - I'm suspecting we're missing a few DB changes on the act-ddb system following the modifications to the mail template system?

**Comment by chrispeacockbl** [comment]
Yes. Is it possible for me to connect to the database with my own pgAdmin?

**Comment by anjackson** [comment]
It's probably not set up for remote connections right now, but maybe @GilHoggarth can do so?

**Comment by GilHoggarth** [comment]
@chrispeacockbl  Couldn't you just connect directly, ie how is already set up? Andy or Lee should be able to provide the access details.

**Comment by chrispeacockbl** [comment]
It looks like the Play Evolution hasn't been run on DDHAPT. To compound the issue, some of the new columns for this release have already been created somehow in the database. This will mean backing up the 'document' table, applying the Evolution, and restoring the table backup.

**Comment by anjackson** [comment]
As far as I know, it's not considered a good idea to let the Evolutions thing run itself on (near) production systems. 2/3/4.sql etc. should have been run manually, I think.

**Comment by chrispeacockbl** [comment]
The thing is that the DB seems to indicate that the last evolution run was 3.sql, however some columns from 4.sql are present, preventing the latest evolution from being run.

**Comment by chrispeacockbl** [comment]
This should be fixed now, with plenty of help from @GilHoggarth. 

We removed the document table columns that were present and shouldn't have been, re-ran the evolution, and then re-added the content of the removed columns for the 6 rows that had content.

**Comment by chrispeacockbl** [comment]
Forgot say - no software change necessary.

**Comment by anjackson** [comment]
@nicolabingham this should work okay now. Can you test?

**Comment by nicolabingham** [comment]
tested on ddb. working fine now (no error message when editing the starting seed).
