### ISSUE TITLE
DDHAPT pulling in documents external to the Watched Target

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#539]
There have been occasional instances when DDHAPT has followed links offsite from the Watched Target to retrieve documents, returning them as belonging to the WT. 

For example: https://www.webarchive.org.uk/act-ddb/documents/524554.  The WT is the Office of National Statistics, https://www.ons.gov.uk/, but it has pulled in an external link at the bottom of the page on the Forestry Commission site, 'Timber Price Indices' http://www.forestry.gov.uk/pdf/tpi201503.pdf/$FILE/tpi201503.pdf 

Similarly, this document: https://www.webarchive.org.uk/act-ddb/documents/540796/, for the WT, Local Government Association, http://www.local.gov.uk/, has pulled in a document on the Public Health England site https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/321503/CBOHMaindocumentJUNE2014.pdf 

Is there anything that can be done to refine this behaviour or is it something that we will have to live with?

**Comment by anjackson** [comment]
Yes, this can be modified as it's part of the crawler configuration. I'll modify the new document harvesting crawl engine to avoid pulling in off-site documents, but note that this may prevent the system from pulling in legitimate documents that are held on other servers.
