### ISSUE TITLE
Change email subject heading in acknowledgement emails

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#540]
The subject line of the acknowledgement emails received by website publishers when they have completed an online licence form reads "British Library UKWA Licence Received", see screengrab below. This means that permissions sent by NLS and NLW look as if they are coming from the British Library (although technically coming from a BL administered system.... is this where the problem lies..?)

It should read "UKWA Licence Received" 

![email_subject_heading](https://cloud.githubusercontent.com/assets/11210500/17097673/a8732402-5256-11e6-8628-93e13ab2d793.png)

**Comment by GilHoggarth** [comment]
Assigned back to Nicola for testing.

**Comment by nicolabingham** [comment]
working on act-ddb

**Comment by nicolabingham** [comment]
working on /act/
