### ISSUE TITLE
Edit existing email templates on ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#542]
So, in #513 we added some email templates to the system. Following feedback from the users, I need to replace 3 of them to include welsh translations and some fix some typos. 
They are on the Mail Templates page https://www.webarchive.org.uk/act/mailtemplates (Archivists Tasks > Mail Templates) and appear in the new crawl permissions form in the drop down menu. 
![perreqtem](https://cloud.githubusercontent.com/assets/11210500/17137243/079952f4-5332-11e6-9230-cf2a2705c738.png)

NLW Open Access Permission Request (LD Content) should have the text in this document:
[NLW_LD_openAccess_w_Welsh_FINAL.docx](https://github.com/ukwa/w3act/files/383765/NLW_LD_openAccess_w_Welsh_FINAL.docx)

NLW Permission to Harvest (non NPLD Content) should have the text in this document:
[NLW_nonUK_non_LD_w_Welsh_FINAL.docx](https://github.com/ukwa/w3act/files/383763/NLW_nonUK_non_LD_w_Welsh_FINAL.docx)

The Acknowledgement template
![acktem](https://cloud.githubusercontent.com/assets/11210500/17137343/9e4edeee-5332-11e6-8ab5-3909651597b3.png)
NLW Acknowledgement should have the text in this document
[NLW_acknowledgement_w_Welsh_FINAL.docx](https://github.com/ukwa/w3act/files/383761/NLW_acknowledgement_w_Welsh_FINAL.docx)

**Comment by GilHoggarth** [comment]
Assigned back to Nicola for testing.

**Comment by nicolabingham** [comment]
tested on act-ddb, working ok now.

**Comment by nicolabingham** [comment]
seen to be working on /act/
