### ISSUE TITLE
Error when accessing QA Wayback

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#543]
We have an Execution error message when accessing any target instances in QA Wayback. This was first noticed on 28/07/16
![execution_exception](https://cloud.githubusercontent.com/assets/11210500/17289129/22b5041e-57d0-11e6-9774-7cec57f0e72c.png)

**Comment by anjackson** [comment]
Hum, looks like QA Wayback has fallen over. I'll ask @GilHoggarth to take a look.

**Comment by GilHoggarth** [comment]
I suspect it was more the fault of some idiot who forgot to restart QA wayback.
