### ISSUE TITLE
Report creation page missing

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#544]
https://www.webarchive.org.uk/act/reportscreation/targets doesn't exist. Previously @nicolabingham used this to help with the monthly stats.

**Comment by anjackson** [comment]
This should be fixed in 1.2.1.

**Comment by anjackson** [comment]
Yup, /act-ddb/reportscreation/targets looks good.

**Comment by nicolabingham** [comment]
seen working on /act/ now.
