### ISSUE TITLE
Update FAST subject headings to the latest list

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#559]
There should be an updated list of FAST subject headings in the code base. This should be deployed on act-ddb.

**Comment by chrispeacockbl** [comment]
@anjackson What's involved here, is this simply a deployment task? Does it relate to the subject headings created in #514 ?

**Comment by anjackson** [comment]
Yes @chrispeacockbl, it's related to that. The latest list of FAST headings is here: 
[UKWASubject_TermsJG_A_Z.xlsx](https://github.com/ukwa/w3act/files/657012/UKWASubject_TermsJG_A_Z.xlsx)

This list supersedes the current list. Any unchanged headings should be retained (as they may be referenced from elsewhere), but there may be deletions as well as additions, IIRC.

**Comment by chrispeacockbl** [comment]
@anjackson I've found a problem with the new data, I'm afraid. There are repeated FAST IDs:

Education, Preschool	        fst00903161
Schools				fst00903161
Special education		fst00903161
Vocational education	fst00903161

The existing record is 'Education, Preschool', should this take priority?

**Comment by anjackson** [comment]
We'll have to raise these with Jennie to see what the correct resolution is.

**Comment by nicolabingham** [comment]
@anjackson I will contact Jennie (unless you have mentioned it to her already?)

**Comment by chrispeacockbl** [comment]
@nicolabingham It's OK thanks, it's in hand. Jennie is going to check and update the list.

**Comment by nicolabingham** [comment]
@chrispeacockbl thanks!

**Comment by chrispeacockbl** [comment]
This was quite a long and convoluted process. I could document the details here if that's appropriate, or I could even spend some time coming up with an automated means to do this in future (as clearly there will be a need to do it again in future)?
