### ISSUE TITLE
Check current 2.0.7 issues are done

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#583]
The current [2.0.7](https://github.com/ukwa/w3act/milestone/29) release has been delayed by teh delays in document harvester testing. We need to push on, so can you check all those issues apper to be done, and ask @nicolabingham if she's happy with any that require her feedback? The latest version is deployed on https://beta.webarchive.org.uk/act/ so that can be used for evaluating these minor issues.

Assuming all is well, we can tag this version and roll it out, so we can move on to 2.1.0.

**Comment by min2ha** [comment]
Okay, it shouldn't be a problem, because all isues are marked as **"1 - Ready to test on stage"**. I just need some **login** and **password** to login to https://beta.webarchive.org.uk/act/ :)

**Comment by anjackson** [comment]
You can get the details from @GilHoggarth

**Comment by GilHoggarth** [comment]
@min2ha These details are recorded in ss (secret server) - you should have access to that.

**Comment by anjackson** [comment]
Thanks @min2ha this all looks good to me. Agreed?

**Comment by min2ha** [comment]
Yes @anjackson , agreed :)

**Comment by anjackson** [comment]
Okay, I'll tag 2.0.7 and send it off to build on Docker Hub then...
