### ISSUE TITLE
URL validation rules in ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#585]
There is a bug, we think in adding seeds with alternative TLDs to ACT. e.g. https://mysticalmoments.shop/ and https://emshort.blog/ or https://worldrugbymuseum.blog/. ACT returns the error message "The URL is not valid". These are UK websites that have been selected by curators. Thanks.

**Comment by ldbiz** [comment]
![image](https://user-images.githubusercontent.com/16339290/46417673-13cfc880-c722-11e8-85ea-1d63578686b7.png)

**Comment by ldbiz** [comment]
Dev allocation priority to be set by @nicolabingham  as product owner.

**Comment by anjackson** [comment]
Hm, okay. If you ignore the error message, can you still [Add Target]?

**Comment by anjackson** [comment]
The problem appears to be [this regex](https://github.com/ukwa/w3act/blob/ae2fc7c329a21b440b020b44a6b00bf4bc1a3a8f/app/uk/bl/api/Utils.java#L765), which seems overly picky.

**Comment by ldbiz** [comment]
Check this page for an explanation of a similar looking regex (probably the source for ours)?

https://www.mkyong.com/regular-expressions/domain-name-regular-expression-example/

**Comment by ldbiz** [comment]
Is there a TLD field in the w3act db (assuming no config property)? I'm starting to think it is a lookup issue, rather than regex.

e.g. .blog and .shop don't work but registered 4 and more letter TLDs do: .academy and .auto

![image](https://user-images.githubusercontent.com/16339290/46421235-9e67f600-c729-11e8-92f7-62470622a1e2.png)

**Comment by nicolabingham** [comment]
I've downgraded this as UI takes precedence at the moment due to limited dev time.

**Comment by crarugal** [comment]
https://www.pissarro.art/ also fails

**Comment by jasonwebber-bl** [comment]
Our new phd guy, Liam has a blog that can't be added either: https://lastposts.blog/

**Comment by anjackson** [comment]
I think this is enforcing three-section domain names?

https://github.com/ukwa/w3act/blob/ae2fc7c329a21b440b020b44a6b00bf4bc1a3a8f/app/uk/bl/api/Utils.java#L764-L767

**Comment by anjackson** [comment]
Okay @min2ha I've added all the valid URLs in this ticket to the automated test, so we should know we're good when the tests pass. They current disallow `http://www.nicelife` and allow `https://emshort.blog/` which I think makes sense.

**Comment by emacglone** [comment]
Hello, just noting that Trevor Thomson has reported this URL: http://www.jupiterrising.art/ isn't being accepted either.

**Comment by min2ha** [comment]
Thanks @anjackson 
everybody can test bugfixes at https://beta.webarchive.org.uk/act/about

**Comment by nicolabingham** [comment]
Thanks @min2ha 
Could you test this please @crarugal ?

**Comment by crarugal** [comment]
Thanks @min2ha, cool will do @nicolabingham

**Comment by crarugal** [comment]
Hi all, these are the URLs I tried and they were all accepted:

http://nic.horse/
http://nic.beer/
https://art.art/
https://get.blog/
https://www.domain.luxury/
https://mysticalmoments.shop/

thanks @min2ha

**Comment by emacglone** [comment]
Hello,
I'm having problems with this URL: https://www2.gov.scot/. I agreed to set this to collect next week, but ACT will not validate it (it had been before).

**Comment by HelenaByrne** [comment]
HAving issues with this website and I think it is the same issue - [https://www.massaction.charity]

**Comment by crarugal** [comment]
Another example: https://intrl.sport/

![image](https://github.com/ukwa/w3act/assets/18530934/986cca27-de30-4db3-b8fd-6e0b085643d9)

**Comment by anjackson** [comment]
Something must have gone wrong during testing of the original fix for this, as there were additional (unnecessary) URL validation checks in place that were breaking submission.

**Comment by anjackson** [comment]
Okay, deployed a patched version on BETA: https://beta.webarchive.org.uk/act

Can someone check it seems to work as expected now?

**Comment by HelenaByrne** [comment]
Hi Andy, I was able to create a record with that URL on Beta: https://beta.webarchive.org.uk/act/targets/169786

**Comment by anjackson** [comment]
2.3.5 live as of last night.
