### ISSUE TITLE
ACT sending blank permission emails

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#592]
Over the past couple of days we have noticed that the permission emails generated from ACT are blank. We don't know when this first started but we'll try and trace it.  We’ve tested this by sending permission requests to our own email addresses and found the same issue. 
Examples of the blank emails include the 8 messages sent in the screengrab here: 
![blank_permission_examples](https://user-images.githubusercontent.com/11210500/41712587-cfa6011e-7542-11e8-88f0-ca93008e9fdc.png)

**Comment by nicolabingham** [comment]
Comment from Carlos: the last permissions granted was from http://johnmoloney.co.uk/ | 14/06/2018 15:34)
so I think the blank emails may be related to Saturdays server downtime.

**Comment by crarugal** [comment]
ACT is sending out blank emails again, this was recently noticed when a batch of permissions was released 31-03-2020. However, as many permissions had been in the queue for some time, it's possible that this issue could have been present since the beginning of March, or perhaps earlier.
