### ISSUE TITLE
ACT edit target NPLD Scope for No LD Criteria Met

### ISSUE THREAD

**Issue by HelenaByrne** [ukwa/w3act#596]
![image](https://user-images.githubusercontent.com/43820507/48423039-c2225100-e757-11e8-8aaf-626c3f128685.png)

I tried to tag a target with the No LD Criteria met but it wouldn't let me save it. It gave this message: 
One of the checks for NPLD permission has been passed. Please unselect the 'No LD Criteria Met' field and click Save again

It was manually passed but I removed that and saved it and the NPLD symbol was red but I can't save the check box for No LD criteria met, which is important as someone reviewing it might think that it needs to be manually adjusted rather than out of scope.

Target link: https://www.webarchive.org.uk/act/targets/82673#crawlpermission

**Comment by HelenaByrne** [comment]
I had another look at this but issue is still standing.

**Comment by anjackson** [comment]
Hm, odd. Relevant code is here:

https://github.com/ukwa/w3act/blob/ae2fc7c329a21b440b020b44a6b00bf4bc1a3a8f/app/controllers/TargetController.java#L1634-L1643

**Comment by anjackson** [comment]
What appears to be happening is that this site now meets one of the automated NPLD checks, e.g. UK Hosting. But the way the system is implemented means that this is not shown properly. The checks are updated, but the form value is not.  We could use:

    theForm = theForm.fill(updatedObject)

This is also related to the need to update the NPLD fields, i.e to re-run the following checks for all Targets periodically:

https://github.com/ukwa/w3act/blob/ae2fc7c329a21b440b020b44a6b00bf4bc1a3a8f/app/models/Target.java#L2416-L2421

i.e. this is related to #594 and #602.

**Comment by crarugal** [comment]
Looks like issue has been fixed, I tested it on another target with similar criteria: https://beta.webarchive.org.uk/act/targets/69565#crawlpermission. The "No LD Criteria" can be checked and unchecked and either state will persist.
![image](https://user-images.githubusercontent.com/18530934/56959947-26d73980-6b47-11e9-85fc-be7ac89efa4b.png)

![image](https://user-images.githubusercontent.com/18530934/56959952-29d22a00-6b47-11e9-8062-fb217886982f.png)
