### ISSUE TITLE
WCT to ACT Migration Issue UK General Election Collection 2015

### ISSUE THREAD

**Issue by HelenaByrne** [ukwa/w3act#599]
This is a screenshot of the UK General Election Collection 2015 in ACT 
![image](https://user-images.githubusercontent.com/43820507/48852530-7c900480-eda5-11e8-9312-76c941330a56.png)

All the targets migrated over are also published to the website: https://www.webarchive.org.uk/en/ukwa/collection/60

![image](https://user-images.githubusercontent.com/43820507/48852569-929dc500-eda5-11e8-84c3-f049c37eb688.png)

**Comment by anjackson** [comment]
Er, sorry, but what's the problem?

**Comment by HelenaByrne** [comment]
Hi Andy,
The subsections with no description are migrated from WCT and were made publicly available. @crarugal just unpublished them so they will disappear from the public view tomorrow. This is maybe a question for @nicolabingham, do we check if the websites tagged into those subsections are in the main subsections and then delete them?

**Comment by nicolabingham** [comment]
Hi Helena, I’m not sure I totally understand the problem. Is it that the wrong sub-sections appear under the 2015 collection in W3ACT? I think this is one that will require some tidying up on our part I’m afraid. But we can always get Joan to help.

**Comment by nicolabingham** [comment]
@HelenaByrne @crarugal are any other collections affected in this way?

**Comment by HelenaByrne** [comment]
@nicolabingham I think the GE 2015 collection was the only one that existed on both systems that had subsections.

**Comment by nicolabingham** [comment]
I will edit the sub-categories directly in ACT
