### ISSUE TITLE
w3act API returning "Pending" records as valid for Open Access?

### ISSUE THREAD

**Issue by ldbiz** [ukwa/w3act#600]
This appears at first investigation to be the cause of ukwa/ukwa-ui#212

Open access to Wayback resources with "Pending" license. The status (or lack of check on it) appears to be derived from one of the management scripts which is calling out to the w3act API for its results.

**Comment by anjackson** [comment]
I think this is the same underlying problem as #601.

**Comment by anjackson** [comment]
Ah, no it's a different thing. The hard-coded WCT whitelist for some reason included `http://sites.google.com`. Removing.
