### ISSUE TITLE
Manually assign NPLD criteria to sites migrated from WCT to ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#602]
c. 11,000 Targets have come across from WCT and have not had the NPLD criteria updated, despite the fact that most of them are on a UK TLD. Is it possible for these Targets to be manually updated (or by some scripting magic) to meet the criteria if we supply a list of the Targets? Currently they are not being crawled as they don't meet the NPLD criteria.

**Comment by anjackson** [comment]
Should be resolved by #594
