### ISSUE TITLE
Need to search aliases when looking up Targets

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#606]
My original [http://digital-archiving.blogspot.co.uk/ record](https://www.webarchive.org.uk/act/targets/82288) collided with one from @jasonwebber-bl because when lookup up the `co.uk` alias the Target didn't show up because this was down as an alias rather than a secondary seed.

Also, a related problem is that downstream processing ignores the alias field. Both the crawls and the generation of metadata like the OA allow list.

**Comment by anjackson** [comment]
This only works because I duplicated the alias as a seed:

https://www.webarchive.org.uk/act/targets/lookup?f=http%3A%2F%2Fdigital-archiving.blogspot.co.uk%2F

**Comment by min2ha** [comment]
@anjackson not sure who is involved in testing of this bugfix
(BTW it may take some time to get on beta)

**Comment by anjackson** [comment]
I can be the tester for this.

**Comment by crarugal** [comment]
This looks like it is fixed, there are roughly ~500 targets that have aliases, which is stored within the "synonyms"  field in the "target" table. Searching for those synonyms in beta works, but does not work in current production.

Seaerching for synonym "http://www.atalyfro.org", that is held in record https://www.webarchive.org.uk/act/targets/46464.

Production:
![Screenshot 2019-04-30 13 34 59](https://user-images.githubusercontent.com/18530934/56962027-6012a800-6b4d-11e9-9bd3-9c7a2bb15f49.png)

Beta:
![Screenshot 2019-04-30 13 34 52](https://user-images.githubusercontent.com/18530934/56962055-702a8780-6b4d-11e9-9239-153d5a3dfe5c.png)

Targets with aliases:
[Aliases.xlsx](https://github.com/ukwa/w3act/files/3131249/Aliases.xlsx)
