### ISSUE TITLE
Reports page taking a long time to load

### ISSUE THREAD

**Issue by ldbiz** [ukwa/w3act#608]
https://www.webarchive.org.uk/act/reports

Takes quite a long time to load and at each refresh. Caused issues that required timeout being raised on nginx today.

According to @crarugal this delay is a recent "feature".

Possible bug or routing/connectivity issue?

**Comment by crarugal** [comment]
Could it be because too many database records are being pulled in by default when trying to load the reports page:  
Reports: Open UKWA Licences>Requested
https://www.webarchive.org.uk/act/reports
      >roughly 11K records are listed on one single page 


The loading time seems fine when loading a different Reports tab: 
Reports: Target Creation
https://www.webarchive.org.uk/act/reportscreation/targets?s=createdAt&o=desc&curator=-1&organisation=-1&tld=either
       >only 10 records

**Comment by min2ha** [comment]
it's obviously a common problem, lack of pagination. I'm not W3ACT user so I'm not sure if it was working in earlier version.

**Comment by min2ha** [comment]
sorry @nicolabingham and @crarugal, could you provide menu items/links where pages have slow load?

**Comment by crarugal** [comment]
I believe it's really only https://www.webarchive.org.uk/act/reports that is slow to load

**Comment by crarugal** [comment]
the final HTML page ends up being 27mb;
![image](https://user-images.githubusercontent.com/18530934/198356733-eea2e3ab-48d6-4119-a29d-1dbcea2ff919.png)

**Comment by crarugal** [comment]
The current fix includes some tweaks to the UI

**The current version:**
![image](https://user-images.githubusercontent.com/18530934/206721851-c6cbb93f-1326-4600-85bf-368bad8c8a6d.png)

**The proposed fix:**
![image](https://user-images.githubusercontent.com/18530934/206721956-902b55d5-6c77-456c-869d-6be628833730.png)

**Choosing between dates works as expected, and you can move in between filters, just as before**
Requested date
![image](https://user-images.githubusercontent.com/18530934/206724262-5a029c9a-2c64-4b93-bb54-10b3324e7096.png)
Granted date within same period
![image](https://user-images.githubusercontent.com/18530934/206724301-717bfff6-b38a-472a-bd56-2cf741bf58d4.png)

You can also export the list as a CSV, much like what can be done already. However, the newer fix seems to export much quicker.

One thing to note is the new export of the CSV contains a different format, but this can altered in excel etc
**Old export format:**
![image](https://user-images.githubusercontent.com/18530934/206724784-b259c595-cda2-4037-aecd-72d57c1408a3.png)

**New export format:**
![image](https://user-images.githubusercontent.com/18530934/206724871-0898a501-a467-47c3-9fa9-6c20319e42d9.png)

**New export format with column format changed to custom date**
![image](https://user-images.githubusercontent.com/18530934/206725086-3cb68e7b-8c95-4040-a47e-fa78e186e5fc.png)

The fix works well and loads significantly faster, thanks @min2ha
