### ISSUE TITLE
Refer to OutbackCDX rather than Wayback for crawl/instance counts

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#612]
Since updating to pywb, some reporting within W3ACT is broken because it relies on OpenWayback's XML query interface.

We should move to a supported API. OutbackCDX's CDX API is likely the simplest and fastest alternative.

Reported by @crarugal

**Comment by anjackson** [comment]
AS @min2ha points out, this is pointing at something that no longer exists:

https://github.com/ukwa/w3act/blob/b50917393ed688668950e79c631396ae9126ee89/app/controllers/WaybackController.java#L118

**Comment by anjackson** [comment]
So, simplest approach is likely to add another separate parameter for specifying the location of the CDX Server:

    application.cdxserver.endpoint=http://cdx:9090/collection

Then modify the two places in the code that currently mention `xmlquery` and point them at the CDX service instead, using the syntax that makes it return XML:

    http://bigcdx:8080/data-heritrix?q=url:http://www.bl.uk/+type:urlquery

and for prefix queries

    http://bigcdx:8080/data-heritrix?q=url:http://www.bl.uk/+type:prefixquery

as the XML format should be correct, the remainder of the code should be identical. Hopefully.

**Comment by crarugal** [comment]
Searching for a target in BETA ACT now shows the correct number of crawled instances.

BETA ACT
![image](https://user-images.githubusercontent.com/18530934/58163318-b7eb8d00-7c7b-11e9-81ea-c45f41b19e8b.png)

Production ACT
![image](https://user-images.githubusercontent.com/18530934/58163350-c76ad600-7c7b-11e9-8d78-5c1991073dd8.png)

**Comment by emacglone** [comment]
I now see the correct number of crawled instances, but clicking on the number results in the following error:
"UKWA Error
http://query/?type=prefixquery&url=https://twitter.com/KateForman9/

Error Details:

                    {'args': {'coll': 'archive', 'type': 'replay', 'archive_paths': 'webhdfs://192.168.45.13:14000', 'index_paths': 'xmlquery+http://192.168.45.21:8080/data-heritrix'}, 'error': '{"message": "Internal Error: object of type \'NoneType\' has no len()"}'}"

**Comment by min2ha** [comment]
Sorry, but we are forced to leave as-is at the moment, as PYWB is the problem actually. 
Related to https://github.com/webrecorder/pywb/pull/421

**Comment by emacglone** [comment]
I see! Thanks for letting me know.
