### ISSUE TITLE
Domain crawl frequency target not crawled

### ISSUE THREAD

**Issue by emacglone** [ukwa/w3act#613]
We have found https://www.webarchive.org.uk/act/targets/32620 had been set up for a "domain crawl" frequency in 17-11-2015, but no crawls have been made yet.

**Comment by anjackson** [comment]
I checked and it was picked up in the 2018 domain crawl but we still haven't got that into Wayback yet.

    com,isleofberneray)/ 20180710185045 http://www.isleofberneray.com/ text/html 200 JHUSCII3OIQVN7ZVSD2G7W7U4EPADXBI http://www.isleofberneray.com/ - 0 44693425 BL-20180710125536239-00004-11361~fdfa71ea4831~8443.warc.gz

Unfortunately it looks like we missed it in earlier years.

**Comment by emacglone** [comment]
Thanks very much for checking this out, good to hear we got in 2018. If I increase the frequency, would it be more likely to pick it up?

**Comment by anjackson** [comment]
If you up the frequency, it shifts over to the frequent crawl stream so yes. However, future domain crawls should pick it up as we've changed how we launch them and it should be more reliable.

**Comment by emacglone** [comment]
Will do - thanks again :)
