### ISSUE TITLE
Reporting tool under-reporting "UK Hosting" figures

### ISSUE THREAD

**Issue by crarugal** [ukwa/w3act#618]
Filtering by NPLD then choosing "UK Hosting", should show more results.

https://www.webarchive.org.uk/act/reportscreation/targets?s=createdAt&o=desc&curator=-1&organisation=-1&npld=UK_HOSTING&tld=either

![Screenshot 2019-06-20 12 22 14](https://user-images.githubusercontent.com/18530934/59845771-1036ad00-9356-11e9-94b5-7200353195ac.png)

Previous records show that it should show 20k+ records, as opposed to 125. The "UK Hosting" facet maps to "UK GeoIP" in the monthly stats

![Screenshot 2019-06-20 13 33 15](https://user-images.githubusercontent.com/18530934/59849644-2184b700-9360-11e9-88ba-4864940b3e98.png)

**Comment by anjackson** [comment]
Yes, GeoIP has been broken for a while. Should be resolvable once #610 is deployed. i.e. after rolling out 2.0.13 we'll need to update all the targets.

**Comment by nicolabingham** [comment]
Closed this issue as it is covered under #610
