### ISSUE TITLE
Encoding for space character is stripped in link to QA Wayback

### ISSUE THREAD

**Issue by crarugal** [ukwa/w3act#620]
We had a URL that was successfully added to ACT (https://www.springthing.net/2019/play_online/AmongTheSeasons/Among%20the%20Seasons.html)
Unfortunately, the encoding is being removed and the wrong URL is looked up in QA Wayback.

Correct (but only works for Open Access pywb): 
https://www.webarchive.org.uk/wayback/archive/*/https://www.springthing.net/2019/play_online/AmongTheSeasons/Among%20the%20Seasons.html

Incorrect (QA pywb): 
https://www.webarchive.org.uk/act/wayback/*/https://www.springthing.net/2019/play_online/AmongTheSeasons/Among the Seasons.html

https://www.webarchive.org.uk/act/targets/91913
![image](https://user-images.githubusercontent.com/18530934/59850442-26e30100-9362-11e9-8d2e-5963e0c0666b.png)

**Comment by anjackson** [comment]
The link to Open Access PYWB works fine, so this appears to be a problem with the proxying between W3ACT and the internal QA Wayback (which goes via an internal NGINX, just to confuse things).

**Comment by crarugal** [comment]
It looks as though excluding **/act/**will work in pywb 
(https://www.webarchive.org.uk/wayback/archive/*/https://www.springthing.net/2019/play_online/AmongTheSeasons/Among%20the%20Seasons.html).

However inlcuding /act/ for QA pywb will strip the space character (https://www.webarchive.org.uk/act/wayback/archive/*/https://www.springthing.net/2019/play_online/AmongTheSeasons/Among%20the%20Seasons.html)

**Comment by min2ha** [comment]
Limited solution was created, could be tested on beta.

**Comment by crarugal** [comment]
The link to QA Wayback now takes you to the correct instances. 
![Screenshot 2019-07-02 10 15 28](https://user-images.githubusercontent.com/18530934/60504946-8faf6f00-9cba-11e9-880f-136367620c2c.png)

The QA Wayback link (https://beta.webarchive.org.uk/act/wayback/*/https://www.springthing.net/2019/play_online/AmongTheSeasons/Among%20the%20Seasons.html) will take you here:
![Screenshot 2019-07-02 10 15 33](https://user-images.githubusercontent.com/18530934/60504995-afdf2e00-9cba-11e9-9a2e-ec50c71aa817.png)


Solutions looks as though it works

**Comment by anjackson** [comment]
I updated the production setup to work like the beta and https://www.webarchive.org.uk/act/wayback/*/https://www.springthing.net/2019/play_online/AmongTheSeasons/Among%20the%20Seasons.html works now.
