### ISSUE TITLE
Possibility that Targets are added as Watched Targets by mistake

### ISSUE THREAD

**Issue by crarugal** [ukwa/w3act#621]
There are Expert and Archivist users who have permission to use DDHAPT and it seems that this additonal permission changes the UI slightly. The outcome may be leading users to accidently make a Target a Watched Target. 
This can occur if a DDHAPT user is logging in and the homepage is the Watched Target page.

Currently, a user without DDHAPT access can click on the W3ACT logo and will be taken to this screen:

https://www.webarchive.org.uk/act

![Screenshot 2019-06-27 11 36 40](https://user-images.githubusercontent.com/18530934/60259897-36b59480-98d0-11e9-8945-3b2767a85a5e.png)

However, a user with DDHAPT permissions will click on the same W3ACT logo and be redirected to this screen:
https://www.webarchive.org.uk/act is redirected to https://www.webarchive.org.uk/act/overview/watchedtargets

![Screenshot 2019-06-27 11 40 14](https://user-images.githubusercontent.com/18530934/60259995-62387f00-98d0-11e9-9a6d-c9c3997e345c.png)

This could be an issue whereby a DDHAPT users may be searching for a target but accidentally makes  it a Watched Target by unintentionally entering a URL in the Watched Target page:

![image](https://user-images.githubusercontent.com/18530934/60260420-78930a80-98d1-11e9-87d3-1addfdc4ff21.png)

Perhaps the redirect for DDHAPT users should be removed and remain https://www.webarchive.org.uk/act. Or the Watched Target page is redesigned to look significantly different to https://www.webarchive.org.uk/act/targets/lookup

**Comment by nicolabingham** [comment]
Thanks @crarugal. It sounds like making the redirect for DDHAPT users to  https://www.webarchive.org.uk/act would be easier, rather than redesigning the WT page.

**Comment by anjackson** [comment]
I _think_ this isn't an issue, because I _think_ it's just a shortcut to the usual lookup page, and doesn't hard-code in any additional logic to do with document harvesting. However, it's best if @min2ha check this is the case.  Maybe there's some weird JavaScript/cookie stuff going on?

**Comment by min2ha** [comment]
Clarification on roles

**ADD TARGET**
Any role starting from 'user' (aka 4) and higher priority can add new target
_Targets > Look up a URL_
or
**Document Harvesting**
_New Target_ which will be forwarded to the same _Targets > Look up a URL_

**WATCH TARGET**
Any role starting from 'expert user' (aka 3) and higher priority can (de)select to watch the target even if it has ownership of it
Any role starting from 'archivist' (aka 2) and higher priority can (de)select to watch any existing target

Role 'user' (aka 4) cannot (de)select to watch the target even if it has ownership of it from _Targets > Target_ (edit form)

**Comment by min2ha** [comment]
Thanks to @nicolabingham, got new ideas about how unauthorised watched targets could appear in ACT.

![image](https://user-images.githubusercontent.com/15713396/60675982-9f26e780-9e75-11e9-834a-41c4f57462e9.png)

Actually extra things need to be done:
- user list who **do not have** DDHAPT along with Watched Target revision.
- sync data in DB.

**Comment by HelenaByrne** [comment]
A screen shot of my ACT homepage 
![image](https://user-images.githubusercontent.com/43820507/61211435-79140980-a6f7-11e9-9066-a206bfa5847f.png)

**Comment by HelenaByrne** [comment]
The individual target links:

https://www.webarchive.org.uk/act/targets/91018

https://www.webarchive.org.uk/act/targets/57526

https://www.webarchive.org.uk/act/targets/47987

https://www.webarchive.org.uk/act/targets/37989

**Comment by crarugal** [comment]
I'm still seeing targets added to my watch list, additions that I've not made. Something that's been ongoing since the ticket was raised -  although I don't believe they are being added by mistake through an accidental user workflow. 
![image](https://user-images.githubusercontent.com/18530934/171400951-8b52df6f-580d-4bdf-9eef-d22f7bb19eb2.png)

**Comment by crarugal** [comment]
It looks like "The Skeptic" was recently added as Watched: I just noticed that a new target had been added to my watched list:
![image](https://user-images.githubusercontent.com/18530934/195796137-55999fa6-4fa6-4c87-9c86-52986872f45d.png)

I don't usually access ACT through the homepage, so it could have been Watched for some time. It looks like the record was also recently updated: https://www.webarchive.org.uk/act/targets/166891
![image](https://user-images.githubusercontent.com/18530934/195796431-87d9226a-3575-42c8-8c37-054a8d2c0863.png)
![image](https://user-images.githubusercontent.com/18530934/195808991-22b97524-8e1f-4d8d-8e16-52c052d15c2e.png)


Looking at recent ACT activity(10-10-2022 13:42) 

**These are the most recent users (login time should be +1 hour to match current BST):**
![image](https://user-images.githubusercontent.com/18530934/195801892-e33bc787-3d95-4577-a237-ee738e7371ce.png)


**These are the targets that were created at around the same time "The Skeptic" target was updated (looking at targets around 13:42)**
![image](https://user-images.githubusercontent.com/18530934/195807445-ca45e474-70a9-45c4-85d0-a8a43d05a356.png)

**These are the targets that were updated on the 10/10/22:**
![image](https://user-images.githubusercontent.com/18530934/195811079-d6b07a0d-e2e1-4697-96a4-2fc18f2a45a7.png)

Leontien and Alice aren't able to Watch targets, but looking at the times, it's possible another ACT user updated "The Skeptic" to Watched. I will follow up with an email to recent logged-in users and see if they updated "The Skeptic"

**Comment by crarugal** [comment]
It seems that a curator edited "The Skeptic" to remove a URL from that target https://www.skeptic.org.uk/category/alternative-medicine/ and make it a target on its own (https://www.webarchive.org.uk/act/targets/168708/) -  unclear if this could cause it. Still investigating

**Comment by crarugal** [comment]
This may need further investigation, but, for now, the solution is to redirect all users (even with DDHAPT logins) to the same page. This may help because DDHAPT users when logged in, will see a list of all of their watched targets and what looks like a search bar; the search bar may have been accidentally used for search for a target, which is not the intended use:
![image](https://user-images.githubusercontent.com/18530934/206438370-3cd622b7-517e-4bc2-bbc1-b7a97dd36520.png)

To get around this, all users will now see the /act/about page

**Current homepage after login (as DDHAPT user):**
![image](https://user-images.githubusercontent.com/18530934/206438562-40e51d03-a4fb-44da-bca5-62a9475bdbfd.png)


**Fix:**
![image](https://user-images.githubusercontent.com/18530934/206438689-4e46ec42-a856-44e8-bc4a-c8366865eb82.png)
