### ISSUE TITLE
waybackReplayUrl not supported by pywb

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#623]
Since switching to pywb, the code that computes the SHA256 of the document is broken, because pywb does not support the API used by `waybackReplayUrl`.

https://github.com/ukwa/w3act/blob/ae2fc7c329a21b440b020b44a6b00bf4bc1a3a8f/app/uk/bl/documents/DocumentAnalyser.java#L147-L149

Instead, we should construct a URL of the form:

    <WAYBACK_PREFIX>/<TIMESTAMP>id_/<DOCUMENT_URL>

**Comment by anjackson** [comment]
I've added an experimental re-direct to the beta nginx config, but I'm not sure if the implementation will follow the redirect.

**Comment by anjackson** [comment]
Hah guess not!:

https://github.com/ukwa/w3act/blob/ae2fc7c329a21b440b020b44a6b00bf4bc1a3a8f/app/uk/bl/documents/DocumentAnalyser.java#L142

**Comment by min2ha** [comment]
Well, of cause only if I've checked at a right place, but compared to PROD, the **BETA** works  fine!

**Comment by anjackson** [comment]
This is not user facing functionality. That internal URL reference needs fixing so W3ACT can talk to Wayback behind the scenes.

**Comment by anjackson** [comment]
Fixed in https://github.com/ukwa/w3act/commit/89f9c386442ecd068c7a2663720972a8e5a90c2a
