### ISSUE TITLE
Targets > Reports > Target creation > Date created threw ERROR (on sorting)

### ISSUE THREAD

**Issue by min2ha** [ukwa/w3act#625]
Trying to sort by Date created at
Targets > Reports > Target creation > Date created 
threw SQLException:ERROR

![reports creation - date created](https://user-images.githubusercontent.com/15713396/62361544-2c139e00-b513-11e9-836e-df99598124f0.png)

![image](https://user-images.githubusercontent.com/15713396/62361649-55342e80-b513-11e9-8d80-c14d21f12d82.png)

**Comment by crarugal** [comment]
Sorting by date doesn't throw up any errors:
![image](https://user-images.githubusercontent.com/18530934/198355011-5e59d964-e178-4ea8-8b97-e064199a61dc.png)

![image](https://user-images.githubusercontent.com/18530934/198355107-cfb8a02c-57be-4000-8cf9-b7b4aef9d23b.png)
