### ISSUE TITLE
Override robots.txt for https://archivingactivism.com/

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#628]
This site has a restrictive robots policy which is preventing us from going beyond the front page 

User-agent: *
Disallow: /

Can we override robots for this site please as it was a BL project that might not be supported any longer (as flagged to us by Alan Sudlow), so the website may be going offline.

**Comment by anjackson** [comment]
I think this is okay to close now. Let me know if not @nicolabingham
