### ISSUE TITLE
Crawl/instance counts are showing zero

### ISSUE THREAD

**Issue by crarugal** [ukwa/w3act#644]
Crawl/instance counts are showing zero, reported around 11.30 on 21/01/20, https://www.webarchive.org.uk/act/wayback/*/xxxxx was also showing zero instances but was fixed. 

However, the issue remains in ACT

![Screenshot (121)](https://user-images.githubusercontent.com/18530934/72811949-8e469380-3c58-11ea-9a16-328be71d9b35.png)

**Comment by anjackson** [comment]
FIXED!
