### ISSUE TITLE
Add a new Licence Label to ACT "University of Edinburgh"

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#654]
This is to add a new licence label, "University of Edinburgh" to the Licence Templates in ACT https://www.webarchive.org.uk/act/licenses so that ACT users from the University of Edinburgh and NLS can make their websites open access by manually selecting this licence type and 'permission granted'.
Related tickets: #338 was to allow Archivists to add different licence types but this ticket was superceded by #360.
I can edit an existing licence but can't add a new one through the GUI.

**Comment by anjackson** [comment]
Note for future changes: The systems administrator (wa-sysadm) can do this using the form at https://www.webarchive.org.uk/act/licences/new Note that, unfortunately, the UI does not provide a link to the new license form.

I just added the UoE one. We should perhaps add more descriptions to each license to help us keep track? See https://www.webarchive.org.uk/act/licences/list

**Comment by nicolabingham** [comment]
Thanks @anjackson. I can provide the descriptions. Should I add them to a separate ticket?

**Comment by anjackson** [comment]
Ah let's just put them together here.

**Comment by nicolabingham** [comment]
@anjackson I hope it's still ok to put these in this ticket? 

Can we add the following licence descriptions to ACT please? https://www.webarchive.org.uk/act/licenses

**Open UKWA Licence (2014-)**	"NPLD licence used 2014-2016. No longer used."

**Welsh Government (NLW)** "Archived under the “Memorandum of Understanding for the Collection and Preservation of Welsh Government Web Content."

**University of Edinburgh**	"Edinburgh University holds a signed submission agreement by which the signatory assigned the copyrights they possessed in this material to the University of Edinburgh."

**Joint LDL Web Archiving Licence (2016-)**	"Current, standard licence to be used in all general requests for open access to content archived under NPLD"

**Scottish Government (NLS)**	"Archived under the “Memorandum of Understanding for the Collection and Preservation of Scottish Government Web Content” between National Library of Scotland and Scottish Government, signed in Edinburgh, 1st July 2009."

**Open Government Licence** "Applies to websites made available under an OGL. Ratified by Her Majesty's Stationery Office 10th March 2016."

The **UKWA Selective Archive Licence** should be edited to read: "Pre-2013 standard UKWA Selective Archive Licence. Obtained via a paper form or UKWA online web form and stored in SPT. No longer used."

Could the <p> tags be edited out of the remaining descriptions please?

**Comment by anjackson** [comment]
This does not require any coding - its a matter of editing the values through the user interface. Reassigning to @GilHoggarth .

**Comment by GilHoggarth** [comment]
According to https://www.webarchive.org.uk/act/licences/list, descriptions edited as requested above, and paragraph tags removed where they existed.

**Comment by GilHoggarth** [comment]
Assigned to Nicola, to sign off if work done as expected.

**Comment by nicolabingham** [comment]
Checked and works as expected thanks.
