### ISSUE TITLE
Link to QA Wayback being misdirected from ACT

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#664]
When clicking on the "Search QA Wayback" link from within ACT, the link is being misdirected. 

For example, with this Target:  
https://www.webarchive.org.uk/act/targets/141607

Clicking "Search QA Wayback" goes to

https://www.webarchive.org.uk/act/wayback/*/https://elmcip.net/creative-work/500-apocalypses

Which is then directed to http://prod1/act/wayback/archive//https://elmcip.net/creative-work/500-apocalypses 

The correct link should be https://www.webarchive.org.uk/act/wayback/archive/*/https://elmcip.net/creative-work/500-apocalypses

We can work around this by putting the correct link directly into a browser but it's causing a bit of confusion for ACT users.

**Comment by anjackson** [comment]
Hmm, rolled out an update and that didn't fix it. Must be the settings of the web servers. Hang on...

**Comment by nicolabingham** [comment]
Brilliant! Many thanks @anjackson
