### ISSUE TITLE
ACT’s permissions form does not recognise an email which uses an apostrophe

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#665]
We have a small issue to report with ACT’s permissions form – it is not recognising an email which uses an apostrophe: Paul.O'Kane.msp@parliament.scot. This for Paul O’Kane’s MSP website target: https://www.webarchive.org.uk/act/targets/150073/ The permission record is at https://www.webarchive.org.uk/act/crawlpermissions/46125/
The permission form would not accept the email, but returns an “Invalid email” message instead.

**Comment by anjackson** [comment]
As per [this reference](https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address), plain apostrophes are indeed allowed in email addresses. (Note that 'fancy' apostrophies, the ones curved like a 6 or 9, are not allowed.)

Passing this to @min2ha ...

**Comment by crarugal** [comment]
Apostrophe is allowed in dev form.
**Production form: Penny.O'Kane.msp@webarchive.scot**
![image](https://user-images.githubusercontent.com/18530934/198351795-46c71fb4-c4b0-4588-9355-629f4abc99d6.png)



**Dev form: Penny.O'Kane.msp@webarchive.scot**
![image](https://user-images.githubusercontent.com/18530934/198351451-3980a04e-72a5-4e56-9897-349b8ab9fcb1.png)
