### ISSUE TITLE
Logged in user has no access to QA Wayback at NLS

### ISSUE THREAD

**Issue by emacglone** [ukwa/w3act#668]
When logged into ACT and following links from the target page (as in screenshot 1) these are the outcomes:
 
Search QA Wayback - 401 Authorization Required.
Search Open UK Web Archive (following instructions to view using NLS Secure Gateway) - Resource not available
Search other Web Archives - error, logged with id 7nd09ih5b
 
When logged into ACT and following the 'crawled?' link from the Look up a URL page (as in screenshot 2) the user receives a 401 Authorization Required message.

**Comment by crarugal** [comment]
Hi Eilidh, to help reproduce the issues, could you supply the target in question, the browser used and maybe other info such as the ACT user. I also can't see the screenshots, if you could upload them again, it would be helpful. Many thanks

**Comment by crarugal** [comment]
Search QA Wayback - 401 Authorization Required.
- This could be related to https://github.com/ukwa/w3act/issues/662, but I'd need to investigate it further and try to reproduce the issues.

Search Open UK Web Archive (following instructions to view using NLS Secure Gateway) - Resource not available
- The resource not available within Ericom, could be an indexing issue, will explore further

Search other Web Archives - error, logged with id 7nd09ih5b
- mementos issue, as stated in other ticket

**Comment by crarugal** [comment]
I think this ticket can be closed, as other separate tickets have been raised for each issue

**Comment by crarugal** [comment]
issue and fix found, see https://github.com/ukwa/w3act/issues/671
