### ISSUE TITLE
Search Open UK Web Archive link from ACT target is not functional

### ISSUE THREAD

**Issue by emacglone** [ukwa/w3act#671]
Clicking Search Open UK Web Archive https://www.webarchive.org.uk/wayback/archive/*/https:thepeopleslawyeruk.com/ eventually results in a “Resource Not Found” page in ERICOM, rather than the blue site.

**Comment by crarugal** [comment]
Hi Eilidh, it looks as though the URL is missing forward slashes: https:thepeopleslawyeruk.com/: 
![image](https://user-images.githubusercontent.com/18530934/164490299-8d072b09-f5d8-4ec7-b74b-80ca6ac696fe.png)

If you try https://www.webarchive.org.uk/wayback/archive/*/https://thepeopleslawyeruk.com/, it should show 1 capture:
![image](https://user-images.githubusercontent.com/18530934/164490513-023b15d8-bc00-460d-b219-f748a0270ec5.png)

**Comment by emacglone** [comment]
Thanks Carlos - sorry about the typo, I pasted the link in from an email, and I think that's where it slipped in. I have retried it just in case (https://www.webarchive.org.uk/wayback/archive/*/https://thepeopleslawyeruk.com/) I get the same result as from the link in the ACT record, which is a calendar page as above, but no corresponding page in the archive. I think this may be known issue though, so feel free to merge this if so.

**Comment by crarugal** [comment]
Thanks Eilidh, I tried it, and I was able to open https://www.webarchive.org.uk/act/wayback/archive/20220316102517/https://thepeopleslawyeruk.com/

![image](https://user-images.githubusercontent.com/18530934/164496663-86d47c7b-c38f-4d17-91ad-dcd12cc99f29.png)

Which browser are you using?

**Comment by emacglone** [comment]
No worries, I'm being directed to our ERICOM URL: https://nls.ldls.org.uk/accessnow/start.html, and I think that 2022 material can't be found there.

**Comment by crarugal** [comment]
Issue solved by Eilidh MacGlone: ACT user had an ACT account that was not authorised for QA; user organisation affiliation has been changed from "University of Edinburgh" to National Library of Scotland.
