### ISSUE TITLE
Send button on Crawl Permission view does not send email

### ISSUE THREAD

**Issue by emacglone** [ukwa/w3act#674]
A permissions email sent last week to an internal email at NLS as a test, has not arrived to the inbox or junk mail folder.

**Comment by anjackson** [comment]
Hm, just tried sending a permissions email to my own non-BL email address and it worked okay.  Can you tell me the internal email address (via BL email if you prefer) and I'll see if I can reproduce the problem.

**Comment by emacglone** [comment]
Hi Andy,

Thanks for looking at this!

The email is: ***@***.******@***.***>

Eilidh

Eilidh MacGlone
Web Archivist | Collections Management

National Library of Scotland
92 Cowgate, Edinburgh EH1 1JN
Tel: +44 0131 623 3934
Email: ***@***.******@***.***>
Website: www.nls.uk<http://www.nls.uk/>
***@***.***
Facebook:  /NationalLibraryofScotland

**Comment by crarugal** [comment]
I tested out a permission request with this target, a target created by a test NLS ACT user: https://www.webarchive.org.uk/act/targets/160705

I used these settings: 
![image](https://user-images.githubusercontent.com/18530934/169063239-24478ddd-f3b2-4e2e-8c15-ba9a636c6c99.png)


I released the licence and it was sent out: https://www.webarchive.org.uk/act/crawlpermissions/51700
![image](https://user-images.githubusercontent.com/18530934/169063271-594354ee-3c57-4c0c-8930-517ce4191829.png)


Eilidh, are the licence that NLS send out, set up in a similar way?
https://www.webarchive.org.uk/act/crawlpermissions/51700

**Comment by anjackson** [comment]
Sorry @emacglone can you send me that email address some other way, e.g. direct email to my BL account?  I think GitHub ate it.

**Comment by emacglone** [comment]
I have tried with old<https://www.webarchive.org.uk/act/crawlpermissions/47948> and new<https://www.webarchive.org.uk/act/crawlpermissions/51715> test targets and it doesn’t seem to work, they just stay “QUEUED”:

https://www.webarchive.org.uk/act/crawlpermissions/list?s=updatedAt&organisation=3

Eilidh

Eilidh MacGlone
Web Archivist | Collections Management

National Library of Scotland
92 Cowgate, Edinburgh EH1 1JN
Tel: +44 0131 623 3934
Email: ***@***.******@***.***>
Website: www.nls.uk<http://www.nls.uk/>
***@***.***
Facebook:  /NationalLibraryofScotland

**Comment by anjackson** [comment]
Oh dear, this seems to be a very serious error/bug in the user interface.  

There are two buttons labelled 'Send'.  One is on the Crawl Permissions list page:

![2022-05-20-w3act-working-send-button](https://user-images.githubusercontent.com/87843/169497581-71fb8428-7fe2-486a-a6bb-bd84f71ee421.png)

The other is on the individual Crawl Permission view page:

![2022-05-20-w3act-broken-send-button](https://user-images.githubusercontent.com/87843/169497623-06fab4f1-6643-491a-965f-2d03aff21dd0.png)

The code behind this latter button is here:

https://github.com/ukwa/w3act/blob/6d9ca6e7706382ccbc85b338ac356abd98cebfe4/app/views/crawlpermissions/view.scala.html#L223

The second button, the one on each individual crawl permission, _does not send emails._  It only takes you back to the list interface where emails can be sent in bulk.

As I remember, this was the intended workflow, but this means the button label is totally wrong and misleading, and should say something like 'Go to the Crawl Permissions list'.  Note that hovering over the button shows the legend 'Go to the email queue', which is also wrong.

Having an actual Send button there that actually worked seems like a good idea, but I'm not yet sure how easy it will be to change that. The first button offers the ability to select a mail template, and I'm not quite sure how this relates to the 'Permission request template' and 'Acknowledgement template'.

**Comment by crarugal** [comment]
It's been an issue for a long time, I always assumed it was just one of the low priority quirks, which is why I've only ever released the licences in the crawl permission list and not through the individual crawl permission page.

**Comment by anjackson** [comment]
Based on internal conversations, I'm currently proposing that we deal with this issue by re-labelling the button so it says what it does, and otherwise leave things as they are.

**Comment by nicolabingham** [comment]
Thanks @anjackson I agree we should re-label this. Carlos and I are looking at the legacy permissions with Eilidh in the meantime.

**Comment by emacglone** [comment]
That could explain it. Was the issue just that I was making an unnecessary change? I’m a bit worried, I’m not sure when I started doing it that way!

I have sent myself a test email from QUEUED, I’ll let you know if I get it.

Eilidh

Eilidh MacGlone
Web Archivist | Collections Management

National Library of Scotland
92 Cowgate, Edinburgh EH1 1JN
Tel: +44 0131 623 3934
Email: ***@***.******@***.***>
Website: www.nls.uk<http://www.nls.uk/>
***@***.***
Facebook:  /NationalLibraryofScotland

**Comment by min2ha** [comment]
sorry @nicolabingham and @crarugal, so what label to add on button?

**Comment by crarugal** [comment]
When you're looking at an individual licence, you currently see these buttons:
![image](https://user-images.githubusercontent.com/18530934/198357427-4fa258ef-a02b-4283-9ed4-c8794573dedc.png)

I think it should say this, as it does take you back to the list of licences:
![image](https://user-images.githubusercontent.com/18530934/198357578-5762d5a0-ad93-4044-8036-ea2af02d9237.png)

It should then take you back to: https://www.webarchive.org.uk/act/crawlpermissions/list?organisation=-1
![image](https://user-images.githubusercontent.com/18530934/198357667-db06d160-0a53-4e9b-af28-0b14f95178b0.png)

**Comment by nicolabingham** [comment]
Works on dev

**Comment by crarugal** [comment]
I can confirm that it works on DEV:
![image](https://user-images.githubusercontent.com/18530934/201658941-e3692f44-3057-4d24-b1ea-2dc11280352f.png)

button takes you back to the main page for all crawl permissions:
![image](https://user-images.githubusercontent.com/18530934/201659188-e306085f-4493-40bc-bac8-90a9676eaa3d.png)
