### ISSUE TITLE
Update NLS email permission templates with new phone number 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#686]
Please can we update three email templates in ACT, listed in #513:

https://github.com/ukwa/w3act/blob/master/conf/templates/2_NLS_acknowledgement.txt
https://github.com/ukwa/w3act/blob/master/conf/templates/4_NLS_LD_openAccess.txt
https://github.com/ukwa/w3act/blob/master/conf/templates/6_NLS_nonUK_nonLD.txt

Eilidh has a new phone number and the colleague who has inherited her old number is fielding a lot of web archiving calls. The new number is 0131 623 3934
Can we edit the templates and/or make sure the amended template is being issued from ACT please?

**Comment by crarugal** [comment]
I can confirm that the new phone number comes through in dev: 
![image](https://user-images.githubusercontent.com/18530934/198341241-9d5da638-c7a8-4cc6-ae4d-ad7e2173324f.png)

![image](https://user-images.githubusercontent.com/18530934/198341002-9140f45b-8431-4617-a84f-41c50741cfea.png)
