### ISSUE TITLE
Unresolved licence request blocking creation of new request

### ISSUE THREAD

**Issue by alice-austin** [ukwa/w3act#704]
Trying to administer licences for sites under https://sites.eca.ed.ac.uk (e.g. https://www.webarchive.org.uk/act/targets/185567)

Unable to create a new request as requests pending for 2 different targets with similar TL domain URLs - https://www.webarchive.org.uk/act/targets/3190 and https://www.webarchive.org.uk/act/targets/30679.

Unclear which licence is blocking.

**Comment by nicolabingham** [comment]
Hi Alice, I have reset the licence status for https://www.webarchive.org.uk/act/targets/3190. Could you try again with your original target please. Email me directly if this doesn't work, thanks.
