### ISSUE TITLE
Seed URLs and synonym fields

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#91]
The current Seed URL field allows multiple comma-separated values, since a single target can have more than one seed.

However, that field is also used in the Open UKWA licensing process.

(i) To clarify the relationship between the primary and secondary seeds, and the uses to which they are put, we need to rename Seed URLs field as 'Primary URL'  - this may have only one URL in it.
(ii) create another field: Secondary Seed URL. This is not required. It may have multiple comma separated values.
[This will necessitate some data manipulation on ingest, as there will be some records in Andy's ACT with multiple values which will need separating out.]

(ii) Rename Synonyms to Aliases.

(iii) Modify the target search at http://www.webarchive.org.uk/actdev/targets/list/?s=title to search in all three fields.
[This will alert users wishing to create a new target record that it is already referred to in association with an existing target.]

@anjackson  - could you check this over, and assign to Roman if you're happy ? I ran it past Nicola who agreed.

**Comment by peterwebster** [comment]
@anjackson we touched on this in our call last week. Has the time come to open this one up again ?

**Comment by peterwebster** [comment]
@anjackson OK, perhaps we do need to open this one up.

http://www.webarchive.org.uk/actdev/crawlpermissions/2

This crawl permission uses *both* URLs recorded for the target at http://www.webarchive.org.uk/actdev/targets/16936

Also, if the user adds more seed URLs, the most recently added is listed first, and so I'm not sure there is a clear distinction between a primary seed and others.

**Comment by kinmanli** [comment]
@anjackson Is this what you're looking for?

https://github.com/ukwa/w3act/blob/schemarefactor/app/models/Target.java#L108

**Comment by anjackson** [comment]
Hm, okay, so it seems the data model does not really create a List, but a Set (http://stackoverflow.com/questions/6562673/onetomany-list-vs-set-difference), i.e. as it is, there is no 'first' URL, no 'primary seed', just a set of URLs that could turn up in any order.

Kinman, can you find out how many entries have multiple URLs? If its not too too many, it might be easier to process them manually. i.e. we add new fields for aliases and secondary seeds and manually move URLs out of one and into the others.

**Comment by kinmanli** [comment]
@anjackson approximately 412 Targets with multiple URLs

**Comment by anjackson** [comment]
@kinmanli Presumably the URL table ID is a normal auto-incrementing long?

**Comment by kinmanli** [comment]
@anjackson yes it is

**Comment by anjackson** [comment]
So perhaps we can assume the one with the lowest ID is the 'primary' one, and then review?

**Comment by kinmanli** [comment]
@anjackson there's als the 'createdAt' field too.

**Comment by anjackson** [comment]
Okay, given how the import code works, which is likely to be most reliable?

**Comment by kinmanli** [comment]
CreatedAt, if you think inserted first is the primary.

**Comment by anjackson** [comment]
Well, it should be the first in the list coming from Andy's ACT, and if that order is honoured when the data is inserted by the import code, then it should be fine. I think you worked on the import code, but maybe it comes down to how the underling DB system handles the List insertion?

**Comment by kinmanli** [comment]
@anjackson with http://www.webarchive.org.uk/act/node/16.json it reads in the 'field_url' that is in Andy's Act and inserts them into w3act in that order

1. https://www.cafonline.org/
2. http://www.cafonline.org/

```
{"body":[],"field_url":[{"url":"https:\/\/www.cafonline.org\/","attributes":[]},{"url":"http:\/\/www.cafonline.org\/","attributes":[]}],"field_depth":"capped",.........}
```

**Comment by anjackson** [comment]
Okay, so, as FieldUrls are a list, we effectively have a Primary Seed and other seeds (i.e. the zeroth item), but we can improve the presentation to make it clear that one seed is primary.

Obviously it would be nice to use a dynamic list for seeds rather than a comma separated list, but that may be too invasive a change right now.

We also have a field for aliases, but it is misnamed:

> Synonyms: If this content is also hosted at another URL, record it here. For example, if www.company.co.uk is the same as www.company.com

This should be 'Aliases', not 'Synonyms', and should probably be directly below the Seeds field.

**Comment by anjackson** [comment]
Synonyms has been renamed to Aliases and the View mode makes the primary seed clear.

**Comment by anjackson** [comment]
Tested and working on actstage.

**Comment by GilHoggarth** [comment]
Andy, please test this ticket.

**Comment by GilHoggarth** [comment]
Ah, looks like you already have. Okay, accepted as tested on actstage.

**Comment by GilHoggarth** [comment]
Andy, please test again on /actstage.

**Comment by anjackson** [comment]
Tested and working fine on actstage.
